### ISSUE TITLE
Wrong Item Shelf block's name in Jade

### ISSUE THREAD

**Issue by xtrial** [MehVahdJukaar/Supplementaries#10]
There is minor bug with item shelf block's name:
![image](https://user-images.githubusercontent.com/13495566/106150038-e1312000-61b5-11eb-93ec-b394396ced94.png)
This is not affecting vanilla gameplay, but to HYWLA user, it's a bit distracting

**Comment by MehVahdJukaar** [comment]
I have no idea where he's getting that name. its registry name is item_shelf and its translation name in english is Item Shelf.
I usually use the one probe but I've installed hywla just to see if it was working and it's showing its correct name just fine

**Comment by xtrial** [comment]
Sorry, i'm not specific enough, i'm using Jade, fork of HYWLA and assumed it will work just like HYWLA, but i guess not :/

**Comment by MehVahdJukaar** [comment]
Oh I found it. aparently it uses its inventory name, the one that would appear inside a gui. Since I'm not using a gui and I had to implement those methods I simply added untralsated and sometimes random text in them since I never though they would be used. I guess with mods you never know

**Comment by MehVahdJukaar** [comment]
fixed
