### ISSUE TITLE
The Pulley can retract any block

### ISSUE THREAD

**Issue by hjake123** [MehVahdJukaar/Supplementaries#100]
I'm using the Crucial 2 modpack, which includes version 0.15.2b of this mod.

The Pulley, when rotated the correct direction by a turntable, cam collect any block underneath it and store it inside itself, rather than only collecting chains and ropes. The internal inventory is then filled with the block in question, even though only chain or rope can be added by hand. Even normally unharvestable blocks like Bedrock and Spawners can be harvested this way.

The pulley seems to use the same logic to collect these blocks as it would a chain or rope -- it can even retract whole lines of them. Once there are blocks in its inventory, the pulley will also extend lines of these blocks.

Containers collected this way drop their contents, so I assume no NBT data will be maintained.

Here's the pulley collecting and storing a line of pig spawners:
![2021-08-22_19 53 50](https://user-images.githubusercontent.com/5803666/130376432-aabcd539-1d95-4ee8-b809-4b8e32dd8d56.png)
![2021-08-22_19 53 51](https://user-images.githubusercontent.com/5803666/130376433-0d9e25fc-ad2d-469a-86e5-a01ae12beddc.png)
![2021-08-22_19 53 54](https://user-images.githubusercontent.com/5803666/130376436-8958f448-0d26-4f97-9a14-b0693be8375a.png)

Here's a cobble gen made with this bug:
![2021-08-22_19 30 26](https://user-images.githubusercontent.com/5803666/130376426-84f3af51-71e3-4cf4-b42e-73ab80686ebc.png)
![2021-08-22_19 30 28](https://user-images.githubusercontent.com/5803666/130376431-54825a18-2f97-458c-a5fc-a53f3118b0ab.png)

**Comment by MehVahdJukaar** [comment]
Fixed in 0.16
