### ISSUE TITLE
[🐞]:  Clients crash when rendering globes

### ISSUE THREAD

**Issue by the-P1neapple** [MehVahdJukaar/Supplementaries#1008]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FABRIC

### Supplementaries Version

1.19.2-2.4.20

### Moonlight Lib Version

1.19.2-2.3.5

### Issue Detail

Whenever a globe or sepia globe is rendered or placed in a world, it crashes the client. Just before the game crashes, I only see a highlight for where the block is placed but no model appears. I have tested on a separate profile with only Fabric API, Moonlight and Supplementaries and the issue persists.

[crash-2024-04-01_13.24.34-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14818671/crash-2024-04-01_13.24.34-client.txt)

Also if there is a way to disable globes for my server while this gets fixed in the meantime, let me know.

Thanks.

**Comment by the-P1neapple** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14818681/latest.log)
Sorry forgot to post

**Comment by the-P1neapple** [comment]
So turns out it only applies if system clock is set to April 1st

**Comment by Pinkietron** [comment]
A (intentional or not) TIME-BOMB IS WHY I WAS PULLING MY HAIR OUT?????

**Comment by MehVahdJukaar** [comment]
You are not using the latest version

**Comment by the-P1neapple** [comment]
> You are not using the latest version

What version should I be using? I am using the latest on modrinth.

**Comment by MehVahdJukaar** [comment]
get from cf. modrinth publishin plugin is broken and it keeps on timing me out when i try to upload

**Comment by Fr0zka** [comment]
it does happen on 1.20.1 with supplementaries-1.20-2.7.31-fabric, cannot update much cause its in a modpack and cause mayhem for now.. but yeah, was it fixed on future version for that minecraft version ?

**Comment by MehVahdJukaar** [comment]
Yes

**Comment by chachomatic** [comment]
hey so i just ran into the same issue. was able to make it work by setting the date manually to another day aside from April first thru windows settings.

**Comment by WereWhusky** [comment]
It's an April Fools joke, you can change your system date and play without problems to get rid of it.

**Comment by TheRealScarHomie** [comment]
oh, april fools your game crashes lol, (Still an issue)

**Comment by MehVahdJukaar** [comment]
This is a bug specifically when usingoculus shaders. The but was already fixed

**Comment by adam-edword** [comment]
Lmao. This is happening to me, but only with complementary shaders on. Works fine with shaders off. Seems like the globe is transforming into a flat version of itself today & my client/shaders do not like that

**Comment by TheRealScarHomie** [comment]
> This is a bug specifically when usingoculus shaders. The but was already fixed

apparently not, every ATM9 player spent april fools trying to find what was randomly crashing the game lmao

**Comment by Poopooracoocoo** [comment]
ATM9 1.0.7 comes with supplementaries-1.20-3.1.13. That's an outdated version. ATM9 likely uses that version because has many Create add-ons that do not yet support Create 6.0.x. Supplementaries only got a fix for this crash after its Create support was updated for Create 6.0.x.
