### ISSUE TITLE
[🐞]: April 1'st april fools block changes caused globe noise shader to crash. (null)

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#1013]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

2.7.17

### Moonlight Lib Version

2.8.78

### Issue Detail

We only crashed today, have been using it all march, but only on april 1'st did it trigger.

[crash-2024-04-01_18.09.05-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14829421/crash-2024-04-01_18.09.05-client.txt)

**Comment by MehVahdJukaar** [comment]
There are just so many issues like this. All duplicates. You people shouldn't check the first checkbox here if you mods aren't actually updated. This issue has been fixed 2 days ago
