### ISSUE TITLE
Quiver Whitelist

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/Supplementaries#1019]
A quiver blacklist already exists, but i would like to a request a quiver whitelist for items that aren't seen as traditional ammo but can still be shot out of a weapon (eg: potatoes for create's potato cannon, or amethyst shards and torches for enchancement's scatter and torch crossbow enchantments respectively)

**Comment by MehVahdJukaar** [comment]
Thing is quiver needs special code in bow class to work. I could add a whitelist but you wouldn't be able to shoot them
