### ISSUE TITLE
Crash with latest BYG version

### ISSUE THREAD

**Issue by PixusPanic** [MehVahdJukaar/Supplementaries#102]
I've recently updated to the latest version of [Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) in my private modpack, and the game appears to crash when loading up a world because of this. I'm guessing it has to do something with how BYG "Nuke[d] most references to forge API" which consequentially borks something about biome and structure providers.
I'm not too sure if this is either the fault of Supplementaries or BYG, but I'm guessing it's the former since I saw "net.mehvahdjukaar.supplementaries..." in there.

A fix would be greatly appreciated!

[crash-2021-08-27_23.50.56-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7070103/crash-2021-08-27_23.50.56-server.txt)

**Comment by MehVahdJukaar** [comment]
I've already encountered this and I believe is bug fault because my mod simply fails since it gets a null biome while trying to register structures where it shouldn't be one
