### ISSUE TITLE
[🐞]: outdated structure file way_sign.nbt

### ISSUE THREAD

**Issue by Linguardium** [MehVahdJukaar/Supplementaries#1023]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

https://github.com/MehVahdJukaar/Supplementaries/commit/9f49cd6f4d670963d52f253e95ed4ac251cb7a7c

### Moonlight Lib Version

N/A

### Issue Detail

common/src/main/resources/data/supplementaries/structures/way_sign.nbt

You have an outdated structure file in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and cpu usage during worldgen. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt.

**Comment by MehVahdJukaar** [comment]
i wonder if all it takes is literally changing the datafixer number version. No changes needed to the structure file
