### ISSUE TITLE
[🐞]: Quiver doesn't pick up arrow items, only arrow entities

### ISSUE THREAD

**Issue by emeryplyler** [MehVahdJukaar/Supplementaries#1026]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [x] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.10-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.9-fabric

### Issue Detail

When I pick up arrow items (arrows that have been dropped, not fired) they go into my inventory instead of my quiver even when there are arrows of the same kind in a non-full stack in my quiver. I read in the wiki that "Arrows and item arrows you pick up will go in your quiver if it contains non full stacks of the same kind" but I tried it with all types of arrows and the quiver only picks up arrow entities (arrows that I've fired into blocks.) I hope I'm using the item and entity terminology correctly.

**Comment by MehVahdJukaar** [comment]
so this is a forge only feature for now as fabric as no event for item pickup

**Comment by emeryplyler** [comment]
Ohh I see. Thank you! Love your mod.
