### ISSUE TITLE
Wandering Trader Mixin

### ISSUE THREAD

**Issue by Jollyolsport** [MehVahdJukaar/Supplementaries#103]
[crash-2021-08-30_03.02.47-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7074842/crash-2021-08-30_03.02.47-server.txt)

Game crashes upon spawning wandering trader

Forge version: 36.2.2
Supplementaries Version: 1.16.5-0.15.2b

**Comment by MehVahdJukaar** [comment]
For now disable that that wandering trader mixin using my mixin. It was for a feature that I didn't even add yet in that version and it did nothing anyways. I'll try to figure out what other mod it's conflicting wtih
