### ISSUE TITLE
[🐞]: Dye depot dye colors make missing texture flags, candles, etc.

### ISSUE THREAD

**Issue by CloverCorp** [MehVahdJukaar/Supplementaries#1031]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.10-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.12-fabric

### Issue Detail

https://imgur.com/a/nTKybwy Image provided 
the mod recognizes the dye depot colors but all inventory icons. main blocks, etc are now missing textures.
the issue also applies to supp squared and amendments.

**Comment by MehVahdJukaar** [comment]
Not my issue
