### ISSUE TITLE
[❓]: Custom Book and Quill GUI

### ISSUE THREAD

**Issue by Zvzdov** [MehVahdJukaar/Supplementaries#1032]
### Your Question

How to disable custom Book and Quill GUI?

### Detail

I am currently playing with **Amendments** mod which has a lot of features including custom Book and Quill GUI. Recently I've installed **Scholar** mod which also changes Book and Quill GUI but apparently it doesn't work well with Amendments in this regard. 

**Here's the issue:** When Book and Quill is placed on a lectern it shows GUI from Amendments but when I hold it in hand it shows GUI from Scholar.

I couldn't find option to disable custom GUI from Amendments in neither config and mod setting in mod menu. Is there any way to do this?

**Comment by MehVahdJukaar** [comment]
There's an option in the configs

**Comment by Zvzdov** [comment]
Well... How can I find it? VS Code finds nothing on "book", "lectern", etc

**Comment by MehVahdJukaar** [comment]
first of all why is this here? This is supplementaries page.
Secondly its in the common mod config, under lectern

**Comment by Zvzdov** [comment]
Because as far as my knowledge goes Amendments is a part of Supplementaries wiki page and has no dedicated one. As I previously mentioned there is no such thing as "lectern" in nether Supplementaries or Amendments config. If it was that simple I wouldn't even bother asking.

![Screenshot 2024-04-18 001252](https://github.com/MehVahdJukaar/Supplementaries/assets/165063949/6b5aca3b-fbd8-4894-8cf1-b1dce369b977)
![Screenshot 2024-04-18 000731](https://github.com/MehVahdJukaar/Supplementaries/assets/165063949/f2bc0a3a-2b4d-47e4-8c5e-c28e007b429c)

p.s. Yes I've also tried looking for it manually. Nothing.

**Comment by MehVahdJukaar** [comment]
amendments is NOT part of supplementaries. Wiki is just there for convenience sake

**Comment by Zvzdov** [comment]
Okay then I’ll repost this issue on Amendments page once I find it.

p.s. I’m using latest mod version for 1.20.1 with fabric loader.
