### ISSUE TITLE
[🐞]: Parsing error loading custom advancement supplementaries:recipes/planter_rich: Unknown item id 'farmersdelight:rich_soil'

### ISSUE THREAD

**Issue by Insane96** [MehVahdJukaar/Supplementaries#1036]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-2.8.7

### Moonlight Lib Version

1.20-2.11.9

### Issue Detail

If Farmer's delight is not installed this error pops out in the logs
`[minecraft/ServerAdvancementManager]: Parsing error loading custom advancement supplementaries:recipes/planter_rich: Unknown item id 'farmersdelight:rich_soil'`

**Comment by Xelbayria** [comment]
**Supplementaries** is outdated. please update it to **v2.8.10**. Do the same with **Moonlight lib**, it's also outdated. the latest version is **v2.11.12**

**Comment by Insane96** [comment]
Yep, seems fixed in the latest version
