### ISSUE TITLE
Block Tag for Soap Cleaning Blacklist

### ISSUE THREAD

**Issue by DaFuqs** [MehVahdJukaar/Supplementaries#1037]
Soap can convert all kinds of colored blocks to their white variants. While there exists a config setting to add stuff, that is inacessible for other mods that want to blacklist blocks the soap can be used on. It would be nice having a block equivalent for it.

This is analog to #558, which added the item tag `supplementaries:soap_blacklist`, just for blocks instead of items this time around.

**Comment by MehVahdJukaar** [comment]
this was added in newest version of moonlight. Tecnically not directly related to soap

**Comment by DaFuqs** [comment]
Can confirm it working, thank you!
