### ISSUE TITLE
[❓]:  Mod loading error has occurred

### ISSUE THREAD

**Issue by sunduk-01** [MehVahdJukaar/Supplementaries#1041]
### Your Question

 Supplementaries (supplementaries) has failed to load correctly

### Detail

I added velocity to the server for testing, realized that I didn’t need it and deleted it, after which it stopped starting

[crash-2023-05-30_00.14.02-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15211196/crash-2023-05-30_00.14.02-fml.txt)

**Comment by sunduk-01** [comment]
Unfortunately I don't know how to read these logs.

**Comment by MehVahdJukaar** [comment]
check ALL your mods aretheir latest version and you dont have duplicate mods

**Comment by sunduk-01** [comment]
Did not help. Also when starting it gives the following error:
[error_1.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15212446/error_1.txt)
[error_2.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15212447/error_2.txt)
Maybe it makes sense to clear the config folder?

**Comment by sunduk-01** [comment]
haha, I cleaned the config and everything worked
