### ISSUE TITLE
[🐞]: Doesn't work on Quilt 1.19.2

### ISSUE THREAD

**Issue by retropele** [MehVahdJukaar/Supplementaries#1042]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FABRIC

### Supplementaries Version

1.19.2-2.4.21

### Moonlight Lib Version

1.19.2-2.3.6

### Issue Detail

Log:
https://mclo.gs/RjYMxDg

I can't boot the game with Supplementaries, I've tried an older version of Supplementaries and Moonlight (back to Supp 2.4.11) and it still produces the issue.

I've looked around and all I can see is Quilt incompatibilities that are for 1.20.1+ or are resolved for mod conflicts, so if this is a repeat of a problem specific to 1.19.2 please feel free to go ahead and merge or just advise me of its resolution. Sorry for the trouble and thanks for the mod!

**Comment by MehVahdJukaar** [comment]
delete your mod configs

**Comment by retropele** [comment]
This totally resolved the problem! Thank you.

**Comment by retropele** [comment]
This totally resolved the problem! Thank you.
