### ISSUE TITLE
[🐞]: Not compatible with Cobblemon 1.5

### ISSUE THREAD

**Issue by ZzamZ** [MehVahdJukaar/Supplementaries#1044]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-2.8.10

### Moonlight Lib Version

1.20-2.11.17

### Issue Detail

<details>

<summary>Crash Report</summary>

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-05-11 20:57:31
Description: Exception in server tick loop

net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$BadModError: Some other mod loaded the Sheets class to early, causing modded banner patterns and sherds to be invalid.Refusing to proceed further.Check previous forge log to find the offending mod
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.clientStuff(VibeChecker.java:66) ~[supplementaries-1.20-2.8.10.jar%23326!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.utils.VibeChecker.checkVibe(VibeChecker.java:28) ~[supplementaries-1.20-2.8.10.jar%23326!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge.onServerTick(ServerEventsForge.java:228) ~[supplementaries-1.20-2.8.10.jar%23326!/:?] {re:classloading}
	at net.mehvahdjukaar.supplementaries.common.events.forge.__ServerEventsForge_onServerTick_LevelTickEvent.invoke(.dynamic) ~[supplementaries-1.20-2.8.10.jar%23326!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925) ~[forge-1.20.1-47.2.30-universal.jar%23339!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23334!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Cobblemon --
Details:
	Version: 1.5.0
	Is Snapshot: false
	Git Commit: 347e10d (https://gitlab.com/cable-mc/cobblemon/-/commit/347e10d7e474a7741f2d31c439a6696093a6ee23)
	Branch: HEAD
	Timestamp: 05/11/2024 10:26:01 UTC

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 577365024 bytes (550 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37504.54
	Virtual memory used (MB): 23369.07
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 67.37
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:easyanvils, mod:beautify (incompatible), mod:botarium (incompatible), mod:galosphere (incompatible), mod:additionalbanners (incompatible), mod:sophisticatedcore (incompatible), mod:structureessentials (incompatible), mod:modernfix (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:yungsapi, mod:mixinextras (incompatible), mod:bookshelf, mod:sophisticatedbackpacks (incompatible), mod:create_dragon_lib (incompatible), mod:createdieselgenerators (incompatible), mod:railways, mod:carryon (incompatible), mod:cloth_config (incompatible), mod:dummmmmmy (incompatible), mod:twilightforest, mod:embeddium, mod:athena, mod:create_connected, mod:chipped (incompatible), mod:farmersdelight, mod:ends_delight, mod:handcrafted (incompatible), mod:littleframes, mod:resourcefulconfig (incompatible), mod:fairylights (incompatible), mod:cloudstorage (incompatible), mod:mysticaloaktree (incompatible), mod:curios (incompatible), mod:oculus, mod:cobblemon (incompatible), mod:mr_dungeons_andtaverns (incompatible), mod:resourcefullib (incompatible), mod:architectury (incompatible), mod:doapi (incompatible), mod:vinery (incompatible), mod:aiimprovements, mod:cupboard (incompatible), mod:chimes, mod:sliceanddice (incompatible), mod:amendments (incompatible), mod:watermedia (incompatible), mod:easymagic, mod:jei, mod:nethervinery (incompatible), mod:create_cobblemon, mod:decorative_blocks, mod:blueprint, mod:clayworks, mod:allurement, mod:buzzier_bees (incompatible), mod:berry_good, mod:puzzlesaccessapi, mod:forge, mod:iwannaskate (incompatible), mod:elytratrims (incompatible), mod:upgrade_aquatic (incompatible), mod:neapolitan (incompatible), mod:alexscaves, mod:terrablender, mod:moonlight (incompatible), mod:regions_unexplored (incompatible), mod:mixinsquared (incompatible), mod:culllessleaves (incompatible), mod:creativecore, mod:nethersdelight, mod:personality, mod:kotlinforforge (incompatible), mod:flywheel, mod:create, mod:autumnity (incompatible), mod:zeta (incompatible), mod:quark (incompatible), mod:supplementaries, mod:immersive_paintings (incompatible), mod:entityculling, mod:miners_delight (incompatible), mod:betterarcheology, mod:bettertridents, mod:appleskin (incompatible), mod:ferritecore (incompatible), mod:puzzleslib, mod:create_power_loader, mod:valkyrienskies (incompatible), mod:vs_eureka (incompatible), mod:vs_clockwork (incompatible), mod:create_interactive (incompatible), mod:cosmeticarmorreworked, mod:create_enchantment_industry (incompatible), mod:domesticationinnovation (incompatible), mod:ad_astra (incompatible), Supplementaries Generated Pack, bushy_leaves
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-47.2.30
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.30.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.10.0
		lowcodefml@null
	Mod List: 
		EasyAnvils-v8.0.2-1.20.1-Forge.jar                |Easy Anvils                   |easyanvils                    |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		beautify-2.0.2.jar                                |Beautify                      |beautify                      |2.0.2               |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.3.jar                   |Botarium                      |botarium                      |2.3.3               |DONE      |Manifest: NOSIGNATURE
		Galosphere-1.20.1-1.4.1-Forge.jar                 |Galosphere                    |galosphere                    |1.20.1-1.4.1        |DONE      |Manifest: NOSIGNATURE
		AdditionalBanners-Forge-1.20.1-14.0.4.jar         |AdditionalBanners             |additionalbanners             |14.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedcore-1.20.1-0.6.22.611.jar           |Sophisticated Core            |sophisticatedcore             |0.6.22.611          |DONE      |Manifest: NOSIGNATURE
		structureessentials-1.20.1-3.3.jar                |Structure Essentials mod      |structureessentials           |1.20.1-3.3          |DONE      |Manifest: NOSIGNATURE
		modernfix-forge-5.17.0+mc1.20.1.jar               |ModernFix                     |modernfix                     |5.17.0+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.8.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.8              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.5.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.5    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.10.jar                |Bookshelf                     |bookshelf                     |20.1.10             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.20.5.1044.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.5.1044         |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.4.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.4.3               |DONE      |Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2h.jar            |Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2h         |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.6.4+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.6.4+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-11.1.106.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		dummmmmmy-1.20-1.8.17b.jar                        |MmmMmmMmmmmm                  |dummmmmmy                     |1.20-1.8.17b        |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.2145-universal.jar      |The Twilight Forest           |twilightforest                |4.3.2145            |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.18+mc1.20.1-all.jar                 |Embeddium                     |embeddium                     |0.3.18+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.2.jar                     |Athena                        |athena                        |3.1.2               |DONE      |Manifest: NOSIGNATURE
		create_connected-0.7.4-mc1.20.1-all.jar           |Create: Connected             |create_connected              |0.7.4-mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		Chipped-forge-1.20.1-3.0.6.jar                    |Chipped                       |chipped                       |3.0.6               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		ends_delight-1.20.1-1.0.1.jar                     |End's Delight                 |ends_delight                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.6.jar                |Handcrafted                   |handcrafted                   |3.0.6               |DONE      |Manifest: NOSIGNATURE
		LittleFrames_FORGE_v1.3.9_mc1.20.1.jar            |LittleFrames                  |littleframes                  |1.3.9               |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |DONE      |Manifest: NOSIGNATURE
		fairylights-7.0.0-1.20.1.jar                      |Fairy Lights                  |fairylights                   |7.0.0               |DONE      |Manifest: NOSIGNATURE
		cloudstorage-1.4.0-1.20.jar                       |Cloud Storage                 |cloudstorage                  |1.4.0               |DONE      |Manifest: NOSIGNATURE
		mysticaloaktree-1.20-1.11.jar                     |Mystical Oak Tree             |mysticaloaktree               |1.20-1.11           |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.9.0+1.20.1.jar                     |Curios API                    |curios                        |5.9.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.7.0.jar                         |Oculus                        |oculus                        |1.7.0               |DONE      |Manifest: NOSIGNATURE
		Cobblemon-forge-1.5.0+1.20.1.jar                  |Cobblemon                     |cobblemon                     |1.5.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		dungeons-and-taverns-3.0.3.f[Forge].jar           |Dungeons and Taverns          |mr_dungeons_andtaverns        |3.0.3.f             |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.24.jar            |Resourceful Lib               |resourcefullib                |2.1.24              |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		letsdo-API-forge-1.2.11-forge.jar                 |[Let's Do] API                |doapi                         |1.2.11              |DONE      |Manifest: NOSIGNATURE
		letsdo-vinery-forge-1.4.19.jar                    |[Let's Do] Vinery             |vinery                        |1.4.19              |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.20-0.5.2.jar                    |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.6.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.6          |DONE      |Manifest: NOSIGNATURE
		Chimes-v2.0.1-1.20.1.jar                          |Chimes                        |chimes                        |2.0.1               |DONE      |Manifest: NOSIGNATURE
		sliceanddice-forge-3.2.0.jar                      |Create Slice & Dice           |sliceanddice                  |3.2.0               |DONE      |Manifest: NOSIGNATURE
		amendments-1.20-1.1.27.jar                        |Amendments                    |amendments                    |1.20-1.1.27         |DONE      |Manifest: NOSIGNATURE
		watermedia-2.0.44.jar                             |WaterMedia                    |watermedia                    |2.0.44              |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v8.0.1-1.20.1-Forge.jar                 |Easy Magic                    |easymagic                     |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
		letsdo-nethervinery-forge-1.2.12.jar              |[Let's Do] NetherVinery       |nethervinery                  |1.2.12              |DONE      |Manifest: NOSIGNATURE
		Create-Cobblemon-Forge-v0.3.jar                   |Create: Cobblemon Industrializ|create_cobblemon              |0.3                 |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-forge-1.20.1-4.1.3.jar          |Decorative Blocks             |decorative_blocks             |4.1.3               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.20.1-7.1.0.jar                        |Blueprint                     |blueprint                     |7.1.0               |DONE      |Manifest: NOSIGNATURE
		clayworks-1.20.1-3.0.1.jar                        |Clayworks                     |clayworks                     |3.0.1               |DONE      |Manifest: NOSIGNATURE
		allurement-1.20.1-4.0.0.jar                       |Allurement                    |allurement                    |4.0.0               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.20.1-6.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |6.0.0               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.20.1-7.0.0.jar                       |Berry Good                    |berry_good                    |7.0.0               |DONE      |Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.20.1-47.2.30-universal.jar                |Forge                         |forge                         |47.2.30             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		iwannaskate-1.2.0.jar                             |I Wanna Skate                 |iwannaskate                   |1.2.0               |DONE      |Manifest: NOSIGNATURE
		elytratrims-forge-3.1.4+1.20.1.jar                |Elytra Trims                  |elytratrims                   |3.1.4               |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		upgrade_aquatic-1.20.1-6.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |6.0.0               |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.20.1-5.0.0.jar                       |Neapolitan                    |neapolitan                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.1.4.jar                              |Alex's Caves                  |alexscaves                    |1.1.4               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.6.jar             |TerraBlender                  |terrablender                  |3.0.1.6             |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.11.17-forge.jar                  |Moonlight Library             |moonlight                     |1.20-2.11.17        |DONE      |Manifest: NOSIGNATURE
		RegionsUnexploredForge-0.5.5+1.20.1.jar           |Regions Unexplored            |regions_unexplored            |0.5.5               |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.2-beta.4.jar               |MixinSquared                  |mixinsquared                  |0.1.2-beta.4        |DONE      |Manifest: NOSIGNATURE
		CullLessLeaves-Reforged-1.20.1-1.0.5.jar          |Cull Less Leaves Reforged     |culllessleaves                |1.20.1-1.0.5        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.27_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.27             |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		personality-1.20.1-4.0.0.jar                      |Personality                   |personality                   |4.0.0               |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		autumnity-1.20.1-5.0.1.jar                        |Autumnity                     |autumnity                     |5.0.1               |DONE      |Manifest: NOSIGNATURE
		Zeta-1.0-16.jar                                   |Zeta                          |zeta                          |1.0-16              |DONE      |Manifest: NOSIGNATURE
		Quark-4.0-441.jar                                 |Quark                         |quark                         |4.0-441             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.8.10.jar                   |Supplementaries               |supplementaries               |1.20-2.8.10         |DONE      |Manifest: NOSIGNATURE
		immersive_paintings-0.6.7+1.20.1-forge.jar        |Immersive Paintings           |immersive_paintings           |0.6.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.6.2               |DONE      |Manifest: NOSIGNATURE
		miners_delight-1.20.1-1.2.3.jar                   |Miner's Delight               |miners_delight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		betterarcheology-1.1.8-1.20.1.jar                 |Better Archeology             |betterarcheology              |1.1.8-1.20.1        |DONE      |Manifest: NOSIGNATURE
		BetterTridents-v8.0.1-1.20.1-Forge.jar            |Better Tridents               |bettertridents                |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v8.1.19-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.19              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		create_power_loader-1.4.0-mc1.20.1.jar            |Create: Power Loader          |create_power_loader           |1.4.0-mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-120-2.3.0-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.5        |DONE      |Manifest: NOSIGNATURE
		eureka-1201-1.5.1-beta.3.jar                      |VS Eureka Mod                 |vs_eureka                     |1.5.1-beta.3        |DONE      |Manifest: NOSIGNATURE
		clockwork-1.20.1-0.1.13-forge-8cf946b78e.jar      |Clockwork: Create x Valkyrien |vs_clockwork                  |1.20.1-0.1.13-forge-|DONE      |Manifest: NOSIGNATURE
		create_interactive-1201-forge-1.0.2-beta.2.jar    |Create: Interactive           |create_interactive            |1.0.2-beta.2        |DONE      |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.9.d             |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.7.1-1.20.1.jar          |Domestication Innovation      |domesticationinnovation       |1.7.1               |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.5.jar                  |Ad Astra                      |ad_astra                      |1.15.5              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cffd6dee-9245-4fad-b387-f50b63fca73f
	FML: 47.2
	Forge: net.minecraftforge:47.2.30
	Flywheel Backend: GL33 Instanced Arrays

</details>

**Comment by Xelbayria** [comment]
TIP: drag the crash report file here, and it will get uploaded. Please don't use Copy/Paste

**Comment by MehVahdJukaar** [comment]
Some other mod loaded the Sheets class to early, causing modded banner patterns and sherds to be invalid.Refusing to proceed further.Check previous forge log to find the offending mod.

Not a supplementaries issue. Loading sheets class early causes all that even without my mod

**Comment by Natetromino** [comment]
I got a similar crash to this, but removing supplementaries did fix the crashing, so I think there may be some correlation.
[crash-2024-05-15_15.25.11-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15326115/crash-2024-05-15_15.25.11-server.txt)

**Comment by MehVahdJukaar** [comment]
that crash is deliberate put there by me. Of course there is correlation. I'ts a safe guard agains mod accidentally messing stuff up, in that case causing the sheets class banner pattern or sherd map to not contain all textures, possibly messing up other mods ones including mine aswell hence why it was put there

**Comment by JoFrankT** [comment]
> that crash is deliberate put there by me. Of course there is correlation. I'ts a safe guard agains mod accidentally messing stuff up, in that case causing the sheets class banner pattern or sherd map to not contain all textures, possibly messing up other mods ones including mine aswell hence why it was put there

hey how can I find the forge log to see what mod is causing the issue ?

**Comment by neronix17** [comment]
Intentional crashes aren't exactly a great way to handle the issue. What exactly are we supposed to look for to find the cause? You seem to imply there's a way to find it in the logs, so I'm guessing there's _something_ we can do there. If there isn't a way to do that and a binary search would be the way to go then it might be worth rewording the error.

**Comment by MehVahdJukaar** [comment]
Forge does log something. It only does that if that clas is loaded during mod init. After that there's no way to easily know which mod class loaded it. Class loading is a mess and this issue really stem from bad design from Mojang that relies on class loading populating sticky defined maps in classes. As for crash I prefer that rather than having missing textures around possibly involving my stuff as well then having people bother me becaus they don't work. Has happened in the past and went undetected for ages

**Comment by ArchOwlen** [comment]
Having the same issue, uninstalling Supplementaries fixed it

Using ATM9 with Cobblemon added (also used Prism's "update all" feature to make sure every mod was up to date)

Issue does not happen when using Amendments, so not all is lost

**Comment by ytnaa** [comment]
im trying to run a 1.20.1 minecraft forge server with cobblemon mod, everytime i load it, it freezes without loading fully but when i load it without it, it works fine. I have many other mods in the server aswell. Which of these mods would be causing the issue with cobblemon mod? Someone help please.
[latest.log](https://github.com/user-attachments/files/16449893/latest.log)

**Comment by MehVahdJukaar** [comment]
sounds like your game run out of ram

**Comment by ytnaa** [comment]
> sounds like your game run out of ram

25gb of ram for the server

**Comment by MehVahdJukaar** [comment]
Try with no other mods on. Regardless it's not relevant to this particular closed issue here

**Comment by ytnaa** [comment]
Okay. I loaded up my server with only the kotlin and cobblemon mod and it still freezes when trying to start up the server. Here is the log:
[latest (1).log](https://github.com/user-attachments/files/16458836/latest.1.log)

**Comment by ytnaa** [comment]
Would the debug.log be helpful?

**Comment by ytnaa** [comment]
because it doesnt crash it just stops loading after a while
