### ISSUE TITLE
[🐞]: Conflict with Flan 1.20.1-1.10.0

### ISSUE THREAD

**Issue by farlydapamanis** [MehVahdJukaar/Supplementaries#1046]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

Supplementaries 1.20-2.8.10

### Moonlight Lib Version

Moonlight 1.20-2.11.17

### Issue Detail

Minecraft Server shutdown, then i claim land, using golden hoe.
This is the log
https://paste.gg/p/anonymous/68463c9deac344a8bebc1784326c4396

**Comment by MehVahdJukaar** [comment]
update both mods

**Comment by farlydapamanis** [comment]
Thank you
