### ISSUE TITLE
[🐞]: 'moonlight'!'supplementaries'!

### ISSUE THREAD

**Issue by zc1108aaa** [MehVahdJukaar/Supplementaries#1049]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

moonlight-1.20-2.11.17-fabric

### Moonlight Lib Version

supplementaries-1.20-2.8.10-fabric

### Issue Detail

[crash-2024-05-15_20.42.19-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15321902/crash-2024-05-15_20.42.19-client.txt)
1
[crash-2024-05-15_20.53.24-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15321903/crash-2024-05-15_20.53.24-client.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight update eveycompat update macae trapdoors update all your mods
