### ISSUE TITLE
NOT AN ISSUE: Thank you for addressing potential plans to port the mod to Fabric. [INFO]

### ISSUE THREAD

**Issue by enosich** [MehVahdJukaar/Supplementaries#105]
If you do decide to go with a port to Fabric and would like to keep adding features to the Forge mod as well, the Architectury API for [Forge](https://www.curseforge.com/minecraft/mc-mods/architectury-forge) and it's counterpart for [Fabric](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) will help you greatly.

If you need help with any parts of the Fabric loader, the Fabric API, or the Yarn mappings, [please visit The Fabric Project Discord server](https://discord.gg/v6v4pMv). I'm in no way affiliated with the Fabric Project Discord server apart from being a member who's used it for support myself.

I see your updates on r/feedthebeast and I'm incredibly impressed.

There's no pressure to make a Fabric port, least of all from me, but if you decide to go down that route, you've got a massive community who will give you support.

**Comment by MehVahdJukaar** [comment]
Thanks for the encouraging words :)
As I've said I will try to do at least something once I'm finished with major updates and version upgrades of the forge mod. I've already messed with fabric and It's not bad once you get the hang of it even if some thing require more work to be ported over cause of the missing api.
