### ISSUE TITLE
[🐞]: Incompatibility with Cobblemon's 1.5 Update

### ISSUE THREAD

**Issue by Natetromino** [MehVahdJukaar/Supplementaries#1050]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.8.10.jar

### Moonlight Lib Version

moonlight-1.20-2.11.18-forge

### Issue Detail

[crash-2024-05-15_15.43.35-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/15326186/crash-2024-05-15_15.43.35-server.txt)

The game hard crashes when trying to load into a world, but does boot to the main title screen. I removed all other mods excluding these two, and the game still does not work. Supplementaries did work with Cobblemon 1.4, so I also sent a bug report to that mod's devs as well. Thank you for your time, -Nate

**Comment by Natetromino** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/15326331/latest.log)

Here is the latest log as well

**Comment by MehVahdJukaar** [comment]
you are not using latest mod version. Also as message says its not a supplementaries issue. You can double check by removing the mod and trying all modded sherds, some or all will have missing textures

**Comment by CorneliusCornbread** [comment]
> you are not using latest mod version. Also as message says its not a supplementaries issue. You can double check by removing the mod and trying all modded sherds, some or all will have missing textures

This seems to be an issue with the version you have uploaded to Modrinth, would you be willing to update it?
