### ISSUE TITLE
[❓]: What is the stuff function used for in Credits.java?

### ISSUE THREAD

**Issue by moonleay** [MehVahdJukaar/Supplementaries#1056]
### Your Question

What is the stuff function used for in Credits.java?

### Detail

There is an unused function named "stuff" in Credits.java, which opens an URLConnection to a bit.ly address. Whilest it is commented in the source code, it is still included in the fabric version for 1.19.2 when downloading the binaries. What is this function used for? It seems to be an uncalled function. The function seems to be changed in versions of the mod made for 1.20.

Screenshot of decompiled binary for 1.19
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/74376181/040df413-068e-43cc-81e0-008f28fe71e7)

Screenshot of decompiled binary for 1.20
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/74376181/ea249fb0-44b1-4896-b088-fb592abb453d)

[Link to function in source code](https://github.com/MehVahdJukaar/Supplementaries/blob/1.20-split/common/src/main/java/net/mehvahdjukaar/supplementaries/common/utils/Credits.java#L237) (with commented URLConnection)

The bit.ly link seems to [redirect to Google](https://bit.ly/42g4UfZ+).

**Comment by MehVahdJukaar** [comment]
might be some code when i was tyring to figure out how connection stuff worked when i was tyring to fetch these files. They are currently fetched from github. I should clean that class up really

**Comment by moonleay** [comment]
Ah, this makes sense. Thank you for clarifying!
