### ISSUE TITLE
Server Crashes when lighting a gunpowder fuse

### ISSUE THREAD

**Issue by NJL5390** [MehVahdJukaar/Supplementaries#106]
Supplementaries Version: 0.16.0
Forge Version: 36.2.4
Minecraft Version: 1.16.5
Crash Report: https://gist.github.com/NJL5390/892e71b429d6f608e163d5f639757d56

Hi,

I noticed this crash after updating to the latest version of supplementaries (0.16.0). It happened when me and a friend were attempting to test out the new gunpowder features added in this update. This issue also makes the server crash whenever someone tries to join back into the server after the crash has happened the first time. To my knowledge this only seems to happen on a server.

**Comment by MehVahdJukaar** [comment]
I'll publish a fix shortly
