### ISSUE TITLE
[🐞]: Can't pick up safe even unbound or owned.

### ISSUE THREAD

**Issue by ShadwDrgn** [MehVahdJukaar/Supplementaries#1065]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-2.8.14

### Moonlight Lib Version

1.20-2.11.33

### Issue Detail

When I place a safe and then use a key on it, I can't harvest it even if i immediately try with a diamond pick. Even with the key. Even if i remove ownership and harvest it unbound the just disappears.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/2470781/9e765536-4656-4261-affc-e825bb9c9e51)
You can see there is a green check implying i'm using the right tool but it just vanishes when i try to harvest and it take longer than i expect to harvest too.

Note: The pickaxe is from SGear but note that I tried a vanilla diamond pickaxe too.

found this MAYBE related bug from ages ago:
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/897

**Comment by MehVahdJukaar** [comment]
did you change the mod config to now allow breaking non owned safes?

**Comment by ShadwDrgn** [comment]
> did you change the mod config to now allow breaking non owned safes?

I trued both and it disappears whether its keyed or not.  Whether the option is true or false as well

**Comment by MehVahdJukaar** [comment]
fixed
