### ISSUE TITLE
[❓]: I can't create a world on my build with the Supplematerials mod.

### ISSUE THREAD

**Issue by MazTankaz** [MehVahdJukaar/Supplementaries#1066]
### Your Question

How to make the build work with this mod -_-

### Detail

It's just that when creating a world in my build, minecraft crashes due to Supplematerials. Judging by the logs, the modification simply cannot find templates for banners from several other mods. Although, most likely I just misunderstood something, because my knowledge of English leaves much to be desired -_- 

[2024-06-11-1.log](https://github.com/user-attachments/files/15792603/2024-06-11-1.log)

Mod version: supplementaries-1.20-2.8.13
Moonlight lib version: moonlight-1.20-2.11.33-forge

The new version of the mod that came out a couple of hours ago has the same problem. I really want to have this mod on my build, that's why I'm asking for help. Please :З

**Comment by MehVahdJukaar** [comment]
issue from aether reux.

**Comment by MazTankaz** [comment]
> выпуск из эфира реукса.

Понял. Спасибо!
