### ISSUE TITLE
[❓]: Why is there no "crimson_lantern"?(1.20.1)

### ISSUE THREAD

**Issue by QianMuu** [MehVahdJukaar/Supplementaries#1070]
### Your Question

Why is there no "crimson_lantern"?

### Detail

wI'm using 1.20.1-forge
I noticed that some items are missing from this version. Like "crimson_lantern".
I like this lantern, why is it gone in 1.20.1?

![58879346-a320-4079-b377-3b4a41303573](https://github.com/MehVahdJukaar/Supplementaries/assets/50398180/9e5769ce-bc65-4531-bee5-8247fc4e134d)

**Comment by MehVahdJukaar** [comment]
they were removed because i didnt like them. you can get them in supplementaries squared mod
