### ISSUE TITLE
[🐞]: Unable to connect to dedicated server, tag sync failiure.

### ISSUE THREAD

**Issue by jakeismyname** [MehVahdJukaar/Supplementaries#1081]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.15-fabric

### Moonlight Lib Version

moonlight-1.20-2.12.1-fabric

### Issue Detail

https://mclo.gs/NDemotl

**Comment by MehVahdJukaar** [comment]
is this still an issue on latest verson?
