### ISSUE TITLE
[🐞]:  Quiver doesn not allow scrolling when using hotkey

### ISSUE THREAD

**Issue by lotusdrive** [MehVahdJukaar/Supplementaries#1087]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20 2-8-17

### Moonlight Lib Version

1.20 2-12-14

### Issue Detail

When using the hotkey to swap arrows the gui doesnt respond to scrolls or mouse movements.

**Comment by MehVahdJukaar** [comment]
and if you use the item instead you can scroll?

**Comment by lotusdrive** [comment]
yes it would seem that the bug has gone away and i cant reproduce it anymore i havent updated anything done anything any differently so im just gonna close the issue
