### ISSUE TITLE
[🐞]: Duplication bug for stacks over 64

### ISSUE THREAD

**Issue by K-Fitzpatrick** [MehVahdJukaar/Supplementaries#1090]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.20

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue Detail

Originally discovered [here](https://github.com/LunaPixelStudios/SteamPunk/issues/284).

### Describe the Bug

Using Sophisticated Storage's Stack Upgrade and Supplementaries' Sack (right-click-to-add functionality), you can duplicate any item you have more than a stack of (including unstackables).

### Reproduction Steps

1. Put more than 1 full stack in a Sophisticated Backpack with a Stack Upgrade
2. Left click a Sack (to hold it)
3. Right click the overfull stack
4. **The Sack will contain the full amount of the Backpack stack, but the Backpack will have only lost 1 stack**

### Screenshots and Videos
Before reproduction steps:
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/1942774/35a7a1d5-a1e0-4dea-881b-88a6332a78ac)

After reproduction steps:
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/1942774/90e832a0-4be1-4fb9-8dfc-679e9a2075a3)

### Minimal mod list to reproduce issue
1. Supplementaries
2. Sophisticated Backpacks
3. Quark

### Additional Info
Quark Shulker Boxes also have this right-click-to-add functionality, but they don't have the issue (they correctly subtract the amount taken from the Backpack's storage).

**Comment by MehVahdJukaar** [comment]
This should not be an issue in later versions
