### ISSUE TITLE
Quiver Tiers / More config

### ISSUE THREAD

**Issue by ShinryuAspect** [MehVahdJukaar/Supplementaries#1099]
**Before continuing**
Be sure to read the mod wiki page to verify that your requested feature isn't already added. Pay particular attention to the *configuration* section

I was wondering if it was something you had in mind or already planned for a future release. I really love the Supplementaries Quiver design and how it works, but I thought it could use either tiers (like you get the basic quiver via Skeleton drop or anything and you can upgrade it with materials (iron, gold, diamond, netherite...)) and/or being able to configure its slots (either by just enabling the basic tier with no upgrades but being able to configure its max amount of slots or by configuring the tiers' capacity).

**Comment by MehVahdJukaar** [comment]
I'm not a fan of tiered item. Quiver is supposed to be a unique item like bow or trident. You can configure it's slots already via the configs
