### ISSUE TITLE
Several textures are far larger than they should be.

### ISSUE THREAD

**Issue by Vaelzan** [MehVahdJukaar/Supplementaries#110]
While checking out a texture dump of Valhelsia 3 I noticed that these textures are 256x256 (or 256x64 for the sign post), and it appears unintentional since the other hanging signs are 16x16 (and 64x16 for the post):

https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/textures/blocks/hanging_signs/bamboo_blocks/hanging_sign_details_bamboo.png

https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/textures/blocks/hanging_signs/bamboo_blocks/hanging_sign_front_bamboo.png

https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/textures/entity/sign_posts/bamboo_blocks/sign_post_bamboo.png

There's also some 64x64 textures that probably don't need to be so big either:

https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/textures/blocks/rope_extension.png

https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/textures/blocks/rope_knot.png

Note that I have only checked the block texture atlas, so there may be textures in other atlases that need changing too.

These have a pretty big impact on AMD GPUs, especially with mipmaps turned on (as a side effect of how Minecraft handles animated textures). Supplementaries uses a little over 5% of the block texture atlas in Valhelsia 3 at the moment.

**Comment by MehVahdJukaar** [comment]
I'll address that. I didn't make those myself so I was unaware of that
