### ISSUE TITLE
[🐞]: Translation doesn't get loaded

### ISSUE THREAD

**Issue by darceno** [MehVahdJukaar/Supplementaries#1120]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.17

### Moonlight Lib Version

moonlight-1.20-2.12.12-fabric

### Issue Detail

Switching the game language to **pt_br** doesn't translate any of the supplementaries items and blocks, despite the translation file existing in the GitHub repository.

I did not test all languages, but I know that pt_pt, es_es and fr_fr works normally.

**Comment by MehVahdJukaar** [comment]
Somebody translation pull request probably included some missing commas or something
