### ISSUE TITLE
[🐞]: My computer crashed and now Minecraft si in the shadow realms

### ISSUE THREAD

**Issue by davethemodderguy** [MehVahdJukaar/Supplementaries#1122]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

Latest

### Moonlight Lib Version

Latest

### Issue Detail

I'm playing the game and suddently my computer smoked a BSOD. When I'm rejoining, the game breaks permanently
[crash-2024-08-20_14.54.05-fml.txt](https://github.com/user-attachments/files/16671250/crash-2024-08-20_14.54.05-fml.txt)
![image](https://github.com/user-attachments/assets/377
[mod list.txt](https://github.com/user-attachments/files/16671292/mod.list.txt)
62f91-5adc-46af-912c-7aa6179e89a2)
Here's everything you need for the issue. Pls resue my minecraft world

**Comment by MehVahdJukaar** [comment]
Pc crash probably caused some files to be corrupted.
Aka configs. 
Delete them

**Comment by davethemodderguy** [comment]
Specifically supplementarie's config?

**Comment by MehVahdJukaar** [comment]
Yes but others could be broken too
