### ISSUE TITLE
[❓]: Question with safe

### ISSUE THREAD

**Issue by Soulivan71** [MehVahdJukaar/Supplementaries#1126]
### Your Question

The new key can open my safe ?

### Detail
Hello !
How its working ?
Its lock to a player ? Or anyone crafting a key can open my safe chest ??

**Comment by Soulivan71** [comment]
@MehVahdJukaar ?

**Comment by MehVahdJukaar** [comment]
you need to rename it

**Comment by MehVahdJukaar** [comment]
read the wiki

**Comment by Soulivan71** [comment]
Can u send me the link plz ?
