### ISSUE TITLE
Recipe for Deepslate lamp crafts the blackstone lamp instead

### ISSUE THREAD

**Issue by NJL5390** [MehVahdJukaar/Supplementaries#113]
Supplementaries version: 0.17.0
Forge Version: 36.2.4

Hi,
I noticed that when looking at the most recent update to supplementaries and trying to find the recipe for the deepslate lamp, I found that JEI couldn't find a recipe for it. After some looking I found that the recipe for the deepslate lamp crafts the blackstone lamp instead. 
![2021-09-19_14 12 07](https://user-images.githubusercontent.com/64381954/133929147-4c05ea4c-0f27-4289-a9a2-f02096c78620.png)
So, I've gone to the liberty of fixing this recipe (which I tested through a custom datapack).
![2021-09-19_14 24 36](https://user-images.githubusercontent.com/64381954/133929205-70b64c96-810a-461a-a9f4-2d02523ecb83.png)

The recipe JSON file can be found here: https://gist.github.com/NJL5390/8e5613590a153498da4cf3f2e9e8d5a7

Thanks as always for the great work that you do on this mod!

**Comment by MehVahdJukaar** [comment]
awesome. included in 0.17.1
