### ISSUE TITLE
[🐞]: Crash when clicking "singleplayer"

### ISSUE THREAD

**Issue by axtrough** [MehVahdJukaar/Supplementaries#1134]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.8.18

### Moonlight Lib Version

moonlight-1.20-2.12.17-forge

### Issue Detail

Yeah so basically when i click on "singleplayer" the game crashed to desktop. 
[crash-2024-09-04_15.14.28-client.txt](https://github.com/user-attachments/files/16871104/crash-2024-09-04_15.14.28-client.txt)
[latest.log](https://github.com/user-attachments/files/16871108/latest.log)

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by MehVahdJukaar** [comment]
I see an error from elytra trim
