### ISSUE TITLE
[🐞]: Slingshots cannot take certain enchantments in Survival

### ISSUE THREAD

**Issue by Kalikars** [MehVahdJukaar/Supplementaries#1139]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.17-fabric

### Moonlight Lib Version

moonlight-1.20-2.12.17-fabric

### Issue Detail

In survival, the slingshot cannot be combined with Quick Charge, Multishot or Loyalty books on an anvil. It can accept Stasis, Unbreaking, or Mending books. JEI also reports the only compatible enchants are Unbreaking, Mending, and Stasis (+ Curse of Vanishing). Screenshots for all this below.

However, when slingshots are enchanted with Quick Charge or Multishot, the item works as expected. Note that this only works via anvil and not the /enchant command.

Additionally, Loyalty does not seem to work as an enchantment, even though previous versions supported this.

![2024-09-23_18 15 17](https://github.com/user-attachments/assets/6a009051-7ee8-417f-ad58-ddbdd633928d)
![2024-09-23_18 15 19](https://github.com/user-attachments/assets/eb60ae22-7aca-47d0-977d-1d030c070e5c)
![2024-09-23_18 15 20](https://github.com/user-attachments/assets/21e9dc79-ec32-4298-a07a-5129bf3a7d76)
![2024-09-23_18 15 22](https://github.com/user-attachments/assets/41434d47-1944-428f-976f-bdd647b42c9e)
![2024-09-23_18 16 19](https://github.com/user-attachments/assets/75f808a6-4480-4dcc-b367-ec350d0ff50d)
![2024-09-23_18 16 23](https://github.com/user-attachments/assets/235bb16d-125d-4f36-bae0-5774f8cef06f)
![2024-09-23_18 16 24](https://github.com/user-attachments/assets/2a75d04d-1c0e-44a2-8508-3dc0cedd9e08)
![2024-09-23_18 16 32](https://github.com/user-attachments/assets/c005c2d1-7647-4e96-b862-035f9d7115dc)
![2024-09-23_18 16 35](https://github.com/user-attachments/assets/30570d13-1d42-4941-9a53-a46726781745)
![2024-09-23_18 23 24](https://github.com/user-attachments/assets/71db152f-fb2f-4fa2-9a29-c729df609897)

**Comment by MehVahdJukaar** [comment]
that's a fabric limitation. its impossible to add items to an ehcnantment allowed list without major hacks. this is due to fabric poor and non existent api for enchantments. its part of the many many small features that arent in the fabric version of the mod. Luckily due to new ehcnant system this wont be an issue in 1.21 anymore

**Comment by Kalikars** [comment]
Ah, that sucks. I will close this then since there's nothing to be done about it. Thanks for the quick response
