### ISSUE TITLE
Fabric 1.20.1 crash on startup

### ISSUE THREAD

**Issue by Vmobik** [MehVahdJukaar/Supplementaries#1146]
### Your Question

I want to find out which mods conflict or which dependencies are missing

### Detail

[latest.log](https://github.com/user-attachments/files/17225643/latest.log)

**Comment by Xelbayria** [comment]
you should add Crash-report. the `latest.log` doesn't have much of clues. Usually, when a crash happened, the crash-report is generated in `~/.minecraft/crash-report/...`

**Comment by Vmobik** [comment]
[crash-2024-10-01_21.01.47-client.txt](https://github.com/user-attachments/files/17227920/crash-2024-10-01_21.01.47-client.txt)

**Comment by MehVahdJukaar** [comment]
Crash from create disel

**Comment by Vmobik** [comment]
Thank you, it helped
