### ISSUE TITLE
Ready-made quest packs FTB quests

### ISSUE THREAD

**Issue by Vmobik** [MehVahdJukaar/Supplementaries#1147]
### Your Question

Where can I find ready-made quest packs for the minecraft FTB quests mod?

**Comment by Xelbayria** [comment]
that would require you to do research yourself.

**Comment by MehVahdJukaar** [comment]
Why is this here? Has nothing to do with supplementaries

**Comment by Vmobik** [comment]
@Xelbayria I'm not looking for a modpack, but specifically ready-made quests in order to put them on my modpack. I'm just not very good at creating quests.

**Comment by Xelbayria** [comment]
I see. the hidden point is you can use these modpack with quests as a reference to create your own quest. OR you can use them (you'll have to credit the creator, tho). Creating quests is a lot of work.
