### ISSUE TITLE
Not compatible with Mohist

### ISSUE THREAD

**Issue by helixd-2k18** [MehVahdJukaar/Supplementaries#115]
I tried installing your mod on Mohist 1.16.5 but it crashes. 
https://github.com/MohistMC/Mohist/issues/1761

**Comment by MehVahdJukaar** [comment]
Honestly I have no idea how to even approach this. It seems like mohist is a huge core mod that changes a bunch of vanilla methods and stuff so it's very likely that it caused some issues. I'll try to see what I can do

**Comment by Column01** [comment]
We also have this issue: https://gist.github.com/bigbluu722/4e4cc052b352416df65945aa989c6c25

**Comment by Column01** [comment]
I'm wondering if the code here could cause it:
https://github.com/MehVahdJukaar/Supplementaries/blob/05d880c48234796213a328414b69a19a9a5537da/src/main/java/net/mehvahdjukaar/supplementaries/setup/DispenserStuff.java#L164-L167

That's the only code when following the exception that has a division operation. Although it's supposed to add `0.8f` to it to ensure non zero, I wonder if it might do the `0.4f + 0.8f` and then multiply that by `source.getLevel().getRandom().nextFloat()` which Mohist caused to return zero? Logically it shouldn't, but that's my only guess.

**Comment by Column01** [comment]
Easy test would be to do `((source.getLevel().getRandom().nextFloat() * 0.4F) + 0.8F)` and see if Mohist works

**Comment by Column01** [comment]
`nextFloat` can return a zero, I wonder if for some reason it's evaluating it oddly...

**Comment by Column01** [comment]
Oh. Looking at the actual jar code I see you intentionally divide by zero to crash.

**Comment by Column01** [comment]
If you can add some logging to the mod, I can run it on my server and see where exactly it fails to initialize. Not sure why that already doesn't exist since at the moment you just have a binary output of "It worked" or "It didn't" in a long list of initializing steps.

**Comment by Column01** [comment]
If I had to make a guess it has to do with your mixins, Mohist likes to break with Mixins

**Comment by Column01** [comment]
OR could this be an issue? `Configuration file /home/gameservers/atm6/config/supplementaries-common.toml is not correct. Correcting` and then it goes on to change a bunch of stuff in that config file to its defaults

**Comment by idisaj93** [comment]
arclight too

**Comment by MehVahdJukaar** [comment]
Yeah I'm intentionally crashing cause I kept getting weird errors when mod setup failed. Since mod setup is multithreaded it doesn't throw errors when it fails and instead keeps on going. this can cause all softs of issues, most noticeably if it doesn't get past structure registration it can nuke worlds.

**Comment by MehVahdJukaar** [comment]
Oh I've included a bunch of logging next update which will come out shortly so I can better debug this

**Comment by Column01** [comment]
Thank you, I appreciate it. I will let you know if I get a chance to confirm the issues, Mohist has since updated their Mixin version to fix a lot of bugs regarding it so it could already be fixed. I am testing the version that comes with the latest ATM6 update shortly

**Comment by Column01** [comment]
OK, It appears the latest update of Mohist (Build 800+) has fixed this issue. Thank you for adding the logging though, it can drastically help to fix issues like this faster!

**Comment by MehVahdJukaar** [comment]
oh awesome, glad to hear. I'll close this then
