### ISSUE TITLE
Cannon with Better Third Person compatibility

### ISSUE THREAD

**Issue by NotShaung** [MehVahdJukaar/Supplementaries#1156]
The new Cannon Block feature from **Supplementaries 1.20-3.0.0** seems have issue with compatibiliy with **Better Third Person**.

The Cannon’s view gets stuck at the player's current interaction angle and cannot be moved. If I try to adjust it, the view is forcibly pulled back to its original position.
I know that removing **Better Third Person** can fix this issue, but I hope there's a way to make them compatible.

Edited:I forgot one information, it was on Neoforge 1.20.1.

https://github.com/user-attachments/assets/43265daa-1a02-47c5-9ffc-b3a90e7e3e2e

**Comment by AzuryxxVortex** [comment]
This also happens with Leawind's Third Person, my take is that the functionality of these mods should be disabled when using a cannon, however this may require an update for all parties.

**Comment by MehVahdJukaar** [comment]
That's indeed how it would have to be done. It would require me to very haciky mixin I to their mod or they calling one of my classes to disable their renderer . Second option is cleaner of course

**Comment by MehVahdJukaar** [comment]
So you might want to ask them

**Comment by NotShaung** [comment]
> That's indeed how it would have to be done. It would require me to very haciky mixin I to their mod or they calling one of my classes to disable their renderer . Second option is cleaner of course

Ahh I see...Thanks for reply.
