### ISSUE TITLE
[🐞]: [1.20.1 Forge] Crash on startup with Creeper Overhaul

### ISSUE THREAD

**Issue by CaitlynMC** [MehVahdJukaar/Supplementaries#1159]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.0.1

### Moonlight Lib Version

moonlight-1.20-2.13.20-forge

### Issue Detail

Supplementaries version 1.20-3.0.1 for forge crashes on startup with Creeper Overhaul version 3.0.2 and dependencies (resourcefulconfig and geckolib) as the only other mods besides moonlight.
To replicate: Install the latest versions of Supplementaries and Creeper Overhaul on a new 1.20.1 Forge instance. The game should crash at the end of mod loading. Crash log and latest.log made on a fresh instance with only these mods here:
[crash-2024-11-02_12.00.43-client.txt](https://github.com/user-attachments/files/17607537/crash-2024-11-02_12.00.43-client.txt)
[latest.log](https://github.com/user-attachments/files/17607538/latest.log)

**Comment by DracoHero** [comment]
I have the same crash problem with both mods
[crash-2024-11-02_17.30.39-client.txt](https://github.com/user-attachments/files/17608314/crash-2024-11-02_17.30.39-client.txt)

**Comment by MehVahdJukaar** [comment]
Caused by a forge bug. Not my issue
