### ISSUE TITLE
Client crashes when placing or loading chunk with a flower box.

### ISSUE THREAD

**Issue by Lightman314** [MehVahdJukaar/Supplementaries#116]
Forge Version: 1.16.5-36.2.0
Supplementaries Version: supplementaries-1.16.5-0.17.1

Client-side crash when placing or loading into a chunk with a flower box. See the given crash report.

[crash-2021-09-26_16.36.53-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7232220/crash-2021-09-26_16.36.53-server.txt)

Fortunately we were able to move the players away from the offending chunk, but they're unable to return to their home until this gets fixed.

**Comment by MehVahdJukaar** [comment]
You need to update this https://www.curseforge.com/minecraft/mc-mods/selene/files

**Comment by Lightman314** [comment]
Probably should update the version dependency in the mods.toml file then so that others don't encounter this issue.

**Comment by MehVahdJukaar** [comment]
It actually is updated to require 1.7.1. thing is that previous version was just called 1.7 instead of 1.7.0 so it basically passes the check unfortunately. I did have a bunch of people asking the same and I'll fix next update of course by keeping that last digit in newer verison
