### ISSUE TITLE
[🐞]: Crash upon world creation with sodium/indium

### ISSUE THREAD

**Issue by ThePegNok** [MehVahdJukaar/Supplementaries#1166]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-3.0.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.20-fabric

### Issue Detail

When creating a world, it crashes when socium and indium are installed. 
Log:
[latest.log](https://github.com/user-attachments/files/17608489/latest.log)

**Comment by Xelbayria** [comment]
Have you tried without Sodium & Indium?  below is the whole point: 

> Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.

**Comment by squid233** [comment]
This issue doesn't persist without Sodium and Indium.

**Comment by Xelbayria** [comment]
You can mark it that you've tested it without Sodium and Indium

**Comment by MehVahdJukaar** [comment]
try new version and close if it doesnt happen anymore. just try with sodium on
