### ISSUE TITLE
[🐞]: Sign Post do not determine the type of wood

### ISSUE THREAD

**Issue by MrHimera** [MehVahdJukaar/Supplementaries#1168]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.0.1

### Moonlight Lib Version

 moonlight-1.20-2.13.20-forge

### Issue Detail

The signs posts are incorrectly identifying the type of wood and all the signs posts have "Oak Sign Post" in their title.

**Comment by MehVahdJukaar** [comment]
you mean the items? or the placed ones? this on 1.20 and not 1.21 right?

**Comment by MrHimera** [comment]
> you mean the items? or the placed ones? this on 1.20 and not 1.21 right?

The names of the items in the inventory are the same, although they should differ in the type of wood. This is on 1.20.1.
