### ISSUE TITLE
Breaking a Flower Pot that has Flax Seeds in it Destroys the Pot (and seeds)

### ISSUE THREAD

**Issue by Cinderheart** [MehVahdJukaar/Supplementaries#117]
Title, essentially.

Steps to reproduce:

#1 place flower pots.

#2 put several different modded flowers into flowerpots.

#3 break flowerpots.

Expected result: flower pots and flowers/seeds are returned to inventory.

Actual result: as expected, except for flax seeds.

**Comment by MehVahdJukaar** [comment]
I just published an update where I thought I fixed this. I just now realized that it's actually just partially resolved since it now drops either a seed or a pot. Full fix will come next update

**Comment by Cinderheart** [comment]
Thank you.
