### ISSUE TITLE
[🐞]: Crash when Faucet inputs Fluid into/out of Create fluid container?

### ISSUE THREAD

**Issue by AtobaAzul** [MehVahdJukaar/Supplementaries#1171]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.0.1

### Moonlight Lib Version

moonlight-1.20-2.13.20-forge

### Issue Detail

Reproduceable with just Create and Supplementaries (Dependencies and Amendments as well)

Steps to reproduce in the video:
https://cdn.discordapp.com/attachments/859316125958930462/1302430949170085908/Minecraft_Forge__1.20.1_-_Singleplayer_2024-11-02_21-32-07.mp4?ex=672816d8&is=6726c558&hm=2b35981b5a6731966efde9c50dc14ac8c75f7ce5ef9ba45f9d6879aef7b148d6&

One thing I noticed as well is how the faucet flickers a bit before appearing. Issue happens on worlds where this previously worked, as well. (Noticed this crash was a thing when I loaded into a chunk that used faucets.)

[crash-2024-11-02_21.32.12-server.txt](https://github.com/user-attachments/files/17608782/crash-2024-11-02_21.32.12-server.txt)
[latest.log](https://github.com/user-attachments/files/17608783/latest.log)

**Comment by TrkvonStpd1e11** [comment]
Same issue. Not only Create containers, but also fluid containers from other mods.

**Comment by MehVahdJukaar** [comment]
use latest moonlight
