### ISSUE TITLE
[🐞]: Crash on game load 

### ISSUE THREAD

**Issue by m0thknight** [MehVahdJukaar/Supplementaries#1172]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [ ] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-3.0.1

### Moonlight Lib Version

forge_1.20-2.13.20

### Issue Detail

[latest.log](https://github.com/user-attachments/files/17609089/latest.log)
[crash-2024-11-02_22.10.55-client.txt](https://github.com/user-attachments/files/17609090/crash-2024-11-02_22.10.55-client.txt)

**Comment by MehVahdJukaar** [comment]
same issue as https://github.com/MehVahdJukaar/Supplementaries/issues/1173
