### ISSUE TITLE
[🐞]: Crash with creeper overhaul

### ISSUE THREAD

**Issue by DOOMDUDE643** [MehVahdJukaar/Supplementaries#1173]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

3.0.1

### Moonlight Lib Version

2.13.20

### Issue Detail

crash with creeper overhaul
[debug.log](https://github.com/user-attachments/files/17609380/debug.log)
[latest.log](https://github.com/user-attachments/files/17609381/latest.log)

**Comment by DOOMDUDE643** [comment]
also experiencing another issue with supplementaries  and the pancakes
[New Paste 1.txt](https://github.com/user-attachments/files/17609396/New.Paste.1.txt)

**Comment by DOOMDUDE643** [comment]
logs originally provided for 3.0.1 may be incorrect logs. here is another 
[crash-2024-11-02_23.56.19-client.txt](https://github.com/user-attachments/files/17609411/crash-2024-11-02_23.56.19-client.txt)
[latest.log](https://github.com/user-attachments/files/17609418/latest.log)

**Comment by MehVahdJukaar** [comment]
This is a forge bug. Use new neoforge

**Comment by SettingDust** [comment]
> This is a forge bug. Use new neoforge

Is there new neoforge on 1.20.1?

**Comment by DOOMDUDE643** [comment]
damn cause that's gonna happen I've spent a long time developing this mod pack on forge and most of the mods have no version for neoforge

**Comment by DOOMDUDE643** [comment]
after the latest update it seems to work now! Todays actually my birthday so thanks for the present!
