### ISSUE TITLE
[🐞]: Cannon is invisible using shaders

### ISSUE THREAD

**Issue by Purrple101** [MehVahdJukaar/Supplementaries#1177]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.0.1

### Moonlight Lib Version

moonlight-1.20-2.13.20-forge

### Issue Detail

Cannon is invisible when used while using shaders

**Comment by MehVahdJukaar** [comment]
I'm am pretty sure this is not related to shaders. Did you turn flywheel backend off?

**Comment by Purrple101** [comment]
Yes

**Comment by MehVahdJukaar** [comment]
Meaning it persists with flywheel backend on?

**Comment by Purrple101** [comment]
i tried backend off, batching and instancing and it persists

**Comment by Purrple101** [comment]
no i hadn't

**Comment by MehVahdJukaar** [comment]
aparently flywheel auto turns it backend off when iris is installed. try new version. Stil you wont see cannons from afar and like checks and similar they will be laggier since they wont be using flywheel instances
