### ISSUE TITLE
[🐞]: Game crashes when loading world with Sodium installed

### ISSUE THREAD

**Issue by SlovakianMapper** [MehVahdJukaar/Supplementaries#1179]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-3.0.1

### Moonlight Lib Version

moonlight-1.20-2.13.20-fabric

### Issue Detail

Reproduceable with just Sodium and Supplementaries

Whenever I attempt to load into a world, my game crashes after a few seconds of the world loading process
[latest.log](https://github.com/user-attachments/files/17612046/latest.log)

**Comment by Xelbayria** [comment]
related to #1166 

Should be similar. Next time. check for a similar issue before you create a new issue.
