### ISSUE TITLE
[🐞]: Slimed effect makes player data invalid

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/Supplementaries#1180]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [ ] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaires-1.20-3.0.4

### Moonlight Lib Version

moonlight-fabric_1.20-2.13.21

### Issue Detail

When leaving a world after gaining the slimed effect (whether it be by getting hit with a slime ball or taking damage from a large slime), and then later rejoining, you'll be met with an invalid player data screen, essentially locking players out of their world.
![image](https://github.com/user-attachments/assets/6c9814e4-36b9-4b3d-ab83-56d3d9cd113e)
I have only tested this on fabric so far, but it could also be a problem on forge.

**Comment by MehVahdJukaar** [comment]
Should be fixed

**Comment by BlueIsADude** [comment]
indeed it is, ty!
