### ISSUE TITLE
[🐞]: Crash when clicking "Singleplayer" in the Main Menu

### ISSUE THREAD

**Issue by Jergeric** [MehVahdJukaar/Supplementaries#1186]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FORGE

### Supplementaries Version

supplementaries-1.21-3.0.4-alpha-neoforge

### Moonlight Lib Version

moonlight-1.21-2.15.10-neoforge

### Issue Detail

The game crashes when clicking on "Singleplayer" in the main menu. This issue is reproducible and occurs every time. The crash appears to be caused by a registry loading error.

Steps to Reproduce:

Start the game.
In the main menu, click on "Singleplayer".
The game crashes immediately.
Expected Behavior: The singleplayer mode should load without crashing.

Actual Behavior: The game crashes upon attempting to load the singleplayer screen.

Mod and System Details:
NeoForge Version: 21.1.74
Java Version: 21.0.3, Microsoft
Operating System: Windows 10
[crash-2024-11-05_03.28.23-client.txt](https://github.com/user-attachments/files/17626174/crash-2024-11-05_03.28.23-client.txt)
[latest.log](https://github.com/user-attachments/files/17626175/latest.log)

**Comment by MehVahdJukaar** [comment]
Try new verison

**Comment by Jergeric** [comment]
Thanks!
