### ISSUE TITLE
[🐞]: Cabin siding dont drop. (Couldn't parse data file)

### ISSUE THREAD

**Issue by Zeykehasnt** [MehVahdJukaar/Supplementaries#1190]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [ ] Always include a latest.log if you are crashing
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.0

### Moonlight Lib Version

moonlight-1.20-2.13.21-forge

### Issue Detail

Cabin Siding Block and Cabin Siding Stairs do not drop after breaking, this is due to a mistake in the loot table. I think...
![image](https://github.com/user-attachments/assets/620e7750-1ff4-4d0c-b8c1-c70eeef35068)
![major-spelling-mistake](https://github.com/user-attachments/assets/71bf56e9-f60d-4d65-8b60-aaa7d348f99b)

**Comment by MehVahdJukaar** [comment]
indeed

fixed
