### ISSUE TITLE
[🐞]: [Fabric 1.20.1] Crash when paired with TooManyOrigins

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/Supplementaries#1192]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaires-1.20-3.1.0

### Moonlight Lib Version

moonlight-fabric_1.20-2.13.21

### Issue Detail

Honestly, I dont even know why this happens, why its specifically this mod, or even if its on Supplementaries' end or not... but I've been getting COUNTLESS crashes, and have reduced my mods folder to 5 mods (Fabric API, Moonlight Lib, Supplementaries, Origins, and TooManyOrigins), and still it consistently crashes.

To replicate:
1. Create a new world.
2. Pick your preferred origin. It literally doesn't matter what you choose.
3. Grab yourself a Lumisene Bucket.
4. Place it down on the side of a block. The game should now crash, but if it doesn't
5. Destroy the Lumisene by placing a block on it. The game is basically guaranteed to crash at this point.

I have no clue how I whittled it down to these 5 mods, the crash logs dont mention anything about Origins, or even Supplementaries for that matter. And removing TooManyOrigins DOES fix the issue btw. The crash logs do mention something about a FluidloggedCollisionShape, but I'm honestly clueless.

I reported this to the TooManyOrigins github too btw, if this isnt a Supplementaries issue.
[latest.log](https://github.com/user-attachments/files/17638892/latest.log)
[crash-2024-11-05_15.26.54-client.txt](https://github.com/user-attachments/files/17638884/crash-2024-11-05_15.26.54-client.txt)

**Comment by MehVahdJukaar** [comment]
but from water walking fix. not my issue
