### ISSUE TITLE
Lunch Basket UI Change

### ISSUE THREAD

**Issue by Screamermod** [MehVahdJukaar/Supplementaries#1197]
The blue bar for the Lunch Basket is meant to signify the ratio of space a specific food item takes up in the Lunch Basket.

However, considering the bundle's use of that same blue bar to signify the ratio of the bundle filled, I think it would be more intuitive to use that bar to signify the ratio of the Lunch Basket filled? 

I nearly submitted a bug report because I had assumed it was the amount of space left in the Lunch Basket, before I caught on by testing out many different types of food in different amounts.

**Comment by MehVahdJukaar** [comment]
I can make it a different colour. Bundle has that shown as that's the moat significant information it ahoul show. Lunch basket has no item stack restriction so showing its fill level would be useless information from the inventory. Showing how many of the current food you have left is more useful on the other hand

**Comment by Screamermod** [comment]
Oh, that's a very good point, actually. I didn't consider that, my bad. Thank you for your input! 

As a minor addendum, I don't know how feasible this would be to implement, but it would be useful if there was some kind of Appleskin integration where, if you moused over the Lunch Basket, it would display the hunger and saturation values of the highlighted food item? 

Just because I like to choose the food item that fills my hunger up perfectly, and as it is, I'd have to take the item out to check the hunger and saturation values.

**Comment by MehVahdJukaar** [comment]
i'll look into it. Mind sharing a screenshot of aple skin tooltip on a normal food?

**Comment by Screamermod** [comment]
Cropped, but here:
![image](https://github.com/user-attachments/assets/c507644f-65a4-4039-bda3-1d25d9826c48)

Another example with Farmer's Delight food, showing truncated saturation values:
![image](https://github.com/user-attachments/assets/b21e82e4-90aa-4fa1-88df-c53a8e63b06a)

**Comment by MehVahdJukaar** [comment]
done
