### ISSUE TITLE
[🐞]: Soul fired compat failed to load

### ISSUE THREAD

**Issue by lzm11111111** [MehVahdJukaar/Supplementaries#1198]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FORGE

### Supplementaries Version

1.21

### Moonlight Lib Version

1.21-2.15.11-neoforge

### Issue Detail

When installing a lot of mods, the game will crash due to soul fired compat failed to load, I don't want to reproduce the issue by remove the mods one by one, it's too much effort

Even though I spent 30 minutes removing mods one by one to reproduce it, I still can't find the reason.

The game doesn't crash when only soul fired and supplementaries are installed.
[crash-2024-11-08_18.20.54-fml.txt](https://github.com/user-attachments/files/17676935/crash-2024-11-08_18.20.54-fml.txt)

![2024-11-08_18 22 30](https://github.com/user-attachments/assets/ce09a2a1-9187-4772-80d0-6cbbf977cc22)

**Comment by MehVahdJukaar** [comment]
does this happen with latest version?

**Comment by lzm11111111** [comment]
> does this happen with latest version?

Still an issue in latest version

**Comment by lzm11111111** [comment]
Issue still occurs in 3.0.13-alpha

**Comment by lzm11111111** [comment]
Closed as cannot reproduce
