### ISSUE TITLE
JEResources error

### ISSUE THREAD

**Issue by joseth257** [MehVahdJukaar/Supplementaries#12]
I have noticed a strange log error with version 1.16.5-0.9.23c after updating this on my personal modpack.
This error was reproduced in a minimal custom modpack when jei+justenoughresources and supplementaries are installed.
The error in question: https://pastebin.com/jPwVuJvu
I couldn't notice this breaking anything in particular, but since it appeared after updating this mod I decided to mention it here, just to be safe.

**Comment by MehVahdJukaar** [comment]
It might be throwing that since I've added my loot table to the shipreck one by putting in 20% globes and 80% air. It seem to work fine so I don't know why it's complaining and also why jei is looking at a loot table in the first place

**Comment by joseth257** [comment]
The one looking at the loot table is the addon Just Enough Resources (https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) (it adds a dungeon chest section to JEI). 

Testing it further: the error makes the globe not appear on jei as a shipwreck treasure loot (it also hides this one table in particular). However, the error is only visually (jei). By in world testing, the loot generates fine as far as I can see.

JER seems to not like air. It seems to ignore everything after the minecraft:air element, but does not impact any other loot table, so I couldn't notice immediately the impact the error had in the addon. 

I am not sure how the way you implemented differs from other modders. The only thing I can inform is that, I have not seem this happen with others mods that modifies loot tables (ex: botania, enigmatic legacy, pandoras creatures, mystical world, level hearts). They all work fine, and they loot appear normally on the dungeon chest jer section. The only other conflict related to loot tables I noticed was the annoying unnamed loot table bug running rampant, but this one doesn't seem to be related to that, since the loot is generating normally. 

My guess would be that the others are using something equivalent, without using a % with minecraft:air. But I am far too lacking in the skills, to say something with confidence.

**Comment by MehVahdJukaar** [comment]
Ok I've added in an actual chance condition instead of a set amount of air blocks. works better too since one can use non integer numbers
