### ISSUE TITLE
[🐞]: Supplementaries blocks replaced with other blocks?

### ISSUE THREAD

**Issue by 14oserpa** [MehVahdJukaar/Supplementaries#1203]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-3.1.2

### Moonlight Lib Version

fabric_1.20-2.13.21

### Issue Detail

I play on a 5 person Aternos server with my friends and 2 of them are having this issue.

Supplementaries blocks aren't showing up as what they're supposed to be, for example daub is now instead rendered as waterlogged placed blaze rods, stone tiles aren't showing up at all, lapis bricks turned into wooden braces and ash bricks are showing up as lapis brick walls.

![Skärmbild 2024-11-09 191935](https://github.com/user-attachments/assets/42069a07-80d2-44ee-a7e2-51e6bef6d837)
![Skärmbild 2024-11-09 191919](https://github.com/user-attachments/assets/b864068f-1006-4ee8-aa20-c98cb0d34a68)
![Skärmbild 2024-11-09 191944](https://github.com/user-attachments/assets/68c1dc66-47e6-4270-b1ef-20e4af185c52)

none of the textures are broken in single player.

if you walk into them or stand on them it will barely let you move, a lot like stepping into an unloaded chunk.
for some reason it works perfectly fine for me but not for my friends.

before this it worked fine but now it's just broke.

I've tried every trick i know. restarting their computers, turning off all texture packs and performance mods, deleting the supplementaries config file and downgrading to old versions.
none of them worked.

I've looked everywhere and couldn't find anything like this so this is my last resort.

here's my friends Modrinth log.
[message.txt](https://github.com/user-attachments/files/17689137/message.txt)

I'm sorry if i forgot to include something, did something wrong or didn't do something really obvious, I'm not a much of a tech guy.

**Comment by 14oserpa** [comment]
Update: i got infected
![image_2024-11-09_220825217](https://github.com/user-attachments/assets/19163179-38cb-453f-b593-d7c23ebb3ea7)

**Comment by MehVahdJukaar** [comment]
the only possible way that this can EVER happen is that you are on a server AND the mods you have dont 100% match the server.

**Comment by 14oserpa** [comment]
> the only possible way that this can EVER happen is that you are on a server AND the mods you have dont 100% match the server.

TY. I feel pretty stupid, i solved it by redownloading everysingle mod on the server and making sure i got the latest one.

Its solved now, thank you Mehvahdjukaar (amazing mod btw)
