### ISSUE TITLE
[🐞]: Crash on startup game

### ISSUE THREAD

**Issue by fronczek7f** [MehVahdJukaar/Supplementaries#1204]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.2

### Moonlight Lib Version

moonlight-1.20-2.13.22-forge

### Issue Detail

[main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Mod Sorting failed.
Everything starts after update to version 3.0.0, previous 2.8.17 working normally

[latest.log](https://github.com/user-attachments/files/17689503/latest.log)
[debug.log](https://github.com/user-attachments/files/17689504/debug.log)

**Comment by MehVahdJukaar** [comment]
caused by another mod with icorrect load order requirements in mods.toml.
a known one was a crate mod. 
It was fixed tho so
