### ISSUE TITLE
[🐞]: Crash when right clicign pancakes with neapolitan chocolates

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#1206]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-3.1.3

### Moonlight Lib Version

2.13.25

### Issue Detail

If you place some pancakes and right click them with neapolitan chocolate the game will crash

https://gist.github.com/thelegitdolt/193557337994fa0c97a1f4f76e497d08

**Comment by MehVahdJukaar** [comment]
Hm you got crash log? I don't see the crash there

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/df0d3b4ddf91f5c218ebeec75c14f36d

**Comment by MehVahdJukaar** [comment]
fixed
