### ISSUE TITLE
Allow disabling of arrow preview feature in configs

### ISSUE THREAD

**Issue by MiyuwiCodeStuffs** [MehVahdJukaar/Supplementaries#1208]
I already posted this as a bug, but I am requesting there please be a way to disable the arrow preview feature added in 3.0.0 in configs. This is because the game crashes with SAG weapons. Alteratively, there could be a way to make certain weapons such as SAG weapons exempt from this feature. I get that it is an issue with SAG, and I have already reported the issue on the SAG page, but checking the SimpleAnimatedGuns github page, it seems like no issues have been resolved there since 2023, and the last update to SimpleAnimatedGuns was in July. Also, even if they did make a fix, I am not using the main version of the mod but a fan retextured version, so the creator of that version would have to make an update as well, and I am not sure how to get into contact with the creator of that version. I am still going to post it there, but this whole process would most likely take months, so that I why I am asking here first.

**Comment by MehVahdJukaar** [comment]
such config already exists

**Comment by MiyuwiCodeStuffs** [comment]
Thanks!
