### ISSUE TITLE
[🐞]: Bubble Blower doesn't blow bubbles

### ISSUE THREAD

**Issue by edgeanescence** [MehVahdJukaar/Supplementaries#1214]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries 1.21-3.0.13 alpha

### Moonlight Lib Version

moonlight  1.21-2.16.3

### Issue Detail

When using the bubble blower, nothing happens. The bubble blower is still able to be enchanted and refilled with soap normally, but doing neither of these actually gets it to work.

**Comment by MehVahdJukaar** [comment]
try new version
