### ISSUE TITLE
[🐞]: Supplementaries needs version 1.21-2.17.0 of moonlight but it is installed

### ISSUE THREAD

**Issue by KdGaming0** [MehVahdJukaar/Supplementaries#1217]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

Supplementaries fabric_1.21-3.0.14-alpha

### Moonlight Lib Version

Moonlight Lib 1.21-2.17.0

### Issue Detail

The game wont lunch on the latest version of Supplementaries fabric_1.21-3.0.14-alpha because it needs Moonlight Lib 1.21-2.17.0 to be installed and only Moonlight Lib 1.21-2.16.0 is present. But i have installed the lates version from modrinth Moonlight Lib 1.21-2.17.0.
![image](https://github.com/user-attachments/assets/7c7aefbb-59aa-4f89-950b-8c8eae578df6)
![image](https://github.com/user-attachments/assets/f94baa39-4341-437b-83c5-496edd99f2ee)

**Comment by MehVahdJukaar** [comment]
version was somehow mislabled. Try the new published one should have the correct version number
