### ISSUE TITLE
[🐞]: Flax Seed Tick Crash

### ISSUE THREAD

**Issue by dhi-holo** [MehVahdJukaar/Supplementaries#1228]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.16-beta-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.3-fabric

### Issue Detail

The game crashes with the description "Exception ticking world" while a Flax Seed is planted.
This was tested in a full modpack initially, and then an environment with only Fabric API 0.108.0+1.21.1 (on Fabric 1.21.1 0.16.9), Moonlight 2.17.3 and Supplementaries 3.0.16. The attached logs are from this specific clean run test. 
[latest.log](https://github.com/user-attachments/files/17783593/latest.log)
[crash-2024-11-16_15.09.16-server.txt](https://github.com/user-attachments/files/17783595/crash-2024-11-16_15.09.16-server.txt)

How to recreate:
1) Plant a Flax Seed in Farmland
2) Wait for it to crash

**Comment by Xelbayria** [comment]
Just checking, does it happened via Server, not client.

**Comment by MehVahdJukaar** [comment]
Are you using the version published yesterday?

**Comment by dhi-holo** [comment]
> Just checking, does it happened via Server, not client.

Unsure, I only tested in singleplayer worlds

> Are you using the version published yesterday?

The one published 9 hours ago (on Modrinth) as of this reply, where the Wild Flax loot table was fixed

**Comment by MehVahdJukaar** [comment]
should be fixed
