### ISSUE TITLE
[🐞]: 1.20.1 Can't use sack in inventory

### ISSUE THREAD

**Issue by emeryplyler** [MehVahdJukaar/Supplementaries#1237]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.7

### Moonlight Lib Version

moonlight-1.20-2.13.26-forge

### Issue Detail

I'm not able to insert or extract items from the sack without just placing it down and opening it with right-click. In previous Minecraft versions I was able to use it in-inventory like a small bundle with no issues. I've tried running a fresh installation with no other mods and while all other Supplementaries features seem to work fine the sack is still the same. 
I really appreciated being able to open it without placing it down but understand if this was an intentional change. I have a lot of admiration for this mod and its cute and balanced features.

**Comment by MehVahdJukaar** [comment]
sack only has that feature as a quark integration thing

**Comment by emeryplyler** [comment]
Ohhhh just tested it with Quark and now it's fine. Thank you, sorry about the inconvenience

**Comment by crafting-Aaron** [comment]
Sorry for necroposting on this but I recall bundles being able to either scroll or hover over the items to select them. Is this something that can be done with the sacks? 

I am currently only able to right click to drop or put the first item in the sack one at a time. I can use Mouse Tweaks for the scroll wheel to do this more quickly but enabling or disabling that feature does not allow me to select the items within.

**Comment by emeryplyler** [comment]
I think that's from Easy Shulker Boxes, they let you scroll through shulker boxes and may be the mod that lets you do that with bundles too. I heard they also added bundle scrolling to the latest vanilla version of Minecraft.
