### ISSUE TITLE
[🐞]: Suspicious sand/gravel item dupeing bug

### ISSUE THREAD

**Issue by BluePentagram** [MehVahdJukaar/Supplementaries#1238]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-3.1.7

### Moonlight Lib Version

moonlight-1.20-2.13.25

### Issue Detail

Crafting a whole stack of items into Suspicious Sand or Gravel consumes only 1 out of the stack for the crafting and the resaulting craft has NBT on how much was in the crafting table at crafted, after placeing down the block NBT say it has a count of how much was used in the craft table, and when on brushed out it will give more then 1 (also does not always give out how much nbt says is there)
![2024-11-19_21 44 23](https://github.com/user-attachments/assets/b2db2d4e-8b19-4066-9403-1db8e3dd701c)
![2024-11-19_21 44 25](https://github.com/user-attachments/assets/e5283a26-2e94-4760-83d6-05afea2e6c51)
![2024-11-19_21 45 00](https://github.com/user-attachments/assets/81cffd5e-ddff-473e-9c54-5ba10b0bbd44)
![2024-11-19_21 45 08](https://github.com/user-attachments/assets/a5627638-e79d-4088-b4ba-84a87f341090)

**Comment by MehVahdJukaar** [comment]
should be fixed
