### ISSUE TITLE
[🗃]: Rope arrow enhancement

### ISSUE THREAD

**Issue by neonjuno** [MehVahdJukaar/Supplementaries#1245]
Rope arrows feel clunky to craft, especially with them not appearing in the recipe book. It would be a great QoL change if you could pick up ropes in your inventory by right clicking on top of them while holding a rope arrow, similar to how bundles work.

**Comment by MehVahdJukaar** [comment]
I thought I added this once but I forgot. What version are you on?

**Comment by neonjuno** [comment]
I'm on 1.20.1 Fabric on the latest version of Supplementaries. And yeah I discovered right after I posted this that you can click with ropes on the rope arrow but not backwards, I think that's pretty good already
