### ISSUE TITLE
Safe crash

### ISSUE THREAD

**Issue by jeremiahwinsley** [MehVahdJukaar/Supplementaries#125]
Crash log here:
https://gist.github.com/jeremiahwinsley/47fcc4d15ca3e6dba35928b36b337d6e

Pack: ATM6 1.8.7
Selene: 1.8.1
Supplementaries: 0.17.5

Reproducing this issue:
1. Open a single player creative world (also happens on servers)
2. Place a safe.
3. Switch to survival, and mine the safe. 
4. Upon hovering over the item in the inventory, the game crashes.

This line is crashing: https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/java/net/mehvahdjukaar/supplementaries/block/tiles/SafeBlockTile.java#L83
because `level` is Nullable here (and null in this instance).

**Comment by MehVahdJukaar** [comment]
This was fixed in 0.17.6
