### ISSUE TITLE
[🐞]: 1.21.1 Neoforge Crash when starting the game with supplementaries (maybe compatibilities issue)

### ISSUE THREAD

**Issue by SkyRunner55** [MehVahdJukaar/Supplementaries#1254]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-NEOFORGE

### Supplementaries Version

supplementaries-1.21-3.0.23-beta-neoforge

### Moonlight Lib Version

moonlight 1.21-2.17.7-neoforge

### Issue Detail

It crash on start, i don't know which of my mods cause this

![Capture d'écran 2024-11-30 012953](https://github.com/user-attachments/assets/35916c85-e456-4f7f-bc07-db7b85e93e59)

[crash-2024-11-30_01.34.07-client.txt](https://github.com/user-attachments/files/17963637/crash-2024-11-30_01.34.07-client.txt)

[latest.log](https://github.com/user-attachments/files/17963638/latest.log)

I tried my best to add the most info i could, i'm not a pro a bug reporting

**Comment by MehVahdJukaar** [comment]
From that thing you sent I only see an error from solarflux

**Comment by SkyRunner55** [comment]
i removed solar flux & hammer lib(core mod) it still crash

![image](https://github.com/user-attachments/assets/da979fbc-15cb-4d66-830d-4bb86b88a473)

[crash-2024-11-30_12.00.16-client.txt](https://github.com/user-attachments/files/17965158/crash-2024-11-30_12.00.16-client.txt)

[latest.log](https://github.com/user-attachments/files/17965159/latest.log)

**Comment by MehVahdJukaar** [comment]
try new supplementaries

**Comment by SkyRunner55** [comment]
the game start properly now
