### ISSUE TITLE
[❓]: Is the wild flax plant supposed to drop seeds?

### ISSUE THREAD

**Issue by CrashTestJava** [MehVahdJukaar/Supplementaries#1268]
### Your Question

Is the wild flax plant supposed to drop seeds?

### Detail

The wild flax plant does not drop seeds for me. Is this intentional? And if it is, how can I get seeds from the wild flax plant?

**Comment by MehVahdJukaar** [comment]
Are you using latest version?

**Comment by CrashTestJava** [comment]
Yes.

**Comment by FreyrDev** [comment]
Confirmed on Fabric 1.21.1. The loot table in the jar has a predicate `"tag": "c:tools/shear"`, changing this to `"items": "#c:tools/shear"` fixes the issue. This was [a vanilla change in 1.20.5](https://minecraft.wiki/w/Predicate#History) it seems so I suspect it affects Forge too.

**Comment by MehVahdJukaar** [comment]
fixed
