### ISSUE TITLE
[🐞]: Some placed book models are broken

### ISSUE THREAD

**Issue by FreyrDev** [MehVahdJukaar/Supplementaries#1270]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.25-beta-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.10-fabric

### Describe Issue

Some colours of placed books appear to use a different texture layout and thus don't have the correct UVs. Some book textures were updated in https://github.com/MehVahdJukaar/Supplementaries/commit/93b7ec2fe707e72886a9d46085937d89b804cadc and https://github.com/MehVahdJukaar/Supplementaries/commit/40ed0949b02b0fc82ba35b64a8d7274061dc84ba but not all.

Placed enchanted books also seem to be using any book texture at random rather than exclusively the enchanted one, which I assume is a bug.

![2024-12-06_01 35 41](https://github.com/user-attachments/assets/2f7a52d8-5d5b-49e7-bcaa-80a6a23bb828)

**Comment by Partonetrain** [comment]
Book Piles are invisible for me on NeoForge, but this might not be related

**Comment by maloryware** [comment]
Same thing - confirm that now the models disappear entirely. Not sure what changed on our side, either.

**Comment by MehVahdJukaar** [comment]
not really fixed but book piles have been properly disabled until they are ready to be added again
