### ISSUE TITLE
[🐞]: Breaking Bamboo spikes dropped posioned spikes instead of itself 

### ISSUE THREAD

**Issue by maureenferreira** [MehVahdJukaar/Supplementaries#1277]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-FABRIC

### Supplementaries Version

supplementaries-1.21-3.0.28-beta

### Moonlight Lib Version

moonlight-1.21-2.17.12

### Describe Issue

When breaking standard bamboo spikes, poisoned spikes are dropped instead.

**Comment by MehVahdJukaar** [comment]
fixed
