### ISSUE TITLE
[❓]: Where is the XP Fluid texture in the mod's files?

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/Supplementaries#1278]
### Your Question

Where is the texture for XP in a jar (or cauldron if amendments is installed) located in the source code?

### Detail

I'm making a resource pack that heavily changes how XP looks, with integrated mod support.. but I cant seem to find the textures for XP being put into a jar/cauldron anywhere.

![2024-12-15_12 28 27](https://github.com/user-attachments/assets/89901c5a-5f97-4744-bf33-daaf15364d5a)
Example image to show how the xp looks compared to the fluid version

**Comment by MehVahdJukaar** [comment]
moonlight lib as those "vanilla" fluids are defined there

**Comment by BlueIsADude** [comment]
ok thank you!
