### ISSUE TITLE
[🐞]: HTM (Hey That's Mine) Incompatibilty

### ISSUE THREAD

**Issue by VitaminJake** [MehVahdJukaar/Supplementaries#1279]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

3.1.10

### Moonlight Lib Version

2.13.37

### Describe Issue

A mod that locks chests called Hey That's Mine has a conflict with the presents in Supplementaries, when it checks to see if the container you're accessing is locked with htm or not. It causes an instant CTD when interacting with presents. I imagine this is not a concern/priority to fix, and I simply disabled presents. Just reporting.

**Comment by MehVahdJukaar** [comment]
Send log

**Comment by VitaminJake** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-12-19 12:00:21
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_746 cannot be cast to class net.minecraft.class_3222 (net.minecraft.class_746 and net.minecraft.class_3222 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57d5872c)
	at net.minecraft.class_2624.handler$edp000$htm$checkUnlocked(class_2624.java:539)
	at net.minecraft.class_2624.method_17489(class_2624.java)
	at net.minecraft.class_2621.method_17489(class_2621.java:147)
	at net.mehvahdjukaar.supplementaries.common.block.tiles.PresentBlockTile.method_17489(PresentBlockTile.java:112)
	at net.mehvahdjukaar.supplementaries.common.block.tiles.PresentBlockTile.interact(PresentBlockTile.java:123)
	at net.mehvahdjukaar.supplementaries.common.block.blocks.AbstractPresentBlock.method_9534(AbstractPresentBlock.java:85)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$bjm000$betterthirdperson$onDoItemUse(class_310.java:12096)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2624.handler$edp000$htm$checkUnlocked(class_2624.java:539)
	at net.minecraft.class_2624.method_17489(class_2624.java)
	at net.minecraft.class_2621.method_17489(class_2621.java:147)
	at net.mehvahdjukaar.supplementaries.common.block.tiles.PresentBlockTile.method_17489(PresentBlockTile.java:112)
	at net.mehvahdjukaar.supplementaries.common.block.tiles.PresentBlockTile.interact(PresentBlockTile.java:123)
	at net.mehvahdjukaar.supplementaries.common.block.blocks.AbstractPresentBlock.method_9534(AbstractPresentBlock.java:85)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.redirect$bjm000$betterthirdperson$onDoItemUse(class_310.java:12096)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['JavaEditionJake'/321199, l='ClientLevel', x=-262.30, y=74.00, z=-449.72]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (-282,62,-441), Section: (at 6,14,7 in -18,3,-28; chunk contains blocks -288,-64,-448 to -273,319,-433), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 504775547 game time, 13371087 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, continuity:default, continuity:glass_pane_culling_fix, minecraft:physicsmod, file/TZP_1.20.1_2.7.zip, file/FreshAnimations_v1.8.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1190562824 bytes (1135 MiB) / 2919235584 bytes (2784 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6636
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39805.31
	Virtual memory used (MB): 19049.20
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 109.40
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amendments: Amendments 1.20-1.1.12
			mixinsquared: MixinSquared 0.1.1
		amethyst_core: Amethyst Core 1.4.5+1.20.1
			common-protection-api: Common Protection API 1.0.0
			fzzy_config: Fzzy Config 0.1.2+1.20.1
		anvil_fix: AnvilFix development+20230626064221-1.20.1
		archers: Archers (RPG Series) 1.2.4+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			ranged_weapon_api: RangedWeaponAPI 1.1.0+1.20.1
		architectury: Architectury 9.1.12
		areas: Areas 5.6
		autohud: Auto HUD 6.1+1.20
		azurelibarmor: AzureLib Armor 2.0.3
		balm-fabric: Balm 7.0.7
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beansbackpacks: BeansBackpacks 0.27-v2
		bettercombat: Better Combat 1.8.4+1.20.1
		betterend: Better End 4.0.11
		betterf3: BetterF3 7.0.2
		betternether: Better Nether 9.0.10
		betterthirdperson: Better Third Person 1.9.0
		biomemakeover: Biome Makeover 1.20.1-1.11.4
			taniwha: Taniwha 1.20.0-5.4.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		camerautils: Camera Utils 1.20.1-1.0.9
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chat_heads: Chat Heads 0.10.25
		clean_tooltips: Clean Tooltips 1.0
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.40
		combatroll: Combat Roll 1.2.1+1.20.1
		continents: Continents 1.1.5
		continuity: Continuity 3.0.0-beta.3+1.20.1
		coroutil: CoroUtil 1.20.1-1.3.5
		crafttweaker: CraftTweaker 14.0.40
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		dehydration: Dehydration 1.3.6
		distractingtrims: DistractingTrims 2.0.2
		dsurround: Dynamic Surroundings 0.3.3
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.17b
		dynamiccrosshair: Dynamic Crosshair 7.0.4+1.20
			yaclx: YetAnotherConfigLibExtensions 1.3+1.20
		eatinganimationid: Eating Animation 1.9.4+1.20
		endermanoverhaul: Enderman Overhaul 1.0.3
		enhancedvisuals: EnhancedVisuals 1.6.7
		entity_model_features: Entity Model Features 2.1.2
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		expandedstorage: Expanded Storage 10.0.0-beta.3
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.9+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.15.11
		farmersdelight: Farmer's Delight 1.20.1-2.1.1+refabricated
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		fastquit: FastQuit 3.0.0+1.20+
		faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
		ferritecore: FerriteCore 6.0.0
		firstperson: FirstPerson 2.3.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		fwaystones: Fabric Waystones 3.3.2+mc1.20.1
		fzzy_core: Fzzy Core 0.3.4+1.20.1
		geckolib: Geckolib 4.2.3
			com_eliotlash_mclib_mclib: mclib 20
		glitchcore: GlitchCore 0.0.1.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
			net_jodah_typetools: typetools 0.6.3
		hardcorerevival: Hardcore Revival 12.0.4
		harvest_scythes: Harvest Scythes 2.5.6+mc1.20
		healthindicators: PlayerHealthIndicators 1.1.0
		heracles: Heracles 1.1.13
			hermes: Hermes 1.6.0
		hidehands: Hide Hands 4.2
		htm: Hey That's Mine 1.1.9
		immersive_aircraft: Immersive Aircraft 0.7.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		improvedmobs: Improved Mobs 1.20.1-1.12.4
		indium: Indium 1.0.34+mc1.20.1
		invisibleframes: Invisible Frames 1.1.0
		invmove: InvMove 0.8.4
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jewelry: Jewelry (RPG Series) 1.3.0+1.20.1
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.33.81
		map_atlases: Map Atlases 2.6.0
		memoryleakfix: Memory Leak Fix 1.1.2
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		moonlight: Moonlight 1.20-2.13.37
			mixinextras: MixinExtras 0.3.6
		mousetweaks: Mouse Tweaks 2.25
		mru: Mineblock's Repeated Utilities 1.0.4+1.20.1+fabric
		music_control: Music Control 1.6.3+1.20.1
		mutantmonsters: Mutant Monsters 8.0.3
		nethermap: Better Nether Map 3.0.0-1.20.1
		noisium: Noisium 2.0.3+mc1.20-1.20.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nyfsspiders: Nyf's Spiders 2.1.1
		overflowingbars: Overflowing Bars 8.0.0
		owo: oωo 0.11.1+1.20
		paladins: Paladins & Priests (RPG Series) 1.2.0+1.20.1
		physicsmod: Physics Mod 3.0.14
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_attributes: Pufferfish's Attributes 0.4.0
		puffish_skills: Pufferfish's Skills 0.12.2
		puzzleslib: Puzzles Lib 8.0.12
		repurposed_structures: Repurposed Structures 7.0.0+1.20-fabric
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rocks: This Rocks! 1.7.1
		rogues: Rogues & Warriors (RPG Series) 1.0.7+1.20.1
		roughlyenoughitems: Roughly Enough Items 12.1.712
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.11+1.20.1
		sereneseasons: SereneSeasons 9.1.0.0
		simplyskills: SimplySkills 1.5.0+1.20.1
		simplyswords: Simply Swords 1.55.0-1.20.1
		sleepwarp: SleepWarp 2.2.0_rc1+1.20.1
		slotswap: Slot Swap 1.1.0+mc1.20.1
		smallships: Small Ships 2.0.0-b1.1
		snowundertrees: Snow Under Trees 2.5.3+1.20.1
		sodium: Sodium 0.5.11+mc1.20.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.2
		spawnanimations: Spawn Animations 1.9.4+mod
		spell_engine: Spell Engine 0.15.6+1.20.1
		spell_power: Spell Power Attribute 0.11.0+1.20.1
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supplementaries: Supplementaries 1.20-3.1.10
		tawct: Time & Wind Custom Ticker 1.4.7+1.20
		tenshilib: TenshiLib 1.20.1-1.7.6
		terralith: Terralith 2.5.1
		treechop: HT's TreeChop 0.19.0
		trinkets: Trinkets 3.7.1
		universal_shops: Universal Shops 1.3.2+1.20.1
			common-economy-api: Common Economy API 1.1.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			polymer-core: Polymer (Core) 0.5.3+1.20.1
				polymer-networking: Polymer (Networking) 0.5.3+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.3+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.3+1.20.1
				polymer-common: Polymer (Common) 0.5.3+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.3+1.20.1
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		visualworkbench: Visual Workbench 8.0.0
		voicechat: Simple Voice Chat 1.20.1-2.4.18
		watut: What Are They Up To 1.20.1-1.0.12
		whats_that_slot: What's That Slot? 1.3.4+1.20.1
		wizards: Wizards (RPG Series) 1.2.0+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.0.10
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
	Loaded Shaderpack: Complementary.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.36, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, continuity:default, continuity:glass_pane_culling_fix, minecraft:physicsmod (incompatible), file/TZP_1.20.1_2.7.zip, file/FreshAnimations_v1.8.1.zip (incompatible)
	Current Language: en_us
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz

**Comment by MehVahdJukaar** [comment]
error happens in their code.

**Comment by MehVahdJukaar** [comment]
they have a very clear and blatant unsafe hardcast to ServerPlayer entity

**Comment by Xelbayria** [comment]
@VitaminJake There are 2 ways: 
1) You can drag the files (latest.log or crash-report) here. DEVs can download this to take a look
2) use https://mclo.gs/ to share link containing the latest.log|crash-report. **Preferred this so DEV don't have to download and take a look**

Next time, Please don't use copy/paste, thanks

**Comment by VitaminJake** [comment]
Thanks for looking this over guys. Could you help me understand what was wrong so I can go report it to them instead? I feel like I won't be a very effective messenger.
