### ISSUE TITLE
[🐞]: Golden and netherite doors and hatches

### ISSUE THREAD

**Issue by Number0ne1** [MehVahdJukaar/Supplementaries#1281]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.11

### Moonlight Lib Version

moonlight-1.20-2.13.37-forge

### Describe Issue

Golden and netherite doors and hatches do not respond to the redstone signal

**Comment by MehVahdJukaar** [comment]
Those doors are not just a reoclored iron door. Check the wiki
