### ISSUE TITLE
The 1.16 branch currently has an invalid loot table for flax blocks.

### ISSUE THREAD

**Issue by Vaelzan** [MehVahdJukaar/Supplementaries#129]
For some reason this differs from the master branch, and looks potentially half-finished (isn't a valid loot table - is shaped but uses shapeless ingredients instead of a key):

https://github.com/MehVahdJukaar/Supplementaries/blob/a7e875856ee2cdf2680de312e63be23ede3b7063/src/main/resources/data/supplementaries/recipes/flax_block.json

(it ended up in the 0.17.7 release on CurseForge)

**Comment by MehVahdJukaar** [comment]
fixed in 0.17.8
