### ISSUE TITLE
[🐞]: Game Crash - RopeSlideSoundInstance

### ISSUE THREAD

**Issue by stlouisn** [MehVahdJukaar/Supplementaries#1299]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1-NEOFORGE

### Supplementaries Version

1.21-3.0.29-beta

### Moonlight Lib Version

1.21-2.17.12

### Describe Issue

Game crashes after upgrading from version 3.0.28 to 3.0.29. Tested with only moonlight and supplementaries.

Suspect issue related to commit: https://github.com/MehVahdJukaar/Supplementaries/commit/78376835bb221d3e1eed7ad5b2c7bfcea9dde8ae

crash log: https://mclo.gs/xaklWIG

**Comment by MehVahdJukaar** [comment]
You are not using latest mod version

**Comment by TheLastFriendly** [comment]
If they've downloaded the mod from Modrinth, that is the latest version available for NeoForge found there. 

![grafik](https://github.com/user-attachments/assets/94744d93-075f-4b30-aac2-0490ac55a5c0)

**Comment by stlouisn** [comment]
You are correct, modrinth shows ver 3.0.30 but its not being offered as a download while trying to update via prism launcher. I manually downloaded and it's still not working.

**Comment by stlouisn** [comment]
Wait, its fabric only on modrinth. downloaded from CF and now its working with version 30

**Comment by stlouisn** [comment]
Closing
