### ISSUE TITLE
[1.16.5] Crash in multiplayer when using map on a bed

### ISSUE THREAD

**Issue by Lgmrszd** [MehVahdJukaar/Supplementaries#133]
Steps to reproduce:
- Go into multiplayer
- Grab a map, activate it and rightclick with it on a bed

Crashlog:
https://gist.github.com/Lgmrszd/d65bb854d08344e541f9c1dde72cb866

Versions:
forge: 36.2.8
supplementaries: 1.16.5-0.17.8
selene: 1.16.5-1.9.0

**Comment by MehVahdJukaar** [comment]
fixed in 0.17.9
