### ISSUE TITLE
[ Request ] Different Cog Block Textures & Break Sounds

### ISSUE THREAD

**Issue by zndrmn** [MehVahdJukaar/Supplementaries#136]
### **[ Request ] Different Cog Block Textures & Break Sounds**
_New cog block textures that are based off of the vanilla copper blocks and their color pallet, also using the vanilla copper block break sounds would be nice_
- - -
here's an edited version of the cog block that I made in minecraft's style
https://i.imgur.com/XK818Kg.png

**Comment by MehVahdJukaar** [comment]
That's how it looked originally. Those textures might still be in the texture folder. I didn't like the vanilla palette and decided to change it. I'm still debating if I should change it back or not but I've already heard some opinions and they seem more towards keeping its current look

**Comment by MehVahdJukaar** [comment]
sound are already there, new textures will be in the next update
