### ISSUE TITLE
All nearby mobs of the same type should target you when you pick one of them (either a baby or not) with a jar or a cage

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#14]
For instance, if you capture a baby zombified piglin with a cage, all nearby zombified piglins would aggro you; or if you capture a bee with a jar, all nearby bees would target you.

**Comment by MehVahdJukaar** [comment]
I like that, I'll try to add it in

**Comment by MehVahdJukaar** [comment]
coming next version

**Comment by Toma400** [comment]
Is that configurable, though? I feel like this should be at least possible to be overwritten by user.
