### ISSUE TITLE
[BUG] 1.16.5-0.17.10 Patchouli Guide

### ISSUE THREAD

**Issue by ladylexxie** [MehVahdJukaar/Supplementaries#140]
Latest.txt is getting spammed by errors from patchouli missing things.

https://pastebin.com/xTp8q1E6
https://pastebin.com/e8MUye43

**Comment by ladylexxie** [comment]
Yay! no more errors :D

**Comment by AlleCraft-alterego** [comment]
sorry but that was one of my drafts (and it was not to be published)
