### ISSUE TITLE
Suggestion: remove or change speaker block narrator "feature"

### ISSUE THREAD

**Issue by Coji4000** [MehVahdJukaar/Supplementaries#142]
The speaker blocks narrator setting bypasses all narrator settings on both the windows machine AND minecraft. it ignores volume settings and is as far as I can tell completely unblockable. It can be VERY loud and has no permissions to block users from abusing it. I've reduced the range to 0 to solve my issue but this is a huge issue IMO. I have some audio leveling going on my computer and when these blocks kick off narrator it is deafening.

**Comment by MehVahdJukaar** [comment]
I'll add 2 options on  both clients for locally muting it and server to globally disable the narrator feature

**Comment by MehVahdJukaar** [comment]
added 1 config option in latest version
