### ISSUE TITLE
Xp jars being improperly rendered.

### ISSUE THREAD

**Issue by Oxy8** [MehVahdJukaar/Supplementaries#143]
Mod list:
supplementaries-1.16.5-0.17.11
selene-1.16.5-1.9.0

After changing the jar capacity from 12 to 144 in the supplementaries-common.toml file, I noticed that the game renders improperly any amount of xp over 12 in the jar.  

[screenshot](https://prntscr.com/20y3g63)
[config file](https://prntscr.com/20y3ghd)

**Comment by MehVahdJukaar** [comment]
Does this happen for newly placed jars too? Are you on a server? I just tried and it does seem to work fine

**Comment by MehVahdJukaar** [comment]
Oh wait it only happens for the item, not the block. I'll fix
