### ISSUE TITLE
Bug: NoSuchMethodError Crash Using a CC: Tweaked Turtle Caused By Supplementaries

### ISSUE THREAD

**Issue by KasKatto** [MehVahdJukaar/Supplementaries#144]
Being around the mining turtle from CC: Tweaked causes an instant crash.
MC 1.16.5
Supplementaries 0.17.11
CC: Tweaked 1.99.0

Issue first was spotted on a server which is running the lastest build of Mohist (868), however this issue also occurs on singleplayer - it did not occur before updating from 0.17.10.

Crash log:
[crash-2021-11-29_23.08.58-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7621795/crash-2021-11-29_23.08.58-server.txt)

Please see:
https://github.com/cc-tweaked/CC-Tweaked/issues/972

**Comment by MehVahdJukaar** [comment]
CC just updated 4h ago and tweaked their API. I'm using its API and this means it broke. downgrade cc in the mean time. I'll publish an update soon-ish

**Comment by MehVahdJukaar** [comment]
fixed
