### ISSUE TITLE
Non [a-z0-9/._-] character in path of location: supplementaries:textures/blocks/hanging_signs/betterendforge/hanging_sign_front_helix_tree - Copy (2).png

### ISSUE THREAD

**Issue by Zarepheth** [MehVahdJukaar/Supplementaries#147]
Looks like Minecraft is now enforcing resource name and path requirements with Fatal errors that crash the game while it attempts to startup.

The first such error this evening was with Twilight Forest, they've produced a fix (very quickly, I should add), and until they push the fix to Curse Forge, I disabled that mod only to get the same error on a different resource with Supplementaries.

[Crash Report Gist](https://gist.github.com/Zarepheth/8f19e6718bb9ea76755886c241d006d7).

**Comment by MehVahdJukaar** [comment]
hmm wait did they push another 1.17 update or something? how come this worked before and now doesn't? I'm confused

**Comment by Zarepheth** [comment]
As @tamaized responded [here](https://github.com/TeamTwilight/twilightforest/issues/1402#issuecomment-983219807), some mods can be a bit aggressive in loading unused resources in other mods. And with a bit of trouble-shooting, I narrowed it down to "curios-forge-1.17.1-5.0.2.0.jar" - whose authors quickly fixed it: TheIllusiveC4/Curios#183

**Comment by Zarepheth** [comment]
I think Supplementaries has one or more unused resources with no longer valid paths or names, so when another mod erroneously loads those resources, MineCraft crashes.

**Comment by MehVahdJukaar** [comment]
I've removed those in the latest update
