### ISSUE TITLE
1.17.1 Forge Server Crash

### ISSUE THREAD

**Issue by B10Reaper** [MehVahdJukaar/Supplementaries#152]
I've got a weird crash that breaks in such a way that I can not get a proper error message, it just hangs during loading. It only happens with supplementaries-1.17.1-1.0.0, not with V0.18.1. Selene is V1.11, and loads fine. All other mods are up to date, and forge is 37.1
[I've taken a copy of the console and uploaded it here](https://gist.github.com/B10Reaper/630d0044731af0c6a8c7a85a1fd28e52), if it eventually crashes properly and generates a report I'll update with that.

**Comment by MehVahdJukaar** [comment]
I'll publish a fix soon. It's the same stuff that I fixed on 1.18

**Comment by MehVahdJukaar** [comment]
fixed
