### ISSUE TITLE
[Bug] [1.18.1] V: 1.0.7 Z-fighting on flags top texture

### ISSUE THREAD

**Issue by Vapaman** [MehVahdJukaar/Supplementaries#158]
The top texture of the flags has obvious z-fighting.
![2021-12-16_18 59 58](https://user-images.githubusercontent.com/77460466/146416419-a653ebba-3d59-4c2e-b2f3-e035e34d92ed.png)

Mod list:
configured-1.5.1-1.18.1.jar
MouseTweaks-forge-mc1.18-2.18.jar
ferritecore-4.0.0-forge.jar
AI-Improvements-1.18-0.4.0.jar
ToastControl-1.18.1-6.0.0.jar
jei-1.18.1-9.1.0.46.jar
TesseractAPI-1.18.1-0.1.jar
forge-1.18.1-39.0.5-universal.jar
appleskin-forge-mc1.18-2.2.0.jar
flywheel-forge-1.18-0.4.2-rc.jar
supplementaries-1.18-1.0.7.jar
GameMenuModOption-1.18-Forge-1.13.jar
create-mc1.18.1_v0.4a.jar
Clumps-forge-1.18.1-8.0.2.jar
selene-1.18-1.11.jar
Controlling-forge-1.18-9.0.4.jar
Placebo-1.18.1-6.0.1.jar
citadel-1.10.3-1.18.jar
alexsmobs-1.14.3.jar

**Comment by MehVahdJukaar** [comment]
hmm I can't replicate. Must be a conflict with one of those mods. does it happen on only 1 orientation?

**Comment by Vapaman** [comment]
It happens in all orientations.

The culprit seems to be create/flywheel, since it only happens with those installed.

**Comment by Vapaman** [comment]
Nevermind, it seems to happen even with just supplementaries and selenelib, no other mods installed.

**Comment by MehVahdJukaar** [comment]
yeah also cause I usually have flywheel installed. I'm not sure what's going on here since it doesn't happen with I boot up with it with the mod alone

**Comment by Vapaman** [comment]
If its any help, here is a debug crash log:
[crash-2021-12-20_22.39.09-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7747867/crash-2021-12-20_22.39.09-client.txt)

**Comment by Vapaman** [comment]
Its fixed in the newest version. Thanks!
