### ISSUE TITLE
Game crashes when adding many items/mobs or removing items/mobs from "supplementaries-common" config file?

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#16]
I mean, I don't know exactly what happened, but when I finished adding items and mobs to cage and jar configs, the game crashed before it even loaded. After that, I tried to remove many items and mobs I added previously, as well as the ones that were already there, but the game was still crashing. The only solution I had was removing the config. file, because the game would create another after that, and then I could play the game (without my custom config, unfortunatelly). Is there some limit on the amount of things I can put? I doubt, because the game was still crashing when I removed many of these things, so is there some other reason for this?

**Comment by MehVahdJukaar** [comment]
I suggest you use some editor like atom or vs code with the appropriate json extension when editing config files. That way they'll tell you when you are making mistakes like forgetting commas or that kind of stuff. There is no limit to them, you probably just forgot some " or ,

**Comment by Brun333rp** [comment]
ok, thanks for the help!
