### ISSUE TITLE
[bug] when bees fertilize flax, it sometimes pops the crop

### ISSUE THREAD

**Issue by esotericist** [MehVahdJukaar/Supplementaries#161]
forge 1.18.1-39.0.5, suplementaries-1.18-1.0.7.

ever since i brought bees home to my indoor farm, i started having my flax crops seemingly randomly get popped. it almost looked like trampling, except the farmland wasn't transformed to dirt. the problem was also restricted solely to my flax, even though i have alternating rows of carrots/flax for growth rate purposes.

eventually i managed to see it in action: a bee happened to fertilize flax, and the at the same time as the green particles showed up on the flax, the plant popped like it had gotten broken.

the one that i watched get popped happened to be fully grown. i've seen other flax be fertilized without trouble. so it seems to be connected to a bee fertilizing fully grown flax.

**Comment by MehVahdJukaar** [comment]
wait a sec bees can fertilize crops?? 0.0
Didnt know that lol. I'll check and try to fix

**Comment by MehVahdJukaar** [comment]
forgot to mentioned but I added a patch to specifically fix this issue in 1.1.0. Might also resolve similar issues with other double plant crops from other mods
