### ISSUE TITLE
Invisible Hanging Flower Pots

### ISSUE THREAD

**Issue by illuen** [MehVahdJukaar/Supplementaries#165]
The rope texture shows up, the pot itself doesn't. Modlist:
3dSkinLayers-forge-mc1.18-1.3.1.jar
absentbydesign-1.18-1.6.0.jar
Adorn-3.0.0+1.18.1-forge.jar
alexsmobs-1.15.0.jar
AmbientSounds_v5.0.0-pre04_mc1.18.1.jar
Amplified+Nether+1.0.1+~+Forge.jar
appleskin-forge-mc1.18-2.2.0.jar
Aquaculture-1.18.1-2.3.1.jar
awesomedungeon-1.1.3.jar
balm-2.3.1+0.jar
BetterThirdPerson-Forge-1.18-1.5.4.jar
bigbrain-1.4.0.jar
castle_in_the_sky-1.18.1-0.2.7.jar
catalogue-1.6.0-1.18.1.jar
chalk-1.18-1.0.0.jar
cherishedworlds-forge-1.18-5.1.1.0.jar
citadel-1.10.5-1.18.jar
cleancut-mc1.18-3.0-forge.jar
clear-skies-forge-mc118-2.0.88.jar
cloth-config-6.1.48-forge.jar
Clumps-forge-1.18.1-8.0.2.jar
collective-1.18.1-3.8.jar
comforts-forge-1.18-5.0.0.1.jar
configured-1.5.1-1.18.1.jar
CreativeCore_v2.4.1_mc1.18.1.jar
Cucumber-1.18.1-5.0.1.jar
curios-forge-1.18.1-5.0.3.0.jar
doubledoors_1.18.1-3.2.jar
EasyMagic-v3.2.0-1.18.1-Forge.jar
effective_for_forge-1.001.jar
enhancedcelestials-2.0.9-1.18.jar
FarmersDelight-1.18.1-1.0.0.jar
firstperson-forge-2.1.0-mc1.18.jar
furniture-7.0.0-pre27-1.18.1.jar
goblintraders-1.7.0-1.18.1.jar
gravestone-1.18.1-1.0.0.jar
guardvillagers-1.18.1.4.0.jar
habitat-1.1.1.jar
hexerei-0.1.7.jar
ItemPhysic_v1.4.19_mc1.18.jar
Jade-1.18-4.0.2.jar
jei-1.18.1-9.1.0.47.jar
kotlinforforge-3.0.0-obf.jar
LetSleepingDogsLie-1.18-1.1.1.jar
mcw-bridges-2.0.1-mc1.18.1.jar
morevillagers-FORGE-1.18-3.0.0.jar
MouseTweaks-forge-mc1.18-2.19.jar
notenoughanimations-forge-1.4.0-mc1.18.jar
OfflineSkins-1.18.1-v1.jar
OptiFine_1.18.1_HD_U_H4.jar
PuzzlesLib-v3.1.1-1.18.1-Forge.jar
Regrowth--1.18.1-1.39.0.24.jar
repurposed_structures_forge-4.0.7+1.18.1.jar
selene-1.18-1.11.jar
shutupexperimentalsettings-1.0.4-1.18+.jar
smarterfarmers-1.18-1.2.1.jar
sophisticatedbackpacks-1.18-3.12.1.433.jar
supplementaries-1.18-1.0.7.jar
Terralith_v2.0.5_~_Fabric+Forge.jar
treeharvester_1.18.0-4.1.jar
villagernames_1.18.0-3.4.jar
villagespawnpoint_1.18.1-1.9.jar
Xaeros_Minimap_21.22.6_Forge_1.18.jar
XaerosWorldMap_1.18.8_Forge_1.18.jar

**Comment by MehVahdJukaar** [comment]
I've had another report for this but oddly enough I can't replicate it so idk what's going on. Does it drop the pot when broken?

**Comment by illuen** [comment]
Yes, it does

**Comment by MehVahdJukaar** [comment]
hmm weird then. Can you confirm it still happens with the version I just posted?

**Comment by illuen** [comment]
Just checked, sorry for the delay. Yes, it still does.
![изображение](https://user-images.githubusercontent.com/95983352/147490917-fc07cb2d-7183-4024-87b2-f4dd37ee43b7.png)

**Comment by MehVahdJukaar** [comment]
fixed in 1.1.2
