### ISSUE TITLE
An incompatibility with the 1.17.1 version of Flywheel

### ISSUE THREAD

**Issue by ProfessorDrac** [MehVahdJukaar/Supplementaries#166]
I was browsing through the Curseforge Page, looking for new mods to play and I stumbled upon one of your mods - Supplementaries. I tried adding it to my mod selection but my game kept crashing. When troubleshooting, I realized that Supplementaries was incompatible with the 1.17.1 version of Flywheel, and therefore I had choose between using Supplementaries and, by extent, Create.

**Comment by MehVahdJukaar** [comment]
I need a crash report. I can't help you without a crash report

**Comment by ProfessorDrac** [comment]
Dear MehVahdJukaar,
In light of your request, I shall send you the crash reports later. Unfortunately, I have realized that I have placed the issue thread in the wrong GitHub page, for the issue isn't with Supplementaries itself, but with Selene Lib, another one of your mods. Nevertheless, I shall write another thread (this time in the correct page) tomorrow morning.
Kind regards,
Samuel Vieira

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MehVahdJukaar** [comment]
this is weird tho I'm not doing anything with flywheel in neither of those mods

**Comment by MehVahdJukaar** [comment]
so I tried doing this with other mods without my stuff and it still happens.

**Comment by Nilanurhayatiec** [comment]
i can't open curseforge, need .net framewok 4.6/4.8, but if me installed get message windows not support this framework , i used windows 10 pro version 1511

**Comment by thepetax15** [comment]
> i can't open curseforge, need .net framewok 4.6/4.8, but if me installed get message windows not support this framework , i used windows 10 pro version 1511

i have same problem, but it's clear now, for fix the problem you must be upgrade your windows to a new version, version 1509 and 1511 not supported .net framework 4.6 or 4.8

**Comment by Nilanurhayatiec** [comment]
> > i can't open curseforge, need .net framewok 4.6/4.8, but if me installed get message windows not support this framework , i used windows 10 pro version 1511
> 
> i have same problem, but it's clear now, for fix the problem you must be upgrade your windows to a new version, version 1509 and 1511 not supported .net framework 4.6 or 4.8

thanks ill try
