### ISSUE TITLE
How to make Ash

### ISSUE THREAD

**Issue by Teshu00** [MehVahdJukaar/Supplementaries#167]
This might be dumb but everywhere I looked I can not find a recipe for Ash or Ash bricks. I also have NEI installed but it doesn't tell me the recipe either

**Comment by MehVahdJukaar** [comment]
it's written on the 1.0.0 patch notes. I haven't updated the wiki yet, I've been pretty busy. You can get it by burning stuff or by finding it in urns

**Comment by Teshu00** [comment]
I couldnt find the patch notes but where do I burn things exactly?

**Comment by MehVahdJukaar** [comment]
you can find the patch notes on the curseforge page in the file section in each file description like here https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3551725
Alternatively they are all written on my discord page.
You can burn blocks wherever you want. location doesn't matter
