### ISSUE TITLE
[1.18.1] Supplementaries crashes server side with newest released Create + Flywheel.

### ISSUE THREAD

**Issue by Gbergz** [MehVahdJukaar/Supplementaries#170]
Title^

Updated Create & Flywheel to their latest versions and now game won't boot. Spits out Supplementaries errors.

Minecraft: 1.18.1
Forge: 39.0.5
Create: v0.4b
Flywheel: 0.5.0
Supplementaries: 1.1.2

Log/Crash-report: https://gist.github.com/Gbergz/1d50ba310c0db12328244e0f6a5ba7f5

**-** Gbergz

**Comment by MehVahdJukaar** [comment]
fixed in 1.1.3
