### ISSUE TITLE
[1.18.1] Default value in config file is wrong.

### ISSUE THREAD

**Issue by esilaanawic** [MehVahdJukaar/Supplementaries#171]
Default value for Cave Urns blacklist in config results in this warning:
`[14:56:35] [modloading-worker-0/WARN]: Configuration file C:\Users\Ecila Anawic\curseforge\minecraft\Instances\Just Create\config\supplementaries-common.toml is not correct. Correcting `
`[14:56:35] [modloading-worker-0/WARN]: Incorrect key spawns.structures.cave_urns.biome_blacklist was corrected from [ResourceKey[minecraft:worldgen/biome / minecraft:dripstone_caves], ResourceKey[minecraft:worldgen/biome / minecraft:lush_caves]] to its default, [ResourceKey[minecraft:worldgen/biome / minecraft:dripstone_caves], ResourceKey[minecraft:worldgen/biome / minecraft:lush_caves]].`
A backup file is created every time this happens, which is identical to the corrected file, so the backups keep piling up, and is very annoying.

**Comment by MehVahdJukaar** [comment]
Fixed
