### ISSUE TITLE
Crash on WorldGeneration or Save Startup

### ISSUE THREAD

**Issue by lhaeussler** [MehVahdJukaar/Supplementaries#174]
[2022-01-02-1.log](https://github.com/MehVahdJukaar/Supplementaries/files/7798576/2022-01-02-1.log)
[crash-2022-01-02_01.23.38-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/7798577/crash-2022-01-02_01.23.38-client.txt)

**Comment by MehVahdJukaar** [comment]
Check if all your other mods are up to date, specifically the one I have compat stuff for like create

**Comment by lhaeussler** [comment]
i have currently all mods up to date but error still persists

**Comment by MehVahdJukaar** [comment]
doesn't seem like it. I see flywheel that is outdated for example
