### ISSUE TITLE
A vulnerability about faucets causing fluids to replicate.

### ISSUE THREAD

**Issue by leezy2** [MehVahdJukaar/Supplementaries#185]
My version of the game is 1.18. When I tried to transfer lava from the jar on the left to the right with a tap, his amount quadrupled. And almost all fluids do. And it has nothing to do with the size of the container. Is this a bug？[
![G_2%CE0`F7~7_21TQ84YPMM](https://user-images.githubusercontent.com/51877554/149344918-d4f9fd6c-029e-4cf0-8a67-5111d86ae7c6.png)
![HN ~5OW1}$XG7FSXV(IDTRC](https://user-images.githubusercontent.com/51877554/149344928-03ccd73a-d360-44d7-9c0a-f5528d7a4333.png)
]

**Comment by leezy2** [comment]
And my Supplementaries is the latest version.

**Comment by MehVahdJukaar** [comment]
seems to be something I overlooked when making them be able to trasnfer lava. I'll fix asap

**Comment by MehVahdJukaar** [comment]
should be fixed now
