### ISSUE TITLE
Sack dublication glitch

### ISSUE THREAD

**Issue by IamRyan30** [MehVahdJukaar/Supplementaries#188]
Mc version: 1.16
Forge Forge: 36.2.4
Mod Version: supplementaries-1.16.5-0.18.2.jar

What's happening: When I try to sort items in a sack with the middle mouse button, the items get duplicated, some of them get lost and some of them.. are mirrored on other rows. I have the simple sorter mod for the mouse wheel sorting thingy.

![2022-01-28_16 23 57](https://user-images.githubusercontent.com/91336389/151563467-0a9f3868-25b4-4e56-a564-2f12e51760e1.png)

**Comment by MehVahdJukaar** [comment]
Should be fixed in 1.18.3
