### ISSUE TITLE
Speakers with Narrator mode not working

### ISSUE THREAD

**Issue by Ehllay** [MehVahdJukaar/Supplementaries#193]
When I try to use the narrator mode, it just displays a message in the chat. Nothing else

**Comment by MehVahdJukaar** [comment]
What version are you using? Could it be that you are playing a modpack which has disabled narrator mode in the configs?

**Comment by AcceptCookiesPls** [comment]
> What version are you using? Could it be that you are playing a modpack which has disabled narrator mode in the configs?

Latest version and custom modpack with untouched configs

**Comment by DWalz** [comment]
Can confirm. Chat messages by the Speaker block are not Narrated by the Narrator.
I first assumed that chat messages were filtered by message sender, but even command blocks and server messages seem to be narrated.

I took a shallow dive and think that `ClientRecievers#handlePlaySpeakerMessagePacket` is responsible for the error:
```java
withPlayerDo((p) -> p.sendMessage(str, Util.NIL_UUID));
```
The message is being sent without any sender UUID. I don't know the behavior of the Narrator around UUIDs but I do know that both command blocks and the server console have sender UUIDs.

**Comment by DWalz** [comment]
I've looked into it and I couldn't get it to work, even with a random sender UUID (`UUID#randomUUID`). Searching both Minecraft and Forge issue boards is a huge pain and the only thing I was able to gather is that system & server messages have been unreliably narrated int he past.

I was able to get it to work by manually checking for the clients narrator status and narrating if the narrator is on. I don't like that solution though.

**Comment by MehVahdJukaar** [comment]
I've neglected this issue since it was 1.16.5 only and 1.18.2 works but I finally found out what it was. The config was simply flipped so that means to fix this you can just turn off the narrator in the configs and it will have the opposite effect. Since its a minor thing and 1.16 is outdated I probably wont push any updates for this

**Comment by MehVahdJukaar** [comment]
So by turning off the narrator I meant the setting that isn't in the registry cobfigs. Have you done that?
