### ISSUE TITLE
[1.18.1] Planter turns into dirt when sapling grows into tree

### ISSUE THREAD

**Issue by Pentasis** [MehVahdJukaar/Supplementaries#194]
Reproduce:

1. Place a sapling in a planter
2. Apply Bonemeal
3. Sapling turns into tree and planter turns into dirt

Version 1.1.11
Forge 39.0.76

**Comment by MehVahdJukaar** [comment]
Not sure if I should fix or turn it into a feature by adding a planter breaking sound when it does

**Comment by Pentasis** [comment]
I was thinking the same thing. Breaking it would be more believable?

**Comment by MehVahdJukaar** [comment]
added in 1.3.0
