### ISSUE TITLE
Issue with new 1.2.0 dynamic wood detection system

### ISSUE THREAD

**Issue by TheCebulaShark** [MehVahdJukaar/Supplementaries#198]
I testet new update and want to share my feedback.
Wood detection system works very good with better azalea, however its nopt detecting wood types from ecologics and biome makover mods and even hides their planks versions in jei

forge: 39.0.79

**Comment by MehVahdJukaar** [comment]
Hm that's weird I tested with biome makeover and it was working for me. Ecologics was working too but for some reason it's planks block is just missing for some reason so it doesn't generate (might be a bug on the verison I was on)

**Comment by TheCebulaShark** [comment]
Same think with new quark woods

**Comment by TheCebulaShark** [comment]
> Hm that's weird I tested with biome makeover and it was working for me. Ecologics was working too but for some reason it's planks block is just missing for some reason so it doesn't generate (might be a bug on the verison I was on)

I probably found source of the problem. If number of mods is lower than 50 (minecraft + forge + 48 mods in mods folder) works fine, however if you have more than 50 mods this issue happend

**Comment by MehVahdJukaar** [comment]
did fix that in 1.2.1. Very weird issue indeed. Basically I was accessing the wood item of those planks too early nuking it (but only if this code would run after its registration which depends on mod list)
