### ISSUE TITLE
Crash after updating Supplementaries (0.18.3, Forge 1.16)

### ISSUE THREAD

**Issue by Toma400** [MehVahdJukaar/Supplementaries#199]
I updated Supplementaries yesterday and today I turned the game on.. but it didn't even get to start menu, because it turned out to have fatal crash. As far as I can read logs, it seems like fatal bug is caused by Supplementaries.

Also, as a proof, downgrading Supplementaries to 0.18.2 fixed the crash issue.

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/8096037/latest.log)

**Comment by MehVahdJukaar** [comment]
Use the latest version. 2 days ago I uploaded a buggy version

**Comment by Toma400** [comment]
Thanks a lot ^^
