### ISSUE TITLE
Compatibility issue - Supplementaries allows Locks (from Locks mod) to be bypassed by a stick

### ISSUE THREAD

**Issue by TheDaftWizard** [MehVahdJukaar/Supplementaries#202]
**(Minecraft 1.16.5, tested on Forge 36.2.19 and 36.2.20)**
Noticed this after installing the Locks mod into a modpack based on Crucial II. Managed to isolate it down to these two mods. Easily replicable:

1. Install Locks
2. Install Supplementaries (and Selene Lib)
3. Place any Lock on any Chest
4. Hold a Stick in hand and open the locked chest

This seems to only work if BOTH 
[tweaks.placeable_sticks] sticks = true _(in supplementaries-common.toml)_ AND
[initialization.blocks] stick = true _(in supplementaries-registry.toml)_
Setting either of these to false disables this issue entirely.

I have not tested what combination of settings will change this issue when it comes to client config vs. server config.
_EDIT:_ this issue also arises with the use of Blaze Rods and Books, leading me to believe it has something to do with how Supplementaries handles attempts to place Sticks, Blaze Rods and Books.

I'm posting this in the Locks page as well
https://github.com/Melonslise/Locks

**Comment by carthon** [comment]
I tried again with the stick and the book, but seems that the bug is not fixed
