### ISSUE TITLE
Waystones as Map Markers

### ISSUE THREAD

**Issue by Spazmunki13** [MehVahdJukaar/Supplementaries#204]
Hello! I have really enjoyed playing with your mod, so thank you for making it. :smile: 

I would like to suggest possibly adding compatibility with Waystones mod, so that we can mark them on our maps. I think it could be really useful for those of us who also use that mod.

Thank you!

**Comment by MehVahdJukaar** [comment]
coming next update

**Comment by Spazmunki13** [comment]
Wooh! Thank you! 🙂

**Comment by MehVahdJukaar** [comment]
added
