### ISSUE TITLE
supplementaries-1.18.1-1.2.3: Config to disable placing books doesn't work.

### ISSUE THREAD

**Issue by Cinderheart** [MehVahdJukaar/Supplementaries#212]
The 4 high piles of enchanted books still crashes and corrupts worlds, so I thought that disabling being able to place books would fix things. However, that config doesn't seem to do anything, and I can still place books (and crash my game.)

**Comment by Cinderheart** [comment]
I also have Jade installed, that could be it. I really don't want to switch off of it, it's such a good alternative to dealing with the hassle that is the other HWYLA alternatives.

Still, my bug report is for the config to disable placing books not working. I cannot turn the feature off.

**Comment by MehVahdJukaar** [comment]
Hmm that's weird I tested that and it was working. I start to wonder if I uploaded the right file

**Comment by MehVahdJukaar** [comment]
fixed in 1.18.2 version
