### ISSUE TITLE
[1.15.2] Several recipes in the 1.15.2 release use 1.16-only items.

### ISSUE THREAD

**Issue by Vaelzan** [MehVahdJukaar/Supplementaries#22]
The ones that I was able to spot in the log are:

`[15Feb2021 16:43:10.446] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe supplementaries:stone_lantern_recipe
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:shroomlight'` - you could set this to use the "Extended Nether Backport" version of the item (a mod that does add Shroomlight), or otherwise substitute the recipe with something else from vanilla Minecraft.

`[15Feb2021 16:43:10.641] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe supplementaries:sconce_ender_recipe
com.google.gson.JsonSyntaxException: Unknown item 'endergetic:ender_torch'` - The Endergetic Expansion doesn't have Ender Torches in 1.15.2, so the item either shouldn't exist or needs to use a different recipe.

And one loot table issue:
`[15Feb2021 16:43:50.851] [Render thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]: Couldn't parse loot table supplementaries:blocks/stone_lamp
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'supplementaries:glowstone'`

Side note: We're getting ready to update two of our 1.15.2 packs (Valhelsia 2 and Valhelsia: Origins) with Supplementaries within the next day or two. I can add working recipes and fix the loot table on our end if needed (although I think the errors will still clog the log file), but if you have spare time in the near future a 1.15.2 update would be extremely appreciated. I completely understand if that isn't practical though, since a lot of developers have dropped 1.15.2 support entirely anyway.

I was going to suggest that I could make a PR with the fixes if that makes things easier, but I can only see the 1.16.5 branch on GitHub. :(

**Comment by MehVahdJukaar** [comment]
well I didn't have plans to update 1.15 but since it had some issues (mainly server syncing stuff when changing configs) I've decided to update one last time. Took me a while, I'm not going to lie, but I hope it was worth it. I've changed all the recipes and removed 1.16 stuff

**Comment by Vaelzan** [comment]
I really appreciate the effort!

I'm not sure what you consider worth it, but at the moment we're still getting about 100k downloads per month of Valhelsia 2, and probably will continue to do so as long as it's a CurseForge featured pack, so you should see a similar rise in download count, hopefully. :)

**Comment by MehVahdJukaar** [comment]
Well I had alot of other people asking for a 1.15 update so I'm happy they'll be able to enjoy the latest version. I don't know why they won't update to 1.16 though.

**Comment by jobukkit** [comment]
Is the source code of the 1.15 version available? The sconce doesn't emit any light. I wanted to try to fix it myself, but there's no 1.15 branch.

**Comment by MehVahdJukaar** [comment]
I don't have that anymore. 1.15 version is extremely old, missing almost all of the features in their current form (everything has been rewritten and improved at one point or another) and I don't recommend anybody to use that
