### ISSUE TITLE
[1.18.1] Notice board just shows a random scrolling text

### ISSUE THREAD

**Issue by GeheimagentNr1** [MehVahdJukaar/Supplementaries#220]
Minecraft Version: 1.18.1  
Forge Version: 39.1.2  
Mod Version: 1.2.5

I updated this mod from version 1.2.3 to 1.2.5. Before the notice boards showed the text written in the book inside it, now it only shows this random scrolling text´:  
![2022-04-01_22 44 31](https://user-images.githubusercontent.com/20889593/161341731-1cd1cda7-819a-48e5-a943-b8b82578565f.png)

Edit: I just tested it for 1.2.4 and 1.2.3 and got the same result.

**Comment by MehVahdJukaar** [comment]
that's the bee movie script

**Comment by MehVahdJukaar** [comment]
also check the date
