### ISSUE TITLE
Cant join world

### ISSUE THREAD

**Issue by freopt** [MehVahdJukaar/Supplementaries#225]
1.18.2
Happens when I create or world or try to join the one that was just created
[relevant part I think](https://gist.github.com/freopt/76496fe450b09ab236841a41f2a2a00f)
[full log](https://github.com/MehVahdJukaar/Supplementaries/files/8456172/latest.log)
If I remove supplementaries and selene its fixed

**Comment by MehVahdJukaar** [comment]
That log isnt helpful since it's one in which you do not have the mod installed

**Comment by freopt** [comment]
[2022-04-08-5.log](https://github.com/MehVahdJukaar/Supplementaries/files/8457235/2022-04-08-5.log)
my bad

**Comment by MehVahdJukaar** [comment]
I'm not sure what's causing this but I've added some logs so it should at least say what went wrong this time & it might possibly even partially fix it. If it does can you send me those logs?

**Comment by freopt** [comment]
it seems to be fixed now, I can join the world
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/8459480/latest.log)
