### ISSUE TITLE
Hanging signs item textures bugged

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#226]
<img width="361" alt="Screen Shot 2022-04-08 at 10 14 00 PM" src="https://user-images.githubusercontent.com/50085439/162557489-e05c98e7-53dd-468c-9d5e-c7fd573e3fef.png">
i'm guessing this is a bug with models stuff

**Comment by thelegitdolt** [comment]
the placed blocks are fine though

**Comment by thelegitdolt** [comment]
i will provide mod list if needed

**Comment by MehVahdJukaar** [comment]
I need your logs. Very weird since I thought I even removed that particular item model

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/025a5cf9e7f87326bbb31364baf74681

i got chu

**Comment by MehVahdJukaar** [comment]
So this is so weird. it's as if somehow you have some older models from older version still there. Do you have any resource pack installed? maybe try with a fresh install (with all the mods) and see if it does that
