### ISSUE TITLE
Honey in hourglass is missing its texture. 1.18.2

### ISSUE THREAD

**Issue by TehFoxFire** [MehVahdJukaar/Supplementaries#228]
Issue: Honey is missing texture in hourglass
![Screenshot_20220411_180207](https://user-images.githubusercontent.com/20863498/162847159-4d85c891-4818-4fc1-b1e9-782bec17802b.png)

Forge version: 40.0.44
Mod version: 1.3.5
Minecraft: 1.18.2

**Comment by MehVahdJukaar** [comment]
should be fixed in latest version
