### ISSUE TITLE
Quark interaction "Experimental Settings"

### ISSUE THREAD

**Issue by RobinBrossard42** [MehVahdJukaar/Supplementaries#230]
Having quark and supplementaries installed together, results in "Worlds using Experimental Settings are not supported", even on newly created worlds.
No other known issues.

Minecraft: 1.18.2
Forge: 40.0.54
AutoRegLib: 1.7-53
Quark: 3.2-349
Selene Lib 1.15.1
Supplementaries: 1.3.6
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/8509140/latest.log)

**Comment by MehVahdJukaar** [comment]
Does this result in a crash or misbehaviour? Or is it just that it makes that experimental settings popup appear?

**Comment by RobinBrossard42** [comment]
It's just the experimental settings popup. I was looking to update my server and I got a little spooked by it, and I thought you guys should know.

**Comment by MehVahdJukaar** [comment]
That's normal tho
