### ISSUE TITLE
[1.18.2] Missing candelabra and candle holders?

### ISSUE THREAD

**Issue by MonaMoonlight** [MehVahdJukaar/Supplementaries#234]
There are no candelabra or candle holders when I look in creative inventory or JEI.
Do they need to be enabled manually in the config?
I found no entries for them set to false.

**Comment by BookerCatch** [comment]
I noticed you have the magma cream block commented out as well. Just bringing that up in case this one was a mistake.

**Comment by MehVahdJukaar** [comment]
they are back
