### ISSUE TITLE
1.18.2 1.3.7 Crash on Server Startup

### ISSUE THREAD

**Issue by ToastiMan** [MehVahdJukaar/Supplementaries#236]
Server Crashes on Startup. Forge Version is 1.18.2-40.1.0.

Searched for 2 hours, definitly seems to be a Problem with Supplementaries.

"Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER"

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/8596805/latest.log)

**Comment by MehVahdJukaar** [comment]
update Selene Library. You are using a buggy version 5 updates behind
