### ISSUE TITLE
Errors in the logfile on a clean world with no other mod/resourcepack/shaderpack

### ISSUE THREAD

**Issue by ccrowles** [MehVahdJukaar/Supplementaries#238]
As per title, I'm getting errors in the console log even on a new world with no other mods aside from Supplementaries and Selene Lib, no resourcepacks, no shaderpacks, etc.

Minecraft version: 1.18.2
Forge version: 40.1.16

Logfile: [here](https://0x0.st/om-L.txt).

**Comment by MehVahdJukaar** [comment]
Those are all harmless, recipe ones show up as intented (by forge)

**Comment by ccrowles** [comment]
Understood, thanks
