### ISSUE TITLE
[Suggestion] Keyring, and Curios support

### ISSUE THREAD

**Issue by ChloeDawn** [MehVahdJukaar/Supplementaries#24]
It would be nice to have a keyring item for storing multiple named keys in one slot; following this, it would be nice if said keyring could be stored in a [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) slot, possibly a dedicated keyring slot type?

**Comment by MehVahdJukaar** [comment]
Seems like a nice Idea, I'll try to add that in

**Comment by MehVahdJukaar** [comment]
I've added curios support for normal keys in the latest update. I will probably add keyrings later
