### ISSUE TITLE
Cannot harvest ash (1.18.2)

### ISSUE THREAD

**Issue by Grimalakin** [MehVahdJukaar/Supplementaries#241]
As title says, I cannot harvest ash. according to the Wiki, it says a shovel is required (makes sense), but the only thig that happens is the block breaks. I've tried using silk touch enchanted shovels, fortune enchanted shovels, unenchanted shovels.. tried harvesting the layers as well as the full block and, nothing. just a broken block
currently using the most recent version (1.3.7)

**Comment by MehVahdJukaar** [comment]
weird. I cant replicate that

**Comment by Grimalakin** [comment]
I've found the issue...
don't know the specifics, but apparently there's a conflict between Supplementaries and Project Brazier
https://www.curseforge.com/minecraft/mc-mods/project-brazier
will post this in their bug tracker..
