### ISSUE TITLE
Alex's Mob's catfish jar crash

### ISSUE THREAD

**Issue by Helpbot3000** [MehVahdJukaar/Supplementaries#242]
---- Minecraft Crash Report -------- Minecraft Crash Report ----// You're mean.
Time: 5/11/22, 5:22 PMDescription: Unexpected error
java.lang.IllegalArgumentException: value already present: alexsmobs:catfish at com.google.common.collect.HashBiMap.put(HashBiMap.java:310) ~[guava-31.0.1-jre.jar%2328!/:?] {} at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.0.1-jre.jar%2328!/:?] {} at java.util.Map.putIfAbsent(Map.java:826) ~[?:?] {re:mixin} at net.mehvahdjukaar.supplementaries.common.capabilities.mobholder.BucketHelper.associateMobToBucketIfAbsent(BucketHelper.java:96) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.doInteract(AbstractMobContainerItem.java:309) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.JarItem.doInteract(JarItem.java:94) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.m_6880_(AbstractMobContainerItem.java:93) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.minecraft.world.item.ItemStack.m_41647_(ItemStack.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A} at net.minecraft.world.entity.player.Player.m_36157_(Player.java:984) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B} at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105226_(MultiPlayerGameMode.java:370) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.optifine.override.PlayerControllerOF.m_105226_(PlayerControllerOF.java:111) ~[OptiFine_1.18.2_HD_U_H7.jar%2381!/:?] {re:classloading} at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1551) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1846) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1663) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at com.google.common.collect.HashBiMap.put(HashBiMap.java:310) ~[guava-31.0.1-jre.jar%2328!/:?] {} at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.0.1-jre.jar%2328!/:?] {} at java.util.Map.putIfAbsent(Map.java:826) ~[?:?] {re:mixin} at net.mehvahdjukaar.supplementaries.common.capabilities.mobholder.BucketHelper.associateMobToBucketIfAbsent(BucketHelper.java:96) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.doInteract(AbstractMobContainerItem.java:309) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.JarItem.doInteract(JarItem.java:94) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.mehvahdjukaar.supplementaries.common.items.AbstractMobContainerItem.m_6880_(AbstractMobContainerItem.java:93) ~[supplementaries-1.18.2-1.3.7.jar%2375!/:1.18.2-1.3.7] {re:classloading} at net.minecraft.world.item.ItemStack.m_41647_(ItemStack.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A} at net.minecraft.world.entity.player.Player.m_36157_(Player.java:984) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B} at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105226_(MultiPlayerGameMode.java:370) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A} at net.optifine.override.PlayerControllerOF.m_105226_(PlayerControllerOF.java:111) ~[OptiFine_1.18.2_HD_U_H7.jar%2381!/:?] {re:classloading} at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1551) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1846) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A}-- Affected level --Details: All players: 1 total; [LocalPlayer['TurboSoggy24'/161, l='ClientLevel', x=90.90, y=87.00, z=-74.34]] Chunk stats: 961, 618 Level dimension: minecraft:overworld Level spawn location: World: (0,89,0), Section: (at 0,9,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) Level time: 7430 game time, 7430 day time Server brand: forge Server type: Integrated singleplayer serverStacktrace: at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:516) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default} at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2255) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A} at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --Details: Reload number: 1 Reload reason: initial Finished: Yes Packs: Mod Resources, Supplementaries Virtual Resourcepack, Default, quark-emote-pack, Squids 101.zip, better-night.zip, isometric-sun-and-moon-cubes-e680.zip, Concrete Retextures, lily-pads-remade-2d-e101.zip, Peeves+v4.0+-+1.18.zip, Resource+pack+for+Better+End+Sky+mod.zip
-- System Details --Details: Minecraft Version: 1.18.2 Minecraft Version ID: 1.18.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.1, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft Memory: 875153152 bytes (834 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB) CPUs: 16 Processor Vendor: AuthenticAMD Processor Name: AMD Ryzen 7 2700X Eight-Core Processor          Identifier: AuthenticAMD Family 23 Model 8 Stepping 2 Microarchitecture: Zen+ Frequency (GHz): 3.69 Number of physical packages: 1 Number of physical CPUs: 8 Number of logical CPUs: 16 Graphics card #0 name: NVIDIA GeForce GTX 1070 Graphics card #0 vendor: NVIDIA (0x10de) Graphics card #0 VRAM (MB): 4095.00 Graphics card #0 deviceId: 0x1b81 Graphics card #0 versionInfo: DriverVersion=27.21.14.6089 Memory slot #0 capacity (MB): 8192.00 Memory slot #0 clockSpeed (GHz): 2.40 Memory slot #0 type: DDR4 Memory slot #1 capacity (MB): 8192.00 Memory slot #1 clockSpeed (GHz): 2.40 Memory slot #1 type: DDR4 Virtual memory max (MB): 25531.51 Virtual memory used (MB): 13182.36 Swap memory total (MB): 9216.00 Swap memory used (MB): 111.14 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Launched Version: 1.18.2-forge-40.1.16 Backend library: LWJGL version 3.2.2 SNAPSHOT Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.89, NVIDIA Corporation Window size: 1920x1080 GL Caps: Using framebuffer using OpenGL 3.2 GL debug messages:  Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' Type: Integrated Server (map_client.txt) Graphics mode: fancy Resource Packs: mod_resources, Supplementaries Virtual Resourcepack, vanilla, quark:emote_resources (incompatible), file/Squids 101.zip, file/better-night.zip (incompatible), file/isometric-sun-and-moon-cubes-e680.zip (incompatible), file/Concrete Retextures (incompatible), file/lily-pads-remade-2d-e101.zip, file/Peeves+v4.0+-+1.18.zip, file/Resource+pack+for+Better+End+Sky+mod.zip Current Language: English (US) CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor  Server Running: true Player Count: 1 / 8; [ServerPlayer['TurboSoggy24'/161, l='ServerLevel[New World]', x=90.90, y=87.00, z=-74.34]] Data Packs: vanilla, mod:smarterfarmers (incompatible), mod:configured (incompatible), mod:seamless_loading_screen (incompatible), mod:quarkoddities (incompatible), mod:bigbrain (incompatible), mod:improvedmounthud (incompatible), mod:bedspreads (incompatible), mod:chimes (incompatible), mod:jei (incompatible), mod:puzzleslib (incompatible), mod:endsky (incompatible), mod:highlighter (incompatible), mod:heartstone (incompatible), mod:forge (incompatible), mod:iceberg (incompatible), mod:geckolib3 (incompatible), mod:curious_feasts, mod:selene (incompatible), mod:supplementaries (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), Supplementaries Virtual Resourcepack World Generation: Experimental OptiFine Version: OptiFine_1.18.2_HD_U_H7 OptiFine Build: 20220410-185216 Render Distance Chunks: 12 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: null OpenGlVersion: 3.2.0 NVIDIA 460.89 OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2 OpenGlVendor: NVIDIA Corporation CpuCount: 16 ModLauncher: 9.1.3+9.1.3+main.9b69c82a ModLauncher launch target: forgeclient ModLauncher naming: srg ModLauncher services:  mixin PLUGINSERVICE  eventbus PLUGINSERVICE  slf4jfixer PLUGINSERVICE  object_holder_definalize PLUGINSERVICE  runtime_enum_extender PLUGINSERVICE  capability_token_subclass PLUGINSERVICE  accesstransformer PLUGINSERVICE  runtimedistcleaner PLUGINSERVICE  mixin TRANSFORMATIONSERVICE  OptiFine TRANSFORMATIONSERVICE  fml TRANSFORMATIONSERVICE  FML Language Providers:  minecraft@1.0 javafml@null Mod List:  client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f smarterfarmers-1.18.2-1.5.0.jar                   |Smarter Farmers               |smarterfarmers                |1.18.2-1.5.0        |DONE      |Manifest: NOSIGNATURE configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE seamless_loading_screen-1.18-3.0.0.jar            |Seamless Loading Screen       |seamless_loading_screen       |1.18-3.0.0          |DONE      |Manifest: NOSIGNATURE QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE bigbrain-1.5.0.jar                                |Big Brain                     |bigbrain                      |1.5.0               |DONE      |Manifest: NOSIGNATURE ImprovedMountHUD-v3.1.0-1.18.2-Forge.jar          |Improved Mount HUD            |improvedmounthud              |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a bedspreads-forge-1.18.1-5.1.0.5.jar               |Bedspreads                    |bedspreads                    |1.18.1-5.1.0.5      |DONE      |Manifest: NOSIGNATURE Chimes-1.1.2-1.18.2.jar                           |Chimes                        |chimes                        |1.1.2               |DONE      |Manifest: NOSIGNATURE jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |DONE      |Manifest: NOSIGNATURE PuzzlesLib-v3.3.3-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a End+Sky(forge)+-+1.18+-+1.3.jar                   |Better End Sky                |endsky                        |1.3                 |DONE      |Manifest: NOSIGNATURE Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |DONE      |Manifest: NOSIGNATURE heartstone-1.18-1.0.0.jar                         |Heartstone                    |heartstone                    |1.18-1.0.0          |DONE      |Manifest: NOSIGNATURE forge-1.18.2-40.1.16-universal.jar                |Forge                         |forge                         |40.1.16             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 Iceberg-1.18.2-1.0.40.jar                         |Iceberg                       |iceberg                       |1.0.40              |DONE      |Manifest: NOSIGNATURE geckolib-1.18-forge-3.0.17.jar                    |GeckoLib                      |geckolib3                     |3.0.17              |DONE      |Manifest: NOSIGNATURE chorus_soda1.18.2-1.1.0.jar                       |Example Mod                   |curious_feasts                |1.0                 |DONE      |Manifest: NOSIGNATURE selene-1.18.2-1.15.7.jar                          |Selene                        |selene                        |1.18.2-1.15.7       |DONE      |Manifest: NOSIGNATURE supplementaries-1.18.2-1.3.7.jar                  |Supplementaries               |supplementaries               |1.18.2-1.3.7        |DONE      |Manifest: NOSIGNATURE citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE alexsmobs-1.18.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.3              |DONE      |Manifest: NOSIGNATURE AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE Quark-3.2-356.jar                                 |Quark                         |quark                         |3.2-356             |DONE      |Manifest: NOSIGNATURE Crash Report UUID: 6222dd4b-eba1-472a-9525-0d9eb4fe47f9 FML: 40.1 Forge: net.minecraftforge:40.1.16

**Comment by MehVahdJukaar** [comment]
should be fixed
