### ISSUE TITLE
Cake and Candle interaction is broken

### ISSUE THREAD

**Issue by MythrilBagels** [MehVahdJukaar/Supplementaries#245]
Placing down a cake and eating it works fine. But when I place a candle on said cake, things start to break.
Simply clicking on the candle cake with full hunger, the candle will break off and duplicate.
Clicking on the candle cake when hungry, a slice will be eaten and the candles will also break off and duplicate.
Trying to light the candles with a flint and steel will also break the candles and duplicate them.

Cakes and Candles started working correctly after removing this mod.
All this cause I wanted to make a little video for a friends birthday, smh
Hopefully this isn't too hard to fix! I believe in you!

https://user-images.githubusercontent.com/52741226/169437979-af769715-d5cb-46d7-a4b1-d097103e2909.mp4

https://user-images.githubusercontent.com/52741226/169437990-e7a0fb73-0665-4d43-9ca2-3d645e6206f3.mp4

**Comment by MehVahdJukaar** [comment]
seems like I had a duplicate line there lol

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by MythrilBagels** [comment]
The duplication issue is fixed, but we still cannot light the candle.
It does work with modded cakes though, just not the Vanilla one.
 
![image](https://user-images.githubusercontent.com/52741226/169947443-832ce310-ec50-4dd5-81c2-2f7c1f4850f7.png)

https://user-images.githubusercontent.com/52741226/169947472-77c7bc6c-c041-47a3-b5d8-0565e92552fa.mp4
