### ISSUE TITLE
Order of PancakeBlock#getTopping conditions disallows items that extend HoneyBottleItem from being syrup or chocolate

### ISSUE THREAD

**Issue by Charnuz** [MehVahdJukaar/Supplementaries#249]
https://github.com/MehVahdJukaar/Supplementaries/blob/15e84ca7b35d753d0585a61aed33b06920851054/src/main/java/net/mehvahdjukaar/supplementaries/common/block/blocks/PancakeBlock.java#L61-L71

For example, this affects syrup bottles from thermal foundation

**Comment by MehVahdJukaar** [comment]
oh good point I hadn't thought of that
