### ISSUE TITLE
Spacing has to be larger than separation

### ISSUE THREAD

**Issue by Intaria** [MehVahdJukaar/Supplementaries#250]
If you trying to disable way_sign spawn in world, setting config option "minimum_distance" to 1001 cause following error:
```The game crashed whilst mouseclicked event handler
Error: com.google.gson.JsonParseException: Error loading registry data: Spacing has to be larger than separation
Код завершения: 255```

**Comment by MehVahdJukaar** [comment]
The config description is outdated. With the new worldgen stuff you can no longer use that and you have to do it by editing the structure tag instead. Check out the wiki. Also I was sure I fixed both the error throwing and the outdated description in the latest update

**Comment by MehVahdJukaar** [comment]
changed those configs in the latest version so that invalid configuration wont be possible anymore
