### ISSUE TITLE
1.18.2 Way Sign Advancement

### ISSUE THREAD

**Issue by BookerCatch** [MehVahdJukaar/Supplementaries#253]
# Supplementaries Version: 1.18.2-1.4.3
Advancement won't load because of a typo

https://github.com/MehVahdJukaar/Supplementaries/blob/ceba0a64727f437ed73552c9d6c0bc55b6f0ff77/src/main/resources/data/supplementaries/advancements/adventure/way_sign.json#L5

Should be -> "supplementaries:minecraft/sign_post_oak"

**Comment by MehVahdJukaar** [comment]
actually it was the item id that was messed up. fixed it back up to just sign_post_oak
