### ISSUE TITLE
[Suggestion] Use a shovel to snuff sconces!

### ISSUE THREAD

**Issue by MythrilBagels** [MehVahdJukaar/Supplementaries#255]
I suggest making an alternative way of putting out sconces, using a shovel.
This would make it way easier to put out several sconces at a time instead of having to painstakingly water bucket the sconces quickly so the water doesn't go everywhere and make a mess, since currently if you're not fast enough, the water spreads out and can make a mess by breaking other objects in the room such as carpets.
It also makes it consistent with campfires, which can also be put out by right clicking with a shovel.

**Comment by MehVahdJukaar** [comment]
added in latest update
