### ISSUE TITLE
Flax crops not growing properly

### ISSUE THREAD

**Issue by Konin-Sensei** [MehVahdJukaar/Supplementaries#256]
![image](https://user-images.githubusercontent.com/38869772/175425842-ce396c70-63c7-4daa-955e-6b16243941e7.png)
Pictured above, the flax is initially growing fine but turns into this mess with some crops only having their upper half actually in the world. I've tried reconnecting to my server and restarting it as well. 
I initially thought it could be a rendering issue as I've installed optifine but the bottom half of the crops is actually missing, I can stomp out the tilled dirt beneath without the top half decaying and can place blocks into the space where the bottom half of the crop should be. 
I am using this mod as part of the create above and beyond pack so I dropped an issue there as well [linked here](https://github.com/simibubi/Above-and-Beyond/issues/454)

**Comment by MehVahdJukaar** [comment]
very weird. does it happen normally of after you harvest them with some machinery?

**Comment by Konin-Sensei** [comment]
> very weird. does it happen normally of after you harvest them with some machinery?

It looks like it happens when the machines come for it. [shown here](https://youtu.be/4UmFb26pBY0)

**Comment by MehVahdJukaar** [comment]
Are those machine also supposed to replant them?

**Comment by Konin-Sensei** [comment]
> Are those machine also supposed to replant them?
They are. I realized that harvesting from the bottom block with the machine won't cause the issue so I'm just running with that.
