### ISSUE TITLE
[1.19] Crash using any Flags

### ISSUE THREAD

**Issue by osdeibi** [MehVahdJukaar/Supplementaries#257]
Minecraft version: 1.19
Forge: 41.0.45

I tested on a clean installation with other mods and only using Supplementaries, the behavior is the same.

Exit code:
-1

Crash report:
[crash-2022-06-25_17.18.40-client.txt]
(https://github.com/MehVahdJukaar/Supplementaries/files/8985653/crash-2022-06-25_17.18.40-client.txt)

**Comment by MehVahdJukaar** [comment]
Should be fixed
