### ISSUE TITLE
Banner patterns from other mods not working

### ISSUE THREAD

**Issue by il1013** [MehVahdJukaar/Supplementaries#262]
1.19 version of this mod prevents banner patterns from other mods like the ones in Alex's mobs and Additional banners to not work
(Vanilla banner patterns do still work) [https://media.discordapp.net/attachments/457601193926066176/993434311690821632/unknown.png?width=1300&height=676](url)

**Comment by MehVahdJukaar** [comment]
fixed some updates ago
