### ISSUE TITLE
[Suggestion] Keyring

### ISSUE THREAD

**Issue by laserlemons** [MehVahdJukaar/Supplementaries#265]
Problem:
Managing multiple keys is kind of a pain in the ass.

Solution:
Keyring item that stores multiple keys. Works the same as a key when clicking on a lock as long as the correct key is stored inside the keyring.

**Comment by MehVahdJukaar** [comment]
I'm not a fan of this one as it would be a highly specialized item with just that one niche use. Keys can go in any curio slot any anywhere in ones inventory plus if one really wants to open multiple thins with the same key that one can simply used to lock all of them
