### ISSUE TITLE
"Can be Stacked" text is ambiguous

### ISSUE THREAD

**Issue by Vazkii** [MehVahdJukaar/Supplementaries#27]
https://github.com/Vazkii/crucia2-issues/issues/51

Happened in my modpack that someone thought the text meant the cakes can be stacked in inventory rather than in world.

**Comment by MehVahdJukaar** [comment]
I guess it it. Maybe there is a better way to word it but I honestly wouldn't know what that would be. I guess I could just remove those tooltips but I find they are a nice way to show added functionality to people that have not read the mod change list. I'll try to come up with something better for next update and I'm also adding in a config to disable those tooltips entirely

**Comment by MehVahdJukaar** [comment]
I changed it to be very specific although it sounds kind of odd now. Hopefully it's worth it. Also I realized I already implemented the config to disable those tooltips so you could turn that off
