### ISSUE TITLE
[Suggestion/Bug] Making pancake music automatable with create/dispensers

### ISSUE THREAD

**Issue by AdamGoldyn** [MehVahdJukaar/Supplementaries#271]
Using Create's deployer/mechanical arm or simply dispensing it into a jukebox doesn't work.

**Comment by AdamGoldyn** [comment]
This is on the latest version to be clear

**Comment by MehVahdJukaar** [comment]
That's a good point.idk how I didn't think of that

**Comment by MehVahdJukaar** [comment]
I added this in latest 1.19.2 version. It's on if quark dispenser module is on. For create it should already work with deployers
