### ISSUE TITLE
Placing bloks from the mod

### ISSUE THREAD

**Issue by RJHG56** [MehVahdJukaar/Supplementaries#272]
i have 2 wors in one i onle place the gray cup ant crashes in the other I place safer then the game crash

[crash-2022-07-15_17.15.49-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9124459/crash-2022-07-15_17.15.49-server.txt)
[crash-2022-07-15_17.15.57-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9124460/crash-2022-07-15_17.15.57-client.txt)

**Comment by MehVahdJukaar** [comment]
Update this https://www.curseforge.com/minecraft/mc-mods/selene/files
