### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ExDrill** [MehVahdJukaar/Supplementaries#273]
The logs say I'm missing Moonlight Lib, but I have it in my mods folder.

Forge Version: 41.0.100
Mod Version: 1.19-1.4.8b
Moonlight Version: 2.0.0

Log:
https://pastebin.com/iij6Tpbz

**Comment by MehVahdJukaar** [comment]
needs forge <0.63

**Comment by ExDrill** [comment]
That explains it, I will wait then. : )
