### ISSUE TITLE
Conflict with create mod

### ISSUE THREAD

**Issue by Hydrap6** [MehVahdJukaar/Supplementaries#279]
I am having difficulty running this mod alongside the create mod. Minecraft launches perfectly fine, but when I attempt to make or enter a world, my minecraft crashes. I have both mods up to date, and no other mods are conflicting.
Don't wanna post the entire crash report here unless need be, so I'll just post the crash message here:
"The game crashed whilst starting integrated server
Error: java.lang.NoSuchMethodError: 'void com.simibubi.create.AllMovementBehaviours.registerBehaviour(net.minecraftforge.registries.IRegistryDelegate, com.simibubi.create.content.contraptions.components.structureMovement.MovementBehaviour)'
Exit Code: -1"

**Comment by MehVahdJukaar** [comment]
This was fixed
