### ISSUE TITLE
Crash with latest update due to mixins. (Version 0.10.1)

### ISSUE THREAD

**Issue by ZandercraftGames** [MehVahdJukaar/Supplementaries#28]
*This issue is a clone of https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/41*

**Description:** The server crashes immediately at load-time (at startup) after the latest update. This is evidently due to a mixin failing to apply. 
**Version:** 0.10.1
**Client or server?:** Issue occurs on both.
**Logs:** https://pastebin.com/Wse6ea37

**Comment by MehVahdJukaar** [comment]
for some reason unknow to me it didn't compile properly... I uploaded a new working version
