### ISSUE TITLE
Rope doesn't slow descent?

### ISSUE THREAD

**Issue by IdrisQe** [MehVahdJukaar/Supplementaries#280]
I'm not sure if this is intended, or a byproduct of it having no collision, nor do I know if it's necessarily fixable, but rope doesn't slow your descent automatically like being on a ladder does, despite otherwise working like a ladder. To not die from fall damage when going down a rope, you need to either tap jump or sneak repeatedly to slow your descent and reset your falling distance. This makes precise movement downward using ropes pretty difficult.

**Comment by MehVahdJukaar** [comment]
ropes do now slow descent. that's why they are useful as you can slide down them. they sill negate fall damage tho. Are you saying that they dont?

**Comment by IdrisQe** [comment]
I'm not sure if this is the situation you mean, but when I'm in the same block as a rope and I let myself slide down it, if I touch the floor before pressing space or shift to stop myself on the rope, I do take fall damage.

**Comment by MehVahdJukaar** [comment]
I cant replicate this

**Comment by IdrisQe** [comment]
Huh... It's probably some weird mod interaction then. I haven't played in a while so I'm not sure, but when I do play again, I'll probably test some more and see if I can find the cause.
