### ISSUE TITLE
fireflies aren't spawning

### ISSUE THREAD

**Issue by EnderSpy29** [MehVahdJukaar/Supplementaries#282]
Fireflies don't spawn in my world, I am wondering if this is a bug? Or if there's a mod incompatibility. I'm using supplementaries in a 1.18.2 custom modpack

**Comment by EnderSpy29** [comment]
As An Update, There Are No Firefly Related Items in the jar Tab, And I Have Made Sure That The Config Has Firefly Spawning Enabled

**Comment by MehVahdJukaar** [comment]
fireflies are only in 1.16

**Comment by EnderSpy29** [comment]
BUT ITS IN THE CONFIG

**Comment by MehVahdJukaar** [comment]
I can put whatever in the config. Sometimes I forget to clean it up
