### ISSUE TITLE
Error when starting in Forge Server

### ISSUE THREAD

**Issue by Facronactz** [MehVahdJukaar/Supplementaries#285]
I have difficulties when starting Minecraft server. The server refusing to start saying that it's Supplementaries fault. I read it a bit and it have to do with something like "invalid dist DEDICATED_SERVER". I belive i have latest Supplementaries and Moonlight.

Minecraft 1.19
Forge 41.1.0

here is the crash report:
https://mclo.gs/ayNGxe1

**Comment by Codename-11** [comment]
Same issue :(

**Comment by MehVahdJukaar** [comment]
Should be fixed
