### ISSUE TITLE
Flute recordings play back way too fast!

### ISSUE THREAD

**Issue by leftbones** [MehVahdJukaar/Supplementaries#286]
I made a nice song with note blocks, started the recording with `/supplementaries record start`, stopped it with the stop command, pulled out my flute, and played the song at a crazy fast tempo! It was hilarious, but not at all what I was expecting.

Edit: Here's a recording of the song and the flute version: https://medal.tv/games/minecraft/clips/uqPJtF3Fbz3yT/d1337ZXr8iVi?invite=cr-MSxMYzQsODYyMzA1NTUs

**Comment by MehVahdJukaar** [comment]
Hm that shouldnt happen. I think the command had an extra parameter for tempo. If not you can edit it in the JSON it generated to slow it down

**Comment by LunarPhobos** [comment]
Can also vouch for this issue, it happens when you test the playback or use /reload
 it resolves if you leave and join

**Comment by LunarPhobos** [comment]
https://user-images.githubusercontent.com/76231975/186532760-e8d59d26-0b60-4317-977c-6f85e93e0886.mp4

**Comment by MehVahdJukaar** [comment]
Fixed
