### ISSUE TITLE
Random invisible Bellows

### ISSUE THREAD

**Issue by TheSnowyChickens** [MehVahdJukaar/Supplementaries#29]
Hi,
As you can see in the screenshot, at a certain PoV your bellows will simply become invisible.
(only the one pointing upwards)

![grafik](https://user-images.githubusercontent.com/29357962/109725763-e963ed00-7bb1-11eb-865b-407a0413d78f.png)

![grafik](https://user-images.githubusercontent.com/29357962/109725964-33e56980-7bb2-11eb-9f6a-bd5995338fa4.png)

![grafik](https://user-images.githubusercontent.com/29357962/109725983-3ba50e00-7bb2-11eb-939a-a3eaaa98a8c7.png)

1.16.5
Forge .43
No Optifne
Supple. version: 0.10.1c
+ plus ~100 other mods (IE / Thermal / RFTools  / &&&)

Oh and a tiny question:
how can they speed up a furnace ? I don't get it somehow. :/

**Comment by MehVahdJukaar** [comment]
that's a very odd glitch. It's not happening to me so it's another mod doing for sure. I try to put in a possible fix though by making its render shape always stay as 1 block. As for bellows functionality it's really simple, you just place one next to it and power it. it will tick the furnace more often thus making it burn stuff faster. try making a hopper contraption that compares it with a normal one and you'll see that it indeed goes faster. The more bellows you place against a furnace the faster it will go of course. It also depends on the power that bellows are receiving. I have to say that I checked and the code that makes this possible had a tiny bug that wasn't making them go as fast/slow as I wanted so I'll fix it soon. It should still work though, just not with the same speed  curve that I wanted

**Comment by TheSnowyChickens** [comment]
That's good to hear.

Thank you :)

**Comment by MehVahdJukaar** [comment]
possibly fixed in 0.10.2. Let me know if it's still happening

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/110211592-8d41e700-7e97-11eb-8b30-e16330bdf868.png)

I updated Forge to .46

**Comment by MehVahdJukaar** [comment]
dang it. Odd thing is that I can't seem to replicate it whatsoever. I'll try to see if it's optifine

**Comment by MehVahdJukaar** [comment]
I did change another thing with the last hotfix. It might have fixed this idk

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/110221178-fb53d180-7eca-11eb-8584-c8c09e7005cf.png)

Nope, sry. :(

**Comment by MehVahdJukaar** [comment]
:(
I'm wondering if it's only happening when it's powered

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/110250190-555fa000-7f7a-11eb-9669-c8bd3f63f22a.png)

Nope, powered and unpowered

**Comment by TheSnowyChickens** [comment]
Update with the newest version and Forge .46: still invis. :(

**Comment by MehVahdJukaar** [comment]
Unfortunately I don't think I can fix this. I've tried everything I could if that didn't fix it I'm afraid there's nothing more I can do. I still can't replicate this and It seems really odd that it only happens with those since they use the same rendering method as chests and other tile entities in the mod

**Comment by TheSnowyChickens** [comment]
:(, but then it seems that nothing can be done about it. I thank you anyway for the attempts :) 
(and maybe it works with the new render engine of 1.17 (OpenGL 3.2))
