### ISSUE TITLE
Timber Frames Missing Recipes (1.19 Fabric ver. 2.0.9)

### ISSUE THREAD

**Issue by Cymophic** [MehVahdJukaar/Supplementaries#290]
The new timber frames are missing their recipes in the latest update.

Here are some images:

![image](https://user-images.githubusercontent.com/97153344/182524963-a1f9512a-bcff-4374-8a4e-cc9a8e16a00a.png)
![image](https://user-images.githubusercontent.com/97153344/182524972-ab7f3879-9ec6-4099-a29a-19a7174fc3c0.png)
![image](https://user-images.githubusercontent.com/97153344/182524978-622f761a-9699-4424-aa98-da2ac5b7c3a1.png)

I also have the Visual Workbench mod and the timber shows even if the crafting table is empty. It showed after I crafted something.
![image](https://user-images.githubusercontent.com/97153344/182525074-81b28728-3dda-4b6b-a709-2294757212e8.png)

**Comment by MehVahdJukaar** [comment]
fixed in 2.0.10
