### ISSUE TITLE
Gunpowder trails no longer work in 1.19

### ISSUE THREAD

**Issue by wetnood** [MehVahdJukaar/Supplementaries#291]
Hello, big fan of this mod. Was testing out some features and found that gunpowder could now be placed as trails and lit in the world. The feature did not seem to work at all. I tried placing and lighting a trail connecting to TNT, flammable blocks such as wool/wood, and ignitable blocks such as campfires/candles. Nothing seemed to trigger upon the fuse reaching the destination. I'm fairly certain this feature used to function perfectly in 1.18, so I figured this might have been an issue transitioning into 1.19. The only other mods I used in this instance are JEI and World Edit. Also, not sure if this would affect anything, but I did make sure had doFireTick set to true.

Lastly, I was using the fabric version, and I see that the fabric alternative to this mod is not quite finished yet, so I wasn't sure if this feature was unfinished or rather buggy/not working correctly, but decided to post this either way just in case. Keep up the good work on this mod!

**Comment by MehVahdJukaar** [comment]
might be missing some things yeah. I'll try to fix

**Comment by MehVahdJukaar** [comment]
Fixed
