### ISSUE TITLE
[1.18.2 Forge] Crash while scrolling down in loom menu

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#292]
This is likely a conflict with Blueprint, disabling either it or Supplementaries will stop the crash. I'm not really sure how big modders handle mixin conflicts, figure i'd just put this here anyways

Crash Report: https://gist.github.com/thelegitdolt/debab1f8c9881c1392e726893fc83cbf
Latest.log: https://gist.github.com/thelegitdolt/4715f62e4a5aca9a17908c38dd86afa8

**Comment by MehVahdJukaar** [comment]
should have been fixed
