### ISSUE TITLE
CAN'T START A SERVER

### ISSUE THREAD

**Issue by WildLONLON** [MehVahdJukaar/Supplementaries#295]
I tried to start a Server with FORGE 1.19.1 (42.0.9) with MODS, including SUPPLEMENTARIES 1.19-2.0.12 and it's the only one who make it crash.

It was already the case with the previous version of FORGE and SUPPLEMENTARIES 1.19-2.0.9
So when FORGE did an update (yesterday i think ?) i waited for an update of SUPPLEMENTARIES

And i still have crash before the Start of the Server, with SUPPLEMENTARIES 1.19-2.0.12 this time

Here is the Crash Report : https://mclo.gs/6z4grpZ

<img width="1498" alt="Capture" src="https://user-images.githubusercontent.com/110568408/183246541-0da74bc7-940a-4ee6-8a26-6e65ea6b9c92.PNG">

PS : I love your MOD, especially the Black Board where you can draw things with pixels !

**Comment by MehVahdJukaar** [comment]
You are using Minecraft 1.19.1
