### ISSUE TITLE
Crash on Launching: NoClassDefFoundError: IBlockHolder

### ISSUE THREAD

**Issue by Phoupraw** [MehVahdJukaar/Supplementaries#298]
MC: 1.19
Supp: 2.0.12
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9292754/latest.log)
No crash report.

**Comment by MehVahdJukaar** [comment]
Install moonlight

**Comment by Phoupraw** [comment]
> Install moonlight

I see. So why not add it into `depends` in `fabric.mod.json`?
