### ISSUE TITLE
[1.19 Fabric] Server fails to start when disabling sign_post

### ISSUE THREAD

**Issue by JLUsr** [MehVahdJukaar/Supplementaries#301]
Disabling sign post's in _supplementaries-registry.json_ by setting `"sign_post": false,` results in `Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode` where `Generated runtime SERVER_DATA for pack Supplementaries Generated Pack in: 220 ms` should be.

The same issue occurs as long as "sign_post" is set to false even when creating a fresh fabric server with just

- fabric-api-0.58.0+1.19.jar
- moonlight-1.19-2.0.12.jar
- supplementaries-1.19-2.0.12.jar

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9306371/latest.log)

**Comment by MehVahdJukaar** [comment]
I need a log. I just tried replicating this on a fabric sever with way sign off and the server boots fine

**Comment by MehVahdJukaar** [comment]
Should be fixed
