### ISSUE TITLE
[1.19 Fabric] Bricks not dealing damage or breaking glass

### ISSUE THREAD

**Issue by JLUsr** [MehVahdJukaar/Supplementaries#302]
It seems that only the _Ash Brick_ can be thrown. I initially thought this was an incompatibility with **Immersive Weathering** but the issue persists when only **Supplementaries** is installed.

Additionally, thrown bricks do not seem to be dealing damage or breaking glass/jars as intended

https://user-images.githubusercontent.com/47650360/184082174-171f1148-bb0f-4599-9c27-b645af2c4999.mp4

**Comment by MehVahdJukaar** [comment]
I added the tags in the latest version but I'm still missing a fix for the glass breaking

**Comment by MehVahdJukaar** [comment]
this was recently fixed
