### ISSUE TITLE
1.19 fabric crash 

### ISSUE THREAD

**Issue by GhoulGirlz** [MehVahdJukaar/Supplementaries#303]
I added moonlight lib and supplementaries into my game the game crashed giving me a crash report The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries'! Exit Code: -1. I'm using fabric-api-0.56.1+1.19.jar
moonlight-1.19-2.0.14.jar
supplementaries-1.19-2.0.12.jar

**Comment by MehVahdJukaar** [comment]
I can't help you without a crash report

**Comment by MehVahdJukaar** [comment]
How do you know the mod has loaded? Does it show up in the mod menu?

**Comment by GhoulGirlz** [comment]
it shows up in the mod menu but not in game, it doesn't crash but how could I get a crash report

**Comment by MehVahdJukaar** [comment]
So how do you verify that it does not show up in game?  Can you type /supplementaries roll?

**Comment by GhoulGirlz** [comment]
where should I type it? and

[crash-2022-06-19_19.08.39-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9315049/crash-2022-06-19_19.08.39-client.txt)
 now I am using the newest version for 1.19 and it doesn't show at all

**Comment by MehVahdJukaar** [comment]
Asked to type a command because it's a quick way to see if the mod is on. I have never heard of mods showing up in mod menu but not being on so I don't know

**Comment by GhoulGirlz** [comment]
okay I've gotten it to work but the mod doesn't show up in the item menu is that supposed to happen or is there a way to change that if you know?

**Comment by MehVahdJukaar** [comment]
Not all mods have a dedicated creative tab. Looking at those to see if a mod is installed is not the way to do it, that's why I asked to type the command. This one however has an optional tab, it's enabled with the condigs
