### ISSUE TITLE
[1.19.2 / Multiloader] Slingshots are crashing game when you trying to shoot directional blocks.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#307]
Blocks such banners, pistons and etc is crashing game with error "server closed" when you trying to shoot directional blocks.
[crash-2022-08-12_00.13.37-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9312347/crash-2022-08-12_00.13.37-server.txt)

**Comment by MehVahdJukaar** [comment]
Should be fixed

**Comment by murao-kun** [comment]
Fixed.
