### ISSUE TITLE
[1.19.2 / Multiloader] Modded banner patterns do not render with mod installed.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#308]
![image](https://user-images.githubusercontent.com/110398598/184249036-488f4b88-f520-4964-8a90-360818159816.png)

**Comment by MehVahdJukaar** [comment]
Fixed. Bug is caused by any mod that loads the sheets atlas early. I included a hacky fix that will make any of those mods with that bug

**Comment by murao-kun** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/110398598/184499009-b8bfa070-1fb6-4eee-b6b3-f9309eba86b6.png)
