### ISSUE TITLE
[1.19.2 / Multiloader] Antique Ink is not working on regular signs.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#309]
Antique Ink is not working on regular signs, even vanilla ones. But working for hanging signs and sign posts.
![image](https://user-images.githubusercontent.com/110398598/184255569-f5e616d6-3ed5-4f0b-a424-49aee5e31e81.png)

**Comment by MehVahdJukaar** [comment]
fixed in 2.1.0
