### ISSUE TITLE
[1.19.2 / Multiloader] Narrator Block do not working on "Narrator message" mode.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#313]
Narrator Block do not working on "Narrator message" mode. There is no sound. But chat mode works fine.

**Comment by Footage2-Amply-Pounce** [comment]
If you are using MultiMC, the narrator library is broken: https://github.com/MultiMC/Launcher/issues/4783

Other than that can only say that on Fabric/Quilt the Narrator block works in both modes, chat and narrator.

**Comment by murao-kun** [comment]
Oh, that explains everything, since I am using MultiMC. Thought it is up on supplementaries since It was working fine on 1.18 with MultiMC.
