### ISSUE TITLE
[1.19.2 / Multiloader] Cog Block giving wrong redstone signal strength in some cases.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#314]
When you power cog block with just a redstone torch, it is acting like redstone dust. (First block - 15, Second block - 14 and going down by 1 each next)
![image](https://user-images.githubusercontent.com/110398598/184258484-30696038-3903-4956-8b27-158eb7cbbb6f.png)
But when powered with torch + dust or torch + repeater it is acting wrong. (First block - 15, Second block - Still 15 and only then going down by 1 each next)
![image](https://user-images.githubusercontent.com/110398598/184258638-beef96db-8ab9-4d58-ade7-f02db04fcdbf.png)
![image](https://user-images.githubusercontent.com/110398598/184258648-793a95b6-e3d1-4c70-bd75-25abe34bb8d2.png)

**Comment by MehVahdJukaar** [comment]
That is correct behaviour. Repeaters and upward facing torches are strong signal sources which power the block they touch. If you replace the first cog block with stone in all 3 cases you'll see what I mean. (One issue down quite some more to go lol)
