### ISSUE TITLE
[1.19.2 / Multiloader] Crash when you light a soul candle from Bazzier Bees on the skull.

### ISSUE THREAD

**Issue by murao-kun** [MehVahdJukaar/Supplementaries#315]
Crash when you light a soul candle from Bazzier Bees on the skull.
[crash-2022-08-12_02.27.16-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9312642/crash-2022-08-12_02.27.16-client.txt)

**Comment by MehVahdJukaar** [comment]
Should be fixed but I didn't test

**Comment by murao-kun** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/110398598/184498863-e97a2f0c-0082-4891-9377-e4fd08f99be2.png)
