### ISSUE TITLE
Request: Option to use another mod's rope block with the Rope Arrow

### ISSUE THREAD

**Issue by Vazkii** [MehVahdJukaar/Supplementaries#32]
Specifically to help fix content overlap with quark and/or farmer's delight.

**Comment by MehVahdJukaar** [comment]
Ok. Since you asked for it I'll try to make them a sort of universal rope arrow that work for any other modded rope. I would still prefer people to use mine though of course

**Comment by Vazkii** [comment]
thank u

**Comment by MehVahdJukaar** [comment]
added in 0.10.2
