### ISSUE TITLE
Crashes on launch 1.19 FABRIC

### ISSUE THREAD

**Issue by Bukovac** [MehVahdJukaar/Supplementaries#320]
[crash-2022-08-13_22.06.37-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9332102/crash-2022-08-13_22.06.37-client.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight

**Comment by Bukovac** [comment]
[crash-2022-08-14_00.00.46-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9332233/crash-2022-08-14_00.00.46-client.txt)

**Comment by Bukovac** [comment]
I was already using the newest version

**Comment by Bukovac** [comment]
moonlight-1.19.2-2.0.16.jar

**Comment by MehVahdJukaar** [comment]
Pardon my bad. The problem is the opposite actually. If you are on 1.19 and not on 1.19.2 you need to use an older version as the newest only work with 1.19.2

**Comment by Bukovac** [comment]
No problem , already got it working , thanks for the help!
