### ISSUE TITLE
1.19 Fabric Crash at startup

### ISSUE THREAD

**Issue by Bukovac** [MehVahdJukaar/Supplementaries#321]
Crashes at startup - fabric 1.19
supplementaries-1.19-2.0.13
moonlight-1.19.2-2.0.16

[crash-2022-08-14_02.11.02-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9332449/crash-2022-08-14_02.11.02-client.txt)

**Comment by MehVahdJukaar** [comment]
If you are not using 1.19.2 you need an older version of moonlight as latest only works for 1.19.2
