### ISSUE TITLE
create world, crash

### ISSUE THREAD

**Issue by FanRenLa** [MehVahdJukaar/Supplementaries#329]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies
selene-1.18.2-1.17.9
**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

- Mod version, MC version and Loader you are using
supplementaries-1.18.2-1.4.11
1.18.2
forge40.1.73
- A description of your issue and how to reproduce
create world, crash
- If applicable, add screenshots to help explain your problem.
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9386340/latest.log)
[crash-2022-08-20_13.57.34-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9386341/crash-2022-08-20_13.57.34-client.txt)

**Comment by MehVahdJukaar** [comment]
Update create
