### ISSUE TITLE
Water bucket and water bottle when input into jar

### ISSUE THREAD

**Issue by kihgy** [MehVahdJukaar/Supplementaries#33]
Water bucket and water bottle create two new liquid inside the jar from the one liquid, water. It shpuld be that both bucket and bottle create the same water, and you can  use bottles to output water despite inputting with a bucket.

**Comment by MehVahdJukaar** [comment]
odd. I know I had a potion related bug in the last version that wasn't making potion properly merge in jars. It was fixed in the version I just released so try to see if it still does that. Of course I wasn't able to replicate this (probably because I already fixed with that potion fix)
