### ISSUE TITLE
[Fabric] Crash with Colormatic and Advancement Frames

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [MehVahdJukaar/Supplementaries#330]
**MC** 1.19.2
**FAPI** 0.60.0
**Moonlight Lib** 2.0.17
**Supplementaries** 2.0.14
**[Advancement Frames](https://www.curseforge.com/minecraft/mc-mods/advancement-frames)** 1.1.2
**[Colormatic](https://www.curseforge.com/minecraft/mc-mods/colormatic)** 3.1.2

To reproduce simply install all the mods and launch the game.

A similar issue was reported to Colormatic here: https://github.com/kvverti/colormatic/issues/107. According to the dev, it was caused by the affected mod registering its objects too late for Fabric.

Quilt is unaffected.

Logs: https://gist.github.com/Footage2-Amply-Pounce/8a9470e5592cb03acd00972e7ec7c415

**Comment by MehVahdJukaar** [comment]
Hm so you have forge events to register stuff on forge but on fabric registration does not have a set place where it can happen, infact is very more often than not based off classloading static initialization which could very well happen not on mod init. Here I'm registering my stiff right after mod init. I too make the assumption that blocks would have been registered in mod init and infact the reason I register right after is so I can iterate over existing blocks to register my dynamic blocks which are based off existing ones (for every compat for example) however if a mod would not follow this nothing harmful would happen. I actually thing it is a colormatic issue as fabric does not have any designated place for registration and so they should make their code safe to run even if stuff gets registered outside of mod inkt

**Comment by kvverti** [comment]
Colormatic should not affect registries in any way.

**Comment by Footage2-Amply-Pounce** [comment]
Fixed on the latest version of MoonLight.
