### ISSUE TITLE
Using Honey Bottle on Jar results in disconnect

### ISSUE THREAD

**Issue by LunarPhobos** [MehVahdJukaar/Supplementaries#331]
Version: 1.19.2-2.0.14
Loader: Forge 1.19.2-43.0.11

Use a honey bottle on a jar while on a server, get disconnected.
![Screenshot 2022-08-20 202624](https://user-images.githubusercontent.com/76231975/185771462-69934d7f-1d7b-4905-be8f-545ac7e3405d.jpg)

**Comment by LunarPhobos** [comment]
Here's a trimmed log surrounding the issue: https://hastebin.com/efujafawud.sql

**Comment by MehVahdJukaar** [comment]
can you try seeing if it happens with the new moonlight+supplementaries version?

**Comment by LunarPhobos** [comment]
Still persists on those versions.

**Comment by LunarPhobos** [comment]
https://user-images.githubusercontent.com/76231975/186013222-fdf5e0c1-2818-4376-ae57-c35072bf06b2.mp4

**Comment by MehVahdJukaar** [comment]
oh wack, thought I had it

**Comment by MehVahdJukaar** [comment]
this should no longer be a problem in latest versions
