### ISSUE TITLE
[Forge 1.19] Game crash on startup

### ISSUE THREAD

**Issue by brodidly** [MehVahdJukaar/Supplementaries#332]
Mod version 1.19-2.0.13
Game version 1.19
Used both CurseForge launcher and regular MC launcher, same issue persists 
Crashes on its own and with other mods. 

https://pastebin.com/ZReu7h8t

**Comment by MehVahdJukaar** [comment]
you are using moonlight 1.19.2-2.0.16 which is not marked as 1.19

**Comment by brodidly** [comment]
Gah I can't believe I didn't catch that! Thanks for the speedy response!
