### ISSUE TITLE
[Fabric/Quilt] Crash with Waystones, when right clicking the ground with a map

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [MehVahdJukaar/Supplementaries#334]
**MC** 1.19.2
**FAPI** 0.60.0
**MoonLight Lib** 2.0.19
**Supplementaries** 2.0.15
**[Balm](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)** 4.5.2+0
**[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)** 11.1.0
**[ClothConfig](https://www.curseforge.com/minecraft/mc-mods/cloth-config)** 8.0.75

To reproduce:

1. Take any filled map (for convenience, simply take an empty one from creative inventory and fill it in)
2. Right click on top of any block (e.g. just on the ground) while holding the map
3. Crash

Works with any type of filled map: treasure maps, manually made maps, structure maps etc.

The issue happens on both Fabric and Quilt. Logs attached were made using Fabric. Let me know if I need to report this to Waystones, but I think the issue is on your side if I've read the logs correctly (something to do with the Waystones integration module).

Logs: https://gist.github.com/Footage2-Amply-Pounce/0f24192eed362e48fc92fef3f375afec

**Comment by MehVahdJukaar** [comment]
this should be fixed in latest version
