### ISSUE TITLE
[Forge 1.19] Random world crash that seems to be caused by Supplementaries

### ISSUE THREAD

**Issue by GoldenDarius** [MehVahdJukaar/Supplementaries#335]
While playtesting my modpack, I have encountered a weird crash while looting a structure and getting attacked by an army of skeletons. After having the logs checked by someone with experience, they said that the cause seemed to be Supplementaries, and it could have been some incompatibility. I'd like to have my logs checked for a solution, as my modpack has been quite laggy too ever since this issue happened.

[crash-2022-08-22_21.21.25-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9398153/crash-2022-08-22_21.21.25-server.txt)

Mod version: Supplementaries 1.19-2.0.13
Forge version: Forge 41.1.0
Minecraft version: 1.19

**Comment by MehVahdJukaar** [comment]
I believe it might not be supplementaries. It's something with goals and ai, unfortunately it doesnt tell any mod names but I'm not doing anything with ai with exception of animals and the fodder eat goal. If it was a skeleton like I see there then I think it's something else

**Comment by GoldenDarius** [comment]
It was indeed a huge amount of skeletons attacking me in a corner, it wasn't pleasant. I was told that it might have been incompatibility with Supplementaries but I don't really see anything that could be incompatible.. however for some reason the skeletons spawned with a parrot riding their heads, which is quite weird. I'll try to remove supplementaries and check if it happens again
