### ISSUE TITLE
[Forge 1.18.2] Flag causes crash with some modded banner patterns

### ISSUE THREAD

**Issue by skyjay1** [MehVahdJukaar/Supplementaries#337]
[crash-2022-08-22_18.20.59-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9399304/crash-2022-08-22_18.20.59-fml.txt)

Error:
> net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: supplementaries:entity/flags/greekfantasy:spider

Supplementaries is trying to make a flag out of a banner pattern that uses the `:` character. The modded pattern is created with the following:
`BannerPattern.create("GREEKFANTASY_SPIDER", "greekfantasy:spider", "gf:spi", true);`

Original report: [GreekFantasy#99](https://github.com/skyjay1/GreekFantasy/issues/99)

**Comment by MehVahdJukaar** [comment]
you are using an old version. this was fixed some updates ago
