### ISSUE TITLE
[1.18.2] Transparent textures issue

### ISSUE THREAD

**Issue by TheCebulaShark** [MehVahdJukaar/Supplementaries#338]
-MC 1.18.2
-Forge 40.1.68
-Supplementaries 1.4.12 (and only this version - works fine on 1.4.11)
-Newest version of moonlight on 1.18.2

optifine/rubidium etc. aren't causing this

![2022-08-24_19 18 06](https://user-images.githubusercontent.com/87041426/186488418-c235f6d0-f76c-4ea4-b05d-8aa9a86d17a7.png)

**Comment by MehVahdJukaar** [comment]
fixed in latest patch

**Comment by TheCebulaShark** [comment]
> fixed in latest patch

Yea its fixed in supplementaries 1.18.2 1.5.0 but issue reappeared  in 1.15.1

**Comment by MehVahdJukaar** [comment]
I didn't mean that. I tested it on 1.18.2 latest version and I can't replicate. If you say you have that it's probably some incompatibilities
