### ISSUE TITLE
[1.18.2] Missing sound files

### ISSUE THREAD

**Issue by tobi1449** [MehVahdJukaar/Supplementaries#339]
[net.minecraft.client.sounds.SoundManager/]: File supplementaries:sounds/block/rope_step_0.ogg does not exist, cannot add it to event supplementaries:block.rope.step  
[net.minecraft.client.sounds.SoundManager/]: File supplementaries:sounds/block/rope_step_1.ogg does not exist, cannot add it to event supplementaries:block.rope.step 
[net.minecraft.client.sounds.SoundManager/]: File supplementaries:sounds/block/rope_step_2.ogg does not exist, cannot add it to event supplementaries:block.rope.step 
[net.minecraft.client.sounds.SoundManager/]: File supplementaries:sounds/block/rope_step_3.ogg does not exist, cannot add it to event supplementaries:block.rope.step

These missing files lead to minecraft possibly not loading any vanilla sounds.

**Comment by MehVahdJukaar** [comment]
I added back some files in the last 1.18 update I did. Those should have been added back

**Comment by tobi1449** [comment]
They are still missing from https://github.com/MehVahdJukaar/Supplementaries/tree/1.18.2/src/main/resources/assets/supplementaries/sounds/block in the latest version

**Comment by MehVahdJukaar** [comment]
so I checked and they are not missing from the mod jar, just from github. from a user it shouldnt make a difference
