### ISSUE TITLE
Crash on Fabric 1.19, while eating cake?

### ISSUE THREAD

**Issue by TalEdd** [MehVahdJukaar/Supplementaries#343]
**Before continuing**
- [x] Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[crash-2022-08-27_22.00.19-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9438121/crash-2022-08-27_22.00.19-client.txt)
- Mod version, MC version and Loader you are using
  -  [supplementaries-1.19-2.0.13.jar](https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/3929293)
  -  Minecraft 1.19
  -  Fabric loader 0.14.9, Fabric API 0.58.0+1.19

- A description of your issue and how to reproduce
  - Most likely caused by eating a cake while having [Farmer's Delight](https://modrinth.com/mod/farmers-delight-fabric/version/1.3.3) v1.19-1.3.3 installed?

- If applicable, add screenshots to help explain your problem.
   - NIL

**Comment by MehVahdJukaar** [comment]
This is fixed in the latest version. 1.19 is not supported anymore

**Comment by TalEdd** [comment]
I see. Welp, I'll just have to temporarily remove it from the modpack, till it gets updated. Thanks for the update!
