### ISSUE TITLE
A bug that causes the server to crash

### ISSUE THREAD

**Issue by CaesarGalahad** [MehVahdJukaar/Supplementaries#345]
The faucet in version 1.19.2 will cause the server to crash If you need to provide log please leave a message and contact me

**Comment by MehVahdJukaar** [comment]
I need a log and version. Be sure you are on latest

**Comment by CaesarGalahad** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9439958/latest.log)
[crash-2022-08-28_23.29.37-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9439960/crash-2022-08-28_23.29.37-server.txt)

**Comment by MehVahdJukaar** [comment]
This is an issue with Illuminations mod modMenu integration. I think they set the wrong class path in their fabricmod.json
