### ISSUE TITLE
[Fabric 1.19.2] Faucet not dropping items / Lantern visual glitch / Invisible Blackboard

### ISSUE THREAD

**Issue by Gfauf** [MehVahdJukaar/Supplementaries#349]
I'm using TLauncher.

Mod that I'm currently using (Tried without everything but sodium, iris, moonlight and supplementaries too):
supplementaries-1.19.2-2.0.15-fabric
moonlight-1.19.2-2.0.24-fabric
iris-mc1.19.2-1.2.8
sodium-fabric-mc1.19.2-0.4.4+build.18
BetterF3-1.3.2-Fabric-1.19
cloth-config-8.0.75-fabric
fabric-api-0.60.0+1.19.2

I'm using Complementary Shaders but disabled it for troubleshooting purposes and still didn't fix the visual glitches. Didn't disable sodium or iris when troubleshooting.

Issues:
Blackboard is invisible, tried not using resourcepack (vanilla tweaks) and disabling shaders, still invisible.
Lantern doesn't have base when attached to a wall. And when you stumble it the waving animation frame skips to the last direction you moved and then start swinging.
Faucet doesn't drop items from chest.

In the photo I have Complementary Shaders enabled, but nothing changes without them.
Everything was in Singleplayer, didn't test in Multiplayer.
Tried downgrading 1 version of Moonlight libraries, 1 version of Supplementaries, and I intersperse them (1 old, 1 new, 2 olds, etc) to see if it would fix but no luck.

![2022-09-02_21 16 59](https://user-images.githubusercontent.com/112735631/188248302-fa83ad0c-36c5-4b8b-bb9c-2dff6bdc48b9.png)

**Comment by MehVahdJukaar** [comment]
You are using sodium which nukes fabric API. You need to install ribidium

**Comment by MehVahdJukaar** [comment]
Indium my bad . I cant keep track of all these mods named like random elements

**Comment by Gfauf** [comment]
Installed Indium:
Blackboard is visible and functioning, can't directrly draw on it with quartz though.
Lantern is not longer glitched.
Faucet still doesn't drop items from chests.

I'm still testing the mod compatibility with sodium+indium, there are some minor and 1 or 2 important things, if you like I can't make a full list of the issues.
Thanks for the fast reply and sorry for the delayed reply!

**Comment by MehVahdJukaar** [comment]
Oh no worries. I'll re open this or I'll forget to fix that faucet lol

**Comment by MehVahdJukaar** [comment]
Faucet should not work
