### ISSUE TITLE
Crash when player enters the game

### ISSUE THREAD

**Issue by Zuruckt** [MehVahdJukaar/Supplementaries#352]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
https://pastebin.com/us5TeGSM
- Mod version, MC version and Loader you are using
2.1.0, 1.19.2, Fabric
- A description of your issue and how to reproduce
Game crashes when player enters the game, supposely they don't own a quiver but that is what the crash report mentions
- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
Update to the latest version. Quiver renderers won't work tho as you are using some mod that somehow replaces the player renderer
