### ISSUE TITLE
[Fabric 1.19.2, Supplementaries 2.1.2] Timber Brace is waterlogged when placed

### ISSUE THREAD

**Issue by SinsOfVirtue** [MehVahdJukaar/Supplementaries#356]
In the Minecraft Launcher with fabric loader 0.14.9 for 1.19.2 (API 0.60.0) and Supplementaries version 2.1.2, the timber brace is always waterlogged when placed. This happens whether the player is in creative mode or not and it's only the diagonal one, the frame and cross are both fine. Pictured below is only with the base Fabric API mod, Supplementaries and matching Moonlight 2.0.26 version. No crashing, just mysterious water!

![2022-09-06_05 43 34](https://user-images.githubusercontent.com/89346757/188603060-4178ca80-0eda-4cbf-9f07-5b8742c7e733.png)

**Comment by MehVahdJukaar** [comment]
fixed
