### ISSUE TITLE
[1.19.2 Fabric] Skinned Wall Lanterns facing block

### ISSUE THREAD

**Issue by JLUsr** [MehVahdJukaar/Supplementaries#358]
Lanterns from the **Skinned Lanterns** mod v2.0.0 are rendered facing the wrong way when using the latest **Supplementaries** v2.1.3's wall lanterns on Fabric 1.19.2

![Shy Lanterns](https://user-images.githubusercontent.com/47650360/188944405-e8f4b257-9af7-4ca9-a204-feefece1b427.png)

The below photo includes a lantern that was placed against the block after disabling the _wall lantern_ feature to verify it is normally placed facing the correct way.
![Placed Correct With Tweak Disabled](https://user-images.githubusercontent.com/47650360/188944421-e0c49431-b46d-44a0-9f37-bb6910dfc36a.png)

**Comment by MehVahdJukaar** [comment]
oh seems like they rotated those. I remember I had to place some special code just for those in 1.16. Should be easy enough to fix

**Comment by MehVahdJukaar** [comment]
Fixed
