### ISSUE TITLE
The Wrench for Wall Lantern Rotation

### ISSUE THREAD

**Issue by JLUsr** [MehVahdJukaar/Supplementaries#359]
Though I don't know if this is possible, It would be nice to be able to use the _wrench_ on a _wall lantern_ like you would a _timber brace_ to rotate the texture of the lantern. This would be especially useful for 3D resource packs and **Skinned Lanterns** to fix inconsistencies and give _wall lanterns_ more use.

**Comment by MehVahdJukaar** [comment]
I dont think I can add this ass wrenches used on wall lanterns already rotate the lantern block normally by attaching it to other faces. Issues you mentioned tho will be fixed
