### ISSUE TITLE
"Rope override" tooltip shows on rope arrows in survival/without F3+H

### ISSUE THREAD

**Issue by Vazkii** [MehVahdJukaar/Supplementaries#36]
![2021-03-08_17 09 52](https://user-images.githubusercontent.com/1794735/110355429-1fc9be00-8031-11eb-8f2b-87c2b21922a9.png)

**Comment by MehVahdJukaar** [comment]
That's actually a nice idea. I have heard a couple of people not wanting those tooltips on other items too but I didn't want to straight up remove those so I think that tying them to the f3+h is a nice solution so I'll do that

**Comment by MehVahdJukaar** [comment]
added in v0.10.3
