### ISSUE TITLE
[BUG] Dispenser dupe w. Minecart with Dispenser

### ISSUE THREAD

**Issue by Shazuli** [MehVahdJukaar/Supplementaries#364]
- Mod version, MC version and Loader you are using
Minecraft: 1.19.2
Forge: 43.1.1
Supplementaries: 1.19.2-2.1.3
Moonlight Library: 1.19.2-2.0.28

- A description of your issue and how to reproduce
Breaking a Dispenser with Minecraft in survival will drop a Dispenser with Minecart *and* a Dispenser, allowing for infinite duping of Dispensers. This occurs on the Fabric version too.

- If applicable, add screenshots to help explain your problem.
![2022-09-10_10 38 31](https://user-images.githubusercontent.com/9884180/189479749-c6c9aebe-579e-4ae0-aaa7-ab6e410a286a.png)
![2022-09-10_10 38 34](https://user-images.githubusercontent.com/9884180/189479765-5f289917-4f99-4995-a104-d13e2f4994cb.png)

**Comment by MehVahdJukaar** [comment]
Fixed
