### ISSUE TITLE
[Fabric] Server Crash, Slingshot Shooting a Traveler's Backpack

### ISSUE THREAD

**Issue by rxay579** [MehVahdJukaar/Supplementaries#365]
Minecraft 1.19.2, Java 17

supplementaries-1.19.2-2.1.3-fabric.jar
travelers-backpack-1.19.2-8.2.1.jar
from slightly modified Medieval MC Fabric v4.5 modpack

Description
I went to shoot a tuff block into a ravine and the slingshot chose to fire a backpack that was in my inventory (I was careless).
The projectile appeared to shoot fine but when it was going to impact, our clients were disconnected and we discovered the server shut down.
The server was able to launch after, but when re-joining in the area, the server crashed again.
I was able to edit (delete) the slingshot's projectile entity from the /world/entities/r*.mca file and clients were able to rejoin again.

I don't expect every modded item to be compatible but I've also not been able to find a config entry or datapack entry that would allow control over a whitelist/blacklist of items that the slingshot can shoot.

If the crash can be fixed, yay.
If there is a way to restrict items from the slingshot, please let me know.
I've found the config entry for disabling the slingshot entirely, so I'm working with that for now.

Crashlog / server log(s) attached (names and IPs edited).

[crash-2022-09-11_23.13.26-server - EDIT.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9545295/crash-2022-09-11_23.13.26-server.-.EDIT.txt)
[2022-09-11-6.log](https://github.com/MehVahdJukaar/Supplementaries/files/9545392/2022-09-11-6.log)
[crash-2022-09-11_23.18.34-server - EDIT.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9545449/crash-2022-09-11_23.18.34-server.-.EDIT.txt)
[2022-09-11-7.log](https://github.com/MehVahdJukaar/Supplementaries/files/9545452/2022-09-11-7.log)

**Comment by rxay579** [comment]
Ah, it appears that the config file entry in supplementaries-registry.json does not remove existing slingshots from the game.
Perhaps I am mistaken about what this config entry does.

...
"items": {
 ...
 "slingshot": false,
 ...
 },
...

**Comment by MehVahdJukaar** [comment]
No config remove existing items, they simply hide them from jei and creative and remove their recipes. Configs can never affect registry entries as if they did one could have a situation where a server and client with same mods and different configs wont be able to connect to eachother. I guess the file name is confusing but its like that for legacy reason since ages ago it used to do that
Anyways this is fixed
