### ISSUE TITLE
[Crash] While breaking a urn - Server & Client Crash - Fabric 1.19.2

### ISSUE THREAD

**Issue by SpigotDE** [MehVahdJukaar/Supplementaries#366]
hey there, the game crashed while breaking a urn in survival mode
newest versions applied

[client latest.log](https://gist.github.com/SpigotDE/0d8e8d7bc38261ff66a326a565ce6c2b)
[client crash report](https://gist.github.com/SpigotDE/7153822cbeeb2f1eeff17498555c4fc4)

[server latest.log](https://gist.github.com/SpigotDE/cabbd98bfd6ba895218947b4f145413d)
server crash report - no crash report created ( server nevertheless shut down )

**Comment by MehVahdJukaar** [comment]
Dont think it has anything to do with supplementaries. It seems some missing dependencies from TemperatureAspects or Dehydration mod (not familiar with those)
