### ISSUE TITLE
Bottling xp should cost xp to prevent xp duping

### ISSUE THREAD

**Issue by firyy** [MehVahdJukaar/Supplementaries#367]
Bottling xp should have additional configuration besides hp cost. Adding a xp cost would prevent xp duping.

"Amount of raw xp to produce an experience bottle"
"default = 10, min 0, max 100"

**Comment by MehVahdJukaar** [comment]
Right now the code that is used to determine how much do bottling works is exactly the same that decides how many orbs are generated, except it always uses its average. This means that in the long run the cost is identical. This can indeed create some instances of a couple xp points being duped but it isn't something that can be replicated at will and on average the xp is the same. This goes for older versions however as in the vey recent 1.19 patch a slight flat xp cost was added aswell so what you are suggesting is basically already there, minus the config that is

**Comment by MehVahdJukaar** [comment]
closing since has been added
