### ISSUE TITLE
More bottle support for jars

### ISSUE THREAD

**Issue by kihgy** [MehVahdJukaar/Supplementaries#37]
Hi I have some other mods with fluid bottles that I want to be compat with the jar:
3 types of dragon blood from Ice and Fire
Hot cocoa from Farmers Delight

**Comment by MehVahdJukaar** [comment]
actually those are among the few that should already be compatible. If you want to add more you can join my discord and I have a whole channed dedicated to jar stuff

**Comment by kihgy** [comment]
> actually those are among the few that should already be compatible. If you want to add more you can join my discord and I have a whole channed dedicated to jar stuff

Yep even the komodo dragons spit from alexs mobs work. But still the dragon bloods doesnt work

**Comment by MehVahdJukaar** [comment]
I've never tested those personally but guys on my discord told me that they work. next update you'll even be able to drink that hot cocoa with the same effect as a milk bottle. If you want to submit more feel free to join my discord, I only need a color and a item id and I can add all the ones you want
