### ISSUE TITLE
crash on startup with Minecraft 1.18.2

### ISSUE THREAD

**Issue by anthule** [MehVahdJukaar/Supplementaries#371]
I've installed Supplementaries but Minecraft now crashed on startup.   I'm using the latest version of Moonlight (although it appears to be called Selene on 1.18)

Crashlog is here: 

https://pastebin.com/R1pL17kT

Thanks for any suggestions

**Comment by GITHUBJacques** [comment]
I have the same problem as well, I have tried to run supplementaries but get error code: -1 on 1.18.2

Crashlog:
[crash-2022-09-18_21.41.53-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9595726/crash-2022-09-18_21.41.53-client.txt)

Thank you

**Comment by MehVahdJukaar** [comment]
Update forge

**Comment by anthule** [comment]
Thanks for the quick response.  That got past the Supplementaries crash, but is now crashing with something else.  I guess the newer version of Forge is incompatible with one of my other mods.

**Comment by MehVahdJukaar** [comment]
Update create. Update all your mods
