### ISSUE TITLE
Blackboard issues. 

### ISSUE THREAD

**Issue by MoonstruckSpirit** [MehVahdJukaar/Supplementaries#377]
Forge: 40.1.80
Supp: 1.18.2-1.5.5
Moonlight: 1.18.2-1.17.9

No other mods, no shaders. 

The GUI for the board does not pop up, I can draw on it using chalk but the UI is not there. I also cannot clear it with a sponge as per the wiki.

**Comment by MehVahdJukaar** [comment]
hm can you check your configs? I have some options to change their behavior to have the gui on or off. Maybe I have that inverted?

**Comment by MoonstruckSpirit** [comment]
client.toml: https://hastebin.com/rotitiwoca.ini
common.toml: https://hastebin.com/ogapehojuc.ini

**Comment by MoonstruckSpirit** [comment]
client.toml : https://hastebin.com/quhexupawo.ini
common.toml: https://hastebin.com/ugogejevoh.ini

**Comment by MehVahdJukaar** [comment]
can you try turning that config ("allow_gui") to false?

**Comment by MoonstruckSpirit** [comment]
Hi! Tried that to no avail :(

**Comment by MehVahdJukaar** [comment]
do you by any chance also arent able to open other mods guis?

**Comment by MoonstruckSpirit** [comment]
Not that I know of. I put Supplementaires on the aforementioned version of forge by itself (with it's dependency) and it's still occurs. But in my main pack Tinkers and things that have their own UI don't seem to struggle

**Comment by MehVahdJukaar** [comment]
Do you have optifine?

**Comment by MoonstruckSpirit** [comment]
I do not use optifine or any of the sorts.The bug still occurs with purely just the mod and its dependencyDoes it work on your end with that specific forge version?On 24 Sep 2022, at 15:42, MehVahdJukaar ***@***.***> wrote:﻿
Do you have optifine?

**Comment by MehVahdJukaar** [comment]
I have fixed this however I don't remember if I included said fix with the latest mod update
