### ISSUE TITLE
Crash due to sus Endstone Lamp texture name

### ISSUE THREAD

**Issue by AdeptusAutumn** [MehVahdJukaar/Supplementaries#381]
**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9640950/latest.log)
[crash-2022-09-25_16.16.55-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9640951/crash-2022-09-25_16.16.55-client.txt)

- Mod version, MC version and Loader you are using
supplementaries-1.18.2-1.5.6, MC 1.18.2, Forge 40.1.80
- A description of your issue and how to reproduce
I was attempting to change my skin using noppes_ More Player Models Mod.
To repoduce install Supplementaries alongside noppes_ More Player Models (called MPM from here) mod.
Start game and create world.
Press F12 to open MPM GUI.
Press Menu
Press Options
When pressing Select the Crash will occure.

**Comment by MehVahdJukaar** [comment]
I swear I already deleted that file, twice... Amogus symbol keeps reappearing lol

**Comment by MehVahdJukaar** [comment]
The sus has been purged once again
