### ISSUE TITLE
What do i need to install?

### ISSUE THREAD

**Issue by settfofinho** [MehVahdJukaar/Supplementaries#384]
Please i only want the decoration stuff, what do i need to install besides the supplementaries itself to be able to have it in my game? whenever i put the file in my mods folder the game crashes when i open it. please help me!

**Comment by MehVahdJukaar** [comment]
Short answer moonlight. Long answer use a launcher to do this automatically or check the dependency tab on the cueseforge page

**Comment by settfofinho** [comment]
> Short answer moonlight. Long answer use a launcher to do this automatically or check the dependency tab on the cueseforge page

thank you so much <3
