### ISSUE TITLE
[BUG] Log spammed when things burn when Carpet Extra is installed

### ISSUE THREAD

**Issue by Shazuli** [MehVahdJukaar/Supplementaries#385]
- Mod version, MC version and Loader you are using
Minecraft: 1.19.2
Fabric Loader: 0.14.9
Fabric API: 0.60.0
Supplementaries: 2.2.3

- A description of your issue and how to reproduce
Every time Ash block falls in the game this is printed to the log:
```
[18:24:04] [Server thread/ERROR]: Failed to handle entity type entity.supplementaries.falling_ash
[18:24:04] [Server thread/ERROR]: Failed to handle entity type entity.supplementaries.falling_ash
```

This will eventually spam the console if anything starts burning as blocks are replaced with Ash and turns into falling entities.

**Comment by MehVahdJukaar** [comment]
are you sure that's an error from vanilla? I cant find anything like that in the game code. needless to say I cant replicate

**Comment by Shazuli** [comment]
Ok, looks like this happens when [Carpet Extra](https://www.curseforge.com/minecraft/mc-mods/carpet-extra) is installed. With just Fabric API, Supplementaries and [Carpet](https://www.curseforge.com/minecraft/mc-mods/carpet) the log is not spammed when Ash blocks are falling.

**Comment by MehVahdJukaar** [comment]
should be reported on their side as that error is logged by carpet mod so they should know what causes it

**Comment by FlynnLies** [comment]
> Ok, looks like this happens when [Carpet Extra](https://www.curseforge.com/minecraft/mc-mods/carpet-extra) is installed. With just Fabric API, Supplementaries and [Carpet](https://www.curseforge.com/minecraft/mc-mods/carpet) the log is not spammed when Ash blocks are falling.

I'm having the same issue, but I didn't have Carpet Extra to begin with. Are you sure that it was that?

Minecraft Version: 1.19.2
Fabric Loader: 0.14.14
Fabric API: 0.73.2
Supplementaries: 2.2.50

**Comment by DrLeonardo95** [comment]
Bug is work on 1.20.1 version :(

**Comment by MehVahdJukaar** [comment]
but is not on my end
