### ISSUE TITLE
[FABRIC] Resource reload loop with Continuity

### ISSUE THREAD

**Issue by NyakoFox** [MehVahdJukaar/Supplementaries#386]
- Fabric 0.14.9, Supplementaries 2.2.3, Continuity 2.0.1

When these mods are added together, it causes a resource reload loop on startup. (The progress bar fills up, and then resets and starts again)

**Comment by MehVahdJukaar** [comment]
maybe report it on their side too. tbh I dont have much of a clue here. Only thing I'm doing with resources is adding some resources to an internal pack before resources used

**Comment by NyakoFox** [comment]
Mirrored it here: https://github.com/PepperCode1/Continuity/issues/171

**Comment by NyakoFox** [comment]
tried to grab a log today and it no longer happens, somehow, despite being consistent yesterday
