### ISSUE TITLE
(forge 1.18.2) game crashes on startup 

### ISSUE THREAD

**Issue by karkodarko123** [MehVahdJukaar/Supplementaries#393]
my game crashes when i try to open it
although it works fine when i try using supplementaries in 1.16.5
![crash](https://user-images.githubusercontent.com/114878296/193471038-b655d812-06fb-411f-8112-a828262b9f39.PNG)

i dont use any other mods than selene and supplementaries
- supplementaries-1.18.2-1.5.8
- selene-1.18.2-1.16.6
 my forge version is the recommended 40.1.0

here is the crash report:

[crash-2022-10-02_20.25.20-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9693242/crash-2022-10-02_20.25.20-fml.txt)

i hope you can help me 
thanks in advance

**Comment by MehVahdJukaar** [comment]
update selene lib

**Comment by karkodarko123** [comment]
i have  now tried both the newest (selene-1.18.2-1.17.9) and the one after what i used before (selene-1.18.2-1.17.0)
it crashes with both

**Comment by MehVahdJukaar** [comment]
You need to send me the one with everything updated then. The one you sent just complains you don't have stuff up to date, logically

**Comment by karkodarko123** [comment]
ok sorry
here it is with selene-1.18.2-1.17.9
[crash-2022-10-03_13.11.22-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9696935/crash-2022-10-03_13.11.22-client.txt)

**Comment by MehVahdJukaar** [comment]
Update forge
