### ISSUE TITLE
[1.16.5] better animals plus butterfly and supplementaries flax crashes server

### ISSUE THREAD

**Issue by xinwolfthorn** [MehVahdJukaar/Supplementaries#397]
https://pastebin.com/SabPuNyw

when i pick up the butterfly that the error lists, the server doesn't crash anymore

**Comment by MehVahdJukaar** [comment]
A butterfly is trying to incorrectly set the age of a flax block. I did work around this in future version but I don't think the issue is really on my end. Also I haven't updated 1.16 in almost a year

**Comment by Kasualix** [comment]
This is not supplementaries's fault and has been fixed in betteranimalplus.
