### ISSUE TITLE
Book pile blocks missing translation

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/Supplementaries#398]
Supplementaries 2.2.6
Minecraft 1.19.2
Forge 43.1.33

The book pile blocks do not have translations. This is glaringly obvious when using WTHIT, which is common in modpacks.
Steps to reproduce:
- Start the game with this mod, moonlight lib, WTHIT (to see the block's translation) and its dependency, Bad Packets.
- Place regular books, enchanted books or Quark ancient tomes.
- Observe lack of translations.

![2022-10-11_18 24 35](https://user-images.githubusercontent.com/69029346/195228360-e33f93d0-faf7-4d27-a613-eda8b330a207.png)
![2022-10-11_18 24 51](https://user-images.githubusercontent.com/69029346/195228363-2ab9e651-c0ed-481e-ad58-6aaf15dfe3b4.png)

**Comment by MehVahdJukaar** [comment]
added
