### ISSUE TITLE
tryed to run on server with newest forge 35.1.37 and your latest version and it crashes the server however if i roll back to older version it runs do you need detail 

### ISSUE THREAD

**Issue by manzipan** [MehVahdJukaar/Supplementaries#4]

**Comment by manzipan** [comment]
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Supplementaries (supplementaries) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
]

**Comment by MehVahdJukaar** [comment]
It was definitely not a smooth release but after two hotfixes I fixed this and another very similar issue
