### ISSUE TITLE
[1.19.x] The quiver mouse wheel interaction is inverted

### ISSUE THREAD

**Issue by SilverDavidMC** [MehVahdJukaar/Supplementaries#400]
When selecting an arrow from the quiver in it's gui, the mouse wheel is inverted from how the hotbar behaves. 

When using the mouse wheel for your hotbar, up = left and down = right. In the quiver UI, up = right and down = left. This results in the quiver being a bit trickier to use if you try using the mouse wheel.

**Comment by MehVahdJukaar** [comment]
Good catch I never noticed

**Comment by MehVahdJukaar** [comment]
fixed
