### ISSUE TITLE
[Crash / 1.18.2] when japanese is set as language

### ISSUE THREAD

**Issue by DoctorMage** [MehVahdJukaar/Supplementaries#401]
Logs
Latest
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9777260/latest.log)

Debug
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/9777262/debug.log)

Crash
[crash-2022-10-13_14.44.52-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9777263/crash-2022-10-13_14.44.52-client.txt)

MC Version - 1.18.2
Forge - 40.1.68
Mods Included
selene-1.18.2-1.17.9.jar
supplementaries-1.18.2-1.5.9.jar

Issue
Set lanague to 日本語 game will crash
repeat of #254 

https://streamable.com/vdzkmp

**Comment by B-Wither** [comment]
I have same issue again in 1.5.9 too.

**Comment by MehVahdJukaar** [comment]
should be fixed now
