### ISSUE TITLE
Crash when rendering faucet with create:chocolate

### ISSUE THREAD

**Issue by unweeked** [MehVahdJukaar/Supplementaries#402]
crash:
https://pastebin.com/cHdSJNmD

Supplementaries 1.19.2-2.2.6
Moonlight 1.19.2 2.0.32
[some other mods, but they're unrelated to the crash]
forge 43.1.15

I placed a faucet coming off of the create:chocolate fluid and my game crashed. Also, **it happened on a server** so it's definitely a rendering issue.
When I tried doing it again, I couldn't reproduce it, idk. However, shortly before the game crashed, the fluid coming out of the faucet appeared completely black if that helps.

**Comment by MehVahdJukaar** [comment]
hm I see. damn I thought I fixed all that stuff for good a while back

**Comment by MehVahdJukaar** [comment]
oh were you on a server?

**Comment by unweeked** [comment]
Yeah I was, that could be the issue

**Comment by MehVahdJukaar** [comment]
Were you using a velocity proxy server?

**Comment by unweeked** [comment]
Well, it was a forge aternos server, maybe you know more about them than I do.

**Comment by MehVahdJukaar** [comment]
Ah I see. Wel the I'm still not surr

**Comment by unweeked** [comment]
Well, I wasn't able to replicate it anyways, maybe it was 1/1000000 and the bug isn't worth the effort :)
Even though it's the most unsatisfying solution D:

**Comment by MehVahdJukaar** [comment]
Oh let's hope it's not an issue anymore then
