### ISSUE TITLE
ive been getting this crash report for my server

### ISSUE THREAD

**Issue by Willywonkascumslut** [MehVahdJukaar/Supplementaries#405]
I have updated my mods and everything but I keep getting this plz help

[crash-2022-10-15_03.41.31-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9793465/crash-2022-10-15_03.41.31-fml.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight. Use a launcher to keep your mods updated
