### ISSUE TITLE
[1.19.2] Crash due to incompatibility with latest version of Forge

### ISSUE THREAD

**Issue by GoldenDarius** [MehVahdJukaar/Supplementaries#406]
I updated forge to 43.1.43, and from checking the logs, the mod (on its latest version, including Moonlight) seem to cause the game to not start at all, bringing me back to the launcher.

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9794277/latest.log)
Here's the logs

**Comment by MehVahdJukaar** [comment]
Can you confirm that it works with an older forge ?

**Comment by GoldenDarius** [comment]
Ironically, it doesn't work with 43.1.34 and it worked in 33

**Comment by GoldenDarius** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9794358/latest.log)
here's the .34 logs

**Comment by GoldenDarius** [comment]
It worked in .33 as I was playing that a few days ago

**Comment by GoldenDarius** [comment]
Alright so: I found out I had the wrong version of Supplementaries installed on the Forge 43.1.34 version, I will check if this is the case with .43

**Comment by GoldenDarius** [comment]
I will be closing this issue, apparently in the .43 version I didn't have the right versions either, it was an oversight by me
