### ISSUE TITLE
Cookielicious Cookie missing

### ISSUE THREAD

**Issue by DigitalPopsicle** [MehVahdJukaar/Supplementaries#407]
The chocolate cookie from Cookielicious won't go into a jar due to an error with the tags.

As per the source:
https://github.com/MehVahdJukaar/Supplementaries/blob/master/common/src/main/resources/data/supplementaries/tags/items/cookies.json

The vanilla cookie is listed twice, so the chocolate cookie doesn't go in the jars. Their latest mint, banana, and adzuki cookies are also missing.

**Comment by MehVahdJukaar** [comment]
Can you send me their Ids or make A PR that adds them to the tag?

**Comment by DigitalPopsicle** [comment]
I was using a datapack that added the tags so this seems to work. There's a few extra that I was using too

```
    {"id":"cookielicious:strawberry_cookie","required":false},
    {"id":"cookielicious:vanilla_cookie","required":false},
    {"id":"cookielicious:strawberry_cookie","required":false},
    {"id":"cookielicious:chocolate_cookie","required":false},
    {"id":"cookielicious:banana_cookie","required":false},
    {"id":"cookielicious:mint_cookie","required":false},
    {"id":"cookielicious:adzuki_cookie","required":false},
    {"id":"buddycardsexp:buddycookie","required":false},
    {"id":"honeyexpansion:honey_cookie_sausage","required":false},
    {"id":"abnormals_delight:mulberry_cookie","required":false}
```

**Comment by MehVahdJukaar** [comment]
added, ty
