### ISSUE TITLE
Cannot hide bamboo spikes in Roughly Enough Items

### ISSUE THREAD

**Issue by dmsw0303** [MehVahdJukaar/Supplementaries#41]
I've never had this issue with any item in REI. The various bamboo spikes are also the only items in Supplementaries that do this. I can filter them out entirely from the REI panel, and they'll still show up. Can look back through my filter list and it will show that they're still hidden, but they never actually are.

**Comment by MehVahdJukaar** [comment]
are you talking about normal spikes or tipped ones? I'm saying this because even if they are different items they are tied together and to disable them you have to disable the tipped variant

**Comment by dmsw0303** [comment]
Well technically, even though I do have them disabled through the registry config, I'm talking about the filtering option in REI. It just keeps items that you've marked as hidden, from showing up in the list, this is useful for disabled items or items that just don't really serve a purpose being there. I use the feature for at least 1 item in most the mods in my mod pack, and I've never had a single issue with it until supplementaries.

Even if items are enabled and craftable, hiding them in REI keeps them from appearing, but this is not the case with bamboo spikes.(the tipped variants).This has been an issue with this specific item and REI for a month or two for me, or whenever they were added. No matter what I do they continue to appear in the list even if the filter still shows that they're suppose to be hidden.

I'm not sure how best to explain this, judging from your comment I'm assuming you don't use REI, so I don't mean to over explain if you do.

You can replicate this on 1.16.5 and forge 36.1.0 by opening REI,  scrolling to the very bottom, clicking the filter button, clicking the gear towards the top right, typing in @Supplementaries, and clicking and dragging over all the bamboo variants,  and then clicking hide selected towards the bottom. make sure you hit back, and then back again, and then save changes, then open up the list and you'll find all the bamboo spikes are still showing.  I have zero idea why this item would be the only one out of my 120 mods to do this with REi

**Comment by MehVahdJukaar** [comment]
I'll look into it. Honestly I don't even know why they are there to begin with. Thing is that with JEI I had to write a plugin to actually put them there because the mod would only display one variant of the item. I'll find a fix worst case scenario I'll add a config option for them

**Comment by dmsw0303** [comment]
Hey, decided to do some more testing in the hopes that i could be a little helpful, changing the registry config to true for bamboo spikes allowed me to hide them without issue. Whether or not that helps you narrow it down, or helps you determine that its not an issue worth worrying about, I'd say this is definitely an ample fix for me

**Comment by MehVahdJukaar** [comment]
I don't know how you got that result cause I've installed rei and I still can't disable any of them whether they are enabled or not in the registry configs. I'm doing exactly what vanilla is doing for tipper arrows so I think this might be a rei issue. It might be an edge case since they are both an nbt item and there are two items that map to the same block. Too bad that there doesn't seem to be an option to only show stuff that's in the crative inventory like with jei.

**Comment by dmsw0303** [comment]
okay so, oddly enough, tried some stuff on a brand new instance. REI doesnt let me hide them properly if i find them in the filtering menu by typing "@supplementaries", but if i type bamboo and hide them that way it actually worked for me. im perplexed. i have absolutely no idea why it would function like this. i have around 200 other items hidden and i've encountered no issues with them whatsoever. 

but given this wierd inconsistency id say this is most likely on REI's part even if its an edge case.

**Comment by MehVahdJukaar** [comment]
well it's still a relatively new mod, at least compared to jei and the forge version is just a port and hasn't seen alot of updates recently so it probably just needs some time to fix some of these minor issues. I'll close this for now since at least you've found a temporary solution
