### ISSUE TITLE
[1.19.2] Server crash (ticking block entity) when RFTools Builder with quarry shapecard mines something from Supplementaries. 

### ISSUE THREAD

**Issue by Gbergz** [MehVahdJukaar/Supplementaries#410]
Title^

Server crash (ticking block entity) when Builder with quarry shapecard from RFTools mines something from Supplementaries.

**Versions:**
**Supplementaries**: 1.19.2-2.2.8.jar
**Moonlight**: 1.19.2-2.0.39.jar
**MCjtyLib:** 7.0.3
**RFTools Builder:** 5.0.4
**RFTools Base:** 4.0.3
**RFTools Power:** 5.0.1

**Forge:** 43.1.39

**Crash Report**: https://gist.github.com/Gbergz/03dcd464f5f4e72f82d193b462c98b58

Original Report on the RFTools issue tracker: 
https://github.com/McJtyMods/RFToolsBuilder/issues/105

**Comment by MehVahdJukaar** [comment]
This happens on framed blocks and sign post blocks

**Comment by MehVahdJukaar** [comment]
Should be fixed now
