### ISSUE TITLE
Flex Seed In Lava Break server

### ISSUE THREAD

**Issue by AzureDoom** [MehVahdJukaar/Supplementaries#411]
**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
https://gist.github.com/AzureDoom/5e638f968c1e16155636fac015ac1fcc

- Mod version, MC version and Loader you are using
2.2.8/1.19.2/Fabric

- A description of your issue and how to reproduce
- Throw Flex Seed into lava, server dies.

**Comment by MehVahdJukaar** [comment]
Flax seeds are just a normal item, they should not perform any such thing, especially calling a method from their block. Do you have any mod that plants stuff from seeds entities? Fabric doesn't even show mixins so I can't tell

**Comment by MehVahdJukaar** [comment]
Maybe same as this one? https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/449

**Comment by parataku** [comment]
Just had to troubleshoot the same issue, in our case it was the selfPlanting option of the vanillatweaks mod

**Comment by MehVahdJukaar** [comment]
A bit late but should be reported to them
