### ISSUE TITLE
Gold, copper, netherite don't support as much blocks as iron

### ISSUE THREAD

**Issue by Hypsellis** [MehVahdJukaar/Supplementaries#413]
The gold, copper, and netherite don't support as much blocks as iron, it would be great and coherent if all the ores supported the same blocks:
- Copper door, trapdoor, bar, gate, chain, ladder, button, plate
- Gold chain, ladder
- Netherite bar, gate, chain, ladder, button, plate

**Comment by Hypsellis** [comment]
At this point the ore integration between Quark and Supplementaries starts to look messy.. It would be great if both mods could agree what should be added or not by one or the other.

**Comment by MehVahdJukaar** [comment]
I don't get why this would be a problem. Why would copper need all that? The only one that would make sense is netherote stuff but I don't see a way to make it unique. Also there are a bunch of mods adding copper things.

**Comment by MehVahdJukaar** [comment]
Also idk what's messy about it, we both added unique items we thought could be nice , expanding on the redstone department with buttons and doors following existing vanilla guidelines that has gold and iron pressure plate. Netherite is sort of an exception on my part but makes sense as it's too unique. I thought of adding buttons and plates but couldn't find a unique use

**Comment by Hypsellis** [comment]
I agree with you, not all of them need to be added, and not necessarily by Supplementaries. It's why I suggested you and Quark devs should agree on what you wish to add or not.

**Comment by MehVahdJukaar** [comment]
I believe we are both happy with the things we added
