### ISSUE TITLE
Crash on startup/ World load

### ISSUE THREAD

**Issue by Mathio95** [MehVahdJukaar/Supplementaries#414]
Game crashes on either load minecraft of loading world. 
don't know for sure if its Supplementaries, but i think its incompatible with something. 

When i delete Supplementaries minecraft works normally 

Can't figure it out tho... 

Please help 

MC 1.19.2 
Forge 43.1.43
Supplementaries 2.2.9
Moonlight 2.1.0

[crash-2022-10-20_17.55.38-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9832157/crash-2022-10-20_17.55.38-client.txt)

**Comment by MehVahdJukaar** [comment]
it says there you actually have supplementaries 2.2.8

**Comment by Mathio95** [comment]
> it says there you actually have supplementaries 2.2.8

You're right! 

Re-installed it trough Curseforge, now the version is correct. 

Didn't update correctly i guess...
