### ISSUE TITLE
Keybind for Quiver Does Nothing

### ISSUE THREAD

**Issue by LolJohn11** [MehVahdJukaar/Supplementaries#415]
**Issue Description**

When pressing the keybind for Quiver (default is "v") its GUI does not open - nothing happens, really. Tried all combinations of different gamemodes, empty hand vs holding a bow, etc. Nothing seems to fix this.

Issue persists on an instance with no other mods installed (other than mandatory Moonlight Library).

All other functionality of the quiver seems to be working normally and as intended.

Hopefully, this is just a bug and not a leftover keybind that is no longer intended to work to make the quiver harder to use. Or maybe I'm misunderstanding how this keybind works.

**Steps to Reproduce**
1. Have a quiver in your inventory
2. Press "v" or whatever the keybind for Quiver is set in the controls

**Platform Info**
- MC 1.19.2
- Forge 43.1.43
- Mod Version: 2.2.9

**Comment by MehVahdJukaar** [comment]
It's actually simply not implement. I forgot to remove that keybind. Just use the quiver normally, there's a 50% chance that keybind will just disappear forever or be actually implemented as I'm still not sure of some things and the current system heavily relies on the item actually being used to open a gui

**Comment by LolJohn11** [comment]
Got it, thanks for clarifying!
I do hope that the ability to use the quiver via keybind will get implemented someday since it would improve usability a lot. For example, I do find it limiting that for ease of access to the quiver it, essentially, has to be kept in the player's hotbar, when regular arrows can be held anywhere in the inventory. I don't know if that is a fair price to pay (in terms of balance) for the ability to switch arrows and store them compactly. I guess if it _does_ get implemented, it will require some more config options to adjust behavior based on the desired level of the quiver being balanced.

**Comment by TheOneArkani** [comment]
Hello MehVahdJukaar,
I don't know if other people have the same problem as me but the Quiver does not work. In the Wiki it says that you can use it as a bundle. I tried it ingame but it does not work and I tried many things for instance key combination but this does not work either. I can open the Quiver with right Mouse click and there are six slots. 
Is it a bug or how can I use the Quiver?
Tested in Java 1.19.2 with forge 43.1.47
I also experimented a bit without a modpack. Only the Supplements and the Moonlight Lib Mod but doesn't seems to work, too.
I hope that you can help me if you have time of course. I do not want to stress you or something.
Nevertheless a really awesome mod. I like it a lot! Very well done!
Best regards
TheOneArkani

**Comment by LolJohn11** [comment]
@TheOneArkani Have you tried (in your inventory) grabbing arrows with the left click and then right-clicking with them on the quiver? That's how you are supposed to add arrows to the quiver. But if that doesn't work then it's probably a bug.

**Comment by TheOneArkani** [comment]
Thank you very much for your quick reply and your advice! It worked! I was just stupid enough to not click the right mouse-button :O
Best regards
TheOneArkani

**Comment by LolJohn11** [comment]
Hi @MehVahdJukaar 
I see that you've added the quiver keybind in the latest update. Thanks!
I've just tested it and it works, but when using the keybind the quiver GUI for choosing the arrow slot is shown for less than a second and then it closes, even when holding down the keybind. It makes it very hard to switch between more than 2 arrow slots at a time. Is this something that can be fixed? Or is it working as intended?
