### ISSUE TITLE
1.18.2 Tomato vine rope missing texture

### ISSUE THREAD

**Issue by ShadeKage** [MehVahdJukaar/Supplementaries#416]
- Mod version: 1.18.2

- Description: If using the tomato's from farmers delight to try and use the "rope vine" mechanic that its supposed to have support for this mod, the block has no texture, the texture file seems to be missing from at least 1.18.2's mod version, unsure if 1.19 is missing the texture or not

Like.. the texture file for "supplementaries:rope_tomatoes" is just... not there lol, shown in the "missing.png" image

- Screenshot
![issue1](https://user-images.githubusercontent.com/109502927/197315785-5e572d5e-61d5-4ca0-bb80-79244947d938.png)
![issue2](https://user-images.githubusercontent.com/109502927/197315839-7103ee76-97b5-41e8-b464-ffa98ca17bef.png)
![missing1](https://user-images.githubusercontent.com/109502927/197315954-e0e9605b-9b53-4c37-ab67-42a9203156a3.png)

**Comment by ShadeKage** [comment]
UPDATE
Its missing from 1.19 AS WELL
So uh.. yea... tag this as both I guess lol

**Comment by MehVahdJukaar** [comment]
It's 1.18 only. Is not missing a texture as it used the rope texture and FD one so it doesn't have it's one unique one. What's missing is the model

**Comment by MehVahdJukaar** [comment]
should be fixed
