### ISSUE TITLE
New 1.18.2 version Crash Server-Client

### ISSUE THREAD

**Issue by XionioXMaster** [MehVahdJukaar/Supplementaries#417]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
[- A log if the issue is casing a crash. These are found in your instance directory under /logs](https://paste.gg/p/anonymous/1d1910f4de0a4441a8d7fe781a1ab4db)

- [supplementaries-1.18.2-1.5.11.jar](https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/4040436)

- start server, done

supplementaries-1.18.2-1.5.9 there is no such beauty

**Comment by MehVahdJukaar** [comment]
Update farmers delight. Keep your mods updated
