### ISSUE TITLE
Crash during worldgen placing vines on/under several Supplementaries blocks

### ISSUE THREAD

**Issue by DesertDweller** [MehVahdJukaar/Supplementaries#419]
The Treetop Tavern structure from Integrated Dungeons & Structures uses many Supplementaries blocks.
This crash occurs in about 20% of these structures.

To duplicate, create a curseforge 1.18.2 modpack using forge version 40.1.73.
Just add IDAS and Feature NBT Deadlock Be Gone (CF does not add this required dependency for IDAS 1.18.2).
Create a new world with seed 1165080016.
Execute comment /locate idas:treetop_tavern and teleport to it - should be at 2832, ~, 720

This crash also occurs in the 1.19.2 version.

I took a copy of the latest version (1.4.7) of IDAS for 1.18.2 from Github and replaced all occurrences of the following Supp. blocks:
          sconce, wall_sconce, and wall_latern replaced with glowstone
          rope and rope_knot replaced with brown_concrete.

With the above changes, the crash does not occur (since these are now full blocks).
Flying around the structure with the above changes reveal that vines are being placed under wall_laterns and on the sides of rope and sconces.

Not sure if this is something you have control over or if this is really a bug in minecraft itself relating to vine placement.
Or is there something that IDAS needs to change in the structure to prevent vines from being placed inside the structure?

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9853312/latest.log)

**Comment by MehVahdJukaar** [comment]
So this seems to happen because of a broken collision shape method in vines block. Happens when vines feature is trying to get placed. Are you sure it's supplementaries?

**Comment by MehVahdJukaar** [comment]
Could you try again using the version I just published?

**Comment by DesertDweller** [comment]
That fixed it!  Thanks so much - this has been driving me nuts for weeks.

**Comment by MehVahdJukaar** [comment]
Well we finally figured it out then. I had some reports ages ago but cause wasn't clear at all. Aparently it tracks down to tile entities not being initialized during worldgen
