### ISSUE TITLE
Netherite Door and Trapdoor are located on "Decorative" tab, instead of "Redstone" tab

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#42]

**Comment by MehVahdJukaar** [comment]
that's because they can't interact with redstone

**Comment by Brun333rp** [comment]
Gold Doors and Trapdoors also can't, so maybe they should be on "Decorative" tab as well?

**Comment by MehVahdJukaar** [comment]
Gold doors can interact with redstone, infact that's their main use. When powered they will block any interaction and when unpowered they'll act as normal doors

**Comment by Brun333rp** [comment]
well, I tried to use redstone in gold doors and trapdoors, but it didn't work
