### ISSUE TITLE
Way Sign Structure Fails to generate with signs on multiplayer

### ISSUE THREAD

**Issue by InfidelKilla** [MehVahdJukaar/Supplementaries#421]
- Mod version, MC version and Loader you are using
Mod Version: supplementaries-1.19.2-2.2.11-fabric.jar Moonlight: moonlight-1.19.2-2.1.3-fabric.jar Fabric 0.14.10 (fabric-api-0.64.0+1.19.2.jar)
- A description of your issue and how to reproduce
Way Signs fail to generate with signs when on a multiplayer server. The mod is installed both server side and client side. The world slowly expands with a world border. The way sign structure works as intended in single player but in multiplayer the post don't generate with signs. The block generator above them is still present and its just spruce fences. 
- If applicable, add screenshots to help explain your problem.
![2022-10-30_12 30 11](https://user-images.githubusercontent.com/91441433/198890629-5cec656c-dced-46da-be95-0ea137c3eca4.png)

**Comment by MehVahdJukaar** [comment]
possibly fixed

**Comment by InfidelKilla** [comment]
Is there a new update?

**Comment by MehVahdJukaar** [comment]
Yes
