### ISSUE TITLE
Quiver not working

### ISSUE THREAD

**Issue by Moneer333** [MehVahdJukaar/Supplementaries#422]
I'm not able to shoot the arrows that are in the quiver at all i don't know why i don't know if anyone else is having this issue.
Moreover, I can't take a stack of arrows out of a quiver once its in so i can't even get my arrows back.

**Comment by MehVahdJukaar** [comment]
It works like a bundle, same way you get stuff out there. If arrows don't work it's a mod incompatibility, mixins clashing or overriding my stuff likely. I know that for example archers paradox nukes my stuff

**Comment by cofl** [comment]
I recently encountered an issue with this as well: CofH Core (the library for the Thermal series) overrides the bow behavior in a way that's incompatible with Supplementaries.

**Comment by mrjasonclifford** [comment]
I am having same issue playing stoneblock3 and using a vanilla bow

**Comment by mrjasonclifford** [comment]
ok nevermind my quiver had some weird arrows in it and that was the issue . seems resolved when i removed arrow of the turtle master and arrow of slowness

**Comment by KingLemming** [comment]
Archer's Paradox doesn't "nuke your stuff" - I provide a capability and a number of other things to work with CoFH's enhanced bow logic. Let's maybe see what you're doing and what I'm doing and get this resolved.

**Comment by MehVahdJukaar** [comment]
Im using a couple of mixins like this one
https://github.com/MehVahdJukaar/Supplementaries/blob/771fc642270a9d61d3cb5516a7af9dc7bcf35621/common/src/main/java/net/mehvahdjukaar/supplementaries/mixins/ProjectileWeaponItemMixin.java#L22

**Comment by KingLemming** [comment]
I believe I have a workaround on my end. My archery code predates the existence of mixins in Forge, and actually predates the GetProjectiles event as well.

I'll see what I can do.

**Comment by MehVahdJukaar** [comment]
Ok cool
