### ISSUE TITLE
[Quilt] Crash when rendering a globe

### ISSUE THREAD

**Issue by SplendidAlakey** [MehVahdJukaar/Supplementaries#424]
**MC** 1.19.2
**QFAPI** 4.0.0-beta18
**Supplementaries** 2.2.13

To reproduce just place a globe down. This crash is different from https://github.com/MehVahdJukaar/Supplementaries/issues/423, because it only happens on Quilt. The logs are also a bit different.

Logs: https://gist.github.com/SplendidAlakey/15ede099fc8c36cc0a3be3ee4f7f409c

**Comment by MehVahdJukaar** [comment]
should be fixed in newest version

**Comment by SplendidAlakey** [comment]
Yep, fixed in .15. Thank you!
