### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Jekliw** [MehVahdJukaar/Supplementaries#426]
I added some mods i got an crash report, after removing this mod it works normaly.
[crash-2022-11-04_18.42.12-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9940885/crash-2022-11-04_18.42.12-client.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight

**Comment by MehVahdJukaar** [comment]
Actually I can't tell you are using the dreaded 1.19 version and I just see supplementaries and moonlight version are mismatched so one is outdated or for the wrong version

**Comment by MehVahdJukaar** [comment]
I suggest using the 1.19.2 version instead as the 1.19 one is discontinued and has many bugs and less content
