### ISSUE TITLE
globe can be supported by water

### ISSUE THREAD

**Issue by catbuddy1028** [MehVahdJukaar/Supplementaries#427]
the globe can be supported by water 
can be recreated by placing the globe on the side of a block, that the placed globe will be on top of a water block 
forge : 43.1.1
minecraft : 1.19.2
the latest supplementaries
![the ](https://user-images.githubusercontent.com/117509705/200111460-93f70700-251c-46e2-9a06-483ce0c3fa94.png)

**Comment by MehVahdJukaar** [comment]
fixed
