### ISSUE TITLE
[1.18.2] Mod Support for Breezy

### ISSUE THREAD

**Issue by SeriousCreeper** [MehVahdJukaar/Supplementaries#430]
Heya,

Breezy is a mod that adds an air balloon and uses its own wind direction to determine which way the balloon goes. 

Link to mod: https://www.curseforge.com/minecraft/mc-mods/breezy

It'd be neat if the Wind Vane from Supplementaries actually shows the current wind direction from Breezy if it's installed as well. 

Cheers,
SC

**Comment by MehVahdJukaar** [comment]
added in 1.19

**Comment by SeriousCreeper** [comment]
Any chance to get this for 1.18 as well, or is that version no longer supported? 

And thanks!

**Comment by MehVahdJukaar** [comment]
should be there now

**Comment by SeriousCreeper** [comment]
Thank you so much!
