### ISSUE TITLE
2 floor cake crash

### ISSUE THREAD

**Issue by slovinsqui** [MehVahdJukaar/Supplementaries#433]
- [latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/9988110/latest.log)
   [2022-11-10-7.log.gz](https://github.com/MehVahdJukaar/Supplementaries/files/9988111/2022-11-10-7.log.gz)

- supplementaries-1.19-2.0.13.jar , MC 1.19.0  fabric 0.14.10
- joined a world and stacked a cake on top of another, then crashed
rejoined, did not crash, cakes are still there and can stack them, after attemting to eat one, crashed again
retried to eat 2 floor cake again, crashed

**Comment by MehVahdJukaar** [comment]
I'm not supporting that old version anymore. This isn't an issue in the latest verison
