### ISSUE TITLE
Urn Duplication with Silk Touch

### ISSUE THREAD

**Issue by gokayerez** [MehVahdJukaar/Supplementaries#434]
Supplementaries 2.2.10, 1.19.2, Forge

Urns in the wild can be picked up with silk touch. They will drop their loot + 1 urn. Placing these urns afterwards and breaking them again with silk touch causes them to drop 2 urns.

**Comment by MehVahdJukaar** [comment]
You are using an outdated version

**Comment by gokayerez** [comment]
Works as intended in latest version, apologies!

**Comment by MehVahdJukaar** [comment]
Cool
