### ISSUE TITLE
Writable books won't place.

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#438]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**

- Mod version, MC version and Loader you are using
1.19.2
- latest version of supplementaries

- A description of your issue and how to reproduce
i don't really know

- If applicable, add screenshots to help explain your problem.
-
![image](https://user-images.githubusercontent.com/181536/203866370-ec8b1c07-f682-4b70-bd86-53ea7f38450a.png)
it says it's place able but you just open the book.

**Comment by MehVahdJukaar** [comment]
Should be fixed now
