### ISSUE TITLE
Crash on servers

### ISSUE THREAD

**Issue by RitzScythe** [MehVahdJukaar/Supplementaries#440]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

I am, updating is what borked my server

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
https://gist.github.com/RitzScythe/da98e6b1b3208d17dd17b482cad6056d
- Mod version, MC version and Loader you are using
Mod v2.2.22, MC 1.19.2 Forge Mod Load 

- A description of your issue and how to reproduce

Server doesnt server when expected to server

- If applicable, add screenshots to help explain your problem.

I start server, console goes, modload fails. CF discord user thinks mod is calling client code on server but idk what that means

**Comment by MehVahdJukaar** [comment]
Downgrade moonlight. Yesterday I uploaded and quickly removed s failed version
