### ISSUE TITLE
Crash on opening some Shipwreck Map loottables (suspecting incompatibility with Yung's mods)

### ISSUE THREAD

**Issue by SirRosenfeld** [MehVahdJukaar/Supplementaries#441]
Hi,

Minecraft 1.19.2
Supplementaries (any version produces the crash, but I'm on 2.2.23)
Fabric 0.14.10

Game crashes when opening some vanilla shipwrecks loot. I suspect an incompatibility with Yung's Better Witch Huts and Better Dungeons which replaces Minecraft vanille Witch Huts and Desert Pyramids.
I imagine the mod hangs on the /locate command when trying to generate Adventurer's maps for removed structures.

There is no crash output in console, just timing out, so I'm really suspecting a /locate failure

[22:34:13] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[22:34:13] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[22:34:14] [Server Watchdog/ERROR]: This crash report has been saved to: /var/directory_serv/minecraft_388062/./crash-reports/crash-2022-11-27_22.34.14-server.txt

Crash report :
https://pastebin.com/w010N7jh

**Comment by MehVahdJukaar** [comment]
thing is adventurer maps dont spawn in shipwrecks loot. Just from villagers. Might very well be something with the locate command. maybe server was already particularly busy. Try increasing max tick time

**Comment by SirRosenfeld** [comment]
Oh, my bad then ! Well, I'll move my research away from Supplementaries !
