### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by SomaLUX** [MehVahdJukaar/Supplementaries#443]
Minecraft crashes on startup when using this mod. I'm playing on 1.18.2, with the latest versions of both Selene and Supplementaries.

[crash-2022-11-29_20.53.07-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10118228/crash-2022-11-29_20.53.07-fml.txt)

**Comment by MehVahdJukaar** [comment]
Update farmers delight
