### ISSUE TITLE
Error: java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by caracolito2-0** [MehVahdJukaar/Supplementaries#444]
I've been having problems launching the game and this error keeps ocurring.
[crash-2022-12-01_21.53.05-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10137383/crash-2022-12-01_21.53.05-client.txt)
![Captura de pantalla 2022-12-01 220105](https://user-images.githubusercontent.com/119640358/205194723-5809e02f-888a-4192-88df-b3066d96ded8.png)
 here is the report :)
btw, ive tried to report this through a curse forge comment and it kept saying i was posting spam

**Comment by MehVahdJukaar** [comment]
Try deleting the mod configs. They might be invslidy

**Comment by caracolito2-0** [comment]
which file is it?

**Comment by MehVahdJukaar** [comment]
Not sure delete all 3

**Comment by caracolito2-0** [comment]
it crashed again:
[crash-2022-12-03_18.55.20-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10147449/crash-2022-12-03_18.55.20-client.txt)

**Comment by MehVahdJukaar** [comment]
now says that this config failed to parse
forge-resource-caching.toml
delete your entire config folder might have been all corrupted or something

**Comment by caracolito2-0** [comment]
It worked!!! thanks :) !!!
