### ISSUE TITLE
Texture Issue with Sophisticated Backpacks

### ISSUE THREAD

**Issue by Puffiefishie** [MehVahdJukaar/Supplementaries#445]
When I installed this mod, I went into the creative menu to check out the stuff it adds. I clicked on the Sophisticated Backpacks menu and noticed the backpacks were missing their textures. They appeared as magenta and black checkered blocks. I have not had this issue before installing Supplementaries.

**Comment by MehVahdJukaar** [comment]
what version?

**Comment by MehVahdJukaar** [comment]
Just tried with those 2 mods on 1.19.2 forge and no issue for me

**Comment by MehVahdJukaar** [comment]
Can you try with those mods alone? I don't see how supplementaries could affect another mods item models

**Comment by Puffiefishie** [comment]
> Can you try with those mods alone? I don't see how supplementaries could affect another mods item models

Alright!

**Comment by Puffiefishie** [comment]
> Can you try with those mods alone? I don't see how supplementaries could affect another mods item models

Yeah the issue was on my part, I opened up the creative menu and the textures were back to normal so I'll close this as complete. Apologies for bothering you 😅.
