### ISSUE TITLE
Bamboo Spike "Player loot" not working on Fabric

### ISSUE THREAD

**Issue by eyesoffaith** [MehVahdJukaar/Supplementaries#447]
Just a short a sweet notice that the blazes aren't dropping blaze rods when killed by bamboo spikes despite player loot being set to true in the config.

**Comment by MehVahdJukaar** [comment]
Its one of those small features here and there that arent implemented for fabric. On forge they rely on forge fake player

**Comment by MehVahdJukaar** [comment]
has now beed added
