### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by dddurandal** [MehVahdJukaar/Supplementaries#448]
[crash-2022-12-12_16.49.44-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10207693/crash-2022-12-12_16.49.44-fml.txt)

hasnt happened ever before i used to use an old version of supplementaries on my modpack had been playng on it for months but then  it started crashing all of a sudden so i tried updating it, didnt help and removed every mod except the dependencies but still same error

**Comment by MehVahdJukaar** [comment]
Check if all your mods are updated. Also I don't think that's related to the mod. Only way such an error can happen is if the game already crashed before meaning something went wrong while loading stuff before it

**Comment by dddurandal** [comment]
> Check if all your mods are updated. Also I don't think that's related to the mod. Only way such an error can happen is if the game already crashed before meaning something went wrong while loading stuff before it

i removed every other mod except supplememntaries and its dependency

**Comment by MehVahdJukaar** [comment]
Try downloading it again or make a new instance

**Comment by dddurandal** [comment]
> Maybe it could be java but still seems weird. Are you in latest forge?

yes but it used to work on previous version too, but still i tried on both versions of forge and it crashed

**Comment by MehVahdJukaar** [comment]
Send me the debug log too

**Comment by dddurandal** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10207806/latest.log)
is this the log?

**Comment by dddurandal** [comment]
![image](https://user-images.githubusercontent.com/120382615/207042420-4797a84c-a9be-463e-b495-cffabcdf559c.png)
![image](https://user-images.githubusercontent.com/120382615/207042549-e6912fcd-2dd2-45ad-a2a6-e2b526ad924e.png)
this is the original modpack

**Comment by dddurandal** [comment]
> ![image](https://user-images.githubusercontent.com/120382615/207042420-4797a84c-a9be-463e-b495-cffabcdf559c.png) ![image](https://user-images.githubusercontent.com/120382615/207042549-e6912fcd-2dd2-45ad-a2a6-e2b526ad924e.png) this is the original modpack
i tried with the latest supplementeries too

**Comment by dddurandal** [comment]
fixed, i repaired the java
