### ISSUE TITLE
bamboo spike without potion in create contraption crash null pointer exception

### ISSUE THREAD

**Issue by CKenJa** [MehVahdJukaar/Supplementaries#450]
Supplementaries 1.5.13
Minecraft 1.18.2 
Forge 40.1.86

bamboo spike without potion in create contraption crash null pointer exception

[crash-2022-12-09_17.54.29-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10208707/crash-2022-12-09_17.54.29-server.txt)

https://user-images.githubusercontent.com/41111170/207065075-6fb4725c-d797-4ff7-b750-4b4b7039a390.mp4

**Comment by MehVahdJukaar** [comment]
should have been fixed
