### ISSUE TITLE
1.19.3 port (Take 2)

### ISSUE THREAD

**Issue by gohkenytp** [MehVahdJukaar/Supplementaries#452]
I was wondering if you can port the Supplementaries mod now to Minecraft 1.19.3. Can you do it for me? Thanks.

**Comment by MehVahdJukaar** [comment]
Please don't bug authors about updates as soon as a new major version comes out. Lots of stuff changed and a lot of things will need to be done for it so be as usual be patient. Updates will come as they always had, just when we have time to work on it and personally I don't have any hurry to do so as I already have other projects that I'd rather work on while the actual 1.20 update comes out

**Comment by gohkenytp** [comment]
Excuse me? Look, I know how you feel about those other projects. But there might be a 1.19.3 recommended build so don't you worry about waiting until 1.20 comes out

**Comment by MehVahdJukaar** [comment]
What do forge recommended builds have to do with this? As with all other major updates I feel no rush to port stuff over especially considering most mods will do the same. As I've said an update will come when I have time and motivation to tackle this big task. It's even bigger considering they changed so much stuff and they all cover crucial stuff that I was heavily relying on. Not to mention the hanging signs situation. Plus If 1.20 will come soon this verison will likely be like 1.17 so update will come out when it will come out

**Comment by gohkenytp** [comment]
Gee, come to think of it. I'm not so sure what to see coming next in 1.20
