### ISSUE TITLE
Water in "Boat in jar" don't show with Sodium mod

### ISSUE THREAD

**Issue by FireFire0525** [MehVahdJukaar/Supplementaries#454]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

- Mod version, MC version and Loader you are using

- A description of your issue and how to reproduce

- If applicable, add screenshots to help explain your problem.

**Comment by FireFire0525** [comment]
[](url)MC version: 1.19.2
Mod version:2.2.27
![2022-12-21_13 51 00](https://user-images.githubusercontent.com/121150134/208832112-b2764f8c-d4ae-485b-bd96-338efb427929.png)

**Comment by MehVahdJukaar** [comment]
I can't do anything here. If sodium doesn't render stuff it's their issue
