### ISSUE TITLE
Blackboard not displaying after game restart

### ISSUE THREAD

**Issue by shrad1994** [MehVahdJukaar/Supplementaries#456]
![image](https://user-images.githubusercontent.com/96917010/209275366-f8a1bede-d9d9-4739-a580-27787ef7ee91.png)
You can see that the design is still saved but is only being shown as a blank black tile. 

I just updated ATM8. Breaking and replacing the board crashed my game.
[crash-2022-12-22_21.14.53-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10292248/crash-2022-12-22_21.14.53-client.txt)
It may have nothing to do with your mod - maybe the ATM team changed something.

**Comment by shrad1994** [comment]
now it's working just fine after several unsuccessful restarts, i can pick it up and replace it with no issues - I changed nothing I just waited :P

**Comment by MehVahdJukaar** [comment]
The crash was a sodium one. Nothing in my end

**Comment by shrad1994** [comment]
Roger that, thank you
