### ISSUE TITLE
Crash when startup 

### ISSUE THREAD

**Issue by FIegaIkCz** [MehVahdJukaar/Supplementaries#458]
Mod Version: 1.18.2-1.5.14

crashed when loading up
[crash-2022-12-26_12.26.24-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10303245/crash-2022-12-26_12.26.24-fml.txt)

**Comment by MehVahdJukaar** [comment]
update farmers delights. keep your mods up to date
