### ISSUE TITLE
Crash using soap on bighorn sheep 

### ISSUE THREAD

**Issue by RandomDude123123** [MehVahdJukaar/Supplementaries#460]
Trying to use the item 'Soap' on a bighorn sheep (twilight forest mod) causes the game to crash. It does successfully remove color from the sheep's wool.

I have not tested it on a normal sheep because I couldn't find one. 

Attached are the 3 crash reports from the 3 tests.

[crash-2022-12-27_08.32.55-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10312486/crash-2022-12-27_08.32.55-client.txt)
[crash-2022-12-27_08.40.57-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10312487/crash-2022-12-27_08.40.57-client.txt)
[crash-2022-12-27_08.45.00-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10312489/crash-2022-12-27_08.45.00-client.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight

**Comment by RandomDude123123** [comment]
Hi,

I updated moonlight
[crash-2022-12-30_05.43.39-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10323239/crash-2022-12-30_05.43.39-client.txt)
 (also had to update snowyspirit), but crashed again same as original. Report attached.

**Comment by MehVahdJukaar** [comment]
You are not using the latest supplementaries version. When reporting issues you should always be on it

**Comment by RandomDude123123** [comment]
Hi,

It didn't crash after updating supplementaries fabric, since I updated moonlight and snowy first I don't know if that was unnecessary or if all 3 had to be updated. But I have my white sheep now 🙌
