### ISSUE TITLE
Soaping colored glazed terracotta into white glazed terracotta is rather illogical

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#461]
Dear Sir MehVahdJukaar,

It is my sincere belief that 
<img width="542" alt="Screen Shot 2022-12-28 at 1 06 54 PM" src="https://user-images.githubusercontent.com/50085439/209872054-6deff205-550c-4219-a6d9-539d65fea38d.png">

this recipe should be removed. 

You see, doesn't make much sense. and there is no way to dye glazed terracotta, anyways. 

Sincerely, Dolt

**Comment by MehVahdJukaar** [comment]
Yeah the system automatically picks up every dyed item in existance but some like that don't make sense so I should add a blacklist

**Comment by MehVahdJukaar** [comment]
Completed
