### ISSUE TITLE
client launch crash 1.19.2

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#465]
https://mclo.gs/hKiDpdC

Quilt/fabric 1.19.2 
supplementaries 2.2.32

**Comment by MehVahdJukaar** [comment]
I can fix this however issue is also on quilt side. Yes it doesnt happen with fabric as their flammable registry isnt initialized immediately like aparently quilt one is. Minor difference but it leads to inconsistent behafvior which doesnt match with their claim that fabric mods work on quilt

**Comment by netcore10** [comment]
I should post this on quilt

**Comment by MehVahdJukaar** [comment]
Eh maybe. I'll fix this soon so maybe no need for it

**Comment by netcore10** [comment]
No worries if so.

**Comment by netcore10** [comment]
Can confirm the work around works!

**Comment by netcore10** [comment]
https://github.com/QuiltMC/quilted-fabric-api/issues/55#issuecomment-1368085385

A message from quilt
