### ISSUE TITLE
Crash when placing blackboard

### ISSUE THREAD

**Issue by MythrilBagels** [MehVahdJukaar/Supplementaries#466]
I have made sure that I am using the correct and up-to-date versions of the mod and its dependency.
- supplementaries-1.19.2-2.2.32
- moonlight-1.19.2-2.1.22-forge
- 1.19.2
- Forge 43.1.7

I come across this issue when I went to place a blackboard in my world.
As I attempted to place the block, the game crashed. I figured maybe I just had an incompatible mod and left it later.
When I attempted to rejoin the world, the game froze for around 5 minutes, not letting me into the world, before I forcefully closed it.
I then updated the mods and tried again, this time resulting in the following crash report and logs:

[crash-2022-12-31_18.43.04-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10326868/crash-2022-12-31_18.43.04-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10326869/latest.log)

**Comment by MehVahdJukaar** [comment]
Update forge. Remove optifine

**Comment by MythrilBagels** [comment]
Nooooo! My Custom Entities resource packs!!
Thanks though, that lets me back in.
Any chance you could report to the OptiFine dev and ask them to try and fix this issue on their side? I've heard they're open to stuff like that.

**Comment by MehVahdJukaar** [comment]
It's actually an incompatibility with forge. They are nuking a forge class. I believe it was fixed in one of theit beta builds after months

**Comment by MehVahdJukaar** [comment]
Somebody even just released a forge optifone crash fix mod
