### ISSUE TITLE
Locks compatibility : cheese locks with sticks/books/lanterns

### ISSUE THREAD

**Issue by Krampus69** [MehVahdJukaar/Supplementaries#467]
Hello,

Locks mod allows us to have locks on chests. But the supplementaries feature that let us place objects (such as sticks, books, lanterns...) can open locked chests for some reason. I'm about to disable the function in the config file of my modpack but I had to tell you about this compatibility issue before doing so because placing these objects is a nice feature.

here is a gif to explain better
https://media3.giphy.com/media/4CSxfVGqayeifbJ9hV/giphy.gif?cid=790b76111ea8a44f0c5366bca251f4e6353614660ac50a2d&rid=giphy.gif&ct=g

Forge 36.2.34
supplementaries-1.16.5-0.18.4b
Minecraft 1.16.5

Thank you for your amazing work !

**Comment by MehVahdJukaar** [comment]
1.16 isn't supported anymore. The system was also completely changed in later versions so they no longer use forge events but act much more like block items instead, fixing these kinds of issues. I wonder if other placeables from mods like FD (pumpkin pie) had the same issue
