### ISSUE TITLE
when a rope arrow is shot by a multishot crossbow it duplicates ropes

### ISSUE THREAD

**Issue by DaLumma** [MehVahdJukaar/Supplementaries#47]
I think rope arrows shouldn't be able to get shot from a crossbow tho prevent this.
or It is solveable in another way

**Comment by MehVahdJukaar** [comment]
I've never thought about this one. Apparently firework rockets and tipped arrows get multiplied too but having a rope dupe is way more op. I think I can fix this without removing them from crossbows, but the fix itself might have to wait for the next big update

**Comment by DaLumma** [comment]
ok nice
