### ISSUE TITLE
Client render crash when putting end crystal on supplementary:pedestal 

### ISSUE THREAD

**Issue by emibanana** [MehVahdJukaar/Supplementaries#471]
crash log: https://mclo.gs/BoAsbpd
client log: https://mclo.gs/7NPMKLP

- Mod version, MC version and Loader you are using
- playing on medieval mc modpack v14.5, which has irish, sodium, lithum install, however have tested without irish and it still crash

- A description of your issue and how to reproduce
putting end crystal on supplementary:pedestal 

- If applicable, add screenshots to help explain your problem.
client crash instantly, exit to desktop, no screenshot

**Comment by emibanana** [comment]
![image](https://user-images.githubusercontent.com/120373920/210492039-411969b4-91c0-4c1d-9b44-e5d53be5474e.png)
i dont see anything special about it, it just crash

**Comment by MehVahdJukaar** [comment]
Please only report issues if you are using the latest version of the mod

**Comment by MehVahdJukaar** [comment]
I need crash report

**Comment by MehVahdJukaar** [comment]
Also the statement was more "I always expect people to use the latest version as the main reason versions get released is to fix bugs such as this one". I can't update an old version. Doing so will make it a new one..
