### ISSUE TITLE
Cages not working Fabric 1.19.2-2.2.13

### ISSUE THREAD

**Issue by moxg22** [MehVahdJukaar/Supplementaries#474]
The cages do not seem to work at all.  I have tried to change the whitelist and no mod goes inside the cage.

**Comment by MehVahdJukaar** [comment]
Check with latest version

**Comment by moxg22** [comment]
It is the latest version sorry.

**Comment by MehVahdJukaar** [comment]
Do all mobs not work? Can you try with just the mod? Must be some incompatibility

**Comment by moxg22** [comment]
I can not get the to load with the latest version at all the game runs but the mod tab in creative is not there.

**Comment by moxg22** [comment]
The latest version works by itself so I will test with the other mods installed to see which one is conflicting.

**Comment by moxg22** [comment]
It is the mod advanced genetics that is causing the cages to not work.
