### ISSUE TITLE
Cannot load worlds due to a datapack error and game crashes upon trying to create a new world

### ISSUE THREAD

**Issue by txb5334** [MehVahdJukaar/Supplementaries#475]
Game Version: 1.19.2
Forge Version: Forge 43.2.3
Mods used:

- supplementaries-1.19.2-2.2.33.jar (latest as of now)
- moonlight-1.19.2-2.1.24-forge.jar

I created a new game profile on CurseForge to verify if this is the mod causing the issue on my custom modpack, as Supplementaries is the only mod I have updated recently on said custom modpack. It worked fine before I updated it.
This new profile only has these 2 mods and it has the same issue. It is definitely Supplementaries causing the issue.

Trying to load an existing world gives a warning that it cannot be loaded due to a datapack error, and it gives an option to load the world with vanilla settings/packs. Trying to create a new world crashes the game.
<img width="610" alt="Screen Shot 2023-01-06 at 17 05 04" src="https://user-images.githubusercontent.com/99324756/211050758-383ebb8c-a4a9-432c-aa88-f38ec6f8689b.png">

I have attached the latest.log, crash message screenshot and crash.txt in this report.

[crash-2023-01-06_16.49.38-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10361417/crash-2023-01-06_16.49.38-client.txt)

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10361420/latest.log)

**Comment by winnetrie83** [comment]
I was just about to report the same issue.
I made a clean environment with only the same mods and same versions txb5334 has and can confirm a crash as soon as you click on single player.
Can confirm everything worked fine before updating this mod

**Comment by Marvolo-Riddle** [comment]
Same here, seems to be a big issue with the latest version

**Comment by txb5334** [comment]
For now, backporting to the version before this one is fine.

**Comment by MehVahdJukaar** [comment]
fixed
