### ISSUE TITLE
Wololo-ing a trader causes a crash

### ISSUE THREAD

**Issue by Crows-Parliament** [MehVahdJukaar/Supplementaries#477]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10362666/latest.log)

Supplementaries version 2.2.32
MC version 1.19.2
Forge loader

Spawn an evoker, spawn a wandering trader, let him wololo, and it crashes.
The trader itself isn't the problem since when i rejoin the world it doesnt crash

**Comment by MehVahdJukaar** [comment]
i think you sent the wrong file as that doesnt seem to have crashed

**Comment by Marvolo-Riddle** [comment]
Oh that's probably since I was loading minecraft again around the same time, crap
Ill try to replicate it and send the report when I can

**Comment by MehVahdJukaar** [comment]
I tried and can't replicate

**Comment by Cell-Technology** [comment]
I've managed to replicate, seems to always happen. here's the crashlog: https://pastebin.com/sAU2LvH8

**Comment by MehVahdJukaar** [comment]
should be fixed
