### ISSUE TITLE
Create world crash

### ISSUE THREAD

**Issue by FanRenLa** [MehVahdJukaar/Supplementaries#478]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
https://t.wss.ink/f/a77c2yvlwqs
- Mod version, MC version and Loader you are using
supplementaries-1.19.2-2.2.34b forge43.2.3
- A description of your issue and how to reproduce
Create world crash
- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
can you check if its fixed with latest version?

**Comment by FanRenLa** [comment]
supplementaries-1.19.2-2.2.34b.jar
He seems to be the latest version

**Comment by FanRenLa** [comment]
supplementaries-1.19.2-2.2.34b.jar
He seems to be the latest version

**Comment by MehVahdJukaar** [comment]
latest is 2.2.35

**Comment by FanRenLa** [comment]
[crash-2023-01-08_12.52.06-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10367745/crash-2023-01-08_12.52.06-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10367746/latest.log)
2.2.35
Launch game crash.

**Comment by MehVahdJukaar** [comment]
I see this mod having a problem org.orecruncher.sndctrl

**Comment by FanRenLa** [comment]
Immersive Fx, when deleted, crashes, too.

**Comment by MehVahdJukaar** [comment]
Is that the mod I listed above? If so send the new log

**Comment by FanRenLa** [comment]
No abnormalities so far, good performance.
