### ISSUE TITLE
Pressing V when entering world seed causes crash

### ISSUE THREAD

**Issue by Canada-LaVearn** [MehVahdJukaar/Supplementaries#479]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[crash-2023-01-07_13.00.41-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10366930/crash-2023-01-07_13.00.41-client.txt)

- Mod version, MC version and Loader you are using
MC 1.19.2, Forge 43.2.3, supplementaries-1.19.2-2.2.34b

- A description of your issue and how to reproduce
When manually entering seed into world creation screen, pressing the V key crashes the game.

- If applicable, add screenshots to help explain your problem.
n/a

**Comment by MehVahdJukaar** [comment]
should be fixed on latest version
