### ISSUE TITLE
[Suggestion] New sign structures should be able to locate villages added by other mods

### ISSUE THREAD

**Issue by NJL5390** [MehVahdJukaar/Supplementaries#48]
Hello!

When playing around with the latest version of your mod and testing the new signpost structures that generate throughout the world, I noticed that they don't seem to be able to locate villages added by other mods such as Repurposed Structures (https://www.curseforge.com/minecraft/mc-mods/repurposed-structures).

It would be great if these signposts could locate and point to modded villages for consistency with these mods should anyone have them on.
![2021-03-25_18 36 24](https://user-images.githubusercontent.com/64381954/112735822-24093d00-8f46-11eb-8af6-02c6aeb1189d.png)
I want to finish by saying that this mod is one of the most interesting and fun I've ever seen and with so much to play around with too! 

Love this mod! Keep up the great work!

**Comment by MehVahdJukaar** [comment]
Yup I can do that and I will. I'm currently learning how to do proper structures so don't worry for now. Consider those just a preview. Also  judging by those high numbers on the signs I'm wondering if you ever found one that didn't point to any village since that can happen as of now (it won't  in the future when they'll become structures)

**Comment by NJL5390** [comment]
> Yup I can do that and I will. I'm currently learning how to do proper structures so don't worry for now. Consider those just a preview. Also judging by those high numbers on the signs I'm wondering if you ever found one that didn't point to any village since that can happen as of now (it won't in the future when they'll become structures)

Believe it or not, I don't remember finding any that didn't point anywhere. There were plenty of signposts that only pointed to one village, even if that village was over 3000 blocks away. It seemed kinda pointless though when there was a modded village about 50 blocks away from it (Like in the screenshot above).
> Oh I'll probably need a whitelist of possible mods that add villages, if you want you can tell me the mods that you have there that you would like to be added on the list by default

The only one that I know of on modern Minecraft versions that adds their own village variants (and the only one I'm using) is called Repurposed Structures (https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
The villages it adds to the Overworld are:

- Badlands Villages (repurposed_structures:village_badlands)
- Birch Villages (repurposed_structures:village_birch)
- Dark Forest Villages (repurposed_structures:village_dark_oak)
- Giant Taiga Villages (repurposed_structures:village_giant_taiga)
- Jungle Villages (repurposed_structures:village_jungle)
- Mountain Villages (repurposed_structures:village_mountains)
- Forest Villages (repurposed_structures:village_oak)
- Swamp Villages (repurposed_structures:village_swamp)

It also adds a couple of villages to the nether too which have piglins instead of villagers. I'll leave it up to you as to whether you will have signposts that will point to these nether villages:

- Crimson Villages (repurposed_structures:village_crimson)
- Warped Villages (repurposed_structures:village_warped)

**Comment by MehVahdJukaar** [comment]
alright thanks. I'm currently following a tutorial by the author of that mod where he explains very well how to do structures. I'll probably even make them fully data driven so they can be customized. For the nether ones I'll probably leave them out for now

**Comment by NJL5390** [comment]
Thanks for this! I Love the new update!
