### ISSUE TITLE
Mod fails to load on startup

### ISSUE THREAD

**Issue by Canada-LaVearn** [MehVahdJukaar/Supplementaries#480]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[crash-2023-01-09_13.58.46-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10376105/crash-2023-01-09_13.58.46-fml.txt)

- Mod version, MC version and Loader you are using
MC 1.19.2, Forge 43.2.3, supplementaries-1.19.2-2.2.35

- A description of your issue and how to reproduce
Unable to open game, Supplementaries failed to load correctly.

- If applicable, add screenshots to help explain your problem.
n/a

**Comment by MehVahdJukaar** [comment]
Last version is marked as beta as its meant to be used with latest quark beta. If you don't have acces to that downgrade
