### ISSUE TITLE
More a question about something i saw than anything (i hope i'm posting this right)

### ISSUE THREAD

**Issue by nbdeity** [MehVahdJukaar/Supplementaries#481]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
n/a

- Mod version, MC version and Loader you are using
1.19.2

- A description of your issue and how to reproduce

when planting the normal flax (not wild) included with the mod, there were times when the flowers on the model turned into a person instead of the blue flax flowers. I do not know how to explain this more than that, but i'm really just wondering what the purpose was.

sometimes when hitting the plant in the current version it seems like it still has those textures in the particles, but i cant reporduce it in the current version. again, this isn't an issue, i just REALLY don't understand what it was and was very curious about it since i first saw it. I will provide screenshots.

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/65470941/211443981-1d0c1f73-e39c-4737-b609-31849a85ec14.png)
an example of some of the particles when hitting the flower part with bonemeal

![image](https://user-images.githubusercontent.com/65470941/211444705-3bb3eb7c-bd55-4e86-96dc-6c8251f2498e.png)
the image in question showing it off

**Comment by MehVahdJukaar** [comment]
That texture is mapped to an unused blockstate. I put it there just not to have to leave it purple and black. Using just the mod or mods that be I know of that can never happen under any circumstance as the block cannot exist like that. What you see is a flax upper stage with age of 0 which can't ever exist as upper stage only grow on stage 3. If that has spawned it means some other mod has forcefully placed it without doing it properly by asking the crop plant or checking if the plant can actually survive there

**Comment by nbdeity** [comment]
Oh cool, thanks for letting me know! I was very confused about it- it must have been caused by a conflicting mod or something back then since it doesn't happen anymore other than with the particles when i hit the plant from the flower section when it's fully grown.

**Comment by MehVahdJukaar** [comment]
I'll have a look. Usually that happens when a faulty mod tries to do stuff like replant the upper stage which causes issues. That block configuration is also invalid and usually breaks on its own but some mods have done auto replanting not correctly and I've got no ways of fixing their mistakes if they just set my block without notifying it. I know quark auto replant works fine for example

**Comment by MehVahdJukaar** [comment]
As for the texture it's just a file for the texture file. Had it not been there it would simple be missing texture at it's not a state that should ever be seen
