### ISSUE TITLE
my mc wont open if i have sodium or optifine in it any suggestions

### ISSUE THREAD

**Issue by zeniboi** [MehVahdJukaar/Supplementaries#483]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

- Mod version, MC version and Loader you are using

- A description of your issue and how to reproduce

- If applicable, add screenshots to help explain your problem.

**Comment by zeniboi** [comment]
[crash-2022-11-04_18.42.12-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10390997/crash-2022-11-04_18.42.12-client.txt)

**Comment by MehVahdJukaar** [comment]
They both break their loader API. For different reasons. There exist 2 mods that fix that

**Comment by MehVahdJukaar** [comment]
Indium fixes sodium nuking fabric rendering API and a forge optifone fix mod does the same for forge..I'm so tired of all these reports of these 2 tbh tho I've been getting on the hundreds for their fuck ups
