### ISSUE TITLE
Silver, lead, and brass lanterns have no config

### ISSUE THREAD

**Issue by Hypsellis** [MehVahdJukaar/Supplementaries#487]
RIP modded ore lanterns config

**Comment by MehVahdJukaar** [comment]
They don't need it. They are bound to the existance of those metals

**Comment by Hypsellis** [comment]
Why they would not have it? since they doors and trap doors have it.

**Comment by MehVahdJukaar** [comment]
That's fair. Tbh I've been contemplating about giving that stuff to organized and let them handle it. It was added with their texture non their request anyways

**Comment by Hypsellis** [comment]
Yeah it might be better if Oreganised managed ore integration.
