### ISSUE TITLE
Crash loading the latest Supplementaries (1.19.2-2.2.37)

### ISSUE THREAD

**Issue by sciguyryan** [MehVahdJukaar/Supplementaries#488]
**Before continuing**
- Always check you are using the latest version of this mods and it's dependencies
As far as I'm aware everything is up to date.

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
I have included the crash report at the end of this bug report.

- Mod version, MC version and Loader you are using
Minecraft Version: 1.19.2
Mod Version: 2.2.37
Loader: Forge

- A description of your issue and how to reproduce
Attempting to load the latest version of Supplementaries after upgrading from version 2.2.35h.

- If applicable, add screenshots to help explain your problem.
Not applicable here, I have included a copy of the crash report below.

[crash-2023-01-18_10.03.55-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10444576/crash-2023-01-18_10.03.55-fml.txt)

**Comment by MehVahdJukaar** [comment]
Don't use the beta version unless you read the patch notes

**Comment by sciguyryan** [comment]
Updated Quark, that appears to have resolved the issue.
