### ISSUE TITLE
Launch game crash

### ISSUE THREAD

**Issue by FanRenLa** [MehVahdJukaar/Supplementaries#489]
**Before continuing**
Always check you are using the latest version of this mods and it's dependencies
yes
**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[crash-2023-01-18_19.40.01-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10445779/crash-2023-01-18_19.40.01-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10445792/latest.log)

- Mod version, MC version and Loader you are using
forge43.2.3, supplementaries-1.19.2-2.2.37
- A description of your issue and how to reproduce
Launch game crash

- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
icyllis.caffeine.cache.Cache.invalidateAll()
Nothing to do wth supplementaries i see that as cause

**Comment by FanRenLa** [comment]
> icyllis.caffeine.cache.Cache.invalidateAll（） 与补充无关，我认为这是原因

Issues with Supplementaries, unrelated to other mods, the game was successfully launched when I deleted Supplementaries.

**Comment by MehVahdJukaar** [comment]
Did you report this to those mods? I still only see their stuff in the log

**Comment by FanRenLa** [comment]
icyllis.caffeine.cache.Cache.invalidateAll（）
Modern UI, which also appears when other mods crash.
So when you see this, you can just rule it out.

**Comment by FanRenLa** [comment]
I reported it. It's normal.

**Comment by FanRenLa** [comment]
> 我报告了。这很正常。

Modern UI officially says this is normal.

**Comment by MehVahdJukaar** [comment]
You using last version of the mod?

**Comment by FanRenLa** [comment]
supplementaries-1.19.2-2.2.37.jar
moonlight-1.19.2-2.1.28-forge.jar

**Comment by MehVahdJukaar** [comment]
Latest is .38

**Comment by FanRenLa** [comment]
This is from yesterday, big brother.

**Comment by FanRenLa** [comment]
Today supplementaries-1.19.2-2.2.39.jar

**Comment by FanRenLa** [comment]
> 最新的是.39。试试看

The game starts normally and will not be downloaded in the future
Beta version.

**Comment by MehVahdJukaar** [comment]
yeah thats why i marked it as beta. I'll close as resolved
