### ISSUE TITLE
Game crash when creating new world due to Quiver key/action being triggered

### ISSUE THREAD

**Issue by e-SonOfAnder** [MehVahdJukaar/Supplementaries#490]
Mod version: 1.19.2-2.2.34b
MC version: 1.19.2
Loader: Forge 43.2.3

Description:
Game crashes during world creation due to QuiverArrowSelectGui attempting to launch when the game has not loaded yet. By default the key bound to this function is 'v', so if you hit the letter 'v' at any point, the game will crash. This includes attempting to search for the letter 'v' in the Key Binds menu to verify what functions are using it.

Repro steps:
Launch MC
Create a new world
Hit the letter 'v'

Alternate: I am unsure what is triggering this, but after unbinding the Quiver Arrow select, I hit the mute/unmute key on my keyboard, and IT then triggered the crash for the exact same reason. How that particular key is triggering an action that supposedly doesn't have a key bound to it is unclear to me, but I have attached crash logs for both scenarios.

[keypress_v_crash.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10453288/keypress_v_crash.txt)
[keypress_mute_toggle_crash.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10453289/keypress_mute_toggle_crash.txt)

**Comment by MehVahdJukaar** [comment]
Use latest version

**Comment by e-SonOfAnder** [comment]
Did that, and get a new crash before the game fully loads, still from Supplementaries. Updated to 1.19.2-2.2.39. Crash log attached.

[crash-2023-01-18_21.05.12-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10453680/crash-2023-01-18_21.05.12-client.txt)

**Comment by MehVahdJukaar** [comment]
disable model gap fix. Its not the cause but failed mod loading makes the game think it had an issue when in reality its just cascading error from failed mod loading. Then boot up the game and send me the log which will show the real error

**Comment by DerpyFrood0421** [comment]
Pretty sure this is also causing my crash from the Server screen. Typing while trying to rename a server from "Minecraft Server" causes a crash consistently. This is in ATM8 (v 1.0.8) / Supplementaries v1.19.2-2.2.34b

[supplementaries_crash_2023_JAN1.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10470298/supplementaries_crash_2023_JAN1.txt)

**Comment by MehVahdJukaar** [comment]
Use latest version, as I've written above

**Comment by DerpyFrood0421** [comment]
Thanks. Playing on a server so I'm locked into this version; but if/when pack updates I'll test it again.  Removing the keybind seems to make the game playable (as long as I don't try to edit the server name).
