### ISSUE TITLE
Launch crash

### ISSUE THREAD

**Issue by T2uyo** [MehVahdJukaar/Supplementaries#491]
[crash-2023-01-21_17.25.35-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10472439/crash-2023-01-21_17.25.35-client.txt)

[fabric]

i tried everything
with old versions and new both of moonlight lib and supplimentaries
the game just doesnt launch when the mod is in the modpack folder
i tried deleting config folder too

**Comment by MehVahdJukaar** [comment]
seems to be a conflict/issue with BetterResourcePackSorting

**Comment by T2uyo** [comment]
> seems to be a conflict/issue with BetterResourcePackSorting

what is that and how to solve it?
