### ISSUE TITLE
Failure message: Supplementaries (supplementaries) has failed to load correctly

### ISSUE THREAD

**Issue by DragonTamer0129** [MehVahdJukaar/Supplementaries#493]
[crash-2023-01-23_02.34.52-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10476416/crash-2023-01-23_02.34.52-fml.txt)
My server crashed and now I get this every time I try and start is up. seems to be the same crash report from when it originally crashed (or at least similar)

**Comment by MehVahdJukaar** [comment]
Seems like you got an invalid config. Check for mistakes or delete it

**Comment by DragonTamer0129** [comment]
Thanks! for some reason there was a random "e" at the very end of the file
