### ISSUE TITLE
Certain Recipe conditions don't function correctly

### ISSUE THREAD

**Issue by surprisedpika** [MehVahdJukaar/Supplementaries#495]
[Fabric][1.19.2][1.19.2-2.2.41]

Some recipes are using the "forge:" conditions when they should be using "fabric:" conditions (see https://github.com/FabricMC/fabric/pull/1656).

Affected Recipes that I could find (may not be exhaustive)
`fabric/src/main/resources/data/supplementaries/recipes/lead_trapdoor.json`
`fabric/src/main/resources/data/supplementaries/recipes/lead_lantern.json`
`fabric/src/main/resources/data/supplementaries/recipes/lead_door.json`
`fabric/src/main/resources/data/supplementaries/recipes/silver_door.json`
`fabric/src/main/resources/data/supplementaries/recipes/silver_lantern.json`
`fabric/src/main/resources/data/supplementaries/recipes/silver_trapdoor.json`
`fabric/src/main/resources/data/supplementaries/recipes/brass_lantern.json`

**Comment by MehVahdJukaar** [comment]
all recipes have conditions registered. Yeah i wasnt aware of that api and no way i'm using it since that would mean splitting my entire recipe folder in 2. What i did instead was having my own super simple implementation of those forge conditons so, unless theres a mod conflicting with they, they sould work there too

**Comment by surprisedpika** [comment]
I don't have lead or silver ingots and the items are replaced with an empty item, rather than the recipe being disabled. (Probably should have led with that lol)

**Comment by MehVahdJukaar** [comment]
odd i should check that. likely that the tag empty condition isnt working. In that case I'll just do that those fabric ones do

**Comment by MehVahdJukaar** [comment]
does this still happen?

**Comment by Molarczsq** [comment]
> does this still happen?

see this
![屏幕截图 2023-01-26 170725](https://user-images.githubusercontent.com/58633604/214801401-cd550109-c59c-4cb2-8054-fabbefd80937.png)
With the version 2.2.44 ,Fabric 0.14.13

**Comment by DistantDig** [comment]
So i can add a bit to this. I was getting this exact issue in a crafting grid in both survival and creative. to get the trapdoors though i have to place an item in to the crafting grid and then remove it (it doesnt seem to matter what item).

![2023-01-26_23 16 23](https://user-images.githubusercontent.com/82922519/215030356-7dc311e1-be5f-4b1f-9042-92099ac155ae.png)

you cant see my mouse in the image, but the trap door shows up once you pick up the item

**Comment by MehVahdJukaar** [comment]
I tried this too and can't replicate it still. Not only that tag is empty so shouldn't allow any item not even air there but also the recipe itself should not have been loaded altogether if the tag was indeed empty. My only explanation is that the tag silver ignots isn't empty and somehow was made to contain air. Check your mods must be a conflict. Also try tagging some item to silver ingot

**Comment by DistantDig** [comment]
Well ill leave my modlist here while i try to narrow down possible incompatibilities, and if anyone else is having the issue it would be nice for them to do the same so we can see common mods. Theres only 39 mods in my pack:

moonlight lib
apple crates
artifacts
attributefix
better combat
charm
cloth config
clumps
colorful azaleas
croptopia
decorative blocks
fabric api
fabric seasons
farmer's delight
forge config api port
geckolib
handcrafted
immersive weathering
jade
jei
lil wings
lootr
mythic mounts
no chat reports
open parties and claims
origins
patchouli
pehkui
pick your poison
player animator
rpgstats
supplementaries
terralith
towns and towers
trinkets
vertical slabs compat
wilder wilds
xaero's minimap
zaero's worldmap

**Comment by DistantDig** [comment]
To fix this all you have to do is update Moonlight Lib. Turns out it was just an issue with Supplementaries dependency

**Comment by MehVahdJukaar** [comment]
Yes I figured out what was causing this and fixed it
