### ISSUE TITLE
Quiver Mode Keybind crashes the game if used in menu

### ISSUE THREAD

**Issue by CrossOnDiscord** [MehVahdJukaar/Supplementaries#496]
There appears to be an issue where when the "Quiver" keybind is used while not in game. When used it causes the game to immediately crash. I've tried unbinding it but my "Play/Pause media" key on my keyboard still activates it, meaning I can't quickly stop my music without my game completely crashing.

Version: 1.19.2-2.2.34b

Crash log:
[crash-2023-01-25_18.03.15-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10505236/crash-2023-01-25_18.03.15-client.txt)

**Comment by MehVahdJukaar** [comment]
you are 10 versions behind :/

**Comment by CrossOnDiscord** [comment]
My fault then, didn't check it out. Currently playing the ATM8 modpack so I don't have much choice in mod versions.
I'll let them know about it.
