### ISSUE TITLE
Server crash when activating a dispenser with flint and steel

### ISSUE THREAD

**Issue by wqferr** [MehVahdJukaar/Supplementaries#499]
Minecraft version: 1.18.2
Mod loader: Forge
How to reproduce: put down a dispenser facing an air block with a non-air block beneath it, insert flint and steel, place lever beside the dispenser and pull it.

Relevant logs section:

>31.01 01:36:33 [Server] Server thread/ERROR Encountered an unexpected exception
31.01 01:36:33 [Server] INFO net.minecraft.ReportedException: Exception ticking world
31.01 01:36:33 [Server] INFO at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
31.01 01:36:33 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
31.01 01:36:33 [Server] INFO at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:Fluidlogged.mixins.json:accessor.StateAccessor,pl:mixin:APP:canary.mixins.json:alloc.blockstate.StateHolderMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at com.cozary.tintedcampfires.dispenser.CampfireDispenseBehavior.m_7498_(CampfireDispenseBehavior.java:29) ~[Tinted%20Campfires-1.18.2-1.2.2.jar%23234!/:1.18.2-1.2.2] {re:classloading}
31.01 01:36:33 [Server] INFO at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.m_6115_(DefaultDispenseItemBehavior.java:15) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
31.01 01:36:33 [Server] INFO at net.mehvahdjukaar.selene.util.DispenserHelper$AdditionalDispenserBehavior.m_6115_(DispenserHelper.java:96) ~[selene-1.18.2-1.17.9.jar%23202!/:1.18.2-1.17.9] {re:classloading}
31.01 01:36:33 [Server] INFO at net.minecraft.world.level.block.DispenserBlock.m_5824_(DispenserBlock.java:90) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:accessors.DispenserAccessor,pl:mixin:APP:farmersdelight.mixins.json:CuttingBoardDispenserMixin,pl:mixin:APP:pollen-common.mixins.json:DispenserBlockAccessor,pl:mixin:APP:create.mixins.json:accessor.DispenserBlockAccessor,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.world.level.block.DispenserBlock.m_7458_(DispenserBlock.java:113) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:accessors.DispenserAccessor,pl:mixin:APP:farmersdelight.mixins.json:CuttingBoardDispenserMixin,pl:mixin:APP:pollen-common.mixins.json:DispenserBlockAccessor,pl:mixin:APP:create.mixins.json:accessor.DispenserBlockAccessor,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60616_(BlockBehaviour.java:677) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,re:classloading,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:block.flatten_states.BlockStateBaseMixin,pl:mixin:APP:canary.mixins.json:chunk.block_counting.BlockStateBaseMixin,pl:mixin:APP:Fluidlogged.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:639) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:ai.nearby_entity_tracking.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:classloading}
31.01 01:36:33 [Server] INFO at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:classloading}
31.01 01:36:33 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:272) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:pluto.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:ai.nearby_entity_tracking.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
31.01 01:36:33 [Server] INFO at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
31.01 01:36:33 [Server] INFO ... 5 more

**Comment by MehVahdJukaar** [comment]
Im not sure if its my problem or this mod here. com.cozary.tintedcampfires.dispenser.CampfireDispenseBehavior
See my dispenser behaviors dont override whats there instead they wrap it, hence why you see it calling that

**Comment by wqferr** [comment]
Ahh thank you, I came here because I saw supplementaries in the stack trace. Sorry for the inconvenience!

**Comment by MehVahdJukaar** [comment]
no worries
