### ISSUE TITLE
Crash when placing a blackboard

### ISSUE THREAD

**Issue by mtmtyu** [MehVahdJukaar/Supplementaries#501]
[crash-2023-02-01_18.57.31-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10555744/crash-2023-02-01_18.57.31-client.txt)

**Comment by MehVahdJukaar** [comment]
Optifone is incompatible with latest forge. Not my problem

**Comment by mtmtyu** [comment]
? I had a crash when I put this mod

**Comment by MehVahdJukaar** [comment]
Uff I had to explain this a million times all because optifrick being bugged for months and months now. Forge updated m any months ago with new rendering API. Optifone is a core mod, unlike any other, and always was barely compatible with forge notoriously breaking other mods

**Comment by MehVahdJukaar** [comment]
Anyways they are incompatible with those rendering changes. Came runs fine until a mod happens to, you know, use that forge API which had been sabotaged so then boom game crashes. There's a mod on CF that fixed it
