### ISSUE TITLE
Add text alignment option to Notice Board

### ISSUE THREAD

**Issue by villainous-j** [MehVahdJukaar/Supplementaries#506]
### Overview
Currently, the text is always displayed using `center` alignment for the text. 

### Suggestion
Allow for the option to change the notice board display's alignment to `left`, `center`, or `right`. This could be done directly in-game in this UI:

![image](https://user-images.githubusercontent.com/63336989/217788773-ef6befe2-418b-40c0-be29-f293facb36b3.png)

Appreciate your time with considering this!

**Comment by MehVahdJukaar** [comment]
Hm that would be a very very minor change. Do you think it should be on the left by default?

**Comment by villainous-j** [comment]
Hah, yeah I do think left should be the default!

**Comment by villainous-j** [comment]
Matches the book and quill more closely then

**Comment by MehVahdJukaar** [comment]
Book and quill GUI is extremely different that this one. Doesn't even have slot.
It is made to match the dispenser gui

**Comment by villainous-j** [comment]
Oh i just mean that the text in Book and quill is left-alignment when you're writing in it :)

**Comment by MehVahdJukaar** [comment]
well yeah that's how writing on a book works XD
Here its a gui and it matches the dispenser one instead of the furnace which is left aligned but i think the discriminator for the difference in vanilla is if a gui is more spread out, like furnace or more centered and symmetrical like dispenser and this one certainly falls in the latter category hence the positioning

**Comment by villainous-j** [comment]
If it makes it easier, I can put together some mockups of what I mean, when I get the chance. :)

**Comment by MehVahdJukaar** [comment]
ah i was confused since you posted the gui image. Yeah i can do it tho i wonder how how the gui should look. dont want to mess that asymmetry

**Comment by MehVahdJukaar** [comment]
I'll probably make it a config, feels like one of those thing that should be handled with those instead as notice boards are meant to be just dumb blocks that display a piece of paper so they shouldnt have the ability to shift text left and right like a pc monitor (altho they do can change pages so maybe wouldnt be such a big issue)

**Comment by villainous-j** [comment]
That makes sense to me as a config! Would greatly appreciate that. (I'm using it as a TODO list in-game, lovely feature!)

**Comment by MehVahdJukaar** [comment]
added

**Comment by villainous-j** [comment]
awesome!! really appreciate that, thank you!
