### ISSUE TITLE
Quark's glowshroom don't emit light on hanging pots

### ISSUE THREAD

**Issue by LeoBeliik** [MehVahdJukaar/Supplementaries#508]
Quark 3.4-389 | Supplementaries 1.19.2-2.2.46 | Forge 43.2.4

### Issue
Quark's glowshroom emit light when placed on a pot, this doesn't happen when placed on a hanging pot.

![2023-02-11_07 03 14](https://user-images.githubusercontent.com/11804768/218252321-4f3b7a3e-8871-419e-b3ef-6294c3aec453.png)
![2023-02-11_07 03 19](https://user-images.githubusercontent.com/11804768/218252324-7231fc9f-00e9-4133-97a2-1cf2a86d46cd.png)

**Comment by MehVahdJukaar** [comment]
fixed. flower box too
