### ISSUE TITLE
Enderman Head

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#510]
1. Wall Enderman heads have no loot table and drop nothing
2. The back of Wall Enderman head Z-fights when it's place on a solid block and you're staring at it
3. YOu cannot pile wall enderman heads on top of each other even if you have the mob head pile feature on in supplementaries mod

**Comment by MehVahdJukaar** [comment]
for last one its intented as they are a special head like dragon head. Making them pilable will inhibit their function as they need space to open

**Comment by thelegitdolt** [comment]
i see

**Comment by MehVahdJukaar** [comment]
other ones fixed

**Comment by thelegitdolt** [comment]
yay
