### ISSUE TITLE
Still possible to clean Glazed Terracotta even though it is in the blacklist

### ISSUE THREAD

**Issue by stuart0035** [MehVahdJukaar/Supplementaries#511]
You can still clean Glazed Terracotta even though it is in `clean_blacklist` in supplementaries-common.toml:
> `clean_blacklist = ["minecraft:glazed_terracotta"]`

Minecraft 1.19.2
Forge 43.2.4
Moonlight Library 1.19.2-2.2.6
Supplementaries 1.19.2-2.2.46
Just Enough Items 11.5.2.1007

![2023-02-12_12 49 48](https://user-images.githubusercontent.com/98527698/218293684-15af7572-42b3-49d4-baad-59d4285b314c.png)

**Comment by MehVahdJukaar** [comment]
ah aparently it only affected the inworld action

**Comment by stuart0035** [comment]
Tested again, and found that the recipe just show up on JEI and doesn't actually work. Thank you!

**Comment by MehVahdJukaar** [comment]
oh ill fix the JEI plugin then
