### ISSUE TITLE
InvocationTargetException: null

### ISSUE THREAD

**Issue by aaronhowser1** [MehVahdJukaar/Supplementaries#512]
**Always include**
[Crash report](https://gist.github.com/b19bea0dc1056b5c626fe4e15c837e4a)
[latest.log](https://gist.github.com/9d62dd869fe439985cb826ce3e015a00)

- Mod version, MC version and Loader you are using
supplementaries-1.19.2-2.2.47
1.19.2
Forge 43.2.5

- A description of your issue and how to reproduce
![image](https://user-images.githubusercontent.com/15698722/218347444-8679bcf7-3461-481a-a492-64897e2517d5.png)

It stops loading before it reaches the main menu. Downgrading back to `supplementaries-1.19.2-2.2.32` (what I was using before) fixes the problem. Updating version by version, the highest I can go is `supplementaries-1.19.2-2.2.35t`.

**Comment by MehVahdJukaar** [comment]
Update quark

**Comment by aaronhowser1** [comment]
Damn you curseforge 🤦 it wasn't showing with the other outdated mods. I'm so sorry
