### ISSUE TITLE
[Feature Request] Give the globe's 4 sides have different redstone signal outputs

### ISSUE THREAD

**Issue by RedSnt** [MehVahdJukaar/Supplementaries#517]
Spinning a globe and getting it to land on a specific side is of course hard, but it'd be a fun feature to be able to read the redstone signal and use it for a secret entrance redstone contraption or some other adventure related activity, or maybe just as a fancy light dimmer.  
Anyway, just a thought.

**Comment by MehVahdJukaar** [comment]
That works already. All 4 sides already have a different singal. Also every time you spin it the current face just shifts over by one, it shouldn't be confusing at all

**Comment by RedSnt** [comment]
Oh excellent!
