### ISSUE TITLE
Broken recipes 

### ISSUE THREAD

**Issue by Rhayn31** [MehVahdJukaar/Supplementaries#520]
Minecraft Fabric 1.19.2 - Supplementaries 2.2.50

My modpack has no lead ore in it and thus breaks the recipes for supplementaries' lead door/trapdoor/lamp. The recipes always trigger after I craft an item and fill my inventory with unwanted junk.
Disabling lead items in both supplementaries-common.json and supplementaries-registry.json has no effect as the items keep showing up in the game anyway.

![broken1](https://user-images.githubusercontent.com/40799893/220089786-c3fe206f-8ab7-42be-9ec8-b1c5268eaaaf.png)
![broken2](https://user-images.githubusercontent.com/40799893/220089809-fc6cb30e-b387-43c1-96c2-9d102c4b58ef.png)

**Comment by MehVahdJukaar** [comment]
This can only happen if some mod is breaking my recipe disabling feature by overriding recipe deserialization. You can test this theory by disabling any other item in the common config (registry one isnt used anymore)

**Comment by Rhayn31** [comment]
Tried disabling the bubble blower for example and it still appears in the game, craftable and working.
How can I detect what mod is causing this interaction? is there any mod known to do so?

**Comment by Rhayn31** [comment]
Little note if someone happens to run into the same problem, in my case the mod causing this issue is KubeJS

**Comment by MehVahdJukaar** [comment]
I'll leave this open

**Comment by MehVahdJukaar** [comment]
try new moonlight version. Should be resolved
