### ISSUE TITLE
Fabric 1.19.2 Crash on startup - Incompatibility with Dramatic Doors Potentially

### ISSUE THREAD

**Issue by EvionFox** [MehVahdJukaar/Supplementaries#521]
Supplementaries version: Tested with 1.19.2-2.2.50 through 2.46
Minecraft 1.19.2
Fabric Loader: Tested on both 0.14.13 and .14.14
Fabric API 0.73.2+1.19.2
Dramatic Doors: Tested with both 1.19.2-1.4.0_1 and 1.4.1

Issue: The game is crashing when attempting to start, throwing these crash logs. I've tried various Fabric loaders, versions of Dramatic Doors, and I had to roll Supplementaries back to version 2.46 for it to stop crashing.

Assorted crash logs, but all look to have the same error:
[crash-2023-02-20_09.54.55-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10786107/crash-2023-02-20_09.54.55-client.txt)
[crash-2023-02-20_10.04.25-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10786108/crash-2023-02-20_10.04.25-client.txt)
[crash-2023-02-20_10.16.10-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10786109/crash-2023-02-20_10.16.10-client.txt)

**Comment by MehVahdJukaar** [comment]
Issue in their side. You can disable one of their mixin which mixes in my classes in the configs
