### ISSUE TITLE
Supplementaries Failed to Load

### ISSUE THREAD

**Issue by TotableHen941** [MehVahdJukaar/Supplementaries#522]
[crash-2023-02-20_19.55.17-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10788899/crash-2023-02-20_19.55.17-fml.txt)

No idea what's wrong. Updated it a while ago and just continue to get this report.

**Comment by MehVahdJukaar** [comment]
Update quark and keep your mods up to date

**Comment by TotableHen941** [comment]
Thank you
