### ISSUE TITLE
⚠️𝗖𝗥𝗔𝗦𝗛⚠️𝘚𝘶𝘱𝘱𝘭𝘦𝘮𝘦𝘯𝘵𝘢𝘳𝘪𝘦𝘴 𝘤𝘢𝘶𝘴𝘦𝘴 𝘮𝘺 𝘨𝘢𝘮𝘦 𝘵𝘰 𝘤𝘳𝘢𝘴𝘩!

### ISSUE THREAD

**Issue by User4716** [MehVahdJukaar/Supplementaries#523]
**Supplementaries** mod (supplementaries-1.19.2-2.2.50.jar) crashes my game.
I have **Moonlight Lib** (moonlight-1.19.2-2.2.7-forge.jardependencies)

**I use Forge 43.2.4 - 1.19.2**

When I load up my game, there is a total of 13 errors

![2023-02-21_12 52 45](https://user-images.githubusercontent.com/97033682/220325743-8cfab0f9-1c9c-49ac-896f-a0e779d2409b.png)
![2023-02-21_12 54 53](https://user-images.githubusercontent.com/97033682/220325945-0ff102fb-bc47-4f3f-8ac6-bb5ca25d743a.png)

And i'm just trying to figure out how to fix each error one by one. 
(But I came here first because in the Minecraft Log it said that this mod had a Mod Issue URL.)

**Here is the latest.log**
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10792802/latest.log)
**And crash.log**
[crash-2023-02-21_12.30.33-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10792845/crash-2023-02-21_12.30.33-fml.txt)

**Below is the error message that this mod gave me. But please check the log files above to get full logs.**

> -- MOD supplementaries --
> Details:
> Caused by 0: java.lang.reflect.InvocationTargetException
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
> 
> 
> Mod File: /C:/Users/PRIVATE/curseforge/minecraft/Instances/1.19.2 Adventure/mods/supplementaries-1.19.2-2.2.50.jar
> Failure message: Supplementaries (supplementaries) has failed to load correctly
> java.lang.reflect.InvocationTargetException: null
> Mod Version: 1.19.2-2.2.50
> Mod Issue URL: https://github.com/MehVahdJukaar/Supplementaries/issues
> Exception message: java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.network.NetworkDirection
> 
> Stacktrace:
> at net.mehvahdjukaar.moonlight.api.platform.network.forge.ChannelHandlerImpl.register(ChannelHandlerImpl.java:51) ~[moonlight-1.19.2-2.2.7-forge.jar%23401!/:?] {re:classloading}
> at net.mehvahdjukaar.supplementaries.common.network.NetworkHandler.registerMessages(NetworkHandler.java:14) ~[supplementaries-1.19.2-2.2.50.jar%23462!/:?] {re:classloading}
> at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:52) ~[supplementaries-1.19.2-2.2.50.jar%23462!/:?] {re:classloading,re:mixin}
> at net.mehvahdjukaar.supplementaries.forge.SupplementariesForge.<init>(SupplementariesForge.java:38) ~[supplementaries-1.19.2-2.2.50.jar%23462!/:?] {re:classloading}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Please can someone help me with this, I am not sure how to fix this..**

**Comment by MehVahdJukaar** [comment]
Issue unrelated to this mod. 
I see a mixin from a certain "imm_ptl" mod which is failing (shown at the top of latest.log)

**Comment by User4716** [comment]
Ok. Here's what I found:

**(Rows: 12-15)**

> [main/ERROR] [mixin/]: Mixin config **imm_ptl**.mixins.json does not specify "minVersion" property
> [main/ERROR] [mixin/]: Mixin config **imm_ptl**_fabric.mixins.json does not specify "minVersion" property
> [main/ERROR] [mixin/]: Mixin config **imm_ptl**_compat.mixins.json does not specify "minVersion" property
> [main/ERROR] [mixin/]: Mixin config **imm_ptl**_peripheral.mixins.json does not specify "minVersion" property

**---------------------------------------------------------------------------------------------------------------------------------**

**(Row: 66)**

> [modloading-worker-0/WARN] [mixin/]: @ModifyConstant conflict. Skipping **imm_ptl**.mixins.json:common.networking.MixinClientboundCustomPayloadPacket->@ModifyConstant::modifySizeLimitWhenReadingPacket(I)I with priority 1000, already redirected by xlpackets.mixins.json:ClientboundCustomPayloadPacketMixin->@ModifyConstant::xlPackets(I)I with priority 1000

_So it has something to do with "XL Packets Renewed" mod mabye?_

**---------------------------------------------------------------------------------------------------------------------------------**

**(Rows: 102-127)**

> [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: paragon, class com.kyanite.paragon.forge.ParagonForge
> java.lang.reflect.InvocationTargetException: null
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?]
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

_So it has something to do with Paragon mod mabye? https://modrinth.com/mod/paragon_

ㅤ
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraftforge.network.NetworkDirection.<clinit>(NetworkDirection.java:28) ~[forge-1.19.2-43.2.4-universal.jar%23494!/:?]
> 	at com.kyanite.paragon.forge.ParagonPacketHandler.init(ParagonPacketHandler.java:28) ~[paragon-forge-3.0.2-1.19x.jar%23514!/:?]
> 	at com.kyanite.paragon.forge.ParagonForge.<init>(ParagonForge.java:20) ~[paragon-forge-3.0.2-1.19x.jar%23514!/:?]
> 	... 14 more

_Yes Paragon has definitely something to do with it. (And I found a file that was in my "config" folder that was named 'paragon.json5')_

ㅤ
> **Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifySizeLimitWhenReadingPacket(I)I in imm_ptl.mixins.json:common.networking.MixinClientboundCustomPayloadPacket failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.imm_ptl.refmap.json**
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
> 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
> 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraftforge.network.NetworkDirection.<clinit>(NetworkDirection.java:28) ~[forge-1.19.2-43.2.4-universal.jar%23494!/:?]
> 	at com.kyanite.paragon.forge.ParagonPacketHandler.init(ParagonPacketHandler.java:28) ~[paragon-forge-3.0.2-1.19x.jar%23514!/:?]
> 	at com.kyanite.paragon.forge.ParagonForge.<init>(ParagonForge.java:20) ~[paragon-forge-3.0.2-1.19x.jar%23514!/:?]
> 	... 14 more

_I wonder what even is the 'imm_ptl' thing and what causes it to crash my game.._
**---------------------------------------------------------------------------------------------------------------------------------**

**Comment by MehVahdJukaar** [comment]
Might be paragon. I see that mixin as the cause of this

**Comment by User4716** [comment]
How do I delete it or fix it? And Im currently making a report to https://github.com/KyaniteMods/Paragon/issues

**Comment by MehVahdJukaar** [comment]
Try removing that first

**Comment by User4716** [comment]
Wait.. I disabled some mods I suspected were causing my game to crash, so I will launch my game now to see if I have still 13 errors or less. And then I will delete this paragon and see how it goes. But I am not sure how to even delete the "paragon" mod because it is not showing up in my mods folder.. 🧐🤔

**Comment by User4716** [comment]
Ok now my minecraft Log output window wont open, it will just close itself after it has opened. My game starts an the minecraft window where it would say Mojang studios pops up. But then my game just crashes, it doesn't even get to the red Mojang studios screen. :c.. I could look at the logs.

**Comment by MehVahdJukaar** [comment]
Why? Just get them from the log folder as usual

**Comment by User4716** [comment]
Yes I will send you the latest.log
It at least launched the game yesterday but now it just crashes and wont open Log output.

**Comment by User4716** [comment]
I usually check the option from Minecraft launcher settings to open Minecraft log utput to get real time log output.

**Comment by User4716** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10807174/latest.log)

**Comment by User4716** [comment]
There is also a
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/10807189/debug.log)

**Comment by MehVahdJukaar** [comment]
Same issue. Still that weirdly named mod

**Comment by User4716** [comment]
Well research might help, or mabye I'll send you my mods folder and you could test this yourself if you have time. 
(I use CurseForge. Minecraft 1.19.2 | Forge version: 43.2.4)

**Comment by User4716** [comment]
Ok yeah I cant upload my mods folder here, its 410MB :D

**Comment by User4716** [comment]
I Google searched "imm_ptl" it seems like a short name of 'ImmersivePortalsMod' which I have installed, lets see if I disable that mod that will it fix it..

**Comment by User4716** [comment]
Ok good news. I removed some mods, including the ImmersivePortalsMod and now my game launches all the way to the main menu without any problems. I will send still the latest.log if we can spot any errors in there, and now I will enable one by one all the mods I've disabled and see what I can enable and what not.

**Comment by User4716** [comment]
My game crashes when I join a world, but I have 'Not Enough Crashes' so I was able to get this: https://bytebin.lucko.me/vXJWwZ6HaG

**Comment by MehVahdJukaar** [comment]
Server side issue from this mod nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents

**Comment by User4716** [comment]
Yes I removed the mod "witherstormmod" it now works. But I have at least 10 mods disabled so I will test what mods I can enable before my game crashes.
