### ISSUE TITLE
[1.18.2]Mechanical Drill Break Fence With Rope Cause Crash!!!!!

### ISSUE THREAD

**Issue by KK1ve** [MehVahdJukaar/Supplementaries#524]
forge version: 40.1.80
Supplementaries version: 1.18.2-1.5.16
Create version: 0.5.0i

![2023-02-22 115502](https://user-images.githubusercontent.com/52612498/220517836-4207b7b1-5e43-4bd2-b667-e5205a524afd.png)
![2023-02-22 115618](https://user-images.githubusercontent.com/52612498/220517996-e854f1dd-8362-4395-8d62-dd10c9ec4449.png)

[crash-2023-02-22_11.56.02-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10799894/crash-2023-02-22_11.56.02-server.txt)

**Comment by MehVahdJukaar** [comment]
this should have been fixed on latest. 1.18 isnt supported anymore
