### ISSUE TITLE
Fabric 1.19.2 Cage delete NBT from Allay's, Allay's don't tag anymore with Note Blocks

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Supplementaries#525]
- Mod version, MC version and Loader you are using
Fabric 1.19.2 -> 0.14.15
supplementaries-1.19.2-2.2.50-fabric.jar

- A description of your issue and how to reproduce
After catch allays with the cage, the allays would not work like Vanilla,they don't tag anymore with an Note Block. 

1. Catch an Allay with Cage
2. Let the allay free from the Cage
3. Try to tag the allay with the note block

We had tested a lot, how the issue is reproducable. the problem appears only with catched Allay in an cage.

**Comment by MehVahdJukaar** [comment]
Do you know what part of NBT isn't persisting? Seems weird as cages saves an entity with its own save method

**Comment by suerion** [comment]
Sorry we don‘t know whats the right NBT tag, but something will be blocked to
change it again

**Comment by MehVahdJukaar** [comment]
Oh that all makes sense. I'll update accordingly. The prrisstance was so some mobs don't respawn after you catch them

**Comment by suerion** [comment]
@MehVahdJukaar is fixed, with the newest update ;) thanks a lot, we had tested it

**Comment by MehVahdJukaar** [comment]
awesome
