### ISSUE TITLE
[Fabric] Port over peripheral support for speaker blocks for CC: Restitched

### ISSUE THREAD

**Issue by Caketaco** [MehVahdJukaar/Supplementaries#528]
[CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched)

> CC: Restitched Updated, is a fork of [CC: Tweaked for Fabric (Discontinued)](https://www.curseforge.com/minecraft/mc-mods/cc-tweakedfabric), which is a fork of [CC: Tweaked](https://github.com/SquidDev-CC/) which ports the mod over to Fabric 1.16.5. It also aims to maintain feature parity with the official CC: Tweaked.

I know, I know, Fabricate some bitches, but it's good to keep track of parity issues between mod loader versions.

Can't have a nuclear powerplant without a robotic voice announcing the power level via poorly written lua code, after all.

**Comment by MehVahdJukaar** [comment]
API seems to be the same. just copy pasted the class and added the mod. hopefully should work

**Comment by Caketaco** [comment]
Works like a charm!
