### ISSUE TITLE
Server refuses to boot caused by... iron gate?

### ISSUE THREAD

**Issue by BeyondTheStarss** [MehVahdJukaar/Supplementaries#529]
Hi! I'm trying to run supplimenteries but it seems to cause the server to crash before even booting up fully
this is a 1.19.2 fabric server self-hosted on my computer
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10832834/latest.log)
steps to reproduce:
have a 1.19.2 server, put mod and necessary dependencies in, attempt to load server, see it crashes
[sorry if this has been reported before]

**Comment by MehVahdJukaar** [comment]
Issue from dramatic doors mod. Disable their iron gate mixin in their configs
