### ISSUE TITLE
Quark's Stack Options doesn't work with Sacks

### ISSUE THREAD

**Issue by Epicbattler3** [MehVahdJukaar/Supplementaries#532]
![image](https://user-images.githubusercontent.com/48891317/221439382-69056609-f2ff-4c80-be62-838881e47cd7.png)
![image](https://user-images.githubusercontent.com/48891317/221439387-d996513b-60f2-40db-9964-24404732fb0a.png)

When Quark is installed, Sacks do not have the inventory management things that chests do

**Comment by MehVahdJukaar** [comment]
you can add those to quark configs

**Comment by MehVahdJukaar** [comment]
added it to default quark configs. will be in next quark update
