### ISSUE TITLE
Banner patterns on sacks

### ISSUE THREAD

**Issue by Epicbattler3** [MehVahdJukaar/Supplementaries#533]
![image](https://user-images.githubusercontent.com/48891317/221439567-97359e89-b373-49da-a86e-18f70d75b118.png)
![image](https://user-images.githubusercontent.com/48891317/221439831-7698ebbb-d233-4d77-96f7-3d64160d3bed.png)

It's a bit hard to tell what's in each sack, so having a way to distinguish them would be nice. My initial idea was banner patterns, because dyes don't really make too much sense to me

**Comment by MehVahdJukaar** [comment]
Seems too similar to the new pots. Closing as I added colored sacks insteaf
