### ISSUE TITLE
[Fabric 1.19.2 2.2.51] Dispensers do not eject potion fluid into jars

### ISSUE THREAD

**Issue by Caketaco** [MehVahdJukaar/Supplementaries#535]
![image](https://user-images.githubusercontent.com/39420594/221441352-16cd3a7e-0b2d-4d59-b704-203970ebea27.png)

**Comment by Caketaco** [comment]
Current behavior:


https://user-images.githubusercontent.com/39420594/221441968-f1df56cd-6983-4300-b173-03d1f98d3901.mp4

**Comment by Caketaco** [comment]
Also this:
![image](https://user-images.githubusercontent.com/39420594/221442567-c3bc640c-db91-4cd0-946f-60d7bd983990.png)
Bug report if this is supposed to happen, feature request if not

**Comment by MehVahdJukaar** [comment]
fixd
