### ISSUE TITLE
Invalid Dependencies - Supplementaries Fabric requires newest Moonlight Lib only available for Forge.

### ISSUE THREAD

**Issue by Zarepheth** [MehVahdJukaar/Supplementaries#537]
As the title says, Supplementaries, `supplementaries-1.19.2-2.2.52-fabric.jar` has a dependency upon Moonlight Lib v2.2.13 - as far as I can tell, that file on CurseForge's website is only valid for Forge.

Currently using the latest **Fabric** versions of both Supplementaries and Moonlight Lib

Log: [latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10845696/latest.log)

Minecraft 1.19.2
Medieval MC [FABRIC] modpack, v18.5
Fabric 0.14.14

**Comment by Zarepheth** [comment]
I tried manually resetting the dependency back to v2.2.12, but Supplementaries is still failing - Supplementaries and Moonlight Lib are the two mods in the stack trace. I guess the Fabric version really needs something in the newer, but not yet available for Fabric, Moonlight Lib.

Crash Log: [crash-2023-02-27_19.39.23-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10845761/crash-2023-02-27_19.39.23-client.txt)

**Comment by Zarepheth** [comment]
Maybe I'm just impatient...
Looks like the Fabric version of Moonlight Lib v2.2.13 was just pushed to CurseForge. Using the new version got me past the startup crash.

**Comment by MehVahdJukaar** [comment]
Cueseforge moment
