### ISSUE TITLE
Wall Lantern Missing Textures

### ISSUE THREAD

**Issue by DisabledWarCriminal** [MehVahdJukaar/Supplementaries#538]
Using fabric on curseforge (better mc for 1.19.2, I updated everything I could to its latest version) mod version is 2.2.54 (I think)
![image](https://user-images.githubusercontent.com/126846509/222631625-2bcf9a0c-c4e5-46de-a655-e5aac60bb795.png)

My wall lanterns (the vanilla ones) are fucked up after I downloaded a mod called Chipped. Tried deleting Chipped and reinstalling this mod but it did not work. I have never done anything mod related so if there is some basic thing I am missing please let me know.

![2023-03-02_21 12 29](https://user-images.githubusercontent.com/126846509/222630706-9df20e5f-2e40-4c63-b894-81d30cd28fe7.png)

**Comment by MehVahdJukaar** [comment]
Ctm

**Comment by MehVahdJukaar** [comment]
Refer to https://github.com/MehVahdJukaar/Supplementaries/issues/395
