### ISSUE TITLE
Faucets still make item dropping sounds even if placed in front of an empty inventory

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#539]
**Always include**
Newest, 1.19.2 forge

Faucets still make item dropping sounds even if placed in front of an empty inventory

1. Place chest. DON"T PUT ANYTHING IN IT
2. Place faucet so that it can empty out the chest.
3. Open faucet
4. Observe that it still makes the dropping sounds despite dropping no items

**Comment by MehVahdJukaar** [comment]
fixed
