### ISSUE TITLE
Waysigns generate in the end

### ISSUE THREAD

**Issue by NJL5390** [MehVahdJukaar/Supplementaries#54]
Forge Version: 36.1.4
Supplementaries Version: 0.12.0

I've noticed that when exploring The End with this mod installed that waysigns will generate in the end despite having nothing to point to. This also seems to make them generate a notice board instead of signposts for some reason...
![2021-04-18_20 10 08](https://user-images.githubusercontent.com/64381954/115161956-7b5b8280-a098-11eb-8488-dab6603290c4.png)
![2021-04-18_22 43 10](https://user-images.githubusercontent.com/64381954/115161935-4fd89800-a098-11eb-9a3e-5d3bfe35c38c.png)
This happens even when no other mods are installed. The overworld waysigns generate correctly and no other dimensions generate them (modded ones included).

**Comment by MehVahdJukaar** [comment]
oof that's a big one. releasing update asap
