### ISSUE TITLE
Enderman heads ITEMS uses the default enderman texture instead of whatever texture pack you have an enderma

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#545]
Steps to reproduce: 
- Get a texture pack that changes enderman
- Notice that the enderman in the hotbar is different than any endermen heads that are placed down.

<img width="1512" alt="Screen Shot 2023-03-06 at 9 44 45 AM" src="https://user-images.githubusercontent.com/50085439/223189367-e44390db-6f3e-4a21-8248-1b6bc5673984.png">
They are clearlyd ifferent^ 

This is inconsistent with the behavior of vanilla mob heads.

**Comment by MehVahdJukaar** [comment]
Fixed
