### ISSUE TITLE
[CRASH] server crashes while running chunk pregenerator and integrated stronghold

### ISSUE THREAD

**Issue by enaye** [MehVahdJukaar/Supplementaries#547]
supplementaries-1.19.2-2.2.56.jar
moonlight-1.19.2-2.2.13-forge.jar

LOG:
[2023-03-06-23.log](https://github.com/MehVahdJukaar/Supplementaries/files/10904148/2023-03-06-23.log)
CRASH:
[crash-2023-03-06_19.37.42-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10904152/crash-2023-03-06_19.37.42-server.txt)

1.19.2-43.1.52 - SERVER CRASH - JVM: Java 17.0.6 (Temurin-17.0.6+10 from Eclipse Adoptium).

- Whenever I run chunk pregenerator with IDAS, a crash occurs. Developer of chunk pregenerator and IDAS say it has to do with supplementaries.

To reproduce:
install integrated stronghold and its API/dependents (which includes supplementaries and moonlight lib)
install chunk pregenerator
run server and start a pregen

everything runs fine until it gets to a chunk where supplementaries objects are being generated (i think)

**Comment by MehVahdJukaar** [comment]
idk how this could ever happen. I'm not sure what that mod does but it seems some of the data registries arent getting initialized properly. Try with latest moonlight version, has some extra logging

**Comment by enaye** [comment]
downloading [moonlight-1.19.2-2.2.15](https://www.curseforge.com/minecraft/mc-mods/selene/files/4426948) fixed the problem
ty for fix!

**Comment by enaye** [comment]
crash is gone, but an error occurs that stops the pregen 
i caught these two in the log:

https://paste.berrybyte.net/z80a5ksP
https://paste.berrybyte.net/wcqv7kwN

**Comment by MehVahdJukaar** [comment]
Hm it says it's expired

**Comment by enaye** [comment]
https://pastebin.com/QFQYEraK
https://pastebin.com/E3FsxB5z

sorry bout that

**Comment by MehVahdJukaar** [comment]
try latest version

**Comment by MehVahdJukaar** [comment]
closing this as it should be fixed
