### ISSUE TITLE
Server crashed after player broke bookshelf

### ISSUE THREAD

**Issue by Quinn-TM** [MehVahdJukaar/Supplementaries#548]
supplementaries-1.19.2-2.2.56-fabric.jar
moonlight-1.19.2-2.2.13-fabric.jar

Version: 1.19.2
Fabric version: 0.14.14

Server log
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10922271/latest.log)

Server Crash log
[crash-2023-03-08_08.26.52-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10922281/crash-2023-03-08_08.26.52-server.txt)

Player Crash Log
[message.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10922412/message.txt)

The server crashed when a player broke a bookshelf in a generated structure. The server does not crash on launch, but crashes when the chunk is loaded in. Supposedly there was a soul lantern on top of the bookshelf.
I honestly don't know how to reproduce this, I've tried to no avail.

**Comment by MehVahdJukaar** [comment]
Do you have vanilla tweaks? If you do it's that. Issue on their side. Has been there for a year
