### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by vampirebats** [MehVahdJukaar/Supplementaries#549]
When I try to start my game, it crashes and gives me this message: 
![image](https://user-images.githubusercontent.com/110431327/223852208-7f3ba2d5-53dd-4b58-a149-bfea8d938a92.png)

I downloaded the latest version of Supplementaries and Moonlight just to make sure that was not my problem, but that did not fix the issue.

Here is my crash log: https://pastebin.com/r7bS96v5

I am using Fabric 1.19.2.

**Comment by MehVahdJukaar** [comment]
i see this. unrelated
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: ladysnake.satin.api.managed.ManagedCoreShader

**Comment by vampirebats** [comment]
I'm not sure what the problem was, but installing Satin API fixed my game. Thank you!
