### ISSUE TITLE
(suggestion) Add support for Quark's vertical slabs

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#55]

**Comment by MehVahdJukaar** [comment]
how?

**Comment by Brun333rp** [comment]
I'm not a coder, but I bet that you need to make the vertical variant of certain blocks and code it so they are only available when Quark is installed

**Comment by MehVahdJukaar** [comment]
define "certain blocks". I would only think of the checker block since that's the only normal block which also has a slab in the mod

**Comment by Brun333rp** [comment]
> Pretty sure you'd need to have Abnormals Core as a dependency to do that (or make your own 'DIY quark vertical slab' system which would probably be a lot of work)

but vertical slabs are a Quark feature, and Quark doesn't need Abnormals Core to work

**Comment by MarioSMB** [comment]
Abnormals Core adds hooks for Quark's flags, one would need to consult their team as to why that is preferred over using Quark's flags directly.  
That said, I too have no clue what Quark's vertical slabs would do for this mod... would the OP mind elaborating on the issue?

**Comment by MehVahdJukaar** [comment]
checker block now has vertical slabs. No need for abnormalis core or anything of the sort
