### ISSUE TITLE
Reloading eventually causes reloads to fail

### ISSUE THREAD

**Issue by kyragit** [MehVahdJukaar/Supplementaries#550]
I'm on the most recent supplementaries, moonlight, and 1.19.2 forge.

Relevant log:
[message.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10926895/message.txt)

I think I know the problem, but I'm not a java programmer so I could be wrong. It looks like every reload is calling `HourglassTimesManager.parse()`, which then reads some data from some file, which is then added to `HourglassTimesManager.DUSTS`. This is then sent as a packet to the client. What I assume is happening is that for whatever reason, the data added to `DUSTS` is hashing to a different value, causing it to grow every reload until it reaches the 1MB packet size limit. This also only happened when I updated supplementaries, and it looks like that file is new since the last update. Hopefully this helps!

**Comment by MehVahdJukaar** [comment]
Oh might be. Was sure that was getting cleared every time, maybe I forgot. How did you find it? Must take so much to reach the packet size limit which ibelieve might be way lower than that

**Comment by kyragit** [comment]
It only took about 4-5 reloads, but I have ~250 mods installed so it's probably made worse by that. The exception was weird, so I figured I'd go look at the source code.

**Comment by MehVahdJukaar** [comment]
Oh it does increase with the more dusts you got. Anyways it's fixed
