### ISSUE TITLE
lanterns

### ISSUE THREAD

**Issue by Developer2704** [MehVahdJukaar/Supplementaries#551]
the lead and silver lanterns do not have proper textures for the rod they hang from when placed on walls. This is also the same for the lanterns from quark.
Hanging lanterns can be hit and make a sound and wobble. vanilla and supplementaries/forbidden and arcanus lanterns hung from a ceiling do not wobble and make a sound when you bump in to them

**Comment by MehVahdJukaar** [comment]
Quark does not have any lanterns tho. Not ones that can be hung on walls at least

**Comment by MehVahdJukaar** [comment]
As for the wobble it's just for horizontal. Imagine if a vertical one attached to a chain would wobble. Would look very put of place as chain itself would stay still

**Comment by Developer2704** [comment]
I was talking about the paper lantern from quark

**Comment by MehVahdJukaar** [comment]
yeah those cant be hung from walls. they are too big. You mean they themselves dont have textures?
