### ISSUE TITLE
A way to get arrow out of the quiver.

### ISSUE THREAD

**Issue by Lord-Volkner** [MehVahdJukaar/Supplementaries#556]
Right now, it seems that the only way to pull arrows out of a quiver is to fire them out. It would be nice to be able to pull them out so that we can load our quivers with the arrows we want.

Thanks
V

**Comment by MehVahdJukaar** [comment]
it works like bundles. you can take them out exactly in the same way

**Comment by Lord-Volkner** [comment]
> it works like bundles. you can take them out exactly in the same way

I appreciate the response, but it definitely doesn't work like a bundle. That was the first thing I tried.

To empty a bundle you can right click or shift right click with the bundle in hand.

Right clicking with the quiver brings up the interface to choose which arrows you want to use. Shift right clicking with the quiver does nothing.

**Comment by Lord-Volkner** [comment]
> Bundles also allow you to click stuff in an inventory slot which you can do here too

Sorry, but that doesn't work either. Right clicking an inventory, left clicking an inventory, shift right clicking, shift left clicking, nothing works. I even tried ctrl clicking, alt clicking (both right and left)

Does it have to be a special inventory?

**Comment by MehVahdJukaar** [comment]
I can't replicate this. If I click while holding a quiver on an empty slot it outputs it places it's content there. Maybe it's some incompatibility?

**Comment by Lord-Volkner** [comment]
> I can't replicate this. If I click while holding a quiver on an empty slot it outputs it places it's content there. Maybe it's some incompatibility?

Ahh, I was clicking on the chest. Open the chest then click on the inventory spot. I got it now. Thanks.

**Comment by ShadowDrakken** [comment]
It'd be nice to have a block that can load and unload arrows from quivers. Right now they completely clog up mob farms.
