### ISSUE TITLE
[1.19.2 Forge] Failing to parse hourglass data

### ISSUE THREAD

**Issue by BookerCatch** [MehVahdJukaar/Supplementaries#557]
- **Mod version:** 
Supplementaries 1.19.2-2.2.57 Forge

- **Issue Description:**
Sugar is invisible inside the hourglass

- Log Snippet

```[Render thread/ERROR] [supplementaries/]: Failed to parse hourglass data: Not a string: ["supplementaries:sugar_block","sugar"]; Not a JSON object: ["supplementaries:sugar_block","sugar"]```

```[Render thread/ERROR] [supplementaries/]: Failed to parse JSON object for hourglass data supplementaries:sugar```

![image](https://user-images.githubusercontent.com/43504436/224829373-91bf7dad-867c-47de-86e2-8f0d1887314b.png)

**Comment by MehVahdJukaar** [comment]
is this still an issue in latest update?
