### ISSUE TITLE
A way to disable flax

### ISSUE THREAD

**Issue by gglobensky** [MehVahdJukaar/Supplementaries#56]
Hi, I am making a modpack and I would like to make mods work in a cohesive manner.
I am trying to make your ropes with Druidcraft's hemp ground up to hemp fibers in a Create millstone.

I managed to do it all with datapacks, BlockSwap mod and KubeJS but AFAIK your flax would still be sold by the wandering trader.

I was wondering if there would be a simple way to turn the flax feature off while keeping your wonderful ropes.

Thank you for reading.

**Comment by MehVahdJukaar** [comment]
like every single other aspect or block added by the mod you can disable them via configs

**Comment by gglobensky** [comment]
I am really sorry, I seem to have completely ignored the supplementaries-registry file... probably because I'm not used to seeing this type of file.

This is a great way to proceed. 

Sorry again for making you waste your time. Thanks a lot for the awesome mod.

**Comment by MehVahdJukaar** [comment]
oh no worries. Look into the other configs files and tags too if you want more config potions. Just so you know, even for other mods, that extra config is needed because to disable blocks entirely a new manual config has to be created because forge configs are loaded after block registration

**Comment by gglobensky** [comment]
Thank you very much. I looked into my configs and I feel using a registry
is a pretty rare practice amongst the mods I use.
This means that some blocks unused in the modpack have to be loaded.

Although I don't mind and I really appreciate every mods even though some
may be imperfect, I think that doing things the way you described could be
a good practice to enforce amongst other modders.

Thank you for taking the time to answer me, I will now always look for a
registry config.

**Comment by MehVahdJukaar** [comment]
well yeah the name "registry" is a bit misleading since I used it a long time ago when I really didn't register stuff based on it. now i just hide it from jei and disable tis recipe
