### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Bloodtube** [MehVahdJukaar/Supplementaries#562]
Hello author, I like the mods you made very much, but I always fail to load when I use them, even with the latest version. The following are all the mods I use and pictures of the failures.
How can I solve the problem of loading failure.
I don't speak English, these are translated using google, please forgive me for any offense.
![1679490297769](https://user-images.githubusercontent.com/128606773/226919036-8b25a139-69ce-4e9f-b39d-d4b746037d41.jpg)
![1679490600988](https://user-images.githubusercontent.com/128606773/226919064-ac198665-6197-4359-a63e-2e064eb14c65.jpg)
![1679490623523](https://user-images.githubusercontent.com/128606773/226919066-0246a139-26d9-446f-8bde-209c9e79ba08.jpg)
![1679490634333](https://user-images.githubusercontent.com/128606773/226919069-67fd88c1-be19-4733-a8ed-3c30087b28e4.jpg)

**Comment by MehVahdJukaar** [comment]
and use latest version

**Comment by Bloodtube** [comment]
I have used the latest version, but it still fails to load

**Comment by Bloodtube** [comment]
Wow, it has been successfully opened, thank you very much

**Comment by MehVahdJukaar** [comment]
Sure no worries
