### ISSUE TITLE
Fabric 1.19.2 Crash / Latest Update 

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Supplementaries#563]
- A log if the issue is casing a crash. These are found in your instance directory under /logs
https://pastebin.com/pwx2DhSf

- Mod version, MC version and Loader you are using
1.19.2 Fabric 0.14.18 with MultiMC andCurseforge

- A description of your issue and how to reproduce
Tried to edit the Sign and Minecraft Crashed with the Crash Log

- If applicable, add screenshots to help explain your problem.
![grafik](https://user-images.githubusercontent.com/55131959/227732352-d143ffd7-3b0c-4eeb-8789-2ddc4d17fb8f.png)

**Comment by MehVahdJukaar** [comment]
try new version
