### ISSUE TITLE
Curseforge Required Mod install always The Bumblezone

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Supplementaries#568]
We don't willing to add with Supplementaries this new Dimension and new Mod, We don't need it, please look on Curseforge and delete it from the Dependents mods. Thanks

![grafik](https://user-images.githubusercontent.com/55131959/228587503-8e89e326-0111-4a3b-b6fb-997fbf094ad7.png)

**Comment by MehVahdJukaar** [comment]
are you sure this happens with latest version? there was an old version that was mislabled but that has long been fixed

**Comment by suerion** [comment]
Hey yeah, it is on the newest version also.


Von meinem iPhone gesendet

Am 29.03.2023 um 21:37 schrieb MehVahdJukaar ***@***.***>:

﻿

are you sure this happens with latest version? there was an old version that was mislabled but that has long been fixed

**Comment by MehVahdJukaar** [comment]
well new version isnt mislabled and if cf app still does that then there's nothing i can do as its outside my control
