### ISSUE TITLE
Launch crash on client and server (quilt)

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#569]
supplementaries: 2.2.64
client: 1.19.2
qfapi: latest.

https://paste.atlauncher.com/view/092987c7-d26e-4cf5-bbe8-eb3d79f969c0

server logs: https://mclo.gs/aKHO5QD

**Comment by MehVahdJukaar** [comment]
you have outdated mods

**Comment by netcore10** [comment]
Really?

**Comment by netcore10** [comment]
Could you give insight in which ones? I've tried all libraries and others, but it still crashes.

**Comment by MehVahdJukaar** [comment]
Sure, I need the new log you have now

**Comment by netcore10** [comment]
I got it!, through some digging i found a rather annoying mod that i hadn't removed properly. Thanks though!
