### ISSUE TITLE
Way Signs breaking Surface World Generation

### ISSUE THREAD

**Issue by czbuendel** [MehVahdJukaar/Supplementaries#57]
Mod Version: 1.16.5-0.12.1
Forge Version: 36.1.0

After updating the version of Supplementaries in our modpack (Engineer's Life 2) we have began getting reports of vanilla surface generation stopping at a point in exploring the world. All vanilla trees and grasses stop spawning but any mod added foliage or items stay (Natural Progression stones and twigs, Various mods added trees). We inserted Blame (https://www.curseforge.com/minecraft/mc-mods/blame) into an instance to see what was causing the world gen issues and it pointed to supplementaries:way_sign.

The full output is below:

[Render thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.9.2 ******************

 This ConfiguredStructure was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredStructure
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {},
  "type": "supplementaries:way_sign"
}

 Biome affected : [minecraft:frozen_ocean, betterendforge:sulphur_springs, minecraft:modified_gravelly_mountains, minecraft:swamp, minecraft:basalt_deltas, minecraft:desert_hills, minecraft:snowy_taiga_hills,
                   minecraft:dark_forest, minecraft:jungle_hills, minecraft:mushroom_field_shore, minecraft:snowy_tundra, minecraft:frozen_river, minecraft:giant_spruce_taiga, minecraft:deep_ocean,
                   minecraft:nether_wastes, minecraft:deep_lukewarm_ocean, betterendforge:foggy_mushroomland, minecraft:snowy_taiga, minecraft:mountain_edge, minecraft:river, minecraft:the_void,
                   minecraft:wooded_hills, minecraft:deep_cold_ocean, minecraft:stone_shore, minecraft:bamboo_jungle_hills, minecraft:end_highlands, minecraft:tall_birch_forest, minecraft:modified_wooded_badlands_plateau,
                   minecraft:eroded_badlands, minecraft:plains, minecraft:modified_badlands_plateau, minecraft:birch_forest_hills, minecraft:snowy_beach, minecraft:jungle, minecraft:ocean,
                   minecraft:warped_forest, minecraft:cold_ocean, betterendforge:dust_wastelands, minecraft:badlands, minecraft:wooded_badlands_plateau, betterendforge:megalake, minecraft:tall_birch_hills,
                   minecraft:deep_warm_ocean, minecraft:snowy_taiga_mountains, betterendforge:megalake_grove, minecraft:giant_tree_taiga_hills, minecraft:savanna_plateau, minecraft:taiga_hills, minecraft:taiga,
                   terraincognita:tundra, minecraft:wooded_mountains, minecraft:savanna, minecraft:jungle_edge, minecraft:giant_tree_taiga, betterendforge:umbrella_jungle, minecraft:ice_spikes,
                   minecraft:crimson_forest, minecraft:lukewarm_ocean, minecraft:warm_ocean, minecraft:mushroom_fields, minecraft:forest, betterendforge:shadow_forest, minecraft:end_midlands,
                   minecraft:sunflower_plains, minecraft:gravelly_mountains, minecraft:flower_forest, terraincognita:lush_plains, minecraft:shattered_savanna_plateau, minecraft:desert, minecraft:beach,
                   betterendforge:chorus_forest, minecraft:deep_frozen_ocean, terraincognita:rocky_tundra, betterendforge:amber_land, minecraft:shattered_savanna, minecraft:desert_lakes, terraincognita:lush_hills,
                   minecraft:bamboo_jungle, betterendforge:glowing_grasslands, minecraft:end_barrens, minecraft:dark_forest_hills, minecraft:small_end_islands, minecraft:badlands_plateau, minecraft:the_end,
                   minecraft:taiga_mountains, minecraft:modified_jungle_edge, minecraft:giant_spruce_taiga_hills, betterendforge:painted_mountains, betterendforge:blossoming_spires, minecraft:swamp_hills, betterendforge:crystal_mountains,
                   minecraft:birch_forest, minecraft:mountains, minecraft:soul_sand_valley, terraincognita:muskeg, betterendforge:ice_starfield, minecraft:modified_jungle, minecraft:snowy_mountains]

[Render thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 

-----------------------------------------------------------------------
****************** Blame Report 1.9.2 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

supplementaries:way_sign

-----------------------------------------------------------------------

**Comment by 5il3nc3r** [comment]
![image](https://user-images.githubusercontent.com/10393041/116622145-39410500-a912-11eb-820b-a3cc82e02a39.png)
![image](https://user-images.githubusercontent.com/10393041/116622215-5675d380-a912-11eb-9b84-7d9928777f0e.png)

**Comment by czbuendel** [comment]
The issue is discussed here:
https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/75

**Comment by czbuendel** [comment]
The user above tested further and when Supplementaries was removed newly generated chunks would generate fine.

**Comment by MehVahdJukaar** [comment]
How odd really. I've played with many other modpacks and I. I'm investigating why blame is complaining since I followed its author tutorial on structures to the word so I'm surprised it has something to say. Needless to say I'm looking into it.
What I can tell you for sure is that this is not due to that way sign at all. Try downloading any previous verison of the mod and the same resoult will happen even if I'm not even remotely touching worldgen there...
I remember there was a similar issue with undergarden that prevented top layer vegetation to spawn. I never figured what was causing that one and it was back when I literally only added blocks and didn't even touch worldgen at all.
I really don't know what the hell is going on...

**Comment by czbuendel** [comment]
Thank you so much for looking into it!

**Comment by TelepathicGrunt** [comment]
@MehVahdJukaar Actually, you are making an unregistered configuredfeature here:
https://github.com/MehVahdJukaar/Supplementaries/blob/d4a42b4d51b2b1e4e6c325b8624a231ab19aeb31/src/main/java/net/mehvahdjukaar/supplementaries/world/structures/FeaturesHandler.java#L31-L35

```
() -> ROAD_SIGN.get()
                .configured(IFeatureConfig.NONE)
                .decorated(Features.Placements.HEIGHTMAP_SQUARE)
                .range(256).chance(100)
```
ROAD_SIGN is the feature. Calling .configure turns it into a configuredfeature. Then the decorated, range, and chance each wrap the previous configuredfeature in a brand new one. The finalized one is the configuredfeature you need to register to WorldGenRegistries and add that instance to the event.

Here's how I register my configuredfeatures. I put them into their own class and call registerConfiguredFeatures() in FMLCommonSetupEvent's enqueueWork to prevent classloading issues and to make sure there's no race condition that could occur with registering to the vanilla registries.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/aebf644c68befe3d686eb332817328f7b9994b6e/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredFeatures.java#L223

Then you can just do this in biomeloading event and it should be good
```() -> ModConfiguredfeatures.ROAD_SIGN_CONFIGUREDFEATURE```

Hopefully this helps

**Comment by MehVahdJukaar** [comment]
hey thanks again :)

**Comment by czbuendel** [comment]
I hate being the person asking for any update info, but do you have an idea on that update release? 
I know that it is finals/exams time around the world for students so all cool if that is what is going on.

**Comment by pm065** [comment]
Would disabling the waysigns in the config fix this issue temporarily, or just keep the issue and not generate the waysigns? The Undergarden dimension has been completely wrecked by this.

**Comment by MehVahdJukaar** [comment]
Also again if this shows up again that generation error isn't connected to waysings to the slightest
