### ISSUE TITLE
18.2 Bug or Feature: extended spawnegg support

### ISSUE THREAD

**Issue by Shibva** [MehVahdJukaar/Supplementaries#571]
Ive noticed that only vanilla spawn eggs when used in trapped presents spawn mobs; could they be extended to support all spawn eggs if its possible

To be honest IDK if this is more of a feature request or is some form of bug

**Comment by MehVahdJukaar** [comment]
Fixed it in 1.19. 1.18 is discontinued

**Comment by Shibva** [comment]
question is; even in 18.2 could this work for modified vanilla spawn eggs (IE: there are commands that can change the spawn eggs contents; including mobs). Dont know if this is a false memory or something but I think I did try this and it worked for summoning lightning

**Comment by MehVahdJukaar** [comment]
Yeah it was just iterating over them a bit too early so the list wouldn't include the modded ones

**Comment by MehVahdJukaar** [comment]
But it should work with those modified ones no? I think it should just use its logic but I'll double check

**Comment by Shibva** [comment]
I think it does

**Comment by MehVahdJukaar** [comment]
2 commits ago I think
