### ISSUE TITLE
Missing block tags in 1.18.2

### ISSUE THREAD

**Issue by DarkNinja3141** [MehVahdJukaar/Supplementaries#577]
Mod version: `1.18.2-1.5.16`
MC version: `1.18.2`
Loader: `Forge 40.2.1`

I am unable to use the flint block to start fires. I looked into it and it was because the block tag "`flint_metals`" is missing from the iron block.

![image](https://user-images.githubusercontent.com/5752255/230741920-2899fe1d-3863-4d44-91db-ccc8ec8fc4d8.png)

![image](https://user-images.githubusercontent.com/5752255/230741924-5b32eed6-eed7-4b88-bf61-3dda163ad826.png)

The file `/src/main/resources/data/supplementaries/tags/blocks/flint_metals.json` is missing from the 1.18.2 branch, and I'm assuming others are too.

**Comment by MehVahdJukaar** [comment]
Those tags aren't used in this version

**Comment by DarkNinja3141** [comment]
I realize that now after searching
Github search kept redirecting me back to the latest branch while searching on the 1.18 one
Sorry
