### ISSUE TITLE
What is the minecraft id for the wall lantern?

### ISSUE THREAD

**Issue by IMadeThisJustToPostThis** [MehVahdJukaar/Supplementaries#578]
Not really a bug, more of a question
Trying to add the wall lantern to the block.properties of my complementary shaders .zip file, but cant figure out the correct id for the wall lantern(s). Tried supplementaries:wall_lantern, supplementaries:wall_lantern_long and supplementaries:wall_lantern_longer but that didn't seem to work

**Comment by MehVahdJukaar** [comment]
Supplementaries:wall_lantern

**Comment by ajh123** [comment]
> Supplementaries:wall_lantern. ALlso you can view ids by looking at a block while in f3

Or you can show the IDs in item tooltips be using `(FN+)F3+H`.
