### ISSUE TITLE
Crash as soon as I attempt to launch minecraft

### ISSUE THREAD

**Issue by Fortun4tus** [MehVahdJukaar/Supplementaries#579]
Crash report and log
[crash-2023-04-09_22.54.24-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11186385/crash-2023-04-09_22.54.24-client.txt)

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/11186387/latest.log)

Mod version: 2.3.2 , MC version: 1.19.2 , Loader: Quilt 0.18.5 

Attempt to launch Minecraft then there is a crash. Also reported it here https://github.com/MehVahdJukaar/Moonlight/issues/99 in the moonlight lib repository,

**Comment by SplendidAlakey** [comment]
This is a Supplementaries Squared crash, not Supplementaries. Supplementaries + Moonlight work just fine

**Comment by Fortun4tus** [comment]
It appears you are correct.
