### ISSUE TITLE
[Suggestion] Make signposts have the name of the village too if Serilium's Random Village Names mod is installed.

### ISSUE THREAD

**Issue by Corvus20** [MehVahdJukaar/Supplementaries#58]
Serilium's random village names mod gives villages names, as the name implies. It would be cool to add compatibility to the signposts to have the name of the village it is pointing in the direction of as well as the distance. This may or may not be possible but I figured I should at least mention it.

**Comment by MehVahdJukaar** [comment]
Oh I wanted to do that but I thought that mod(maybe was another similar one) was for fabric only. I'll see if I can manage it. would indeed be very cool
