### ISSUE TITLE
Help appreciated; Crash when loading some particular chunks. 1.18.2 FML-40.2.0 (Custom modpack)

### ISSUE THREAD

**Issue by BokChewy** [MehVahdJukaar/Supplementaries#580]
I posted this a couple times on the curseforge page but it doesn't seem like it was popping up on the issues tab after posting. If it's just a delay thing and you get spammed with 3 copies of the same issue report my apologies (better safe than sorry).

IN ANY CASE _here we go again_

As I read other bug reports on here and curseforge I saw your disclaimer about how sodium is no longer supported by this mod. I use the "Rubidium" fork of sodium for forge. Suspecting this was the problem, I removed it and tried again, but the problem persisted. Looking at the following crash report, do you see any way for me to salvage or fix supplementaries in my modpack or should I just dump it and move on?

[crash-2023-04-11_01.54.00-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11197411/crash-2023-04-11_01.54.00-server.txt)

thankyou.

**Comment by MehVahdJukaar** [comment]
You are not using latest version. About 20 versions behind. Also I don't see any mention of this me there

**Comment by BokChewy** [comment]
Well don't I look silly. Sorry for wasting your time with such an obvious fix, but regardless, thank you for your help (and frankly creepily fast response time.) Wishing you the best :)

**Comment by MehVahdJukaar** [comment]
Sure no worries

**Comment by MehVahdJukaar** [comment]
I get phone notifications that's why I reply fast xD
