### ISSUE TITLE
Crash when trying explode SignPostBlock (MimicBlock)

### ISSUE THREAD

**Issue by Matorinn** [MehVahdJukaar/Supplementaries#581]
Mod version: 2.2.64 MC version: 1.19.2 (Valhelsia 5.0.17)

StackOverflow due to recursion issue on MimicBlock.getExplosionResistance.
[crash-2023-04-13_00.36.11-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11214373/crash-2023-04-13_00.36.11-server.txt)

SignPostBlock was placed on fence and I tried to explode it with creeper and TNT.

**Comment by MehVahdJukaar** [comment]
You are using an outdated version
