### ISSUE TITLE
Create Deco scarlet brick cannot be thrown

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/Supplementaries#585]
Minecraft 1.19.2
Supplementaries 2.3.4
Forge 43.2.8

[Create Deco](https://www.curseforge.com/minecraft/mc-mods/create-deco)'s scarlet brick (`createdeco:scarlet_brick`) cannot be thrown, as it is missing from the `supplementaries:throwable_bricks` tag. This is inconsistent with the other brick types from the mod, which can be thrown just fine.

**Comment by MehVahdJukaar** [comment]
to be fair its their fault too as they should have tagged all of those as forge:ingots/brick as per convention
