### ISSUE TITLE
All Dupe Forge/Fabic

### ISSUE THREAD

**Issue by XionioXMaster** [MehVahdJukaar/Supplementaries#586]
**Read and delete this text**

**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

- Mod version, MC version and Loader you are using
supplementaries-1.19.2-2.3.4-fabric.jar

- A description of your issue and how to reproduce
Using some chest or box from the mod my friend was able to dupe it using the old portal dupe bug from version 1.18.2, video below. And I don’t remember what kind of chest it was, just dupe on the servers and that’s it XD

- If applicable, add screenshots to help explain your problem.
https://youtu.be/MrH6f8Dpgdw?t=117

**Comment by XionioXMaster** [comment]
https://youtu.be/L9sFCcLWgHA

**Comment by MehVahdJukaar** [comment]
Does this mean that bug isn't in vanilla 1.19?

**Comment by XionioXMaster** [comment]
> Означает ли это, что бага нет в ванильной версии 1.19?

there is, it probably works for anyone

**Comment by MehVahdJukaar** [comment]
If that is a vanilla bug then that's the issue. Scope of my mod isn't to fix vanilla bugs

**Comment by XionioXMaster** [comment]
This is not a vanilla bug, it was fixed in 1.18.2 or the like, but if you reset the block that I have on the video and quickly enter the portal with it, it will lie on the other side like a thing and stand like a block.

**Comment by MehVahdJukaar** [comment]
i was told that this was a vanilla bug and it affects all falling block entities such as this. guess replicating is easy tho, just swap that with a sand block
