### ISSUE TITLE
Make Red Merchants optional

### ISSUE THREAD

**Issue by ElectricVersion** [MehVahdJukaar/Supplementaries#587]
I would like to disable the spawning of Red Merchants on my server; however, there does not appear to be any option to do so in the configuration file. (The fact that they can get into fights with hostile mobs makes them a threat to nearby passives, hence my desire to disable them). Having an option to disable them completely or at least their spawning would be nice, especially since most other features in the mod can be toggled.

**Comment by MehVahdJukaar** [comment]
There is one

**Comment by ElectricVersion** [comment]
What exactly is this option? In 1.18.2 at least the red merchant isn't mentioned in any config files or the documentation for them

**Comment by MehVahdJukaar** [comment]
In general theres supposed to be one. Anyways 1.18 isn't supported anymore
