### ISSUE TITLE
Crash when shoving (empty) cages in Refined Storage and Sophisticated Storage

### ISSUE THREAD

**Issue by ChaosDogG** [MehVahdJukaar/Supplementaries#589]
When I set up an auto-craft system for the cages w Refined Storage, the game just said "nope" and when I tried to get back into the world, the game crashed-

[crash Log](https://github.com/MehVahdJukaar/Supplementaries/files/11302209/crash-2023-04-21_23.00.47-server.txt)
[Latest Log](https://github.com/MehVahdJukaar/Supplementaries/files/11302211/latest.log)
[Latest Debug Log](https://github.com/MehVahdJukaar/Supplementaries/files/11302212/debug.log)

How I did this, I assume:
1. get RS + SS set up
2. get a cage
3. shove cage into RS
4. watch as the game has a meltdown

**Comment by MehVahdJukaar** [comment]
I only see their stuff on the stack trace must be their issue

**Comment by ChaosDogG** [comment]
Yeah, thought i'd share here since this mod was part of the issue. Thanks
for responding quickly!
