### ISSUE TITLE
Effect blacklist for skeletons with quivers

### ISSUE THREAD

**Issue by Shurhaian** [MehVahdJukaar/Supplementaries#591]
Currently, it seems that any (negative?) potion effect is fair game for skeletons that generate with quivers.

The problem is that some potion effects are much deadlier than others (or are otherwise undesirable).

It makes perfect sense for quivers to be able to *hold* any arrows, but it would be very welcome if skeletons could be prevented from using some - like, say, Ars Nouveau's Blasting effect, which is potentially an instant kill (especially with the short duration from tipped arrows). Either attached to this or as a separate option, perhaps it'd also be good to keep the dropped quiver from generating with particular potion effects in it.

**Comment by katubug** [comment]
Seconding this request!

**Comment by MehVahdJukaar** [comment]
Therexis already. It's a tag

**Comment by MehVahdJukaar** [comment]
quiver_blacklist

**Comment by katubug** [comment]
Thanks! Will this prevent it being placed into all quivers, or just prevent
skeletons from using it? Assuming the former, but just curious

**Comment by MehVahdJukaar** [comment]
Skeletons
