### ISSUE TITLE
Placement of Faucet is Crashing my Server

### ISSUE THREAD

**Issue by Mike-1360** [MehVahdJukaar/Supplementaries#592]
Hello,

So I'm on Minecraft 1.19.2 version 17.5 of the Better MC [FABRIC] mod pack.
I'm using Mod Loader FABRIC 0.14.19. All on my own dedicated server.

I noticed today while playing that just placing the "Faucet" would instantly crash my server. I have been able to re-create this instance in a brand new world also... in single-player. Once the server crashes... I'm not able to get back into the world even after restarting it. Same goes for when in a single-player world. I thankfully have multiple backups of the world... so I'm good there. 

The following logs below should be the crash-report from the server side.

[crash-2023-04-25_12.09.27-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11327828/crash-2023-04-25_12.09.27-server.txt)

If you need more info, please let me know.

Thanks!

**Comment by MehVahdJukaar** [comment]
You are not using the latest mod version

**Comment by Mike-1360** [comment]
> You are not using the latest mod version

Okay, thank you!
