### ISSUE TITLE
Recipe Manager Serializer nulling out

### ISSUE THREAD

**Issue by Relaxing9** [MehVahdJukaar/Supplementaries#597]
### Latest Log
https://mclo.gs/PnNiKmT

### Mod version, MC version and Loader you are using
Mod Version: Supplementaries (supplementaries v.1.18.2-1.5.17)
MC Server: Magma version 1.18.2-62ec6408
Forge: 40.2.1

### Detail
I'm currently missing the Supplementaries inventory in Creative mode. I am able to search up via tags though using "#supplemtaries:". Please see the log as it shows that the serializer is null in multiple places which is probably what's causing me to not see the Creative Inventory. Luckily I have EveryCompat mod installed so I still have all the blocks Supplementaries provides in another creative menu. Additionally in the log there is a "potentially dangerous alternative prefix", which may or may not have something to do with it?

# Both Config Files
https://paste.gg/p/anonymous/53b80b51825f48fd9c6521be26447160

**Comment by MehVahdJukaar** [comment]
You say that the mod does not have a creative tab like it's something given for grated for every mod but that's not the case. Supplementaries adds it's items to vanilla tabs. Mods can also choose to not add them altogether. If you want a dedicated tab I also have a config for it

**Comment by MehVahdJukaar** [comment]
As for the recipes that's normal too as that's what happens when an optional recipe condition isn't met

**Comment by Relaxing9** [comment]
Oh I see, my bad I confused myself since they were INFO messages which is intended behavior. I was thinking they were warning messages for a bit.
