### ISSUE TITLE
Potted Sand

### ISSUE THREAD

**Issue by itsdeadfrosty** [MehVahdJukaar/Supplementaries#603]
I know we already have potted soil and Potted rich soil, but it would be really nice to get potted sand. Mainly just for decoration value. That way you could grow slightly smaller cactuses with a nice texture of like flowers or something. and then Also be able to grow like Aloe Vera from I believe it's the Ecologics mod or something? I don't know. I have too many mods downloaded to remember. But potted sand would be great. Also potted basalt. For the Coffee plant from the Farmer's Respite mod. or just compatibility between. The coffee plant. And the potted soil

**Comment by MehVahdJukaar** [comment]
not a big fan of this. point of planter is that you dont need water next to it for stuff to grow. none of the stuff you mentioned needs water anyways. I'm also considering to merge those 2 planters into a single generic one and swap the recipe when the mod is on

**Comment by itsdeadfrosty** [comment]
its for aesthetics? wack.

**Comment by MehVahdJukaar** [comment]
hm might make it so the soil changes depending on the plant above

**Comment by itsdeadfrosty** [comment]
Man I will take that 100%

Yeah coffee beans from one of my mods requires basalt, and another has aloe that requires sand, if it just accepts all crops or something that works.

**Comment by MehVahdJukaar** [comment]
ideas for a list of soil types? cant be dynamic as i dont want these to be tile entities.

**Comment by itsdeadfrosty** [comment]
Sand, Dirt, Farmland, Mycelium, Basalt

just off the top of my head

unrelated
maybe a bit outlandish but what about fishbowls? or aquarium blocks, crafted with just glass and a water bucket, and aquariums connect textures to become bigger fish tanks and can house more mobs, shift RMB with a bucketed fish to put it in a fishbowl, idk these r just random spur of moment ideas

**Comment by MehVahdJukaar** [comment]
well jars already work as aquariums

**Comment by itsdeadfrosty** [comment]
ohh didn't know
