### ISSUE TITLE
Minecraft 1.19.4 won't launch (Fabric)

### ISSUE THREAD

**Issue by teny1989** [MehVahdJukaar/Supplementaries#607]
Minecraft: 1.19.4
Fabric:  0.14.19
Supplementaries: 2.3.10
Moonlight: 2.4.0

Log:
[crash-2023-05-11_21.18.11-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11457860/crash-2023-05-11_21.18.11-client.txt)

**Comment by MehVahdJukaar** [comment]
Use the version that's on cf

**Comment by x29Naybla** [comment]
My also doesn't launch, most recent moonlightlib version. Even if I it's the only mod on the folder
