### ISSUE TITLE
[1.19.2] Named sacks lose names when using Quark's Expanded Item Interactions feature

### ISSUE THREAD

**Issue by SentientBowtie** [MehVahdJukaar/Supplementaries#609]
Forge version: 43.2.11
Supplementaries version: 2.3.10
Quark version: 3.4-400

When inserting an item into a named sack with Quark's Expanded Item Interactions feature (specifically using its Shulker Box Interaction option), the sack's name is removed. This happens whether you click the sack onto the item or the item onto the sack. Shulker boxes themselves, notably, do not have this problem. If Supplementaries Squared is present, the issue also affects colored sacks.

Tested with only Quark, Supplementaries, AutoRegLib, Moonlight Lib, and JEI enabled.

Steps to reproduce: 
1. Acquire a sack and initialize it, if you haven't already (you can't quick-insert items into sacks that haven't been initialized yet).
2. Rename the sack something super cool on an anvil. 
3. Right-click the sack with an item in your inventory, and observe as your super cool name has been replaced by the default "Sack".

(Sorry for posting this on the wrong repository the first time.)

**Comment by MehVahdJukaar** [comment]
fixed
