### ISSUE TITLE
crash when loading world, due to flax?

### ISSUE THREAD

**Issue by kerrschtein** [MehVahdJukaar/Supplementaries#610]
Completely up to date dependencies, crash when loading an already existing world with the 1.19.4-2.4.5-fabric update
[2023-05-18-1.log.gz](https://github.com/MehVahdJukaar/Supplementaries/files/11504242/2023-05-18-1.log.gz)
[crash-2023-05-18_00.01.09-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11504243/crash-2023-05-18_00.01.09-client.txt)

**Comment by MehVahdJukaar** [comment]
fixed in 2.4.6
