### ISSUE TITLE
[1.19.4] Dedicated Server fails to launch with crash

### ISSUE THREAD

**Issue by SmallSansSerif** [MehVahdJukaar/Supplementaries#611]
The latest version of Supplementaries crashes when launched on a dedicated server.

Exception message: java.lang.RuntimeException: Attempted to load class net/minecraftforge/client/event/ScreenEvent for invalid dist DEDICATED_SERVER

supplementaries-1.19.4-2.4.6
moonlight-1.19.4-2.4.6-forge
forge 45.0.64

[latest (1).log](https://github.com/MehVahdJukaar/Supplementaries/files/11519338/latest.1.log)
[crash-2023-05-19_13.44.13-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11519339/crash-2023-05-19_13.44.13-fml.txt)

**Comment by MehVahdJukaar** [comment]
fixed
