### ISSUE TITLE
Enhanced hanging signs crash with Biome Backlog installed

### ISSUE THREAD

**Issue by Swagboi7** [MehVahdJukaar/Supplementaries#619]
How to reproduce:
1. Have Supplementaries and Biome Backlog installed
2. Place any hanging sign

The crash in question:
[crash-2023-05-22_19.58.18-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11537826/crash-2023-05-22_19.58.18-client.txt)

**Comment by MehVahdJukaar** [comment]
Try now. Should be fixed
