### ISSUE TITLE
Crash on releasing a mob from a Jar/Cage

### ISSUE THREAD

**Issue by Bobisnotap** [MehVahdJukaar/Supplementaries#62]
Crash report: 
[crash-2021-05-18_23.10.17-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/6505998/crash-2021-05-18_23.10.17-client.txt)

Description: Releasing a mob from a jar/cage crashes the game, when rejoining the world the entity is properly released (in world, no longer in jar/cage)

Mods that may be part of this crash: Quark, Fabrication/Forgery

**Comment by MehVahdJukaar** [comment]
very odd. the crash is not really happening in my code tho. It's happening here com.gpiay.cpm.client.CPMClient
Now I have no idea what kind of mod gpiay or cpm might be :/

**Comment by Bobisnotap** [comment]
Think cpm was referring to a mod called Custom Player Model Remake, removing said mod stopped the crashing.
