### ISSUE TITLE
Crash net.mehvahdjukaar.modelfix.ModelFix

### ISSUE THREAD

**Issue by BlackAures1** [MehVahdJukaar/Supplementaries#621]
supplementaries-1.19.2-2.3.14.jar
Forge 43.2.11
[crash-2023-05-28_04.11.55-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11583345/crash-2023-05-28_04.11.55-client.txt)
[crash-2023-05-28_04.06.11-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11583346/crash-2023-05-28_04.06.11-client.txt)
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/11583347/debug.log)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/11583348/latest.log)

Just crashed at the start after making minor changes to the modpack. Now I'm in the process of understanding why this happens, but it mentions supplementaries

**Comment by MehVahdJukaar** [comment]
Error is unrelated to this mod. It's instead something about soundohysics config

**Comment by BlackAures1** [comment]
The problem turned out to be your other mod. I didn't change the configs, I just disabled your modelfix-1.8.jar
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/43911230/28f67d84-1119-4976-a449-2baa2ad5ed5c)
I can duplicate this bug on your other github repo, but do you need it?

**Comment by MehVahdJukaar** [comment]
It is not. That mod is a single mixin and it can only ever "fail" if mod loading has already failed as if that happens forge won't apply access wideners and some classes accesse din mixins won't be accessible. That's exactly what was shown in your crash report. I'm still trying to find a way to turn off the mod when this happens so forge can finish "loading" to bring you to the mod loading failed screen as that's what's trying to do there. Unfortunately I keep getting these false flaf kind of reports for that

**Comment by BlackAures1** [comment]
Strangely enough, yesterday I was only able to run the modpack after turning modelfix off, but now it worked with modelfix on. I apologize for misleading you.

If it would be helpful, here are the logs with modelfix-1.8.8.jar turned off
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/11584660/latest.log)
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/11584661/debug.log)

Here are the logs with modelfix-1.8.jar turned on
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/11584667/latest.log)
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/11584668/debug.log)

**Comment by MehVahdJukaar** [comment]
It must have been some missing dependencies that you either added or updated in the mean time

**Comment by BlackAures1** [comment]
I guess we can close this report then? Sorry to have bothered you with that. I was confused by the lack of notification about the lack of compatibility (usually the report mentions problems with it)

**Comment by MehVahdJukaar** [comment]
Yeah sure no worries. I'm working on a patch that should be able to remove these kinds of false flags errors. For the future if you want to know the real source of an issue scroll up in the debug .log until ou find the first error message there

**Comment by BlackAures1** [comment]
Can you give me an example? I very often watch logs, debug and crash reports for my own project, but I'm not a full-fledged coder. Can you give me an example (like this one [28May2023 04:11:53.346]) which line in my first debug I need to look at? There are a lot of lines :3

You wrote about Sound Physics, but it had nothing to do with the problem at all.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/43911230/fdf38e8e-0160-4019-b117-fb20cc658811)


The problem was fixed when I disabled modelfix-1.8 (the crash was fixed, but another mod asked for a config mod) + returned "resourcefulconfig-forge-1.19.2-1.0.20" and updated adaptive_performance_tweaks_core_1.19.2-6.9.0
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/43911230/0ed3189b-687a-4b77-8e56-b74a44ed439b)

**Comment by MehVahdJukaar** [comment]
Well it really depends on the type of crash but you can basically discard all errors and warnings thrown below wherever the log start saying stuff like "cowardly refusing to send event to a broken mod state". That first crash there must have been another reason or a multiple of reasons I'm not sure but the thing i stated above always stands
