### ISSUE TITLE
Config or tag to disable angering entities when caged

### ISSUE THREAD

**Issue by object-Object** [MehVahdJukaar/Supplementaries#624]
#14 suggested angering nearby mobs when caged. While this is a neat mechanic and probably fine in most cases, it would be useful if there were a way to disable it for specific mobs.

My specific use case: I run a Quilt server with a moderately large player count (15-20 online during peak). It's based around Hex Casting, so everyone wants villagers, which of course are quite laggy. I've asked my players to cage their villagers when they're not using them, but since caging villagers angers (and raises prices for) every nearby villager and iron golem, it's not really reasonable to expect them to do this.

**Comment by MehVahdJukaar** [comment]
I can add a config but it seems to me that this isn't really a good solution. There are some mods that turn villagers into blocks just emulating the trading part. You should try that. I thought about making hose cages act the same but never did as it made no sense to me as they are not happy to be there

**Comment by MehVahdJukaar** [comment]
added

**Comment by object-Object** [comment]
Much appreciated! sorry for the additional question, but is this a feature that can be released on 1.19.2 (our pack version)? I would happily build it myself, except I don't see the commit on any branch (may just be blind). we *are* looking at adding one of the "villagers as blocks/items" mods you mentioned, but this is still a good stopgap.
