### ISSUE TITLE
[1.19.2] Exception thrown with Configured

### ISSUE THREAD

**Issue by Nessiesson** [MehVahdJukaar/Supplementaries#632]
Using these mods:
- **Forge:** 1.19.2-43.2.11
- **Configured:** 2.1.1-1.19.2
- **Moonlight:** 1.19.2-2.2.35-forge
- **Supplementaries:** 1.19.2-2.3.15

When you press the Supplementaries mod Config button in the Forge mod list menu nothing visibly happens. However, the following is logged in your logfile:
[classcastexception.log](https://github.com/MehVahdJukaar/Supplementaries/files/11642655/classcastexception.log)

_I was not entirely sure whether to report this here or on the Moonlight issue tracker. ¯\\\_(ツ)\_/¯_

**Comment by MehVahdJukaar** [comment]
fixed
