### ISSUE TITLE
New version causes issues with server

### ISSUE THREAD

**Issue by An-Unnamed-Developer** [MehVahdJukaar/Supplementaries#633]
Logs: 
[crash-2023-06-03_20.46.47-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11643706/crash-2023-06-03_20.46.47-fml.txt)
(Attempted to load client configs on server0

**Comment by An-Unnamed-Developer** [comment]
Version: 1.19.2
Forge: latest
All latest dependencies and mod

**Comment by An-Unnamed-Developer** [comment]
Another thing to note is the server starts fine without Supplementaries.

**Comment by MehVahdJukaar** [comment]
This should have been fixed some time ago
