### ISSUE TITLE
Hanging sign crash on startup

### ISSUE THREAD

**Issue by Froszyy** [MehVahdJukaar/Supplementaries#639]
Latest version of Supplementaries and Moonlight Lib (and using not enough crashes)

I was using 1.19.4 making my own modpack, I tried to open it and it crashed, I was using not enough crashes and it told me that it was suspected to be Supplementaries, so here I am. MC version 1.19.4 mod version "supplementaries-1.19.4-2.4.14" and FML version "Forge - 45.0.66"

tried to open the modpack, crashed, told me to go here. happens every time I open, I tried to reinstall Supplementaries, didn't work.

 here's the Crashy https://crashy.net/b3c4e220-2241-4f0a-bf50-6ca927bead4a

**Comment by MehVahdJukaar** [comment]
I need your latest.log

**Comment by Froszyy** [comment]
https://pastebin.com/u1fKz5bG

I didn't get the problem fixed, just removed the mod after the crashes, I was making a modpack and just switched the modpack to fabric due to that bug and the fact that I was making a origins modpack then realized origins would work with forge 1.19.4 & everything was fixed

**Comment by MehVahdJukaar** [comment]
That is not your latest .log
Also check moonlight and othe mods are updated
