### ISSUE TITLE
[bug] 1.19.2  mod incompatibility with Emojiful after supplementaries-1.19.2-2.3.10

### ISSUE THREAD

**Issue by CKY-** [MehVahdJukaar/Supplementaries#643]
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[https://gist.github.com/CKY-/14a7fd169dc27d10be87e7fce22b05e6](https://gist.github.com/CKY-/14a7fd169dc27d10be87e7fce22b05e6)
- Mod version, MC version and Loader you are using
CurseForge 
1.19.2
- A description of your issue and how to reproduce
This is a mod incompatibility with Emojiful-Forge-1.19.2-4.0.4 or Emojiful-Forge-1.19.2-4.0.3
installing 
supplementaries-1.19.2-2.3.14
supplementaries-1.19.2-2.3.14a
supplementaries-1.19.2-2.3.17
all result in the same crash
[https://github.com/InnovativeOnlineIndustries/Emojiful/issues/80](https://github.com/InnovativeOnlineIndustries/Emojiful/issues/80
)

**Comment by MehVahdJukaar** [comment]
Should probably reported on emojiful as I just see th trying to access their config early

**Comment by CKY-** [comment]
> Should probably reported on emojiful as I just see th trying to access their config early

I sent it to both but since as supplementaries-1.19.2-2.3.10 has no issues
