### ISSUE TITLE
Crash when flax seeds are dropped on ground. Insta crash when joining world

### ISSUE THREAD

**Issue by PapaDimitri** [MehVahdJukaar/Supplementaries#645]
Hi again... I run into problem with flax seeds. Apparently they cause crash when dropped on ground.

Crash log:
[crash-2023-06-10_15.56.39-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11712568/crash-2023-06-10_15.56.39-server.txt)

**Comment by PapaDimitri** [comment]
Is it because of open parties?

**Comment by PapaDimitri** [comment]
quickly joining and killing all items on ground stopped from crashing tho

**Comment by MehVahdJukaar** [comment]
vanilla tweaks bugs. reported many times never noticed. i will not provide a workaround

**Comment by MehVahdJukaar** [comment]
and no this has nothing to do with flax, their issue is deper than that

**Comment by MehVahdJukaar** [comment]
i'll actually mark the mod as incompatible in a month or so as im tired of reports going to me

**Comment by PapaDimitri** [comment]
Oh well then ... I gotta watch for world killer flax xD. Sry for bothering once again have a nice day mate

**Comment by MehVahdJukaar** [comment]
no worries
