### ISSUE TITLE
[1.20] [Forge] Fail to Launch

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/Supplementaries#646]
Log: https://pastebin.com/rrD0J8E8

supplementaries-1.20-2.5.0.jar
Forge 46.0.12
Minecraft 1.20

The game does not launch when supplementaries is installed.

**Comment by gohkenytp** [comment]
I noticed it too

**Comment by MehVahdJukaar** [comment]
[13:37:59] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'moonlight', Requested by: 'supplementaries', Expected range: '[1.20-2.5.2,]', Actual version: '[MISSING]'

**Comment by laurorual** [comment]
Fabric version also is crashing.

**Comment by MehVahdJukaar** [comment]
Then send a log

**Comment by laurorual** [comment]
> If you are not having the same issue as above send a log

here: https://pastebin.com/gDgxJ2su

**Comment by MehVahdJukaar** [comment]
: You seem to have installed Sodium which breaks fabric rendering API.To fix you must install Indium as Supplementaries, as many other mods, rely on said API
	at

**Comment by laurorual** [comment]
> : You seem to have installed Sodium which breaks fabric rendering API.To fix you must install Indium as Supplementaries, as many other mods, rely on said API at

oh, i didnt know that! it really fixed my issue
maybe it's better to put this info on the description of the mod somewhere

**Comment by MehVahdJukaar** [comment]
No I won't put that there as breaking the loader they are built for is something sodium does. I've advocated many times that they should not do that or at least force people to download indium instead they break stuff and expect us to tell people what they do

**Comment by gohkenytp** [comment]
I just noticed the game crashed cause of the hanging signs removal on this mod.
