### ISSUE TITLE
[Suggestion] Add the Bundle Item Preview to Sacks

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/Supplementaries#650]
Instead of the list format of the sack, could the Item preview tooltip of the bundle be used here? 
mostly asking as the 9 slot list hides after five different items. 
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/44974827/804e7dc7-c73f-405a-9abc-ae77d06d17e8)
So having it display like this would help a lot visually 
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/44974827/fe03419f-7945-47b2-8416-1c20ff6edd47)

**Comment by MehVahdJukaar** [comment]
No since shulkers don't and I don't want to add them to shulkers as I've already pretty much that but it uses quarks classes as quark adds these to shulkers too so it makes sense there.
