### ISSUE TITLE
[1.20] Missing Back Curious Slot for quivers

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/Supplementaries#653]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/44974827/1e30a311-8d59-4017-a469-ef082c0e176d)

supplementaries-1.20-2.5.2
Minecraft: 1.20
Forge: 46.0.14
Curious:  curios-forge-5.2.0-beta.3+1.20.1

I tried to manually add the slot via commands, but there are non added by Suplementaries

**Comment by MehVahdJukaar** [comment]
Indeed. Supplementaries adds no curios slot. It just tags the quiver to go in ine

**Comment by Xelbayria** [comment]
are you able to solve the issue? if yes, then please close.

**Comment by ffuentesm** [comment]
> are you able to solve the issue? if yes, then please close.

I need to manually add the back slot via /curios add @a slot:back, that should not be the case, as the mod that adds the compatibility, should automatically add the required slots without the need for user input.
