### ISSUE TITLE
crashing when trying to join a join

### ISSUE THREAD

**Issue by CrystalClear51** [MehVahdJukaar/Supplementaries#657]
i have the latest version of supplementaries and moonlib on both server and on client but it still seems to show an error message for some reason on my modpack server, help?
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/136675801/f09ce0e8-aa23-4284-8365-5658389e879a)

**Comment by MehVahdJukaar** [comment]
that can only ever happen when you try to connect to a server without the mod. Also there was an issue with velocity with datapack registries but they fixed. Whatever this is its not on my side. if thats not those 2 then some mod is breaking minecraft datapack registries like the abovementioned velocity

**Comment by Xelbayria** [comment]
is the issue solved, if yes, then please close?
