### ISSUE TITLE
Crash related to Jars

### ISSUE THREAD

**Issue by Brun333rp** [MehVahdJukaar/Supplementaries#66]
I was playing in a recently-made world when I placed a Jar with a Butterfly mob from the mod Terraincognita. After some seconds, the game crashed. I don't know if it was the exact cause of the crash or if coincidentally something else happened and caused the crash, but either way here's the crash log:
[crash-2021-05-27_15.06.59-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/6556029/crash-2021-05-27_15.06.59-client.txt)

**Comment by MehVahdJukaar** [comment]
yup that's a bug. was introduced last version and happens if you click on a jar that has a mod inside with a mob. will fix next update

**Comment by Brun333rp** [comment]
so basically, it happens when you right click on a jar with a mob from another mod?

**Comment by MehVahdJukaar** [comment]
happened when you right click on then with anything. fixed now
