### ISSUE TITLE
[1.20.x] Sacks cant be opened

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/Supplementaries#661]
Supplementaries: 1.20-2.5.3
Forge: 47.0.3
I can no longer open sacks. 
We see the animation of them opening, but there is no UI activation
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/44974827/cbfc45cd-d86a-4873-8744-079a946e1deb)

**Comment by MehVahdJukaar** [comment]
fixed
