### ISSUE TITLE
Allow the creation of mud blocks using the faucet

### ISSUE THREAD

**Issue by limelier** [MehVahdJukaar/Supplementaries#662]
Dripping water from a faucet onto dirt should turn it into mud, similarly to the way it works for concrete.

**Comment by limelier** [comment]
I've made a few attempts at adding this via data pack, but haven't been successful. The [documentation](https://github.com/MehVahdJukaar/Supplementaries/wiki/Customization#faucet-interactions) isn't very clear on how to achieve this, or if it is even possible.

**Comment by MehVahdJukaar** [comment]
Hm does water turn dirt into mud in vanilla? Faucets just emulate that. Also I've updated the documentation lmk if it's clearer

**Comment by limelier** [comment]
Oh, it's clear after you updated the documentation that you can't use a datapack for this. In that case, yeah, a feature would be nice.

In vanilla, you have to use a water bottle on dirt to turn it into mud. It'd make sense if the faucet worked too.

**Comment by MehVahdJukaar** [comment]
oh i didnt know that ill add then
