### ISSUE TITLE
Game crashed when create a new world

### ISSUE THREAD

**Issue by C7B3RPVNK** [MehVahdJukaar/Supplementaries#665]
I wanna play the '_Integrated Dungeons and Structures_' and add the _supplementaries_ as pre-mod, the game can start with third-party launcher but crashed when I create a new world, I found something wrong with supplementaries in crash report, and there's crashed report by the way.
[crash-2023-06-18_17.40.45-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11781201/crash-2023-06-18_17.40.45-client.txt)

**Comment by MehVahdJukaar** [comment]
Update create
