### ISSUE TITLE
[Fabric 1.20] Creative tabs & REI's default plugin do not load correctly.

### ISSUE THREAD

**Issue by Questwizard** [MehVahdJukaar/Supplementaries#666]
It looks like something dealing with wood in Supplementaries' creative tab code and/or the Moonlight API is causing both the vanilla creative tabs as well as REI to not load correctly.

REI is showing an error:
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_8389()" because the return value of "net.mehvahdjukaar.moonlight.api.set.wood.WoodType.getBlockOfThis(String)" is null

Only the top row of creative tabs shows up (just the blocks ones), and absolutely nothing loads in REI due to the default REI plugin failing to load. Not sure if the root cause of the error is in the Moonlight API or Supplementaries itself. Doing a manual reload in REI's options menu of both plugins and recipes fixes them temporarily, but the creative tabs remain broken.

Version Info:
Minecraft 1.20, Fabric loader v0.14.21, API v0.83.0
Supplementaries v1.20-2.5.6-fabric, Moonlight lib v1.20-2.5.6-fabric.
Just a note: 2.5.7 does load on 1.20 for me despite being marked as .1 only on CF and Modrinth, but produces the exact same error. I used 2.5.6 for the logs since that's the latest version that's officially not marked as .1 only.

Logs:
[rei-issues.log](https://gist.github.com/Questwizard/c9da71c93b83e314ad45e0220ff13696)
[latest.log](https://gist.github.com/Questwizard/cf41f484e6dc24e126337ea937bde363)

**Comment by MehVahdJukaar** [comment]
I know where my oversight is. You must have a mod that has a wood type without a hanging sign

**Comment by Questwizard** [comment]
I do seem to have quite a few mods that don't have hanging signs for their wood. Tech Reborn, Ad Astra, Better Archaeology and Croptopia are a few of them.

On a side note, I apologize if this comment auto-closes the issue. GitHub has been acting goofy for me lately and likes to close things I comment on sometimes despite Clicking on "Comment" rather than "Close with comment".
