### ISSUE TITLE
Allow placing Create's Clipboard on Notice Board

### ISSUE THREAD

**Issue by villainous-j** [MehVahdJukaar/Supplementaries#668]
Create recently added a new [Clipboard](https://create.fandom.com/wiki/Clipboard), which would be very nice to have on the Notice board! Even has pages just like books.

Thanks for considering!

**Comment by MehVahdJukaar** [comment]
well i dont really see the point considering you can already place those. clipboards are way more complex that just text so it would need to basically emulate their entire rendering to be able to exist there which is reduntant since you can just place them themselves

**Comment by villainous-j** [comment]
fair enough! though i wouldn't go as far as to say it's redundant. placing the clipboard doesn't show its contents like your notice board does, which is why i ask!
