### ISSUE TITLE
Safe Issues (Fabric)

### ISSUE THREAD

**Issue by Abhainn-Leth** [MehVahdJukaar/Supplementaries#669]
Mod Versions: 2.5.8 - 2.5.10
MC Version: 1.20.1
Loader: Fabric (loader installer version: 0.11.2)

In version 2.5.8, items in a safe are deleted when the safe is mined and placed down again.

In version 2.5.10, safe is inaccessible by any means (right clicking does nothing, even on a safe with no assigned key).

**Comment by MehVahdJukaar** [comment]
Oh shit safe is unsafe
