### ISSUE TITLE
[1.18.2] [Modrinth] Latest version not uploaded to Modrinth.

### ISSUE THREAD

**Issue by Faeranne** [MehVahdJukaar/Supplementaries#671]
~~Crash log: https://mclo.gs/5HJWHLS

Minecraft version: 1.18.2
Java version: 17.0.7
Forge version: 40.2.9
Supplementaries version: 1.5.16
Create version: 0.5.1.b (tested with 0.5.1.a too)
Moonlight Lib version: 1.17.9

Game crashes during world load.  Replicated on a fresh install.  Seems Create ~~removed~~ ~~added~~ *moved?* a class that's caused several mods to fail with a very similar error.~~

Seems 1.5.18 didn't ever make it to Modrinth. Am changing this issue to track that instead.

**Comment by Faeranne** [comment]
Ok, looking through, I'm guessing this is *technically* fixed, just unreleased.

**Comment by MehVahdJukaar** [comment]
You are 3 supplementaries versions behind. Always use latest when reporting issues

**Comment by Faeranne** [comment]
What's the latest for 1.18.2?  I can't find a newer version for it.

**Comment by Faeranne** [comment]
Ah, nvm. You only support 1.20 now, as per the very bottom of your mod page.  That's unfortunate since Create still doesn't.  Ah well, guess I need to restrip my pack again.

**Comment by MehVahdJukaar** [comment]
No I meant 1.18.2 versions behind

**Comment by Faeranne** [comment]
It is? Modrinth only shows 1.15.16 as the latest for 1.18.  What is the latest version then?

**Comment by Faeranne** [comment]
Ah, seems the last two 1.18 versions never made it to modrinth, hence why I can't access them.

**Comment by Faeranne** [comment]
Renamed and reopened to track the actual issue.  Mostly in case someone else is modrinth exclusive like me and can't figure out why it's not updated correcttly.

**Comment by Faeranne** [comment]
Sweet! Looks like it's updated. Gonna close this one for good now :)
If anything else pops up, I'll make a new issue, but hopefully this goes well.

**Comment by Faeranne** [comment]
Thanks again!

**Comment by MehVahdJukaar** [comment]
Sure no problem
