### ISSUE TITLE
Signpost recipes not working correctly

### ISSUE THREAD

**Issue by L0rne** [MehVahdJukaar/Supplementaries#673]
Supplementaries 1.20-2.5.11-fabric
Minecraft 1.20
Fabric 0.14.21

The recipe for signposts does not work as intended.  

When placed in the crafting table most sign types won't craft to signposts.  Oak signs will craft, but only as cherry wood signposts.

**Comment by MehVahdJukaar** [comment]
Weird I can't replicate

**Comment by utkucandogan** [comment]
Same here in Forge

**Comment by MehVahdJukaar** [comment]
I can't replicate this. Only a few have this issue so idk what it is but must be mod related

**Comment by bytecauldron** [comment]
Hi friends, I have a similar report:

Minecraft 1.20.1
Fabric Loader 0.14.21
Fabric API 0.86.1
Supplementaries 1.20-2.5.19-fabric
Moonlight Lib 2.7.2

I received a report of oak signs turning into cherry sign posts. I got everything updated to the latest version and isolated the mod to a new profile containing the aforementioned dependencies above.

When I loaded a single player world in creative, this is what oak signs were turning into:
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/29267024/29fa25db-e1ac-4ad1-9704-1858d2151350)
When creating a new single player world, it appears to change every time.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/29267024/7abc316a-850c-44fc-9377-90a3f146361b)

> When placed in the crafting table most sign types won't craft to signposts.

I can attest to this as well. Looks like every sign except for oak will not turn into their respective sign post.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/29267024/1c0a9f68-77b8-454e-ae18-9e999448a037)

Please let me know if you want me to try anything else, happy to assist.

**Comment by Le6barbare** [comment]
I had the same issue on Forge 47.1.47

With:
Supplementaries 2.5.28
Moonlightlib 2.8.17

Issue is now resolved by using latest Moonlightlib (2.8.20)
which changelog says : "fixed an issue with shapeless recipe generation"
