### ISSUE TITLE
Sign Post Crashes MC when I want to add text! **Help**

### ISSUE THREAD

**Issue by Bodelia12** [MehVahdJukaar/Supplementaries#675]
I'm able to place signposts just fine but when I want to right-click to add text it crashes. This is the report. 

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/137822995/c5eb6b3c-a237-4c41-b9a7-b63d8dab753c)

**Comment by MehVahdJukaar** [comment]
send latest.log pls

**Comment by Bodelia12** [comment]
[crash-2023-06-26_18.59.51-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11885159/crash-2023-06-26_18.59.51-client.txt)

Heres the crash log.

**Comment by MehVahdJukaar** [comment]
fixed
