### ISSUE TITLE
Fabric 1.20, gift boxes cannot be dyed, which may cause game crashes.

### ISSUE THREAD

**Issue by QianMuu** [MehVahdJukaar/Supplementaries#676]
I tried to synthesize gift boxes of different colors, but they couldn't be dyed, and my game crashed.

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by QianMuu** [comment]
> should be fixed应该是固定的

So is this irreparable?

**Comment by MehVahdJukaar** [comment]
Hm that's the opposite of irreparable. I said that it should be resolved
