### ISSUE TITLE
[1.19.2] Unexpected hotbar lockup with the Quiver and GUIs.

### ISSUE THREAD

**Issue by zaeonNineZero** [MehVahdJukaar/Supplementaries#677]
**Versions**
Supplementaries 2.3.19 for Minecraft 1.19.2. Loader is Forge 43.2.6.
_Forge 1.20.1 versions of Supplementaries may also have this issue but have not been tested for it._

**The Issue**
The hotbar locks up - preventing you from switching slots via the mouse wheel or number keys - if the _Quiver_ keybind is held while a GUI such the pause menu or inventory is opened, then released before closing the GUI.

**To Reproduce**
The simplest way to reproduce the issue is to hold the _Quiver_ keybind and open the pause menu, release the keybind, then close the pause menu. The hotbar will then be locked up. Upon pressing and releasing the _Quiver_ keybind again, the hotbar will unlock and work as expected. This method also works with all other GUIs in the game, included modded ones.

If the Quiver is in the inventory or a valid slot when performing the above sequence, the Quiver's selection GUI will stay up until the keybind is pressed and released again.

**Thoughts**
To me, it looks as though the keybind handler fails to recognize that the _Quiver_ key is not being held after closing an inventory, and doesn't properly update until the key is pressed again. There also appears to be no check for whether there is a Quiver in the inventory or a valid slot before locking the hotbar and running the Quiver slot selection code.

**Comment by MehVahdJukaar** [comment]
Then don't bind it to a key that's already used. If both actions happens at the same time there are bound to be issues

**Comment by zaeonNineZero** [comment]
Confirmed fixed on 1.19.2-2.3.20. Thanks!
