### ISSUE TITLE
Many errors on this release.

### ISSUE THREAD

**Issue by DatsiK96** [MehVahdJukaar/Supplementaries#68]
This log file has just the Supplementaries mod on it, no config files, new world generated.

1.16.5-forge-36.1.23
supplementaries-1.16.5-0.12.2.jar

https://pastebin.com/TsbA3NWS

There are so many errors on this release.

I know there's a lot of issues open for the loot tables, but there's a lot of other errors that I want to make sure they aren't getting missed.

**Comment by MehVahdJukaar** [comment]
yeah all the loot tables and json errors came cause I forgot do delete stuff for blocks coming next update (I'm missing some stuff and I want to release a big update) but they are all harmless and are just annoying cause they like to spam the console log
