### ISSUE TITLE
Feedback an error message when a Speaker face is blocked

### ISSUE THREAD

**Issue by kitoaken** [MehVahdJukaar/Supplementaries#680]
If the Speaker side of a Speaker block is blocked, nothing happens (as intended), but there's no feedback that says it's set up incorrectly. For users who don't know this or don't know that Redstone input also counts, the block's functionality seems broken on the surface.

It would be useful if the UI of the Speaker Block said "Output side is blocked!" or something similar, or if smoke particles were produced after a failed redstone input.

**Comment by MehVahdJukaar** [comment]
well same applies to noteblocks if you place a block above them preventing the note to be played

**Comment by kitoaken** [comment]
That's true. It caught me out at first (haven't used vanilla noteblocks much myself) and a few others from searching in the Supplementaries discord, a text warning in the block's UI could be useful for small QOL
