### ISSUE TITLE
flags bug

### ISSUE THREAD

**Issue by lostopkk** [MehVahdJukaar/Supplementaries#686]
mod version: 1.20-2.5.16
minecraft version: 1.20.1
loader: quilt

examples:
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/50776714/7810e93c-b6a8-4e25-bc5d-f4b1090c294c)
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/50776714/42841838-2f46-4c6a-b110-c4a01648106b)

**Comment by MehVahdJukaar** [comment]
Fixed
