### ISSUE TITLE
Missing Hanging signs icons

### ISSUE THREAD

**Issue by kaz880** [MehVahdJukaar/Supplementaries#687]
Hey! I've come to realise while crafting hanging signs that some of the icons didn't appeared. At least, when you place them in the overworld, it's working fine. Only Spruce, Birch, Jungle, Acacia, Dark Oak, Crimson and Warped icons are not working. They also show up pink and black in your hand. Are those missing files?

The server is in Forge 1.18.2 with the 1.5.18 version do supplementaries with the 1.17.9 Moonlight Lib

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/112892936/83b0a62d-6707-41fc-baf2-97130da6df98)
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/112892936/9c7ace39-d8b0-4729-8ff3-fad95c06fb46)

**Comment by MehVahdJukaar** [comment]
no idea what could be causing this as those models arent even in the mod files anymore. try redownloading the mod on a new instance. maybe you have some mod that caches assets from a previous mod version or something cursed like that

**Comment by Xelbayria** [comment]
Is this issue resolved?  if yes, then please close.

**Comment by kaz880** [comment]
Not really, but we ended up swapping to 1.19.2
