### ISSUE TITLE
[1.20-2.5.17] Crash on startup when used together with create 0.5.1.d

### ISSUE THREAD

**Issue by karelmikie3** [MehVahdJukaar/Supplementaries#691]
When you start the game it crashes because of missing classes (probably because the create compatibility in Supplementaries is outdated and hence tries to use things that don't exist anymore. (not entirely unexpected since Create for 1.20 only released today))

[crash-2023-07-05_15.47.54-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/11958591/crash-2023-07-05_15.47.54-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/11958598/latest.log)
[debug.log](https://github.com/MehVahdJukaar/Supplementaries/files/11958599/debug.log)

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by sandalle** [comment]
Works now with Create 1.20.1-0.5.1.d and Supplementaries 1.20-2.5.18, thanks for the quick turnaround! :)
