### ISSUE TITLE
Mod is incompatible with Create 1.20.1 (create-1.20.1-0.5.1.d.jar)

### ISSUE THREAD

**Issue by celsiusqc** [MehVahdJukaar/Supplementaries#692]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/63996164/31d4700e-7032-4394-87e5-7412d2942717)

Crashing with Create

https://gist.github.com/celsiusqc/284e3db66288d885e7f89a5f0132942a

**Comment by MehVahdJukaar** [comment]
fixed
