### ISSUE TITLE
1.19.2 [FABRIC] Correct Fire particles for end sconce/nether sconce & crafting recipes for all sconce types

### ISSUE THREAD

**Issue by YackMyGack** [MehVahdJukaar/Supplementaries#696]
All of the sconce types are available through commands but they don't show up on the creative menu or JEI.

**Comment by MehVahdJukaar** [comment]
in 1.20 these wont be registered at all when the required mods arent installed

**Comment by MehVahdJukaar** [comment]
closing as i now made all those sconce only appear when the correct mods are on
