### ISSUE TITLE
"Create:Attribute Filter" support for present

### ISSUE THREAD

**Issue by tobi-blackscale** [MehVahdJukaar/Supplementaries#698]
Attribute filter setting "addressed to X"/ "addressed from X" to sort presents.

Would allow automatically unloading and loading presents to/from trains for delivery and sorting them with create machines.

**Comment by MehVahdJukaar** [comment]
What's an attribute filter

**Comment by MehVahdJukaar** [comment]
added but didnt test

**Comment by tobi-blackscale** [comment]
Oh, sorry, just realized that "Create" is not unambiguously in this case.
I wanted to suggest present compatibility with the item attribute filters from the mod "create". 
But it seems you figured it out?

And thanks, I look forward to testing it.
