### ISSUE TITLE
Trinket Support for Fabric 1.20

### ISSUE THREAD

**Issue by Ultimushadow** [MehVahdJukaar/Supplementaries#699]
I'm _pretty_ sure this isn't in the config because from what I can see, this mod does support Curios API but not Trinkets, and it doesn't look like it's in any open or closed issues on the tracker. While this is probably low priority, I would be interested in seeing the Quiver and Key slots you have built in for Curios extending to Trinkets.
I'm sure you have more important things to work on, if so I was wondering if you could tell me where to change the code in the mod to support Trinkets? I can add the slots and stuff in just fine, I'm just not 100% confident I know how to add in the quiver and key use from their respective Trinkets slots - no pressure though ofc

**Comment by Ultimushadow** [comment]
I managed to get the slots in and functional for my own personal use, I'm not quite the best with optional dependencies and since I intended on playing with them together, I did hard depend on Trinkets so I'm not sure it would be of use to you, but if anyone else if curious where I made my changes I can let you know (provided I remember lol)

**Comment by MehVahdJukaar** [comment]
You can make a pull request if you want

**Comment by Ultimushadow** [comment]
Yeah no, I have never understood github and I never will I guess
I made two repos, one for Supplementaries and SuppSquared
https://github.com/Ultimushadow/Supplementaries
https://github.com/Ultimushadow/SuppSquared

**Comment by MehVahdJukaar** [comment]
I'll have a look thanks

**Comment by Ultimushadow** [comment]
So I did a majority of the coding in Supplementaries itself, but the only thing I needed to put in Supp Squared was the Trinkets data. If I included the heavy key item in the tag for the key slot in Supplementaries, but Supp Squared isn't installed, the tag wouldn't load, so I only put the regular key in. Supp Squared overwrites that tag. Should be found in data -> trinkets -> tags -> items

**Comment by MehVahdJukaar** [comment]
alright. i added all that tho translation line for slot doesnt seem to work right it. was that added?

**Comment by MehVahdJukaar** [comment]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/24719182/f4ea2bdd-ea65-4f07-94c3-212f2ded02b5)

also quiver being in trinkets is kind of useless rn as fabric doesnt have keybind yet so i have to add that. not only that but it seems when its there it doesnt even work properly as it dupes arrows

**Comment by Ultimushadow** [comment]
Oh, my bad, you are correct the translation is missing! I can push an update to it in a moment. As for the duping arrows, I did not get that behavior? When I tested the mod the quiver had proper functionality, could you let me know what environment you are testing it with? I will try to fix that if I can

**Comment by MehVahdJukaar** [comment]
i fixed all that. you can try out if you want

**Comment by MehVahdJukaar** [comment]
except for translation as idk what they are

**Comment by Ultimushadow** [comment]
"trinkets.slot.chest.quiver": "Quiver",
"trinkets.slot.legs.key": "Key"

That, more specifically

**Comment by Ultimushadow** [comment]
I notice you used the CuriosCompatImpl for the Trinkets items, Curios API recently updated for Fabric 1.20 though so I imagine that would break things there? I originally hijacked the CuriosCompatImpl when I made my quick and dirty version of the mod, but I re-coded everything to use a Trinkets specific class so it could be expandable. You can probably tell though by some of the code that I am no expert, so if you have your reasons you can disregard this

**Comment by MehVahdJukaar** [comment]
ah why are there 2 of them ;_;

**Comment by Ultimushadow** [comment]
Yeah I have no idea, they operate slightly differently but are very similar which is why I wanted to give you a hand with the Trinkets stuff, seemed silly to not support both but equally silly for you to take time to add what is essentially the same compat
At the very least though I think it should be easy enough for you to take the changes and stick it in it's own class
I appreciate the work you put in for this, I can tell you're a better programmer by some of the ways you got around problems I was having in the code lol

**Comment by Ultimushadow** [comment]
All that's left for the compat besides that though is overwriting the tag when Supp Squared is installed. My shortcut was to just have Supp Squared overwrite the tag for the key slot, but maybe you know a way to only load the tag with both keys if the other mod is installed?

**Comment by Ultimushadow** [comment]
Hey, I think I found something
When the player has an empty quiver in their Trinket slot and a quiver with arrows in their inventory, the arrows are never removed from the inventory quiver
Is this the issue you were running into earlier? I put most of your code into my workspace but I couldn't find anything that handled that, is there a way to tell if a quiver is empty so the game passes it when trying to get the equipped quiver?

**Comment by MehVahdJukaar** [comment]
are you sure you are using my latest code?

**Comment by MehVahdJukaar** [comment]
hm thought i fixed it. cany you just click clone from existing sources in intellij new file window?
