### ISSUE TITLE
Poor server performance

### ISSUE THREAD

**Issue by Zaryu** [MehVahdJukaar/Supplementaries#700]
**Read and delete this text**

**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs
No crashes so far

- Mod version, MC version and Loader you are using
supplementaries-1.19.2-2.3.20 - 1.19.2 - 43.2.14

- A description of your issue and how to reproduce
Supplementaries taking serious server resources and cause lag.

Im trying to look for what exactly causes the server performance to go down this much as it is and with a profiler tool, supplementaries fell into my eye and looks like its taking quite some ressources from the server. Maybe someone have more knowledge than me about this whole thing and maybe can explain whats exactly happening. If not, it may be also fine.

- If applicable, add screenshots to help explain your problem.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/93491851/0e6bf4c3-a9bb-4203-8778-d42cd89adf38)

**Comment by MehVahdJukaar** [comment]
That code you see there is run just once per server lifecycle as it starts. It's impossible for it to take up that much unless server literally isn't doing anything like no entities no block updates no players or maybe the profiler was just taken for a single second as it was starting

**Comment by Zaryu** [comment]
The profiler was running almost 30 minutes and I can say that this scena takes through the complete time I watched. I also thought that it should just get called once on the onWorldLoad event, but this continues the whole time the server is running

**Comment by Zaryu** [comment]
Or are there any known incompatibilities regarding that issue from other mods that depends on supplementaries like integrated dungeons and structure's

**Comment by MehVahdJukaar** [comment]
I'll have a look. I suspect that there must be something messing or firing that forge event on its own as that normally just executes when the event fires for the overwolrd which is exactly once

**Comment by MehVahdJukaar** [comment]
To confirm run the profiler after the world has loaded

**Comment by Zaryu** [comment]
I also thought that the event may be firing multiple times, but I don't really know why. I ran the profiler after the the world has loaded, as I run it as I was on the server, to keep things loaded to look into what's exactly spicing up the server performance. But I'll confirm it again tomorrow, as ist pretty.late right now in Germany ;).

**Comment by Zaryu** [comment]
To let you know, another.player confirmed that the profiler indeed was tracking the startup. After he ran the profiler 5 mins after world load, supplementaries disappeared in the profiler
