### ISSUE TITLE
Compatibility Twig Tables are broken instantly (normal twig tables are not)

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#701]
https://github.com/MehVahdJukaar/Supplementaries/assets/50085439/b029211d-a319-4993-80fa-ab9c4b287a7e

**Comment by MehVahdJukaar** [comment]
I think they once were made like that and recently added the breakable tag/property. Also wrong repo 😔

**Comment by thelegitdolt** [comment]
hehe oops
