### ISSUE TITLE
Crash when opening a faucet plugged in a filled cauldron, when there's nothing below the faucet.

### ISSUE THREAD

**Issue by AzzaDellta** [MehVahdJukaar/Supplementaries#707]
- Mod version, MC version and Loader you are using Fabric 0.14.21 MC 1.20.1 Mod: 2.5.19

Place a faucet on the side of a water filled cauldron, then turn it on. The game crashes.

[crash-2023-07-17_02.00.49-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12066185/crash-2023-07-17_02.00.49-client.txt)

**Comment by MehVahdJukaar** [comment]
try new moonlight version
