### ISSUE TITLE
Jars cause crash upon launching game after updating to 2.5.19

### ISSUE THREAD

**Issue by Kelpiesaurus** [MehVahdJukaar/Supplementaries#708]
Hello. My world crashes upon loading after updating Supplementaries to 2.5.19. I'm using Curseforge with Forge version 47.1.30. (I got the same crash with 47.1.0 if that adds any relevant info.) The launcher gives exit code -805306369. 

Edit: I forgot to add I am using Moonlight Lib 2.6.1 (moonlight-1.20-2.6.1-forge.jar)

How to replicate: Create a new world, place a jar, fill it with water.

World launches fine after reverting to Supplementaries 2.5.18.

Crash log: https://pastebin.com/6ZLMbJhB

**Comment by MehVahdJukaar** [comment]
Are you using latest moonlgiht verison?
