### ISSUE TITLE
Game crashes when thunderstorm starts due to "unluckyLightning" mixin

### ISSUE THREAD

**Issue by MCRusher** [MehVahdJukaar/Supplementaries#709]
Using Quilt Loader 1.19.2

Mod List

- Supplementaries 1.20-2.5.19
- Moonlight 1.20-2.6.2
- QFAPI 7.0.6 and QSL 6.0.4

Also tested with Fabric 0.14.21 and FAPI 0.85.0+1.20.1, same issue

Quilt Crash log: [crash-2023-07-17_15.42.44-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12073368/crash-2023-07-17_15.42.44-server.txt)

Fabric Crash log: [crash-2023-07-17_15.50.23-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12073401/crash-2023-07-17_15.50.23-server.txt)

Fabric log: [latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12073416/latest.log)

To reproduce:

1. install mods
2. create world with cheats
3. do `/weather thunder`
4. wait for game to crash

Game still crashes even when the related option is turned off.

**Comment by Surpos0** [comment]
same issue but on 1.20.1 fabric 
[crash-2023-07-18_02.09.49-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12074537/crash-2023-07-18_02.09.49-server.txt)

**Comment by MehVahdJukaar** [comment]
Should be fixed on latest version. Tbh idk why it wasn't workinf
