### ISSUE TITLE
Trying to use a Pancake on Jukebox does nothing?

### ISSUE THREAD

**Issue by RiddleMeNani** [MehVahdJukaar/Supplementaries#711]
I am using version 1.19.4-2.4.16 on Fabric/Quilt launcher for Minecraft 1.19.4.
Recently I was told about the neat little feature where putting a pancake into a jukebox does a cool little thing and went to try it out today.

But nothing happened? 
I have JEI installed and it shows that it is available, but the object just does nothing. doesnt even flash that any music is playing like it normally would with a vanilla disc.

im partially hoping its just a bug or something, but I did see that some features are missing from the Fabric version for reasons - so I'd understand if that is the case...

**Comment by RiddleMeNani** [comment]
Awwe bollucks. Just my luck lmao

Does just spawning the disc itself as a command still allow it to work or no? It's not game breaking but a little saddening lol

Hopefully I can update everything for 1.20 soon in any case. Just waiting on some servers.

**Comment by MehVahdJukaar** [comment]
Could. That stuff got changed there and I drastically modified how that's handled in newer version.

**Comment by RiddleMeNani** [comment]
POG

Thanks a bunch for the info :D
