### ISSUE TITLE
Everything is copper incompat

### ISSUE THREAD

**Issue by Developer2704** [MehVahdJukaar/Supplementaries#713]
When you hang the copper lanterns on the wall from everything is copper the thing they hang on is miscolored

**Comment by MehVahdJukaar** [comment]
what version?

**Comment by MehVahdJukaar** [comment]
Mod version. Can you send a screenshot?

**Comment by Developer2704** [comment]
everything is copper 2.2.1
supplimentaries 2.5.21
![2023-07-21_10 06 56](https://github.com/MehVahdJukaar/Supplementaries/assets/111246017/a4279fb1-2758-4981-b489-7134397d3bb7)

**Comment by MehVahdJukaar** [comment]
Ah I see. Those can be added with a texture pack. Don't have time myself to make that now as I can't possibly add a new texture for every mod that adds a lantern but people can submit these textures and I'll add
