### ISSUE TITLE
supplementaries fabric 1.20.1 crash with sodium

### ISSUE THREAD

**Issue by LordGriefington** [MehVahdJukaar/Supplementaries#717]
Greetings
I am using the latest version of supplementaries, moolight lib and sodium and fabric api
I tested it, it works without sodium, or supplementaries, but not with both

minecraft 1.20.1 fabric 0.14.21

Mod versions: 
sodium-fabric-mc1.20-0.4.10+build.27, moonlight-1.20-2.7.2, supplementaries-1.20-2.5.21, fabric-api-0.86.0+1.20.1

reproduce:
it crashes on startup, just load it together with sodium

[crash-2023-07-21_22.39.25-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12134592/crash-2023-07-21_22.39.25-client.txt)

I dont wanna play without sodium, and I like to add supplementaries again - great mod

**Comment by MehVahdJukaar** [comment]
Caused by: net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$UnsupportedModError: You seem to have installed Sodium which breaks fabric rendering API.To fix you must install Indium as Supplementaries, as many other mods, rely on said API
	at
