### ISSUE TITLE
Custom Adventurer Maps Warn

### ISSUE THREAD

**Issue by Brittank88** [MehVahdJukaar/Supplementaries#72]
```
[17:05:49] [Server thread/WARN] [ne.me.su.Supplementaries/]: failed to parse config 'custom_adventurer_maps' ([]): expected 9 entries, found1
```

Just wanted to check if this is harmless!

**Comment by MehVahdJukaar** [comment]
yes almost everything that's under "warn" is usually harmless. When something bad goes wrong it's usually good practice to let the game crash. I put that message in when it failed to parse some optional configs for stuff that isn't even totally added in yet

**Comment by Brittank88** [comment]
Understood! I know warns are usually harmless, I just like to report them in case they are actually resolvable (even -0.1% overhead is still less overhead!).
