### ISSUE TITLE
Farmer's Delight integration not working

### ISSUE THREAD

**Issue by limelier** [MehVahdJukaar/Supplementaries#720]
Minecraft 1.20.1
Forge 47.1.0
Supplementaries 1.20-2.5.21
Farmer's Delight 1.20.1-1.2.2a

Sticks and ropes can no longer be placed on farmland for tomatoes to grow on them. They instantly turn the farmland into dirt.

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/20465045/4ee8d453-0c12-44b8-9b19-f43c6ac8e5de)

**Comment by MehVahdJukaar** [comment]
I'm pretty sure this has not been a feature before

**Comment by MehVahdJukaar** [comment]
Also because there's not much they can do on farmland

**Comment by limelier** [comment]
> I'm pretty sure this has not been a feature before

https://github.com/MehVahdJukaar/Supplementaries/wiki/Mod-Integration#direct-integration-and-new-featureshttps://github.com/MehVahdJukaar/Supplementaries/wiki/Mod-Integration#direct-integration-and-new-features

> Roped and Stick-Logged Tomato vines blocks from Farmers Delight. This allows for the base tomato vine block to grow onto placed sticks or ropes. The rope-logged block will maintain both the tomato properties and the underlying block ones. Sticks can now also be placed on the first stage of a tomato vine directly onto farmland

**Comment by MehVahdJukaar** [comment]
Yeah but those are different than just sticks and ropes. Does tomato with stick not work?

**Comment by limelier** [comment]
Trying to place the stick onto the tomato vine also turns the farmland into dirt, breaking the tomato and leaving just the stick.

**Comment by MehVahdJukaar** [comment]
Are tomatoes fully grown? What about ropes?

**Comment by limelier** [comment]
Right-clicking `budding_tomatoes` with a stick or rope does nothing.

Right-clicking `tomatoes` of any age (including fully-grown) with a stick stick-logs them, which turns the farmland into dirt and breaks the tomatoes.

Right-clicking `tomatoes` with rope does nothing.

It's worth noting that, when sufficiently bone-mealed, tomatoes will rise up onto a stick or rope. It's just placing the stick/rope on the bottom block that doesn't work, because it turns the farmland onto dirt.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/20465045/432a5265-e549-44ec-afd6-b161c0e29a61)

**Comment by MehVahdJukaar** [comment]
Fixed
