### ISSUE TITLE
Speaker Volume Causes a Crash.

### ISSUE THREAD

**Issue by Arachnon** [MehVahdJukaar/Supplementaries#721]
1.20-2.5.21 1.20.1 Fabric

changing the speaker volume causes a crash on fabric 1.20.1 on the latest version, it also has no bar showing what volume it is. 

[crash-2023-07-24_09.06.54-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12146995/crash-2023-07-24_09.06.54-client.txt)
![2023-07-24_09 36 23](https://github.com/MehVahdJukaar/Supplementaries/assets/95883022/9dd6e252-f9cb-4832-8ea9-9acbbbf50452)

**Comment by MehVahdJukaar** [comment]
Are you sure you don't have like 2 supplementaries versions installed?

**Comment by Bwapt** [comment]
I have the same problem here. It seems to be a global issue

**Comment by MehVahdJukaar** [comment]
Fixed
