### ISSUE TITLE
jar icon cant be seen on creative menu and inventory menu on fabric

### ISSUE THREAD

**Issue by Thingydude32** [MehVahdJukaar/Supplementaries#722]
**Read and delete this text**

**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

- Mod version, MC version and Loader you are using

- A description of your issue and how to reproduce

- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
Fixed
