### ISSUE TITLE
Faucets, and Hoppers Don't mix Causes A Crashloop Due to Ticking Block entitys

### ISSUE THREAD

**Issue by Arachnon** [MehVahdJukaar/Supplementaries#724]
supplementaries-1.20-2.5.21-fabric
So basically I was seeing what happens if you make a hopper feed into a faucet, and well it Puts the world into a crash loop when you turn the faucet on effectively being a chunk ban.  its being caused by it turning into a ticking block entity 
[crash-2023-07-24_09.06.54-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12149185/crash-2023-07-24_09.06.54-client.txt)
![2023-07-24_14 01 31](https://github.com/MehVahdJukaar/Supplementaries/assets/95883022/9438531d-0492-4e59-8936-6130126e8653)
This is the setup that causes it, as soon as you turn on the faucet, it breaks the game.

**Comment by MehVahdJukaar** [comment]
Nasty issue that happens on fabric with a faucet connected to any inventory due to an offbyone error. I can't upload due to vacation

**Comment by MehVahdJukaar** [comment]
Fixed
