### ISSUE TITLE
Quiver should be on the right side

### ISSUE THREAD

**Issue by DcNdrew** [MehVahdJukaar/Supplementaries#727]
Hi!
Quivers usually are on the back or on the right hip, so they won't be in the way of the sword.

**Comment by MehVahdJukaar** [comment]
Actually historically they weren't used on the back much. You can place them with the configs tho. Also for the hip I was sure I placed them in the appropriate position depending on the player main hand as people would use their other hand to draw arroes

**Comment by MehVahdJukaar** [comment]
so from what i can see they are on the left as they should be placed in the opposite side as to where you hold the bow
