### ISSUE TITLE
Can't find crafting recipes anywhere!

### ISSUE THREAD

**Issue by onyxcrow15** [MehVahdJukaar/Supplementaries#728]
I am using 20.1 version and no matter what no crafting recipes are showing up. Even after I go into creative mode and grab the item, the crafting recipe isn't showing up. I crafted a jar and a clock by looking up the recipe online but not every crafting recipe I need is available.
So the mod works but its impossible to find the crafting recipes.

**Comment by MehVahdJukaar** [comment]
Use jei
