### ISSUE TITLE
[Bug] [Forge 1.19.2] Changing the name of cookies in a jar

### ISSUE THREAD

**Issue by XKonnoRX** [MehVahdJukaar/Supplementaries#732]
Mod version 1.19.2-2.3.20.
If you put cookies with a different name in a jar, when you take out all the cookies will be with the name of the first cookie you put.
It would be nice if each cookie saved its nbt data while in a jar.
To reproduce the bug, put a cookie with a different name in a jar, then start getting it out. All cookies will have the same name.

**Comment by MehVahdJukaar** [comment]
Ooh yes it's an inventory with 1 slot. Could make it have 12 , would also allow to have mixed cookes

**Comment by MehVahdJukaar** [comment]
Added in 1.20. it's a bit of a breaking chsnge and 1.19 is on life support so I won't backport
