### ISSUE TITLE
[1.20.1] Error in the log with Nyf's Spider

### ISSUE THREAD

**Issue by BugmanBugman** [MehVahdJukaar/Supplementaries#733]
**Always include**
-  Log: https://hastebin.com/share/opekuguwaq.bash

- 1.20.1 Forge, Supplementaries 1.20-2.5.21

- On a server load up it says the thing in the log, I'm not sure if it breaks anything but it seems to happen with only supplementaries and nyf's spiders. Just wanted to report it just incase it is a serious bug, or if i should report it to nyf's spider https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders

**Comment by MehVahdJukaar** [comment]
Completely their issue. I've already reported a long time ago. It's not even a supplementaries incompatibility I'm just loggin early (ideally crashing) to prevent a random crash down the line that would happen seemingly at random due to a missing null check in their code

**Comment by Nyfaria** [comment]
I just love how, YOU setting the navigation of an Entity prior to it even existing, is what caused this (which you really shouldn't be doing) is totally a me issue. I fixed it after trying so many things (a null check caused issues that my users would complain about) but tbh, you could have fixed this by delaying whatever navigation you are working with by 1 tick.
