### ISSUE TITLE
Jei/Emi crash on looking at recipes

### ISSUE THREAD

**Issue by DayIsGone** [MehVahdJukaar/Supplementaries#734]
looking at recipes for a sherd from supplimentaries in Jei and Emi caused the cilent to crash. This has happened to two people on my server I was able to replicate it to get the crash report. It does not crash the server just the client.

Minecraft version: 1.20.1
Forge: 47.1.3
Supplientaries: 2.5.21
Moonlight: 2.7.2
JEI: 15.2.0.23
EMI: 1.0.15+1.20.1-Forge

[crash-2023-08-03_13.31.18-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12253462/crash-2023-08-03_13.31.18-client.txt)

**Comment by MehVahdJukaar** [comment]
You have a mod that is breaking avanilla class, the Sheets class by loading it early. This is a rare issue that some.mods have been known to cause
