### ISSUE TITLE
[compat] [1.20.1] Texture Pack Issue

### ISSUE THREAD

**Issue by N0aW** [MehVahdJukaar/Supplementaries#736]
**Versions:**
- Minecraft Version: 1.20.1
- Fabric Loader Version: 0.14.21
- Supplementaries Version: 1.20-2.5.21
**How to Reproduce:**
1: Use minecraft with supplementaries
2: Use hoe on gravel
3: Error occurs
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/76262280/11c3fa01-68c9-400e-bd42-e8f8f2ac8074)

**Comment by MehVahdJukaar** [comment]
i cant replicate. those just use normal gravel texture and works for me. idk why or how it would break

**Comment by N0aW** [comment]
Seems to be a texture pack issue, works just fine without a texture pack

**Comment by MehVahdJukaar** [comment]
so this happens when a pack replaces the farmland model making it use a different format. raked gravel uses that model so it breaks. instead when using packs with mods the correct way to do it is replace the blockstate pointing to a different model entirely
