### ISSUE TITLE
[fabric 1.20.1]Placing a faucet on an empty barrel causes crashes.

### ISSUE THREAD

**Issue by bbyuyund** [MehVahdJukaar/Supplementaries#739]
[crash-2023-08-09_22.23.33-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12303884/crash-2023-08-09_22.23.33-server.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12303885/latest.log)
[游戏崩溃前的输出.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12303886/default.txt)

Fabric0.14.22 
Minecraft1.20.1 
Supplementaries 2.5.21

Placing a faucet on an empty barrel and opening it cause crashes.

(Can be easily replicated.)

**Comment by bbyuyund** [comment]
It doesn't happen in the forge version of this mod.

**Comment by MehVahdJukaar** [comment]
fixed
