### ISSUE TITLE
0.13.1 Crash On Startup

### ISSUE THREAD

**Issue by Valafi** [MehVahdJukaar/Supplementaries#74]
`[B#652]  Exception in thread "main" [06:00:47.221] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[configuredBackground]" defined twice in its table.`

Removing one of the entries fixed the problem for me

**Comment by MehVahdJukaar** [comment]
yeah I added that last minute and pasted it twice... fixed in 0.13.2

**Comment by Valafi** [comment]
Confirmed, thanks :)
