### ISSUE TITLE
recent changes to ash lead to ticking entity crash

### ISSUE THREAD

**Issue by notandvm** [MehVahdJukaar/Supplementaries#741]
> base 1.20.1 fabric instance
> only mods installed are fabric api, moonlight lib, and supplementaries (2.5.22)

[crash-2023-08-11_19.04.52-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12325823/crash-2023-08-11_19.04.52-server.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12325826/latest.log)

can be reproduced by going into a world and placing ash so that they fall
third placement leads to a crash

https://github.com/MehVahdJukaar/Supplementaries/assets/137728158/dc23e700-af89-45de-9b31-ef398f88e156

**Comment by Lolfaceftw** [comment]
can confirm we have similar crash reports: https://mclo.gs/uxIulBr

**Comment by N0aW** [comment]
My minecraft crashes without even placing ash
https://mclo.gs/I8xYWdz

**Comment by MehVahdJukaar** [comment]
fixed
