### ISSUE TITLE
Mineshaft Elevator Piece Server Crash

### ISSUE THREAD

**Issue by Verdigris7** [MehVahdJukaar/Supplementaries#742]
Experienced a reproducible crash while generating a new chunk with a mine shaft, reverting my mod version fixed the issue for me. Seems like it has something to do with the mine shaft pulley elevator. I have a few mods that add new mine shaft variants but this crash was happening near a totally vanilla minecraft mine shaft. (I checked the mineshaft type with the explorers compass mod)

Let me know if I attached the log correctly or not. And thanks for making this awesome mod.

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12330218/latest.log)

**Comment by MehVahdJukaar** [comment]
I'm not sure that's related. I see it somehow got an null Rotation which is an invalid state. no idea how that happened. maybe some faulty mod bug propagated there

**Comment by Verdigris7** [comment]
Wow, thanks for the fast update! I went to 6 vanilla mineshafts on the latest version, and nothing crashed. TYSM

**Comment by MehVahdJukaar** [comment]
Sure glad it's fixed
