### ISSUE TITLE
Fabric 1.20.1 | Is the Ash fixed?

### ISSUE THREAD

**Issue by makumaku1974** [MehVahdJukaar/Supplementaries#743]
**Read and delete this text**

**Before continuing**
Always check you are using the latest version of this mods and it's dependencies

**Always include**
- A log if the issue is casing a crash. These are found in your instance directory under /logs

[crash-2023-08-15_00.13.41-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12337251/crash-2023-08-15_00.13.41-server.txt)

- Mod version, MC version and Loader you are using : Fabric 1.20.1

- A description of your issue and how to reproduce : Placing ash like sand

- If applicable, add screenshots to help explain your problem.

**Comment by MehVahdJukaar** [comment]
My dude you should read the first line of your own post. You are not using latest verison
