### ISSUE TITLE
wall lanterns in 2.5.24+ seem to have broken

### ISSUE THREAD

**Issue by notandvm** [MehVahdJukaar/Supplementaries#745]
> base fabric 1.20.1 instance
> fabric api, moonlight lib (2.8.2), & supplementaries (2.5.25)

attempting to place lanterns on the side of blocks seems to do nothing and assumes vanilla behavior, regardless of config; the issue seems to have been present on version 2.5.24 as well

downgrading to supp 2.5.23 fixes the issue, so likely has something to do with an adjustment from .23 to .24

(_possibly_ a moonlight issue given it coincides with the addition of and improvements on AdditionalItemPlacementsAPI (if thats for what would be assumed given changelogs) though when downgrading supps to .23 moonlight can remain version 2.8.2 and lanterns place as normal)

**Comment by MehVahdJukaar** [comment]
Indeed they use the new API for that. I believe latest version is 2.8.3 which does adress an issue. Can you try it?
