### ISSUE TITLE
Supplementaries-2.3.21 1.19.2Forge Crash on World loading

### ISSUE THREAD

**Issue by DTech10** [MehVahdJukaar/Supplementaries#746]
- A log if the issue is casing a crash. These are found in your instance directory under /logs

[Crash Log](https://paste.shockbyte.com/ulugiposivevunefolal.coffeescript)
[Latest Log](https://paste.shockbyte.com/atoboteyadeqebibanef.md)
- Mod version, MC version and Loader you are using

Mod: 2.3.21
MC: 1.19.2 Forge
- A description of your issue and how to reproduce

I updated the mod to the latest version and whenever I load my world it crashes, the Not Enough Crashes mod says the potential cause is the Nyf's Spiders 2.0. But when I downgraded the Supplementaries its loading properly again
- If applicable, add screenshots to help explain your problem.
![2023-08-16_19 56 09](https://github.com/MehVahdJukaar/Supplementaries/assets/136813833/15914348-0338-4f24-af91-6eb202217ea0)

**Comment by MehVahdJukaar** [comment]
their issue. im porpusefully crashing to prevent random crash that this issue causes

**Comment by SimonMeskens** [comment]
Nyfaria won't fix the issue and says the bug is on your end:

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/4284735/da3311a2-eac1-4bc2-9442-06e515516c35)
