### ISSUE TITLE
Enchanting power of an End Crystal on a pedestal

### ISSUE THREAD

**Issue by Phantom-Knight** [MehVahdJukaar/Supplementaries#748]
I'm using version 1.19.2-2.3.22, on Forge.

From the wiki:
> If an end crystal is placed on a pedestal the block will give off an enchanting power equal to 5 bookshelves. This means that with 5 of such blocks you'll be able to max out an enchanting table

And yet, according to the tooltip, the pedestal is providing 3 points.

![immagine](https://github.com/MehVahdJukaar/Supplementaries/assets/5129465/eb27bb41-fc2e-46ee-9151-efede076fd70)

Given that enchanting power caps at 15 bookshelves, I'd say it's just a typo in the wiki, but which "5" is wrong?

**Comment by MehVahdJukaar** [comment]
Hm yeah seems so

**Comment by MehVahdJukaar** [comment]
Typo is in power. It's supposed to be 3 as with 5 crystals you'll get 15 max power. Also the power is handled in the configs so I guess it's not even that wrong

**Comment by Phantom-Knight** [comment]
Oh, I didn't know about the config option. Thanks for looking into this.
