### ISSUE TITLE
Game crashes on startup when loaded with Two Players One Horse (As of 0.14.0)

### ISSUE THREAD

**Issue by NJL5390** [MehVahdJukaar/Supplementaries#75]
Supplementaries Version: 0.14.0
Two Players One Horse Version: 2.0.2
Forge Version: 36.1.32
Latest Log: https://gist.github.com/NJL5390/927716a7016fef9a6c946ff16817a0d9

After updating to the latest version of Supplementaries, I discovered that my game would just crash during startup. No crash report was generated so I was very confused as to what was causing it at first. 

After looking in the latest log (linked above) I found it was a conflict between Supplementaries and a mod called Two Players One Horse (Link to mod's page here: https://www.curseforge.com/minecraft/mc-mods/two-players-one-horse). After removing that mod I found that my game started just fine. Seems to be something to do with mixins? (I'm not a modder so I'm not really sure what those are). 

I've removed the other mod for now as all it does is allow two players to ride the same horse at the same time. It would be great to get this resolved though. 

Thanks for the amazing mod, You're always able to come up with great new features every update and I greatly appreciate it!

**Comment by sirben99** [comment]
Hey!

I can confirm that i have to exact same issue. This is server sided too, as seen here: https://pastebin.com/YE2Vu6TW

Removing TwoPlayersOneHorse mod makes the server launch.

Minecraft: 1.16.5
Forge: 36.1.32
Supplementaries: 1.16.5-0.14.0
TwoPlayersOneHorse: 1.16.4-2.0.2

Ben

**Comment by MehVahdJukaar** [comment]
Yeah it's a mixin conflict. I'll release an update soon but for now you can just delete skeleton horse mixin inside mixins json located in the mod jar

**Comment by NJL5390** [comment]
I can confirm that this issue has been fixed as of 0.14.1. Thanks a lot!
