### ISSUE TITLE
The arrow from quiver is not consumed when put the quiver into the off-hand slot

### ISSUE THREAD

**Issue by henrique-dev** [MehVahdJukaar/Supplementaries#751]
Minecraft Version: 1.20.1
Fabric Loader Version: 0.14.22
Mod Version: 1.20-2.5.27

Basically when we put arrows in a quiver and then put the quiver in the  off-hand slot, the arrows are not consumed thus allowing the arrows to be duplicated. 
After identifying the problem, I isolated the mod by just installing it in the game, and the problem still persisted.

**Comment by MehVahdJukaar** [comment]
fixed
