### ISSUE TITLE
[1.20.1] Unable to run in the latest version of moonlight

### ISSUE THREAD

**Issue by Dr-WeiAL** [MehVahdJukaar/Supplementaries#754]
I'm having this problem after updating moonlight to the latest version, have checked that the latest version of Supplementaries is 2.5.26
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/47446553/b8b57267-72a3-4b79-beca-876f16b82dba)

[crash-2023-08-26_15.13.35-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12444763/crash-2023-08-26_15.13.35-fml.txt)

moonlight-1.20-2.8.9-forge
supplementaries-1.20-2.5.26

**Comment by MehVahdJukaar** [comment]
shit. fixed
