### ISSUE TITLE
BOP support broken?

### ISSUE THREAD

**Issue by ZEROX7** [MehVahdJukaar/Supplementaries#755]
- 1.20.1 forge

- install supp and bop

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/12628051/31d30a1a-1055-48bf-8185-a8da0f72f9b8)

**Comment by MehVahdJukaar** [comment]
Can you send your log?

**Comment by ZEROX7** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12478463/latest.log)
