### ISSUE TITLE
Buzzier Bees candles support

### ISSUE THREAD

**Issue by SlimF** [MehVahdJukaar/Supplementaries#76]
The new statues are awesome and I love having them in my base. Would it be possible for them to support Buzzier Bees candles? Both regular ones, and scented ones. Not only for them to be able to be placed in the statue, but also for them to still give their respective effect? (For example the Dandellion Scented Candle to still give you Saturation or the Oxeye Daisy Scented Candle to still give you Regeneration while being held in the statue)

**Comment by MehVahdJukaar** [comment]
well buzzier bees candles are quite big and wouldn't really fit there. Right now they use the 1.17 styled candles for all (they should visually accept buzzier bees candles there too)

**Comment by SlimF** [comment]
Ahh, didn't think about their size
