### ISSUE TITLE
Block{supplementaries:urn} doesn't exist console spam

### ISSUE THREAD

**Issue by purejosh** [MehVahdJukaar/Supplementaries#760]
Console being spammed with the following logline, when loading chunks: 
[15:46:55] [C2ME worker #5/WARN]: Block Entity at class_2338{x=-3902, y=-19, z=-6640} for block Block{supplementaries:urn} doesn't exist

supplementaries-1.19.2-2.3.19-fabric.jar
Fabric 1.19.2
Loader 0.14.21

**Comment by MehVahdJukaar** [comment]
Do you have carpet?

**Comment by purejosh** [comment]
I do!

**Comment by MehVahdJukaar** [comment]
The log spam is actually a vanilla bug. Supplementaries suppresses that but some mod might be conflicting with it. Ialso known carpet had some issue with the random log spam so idk which of the two it is. Either way it should be their issue

**Comment by purejosh** [comment]
I think it could be C2ME, as well. I didn't notice these logs until after installing it, but I wasn't sure if it was uncovering another issue.

**Comment by purejosh** [comment]
In either case, thanks for confirming that this isn't an issue.
