### ISSUE TITLE
Dyable Sacks

### ISSUE THREAD

**Issue by Adome11** [MehVahdJukaar/Supplementaries#761]
I feel like a good way to make sacks feel a little nicer to use and closer to their shulkerbox counterparts is via allowing them to be dyed. A good way to not make it as useful as shulkerboxes (a theme you're obviously going for) is to just have the little band around the sack be colored. This means you still have some way to differentiate them at a glance, but they still aren't as useful as dyed shulkerboxes.

**Comment by MehVahdJukaar** [comment]
Download supplementaries squared
