### ISSUE TITLE
Blackboards are not rendered correctly. Only when facing north

### ISSUE THREAD

**Issue by Inf4d3l** [MehVahdJukaar/Supplementaries#762]
- Mod version, MC version and Loader you are using
supplementaries-1.20-2.5.28-fabric.jar
1.20.1
Fabric, Curseforge App
- A description of your issue and how to reproduce
Blackboards only render correctly facing the north direction, any other direction and the actual drawing is offset. To recreate this simply place down blackboards.
- Other mods in this instance

![temp](https://github.com/MehVahdJukaar/Supplementaries/assets/91441433/fb525d37-7431-4574-a91a-9f59d8689e4c)

- Screenshots

![2023-09-01_12 33 44](https://github.com/MehVahdJukaar/Supplementaries/assets/91441433/f2d9397e-e091-4ae4-a851-58b3abf59f13)

**Comment by MehVahdJukaar** [comment]
sus
does latest versions fix?
