### ISSUE TITLE
Unbinding the Quiver Key causes Invalid Key GL Errors to spam the log

### ISSUE THREAD

**Issue by gliscowo** [MehVahdJukaar/Supplementaries#763]
By [directly checking the Quiver keybind against `InputConstants.isKeyDown`](https://github.com/MehVahdJukaar/Supplementaries/blob/8c819330fc863e83b324d77c16234ccf5f3e7c14/fabric/src/main/java/net/mehvahdjukaar/supplementaries/common/events/fabric/ClientEventsFabric.java#L57C63-L57C63) (at least on Fabric), there is no handling for unbound keys (represented as Keycode -1) and the log gets spammed with the game reporting the resulting GLFW errors every tick

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/15788224/13b3b302-06bd-4714-b3eb-f8850a259b50)

To alleviate this, it should first be verified that the binding is actually bound using `KeyMapping.isUnbound` 
Cheers

**Comment by MehVahdJukaar** [comment]
;_;

**Comment by Sxtanna** [comment]
This is not resolved as of `1.20-2.6.12`
