### ISSUE TITLE
game font is broken when using supplementaries and sodium together

### ISSUE THREAD

**Issue by akirapink** [MehVahdJukaar/Supplementaries#767]
mod version: supplementaries 1.20-2.5.28
crash log: not needed
minecraft version: 1.20.1
mod loader: quilt loader 0.20.2

- A description of your issue and how to reproduce
- install sodium
- install supplementaries
- launch game
- font will be broken
- like this
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/33667869/8c86220c-c1cf-4ca0-a5fa-1758f9e2bca0)

**Comment by MehVahdJukaar** [comment]
Sodium issue
