### ISSUE TITLE
[Forge 1.19.2] Tattered Written Books have missing textures

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#773]
Using Supplementaries 2.3.24 and Moonlight 2.2.44

Steps to reproduce: 
- Create a tattered written book
- Open it 
-  Missing texture

The screenshot:
<img width="1512" alt="Screen Shot 2023-09-17 at 22 30 19" src="https://github.com/MehVahdJukaar/Supplementaries/assets/50085439/c95ab93d-3ceb-4dde-9a4d-dacc578219a8">

**Comment by pantman687** [comment]
I have the same issue

**Comment by Xelbayria** [comment]
Try the latest version and check if the issue still persists.

**Comment by thelegitdolt** [comment]
Isn't the latest version for 1.19.2 still 2.3.24?

**Comment by Xelbayria** [comment]
ok, so the issue still persists. I'll leave this issue alone. I'll add "investigation" for this issue as it needs some investigation to find the cause.

**Comment by thelegitdolt** [comment]
Is it a mod incompatability? I could do some testing

**Comment by MehVahdJukaar** [comment]
Nah I just forgot when I changed that stuff recently

**Comment by thelegitdolt** [comment]
<img width="847" alt="Screen Shot 2023-10-24 at 16 38 01" src="https://github.com/MehVahdJukaar/Supplementaries/assets/50085439/aaf57108-84ec-473c-9009-cf61fb813894">
not a mod incompat

**Comment by thelegitdolt** [comment]
still occus with only supplementaries + moonlight

**Comment by thelegitdolt** [comment]
fixed in latest
