### ISSUE TITLE
Beautify's "glowstone essence lamp" incompatibility

### ISSUE THREAD

**Issue by jriesen** [MehVahdJukaar/Supplementaries#774]
Minecraft - 1.19.2
Fabric Loader - 0.14.22
Supplementaries - 1.19.2-2.3.24
Beautify: Refabricated - 1.1.1+fabric-1.19.2

I noticed Beautify's glowstone essence lamp would transform into a Supplementaries wall lantern only when placed on walls, but remained normal when placed on the floor or hung from above. Unfortunately, the lamp has special functionality and maintains NBT data - you can add 1, 2 or 3 glowstone into it that varies its brightness, plus it has special animations - which no longer function after being switched out.

The mod's source is available at [here](https://github.com/Suel-ki/Beautify-Refabricated) and this particular NBT tag is `beautify:lamp_jar`. I believe that can be added to the [wall lanterns blacklist](common/src/main/resources/data/supplementaries/tags/blocks/wall_lanterns_blacklist.json) to prevent the replacement? I'm not really much of a modder but I suspect I could augment that blacklist via my own datapack too. Thank you!

**Comment by MehVahdJukaar** [comment]
There's a config or tag for wall lanterns blacklist so that can be added there

**Comment by jriesen** [comment]
I held off closing this because when it was blacklisted I couldn't place them on walls at all... and then I remembered that placing lanterns on walls isn't even available in vanilla, oops.

Adding `beautify` to the blocklist in the config JSON worked great, thank you.
