### ISSUE TITLE
goblet advancement

### ISSUE THREAD

**Issue by Ciznia** [MehVahdJukaar/Supplementaries#777]
add an trigger that is actually possible to get the goblet related advancement thing
like put water in it and drink it

**Comment by MehVahdJukaar** [comment]
hm so its not triggering? its suppsed to trigger when you drink from a goblet

**Comment by Ciznia** [comment]
I don't have succeed to put water in the goblet so I don't know if it's implemented yet

**Comment by Ciznia** [comment]
And without wiki I don't know if i'm doeing well or not

**Comment by Ciznia** [comment]
I have found a way to fill it when place in the world so now how i drink it

**Comment by MehVahdJukaar** [comment]
Just click. Both are super obvious plus wiki explains it all
