### ISSUE TITLE
Crash when trying to attach a faucet to a dirt block

### ISSUE THREAD

**Issue by ChromaPIE** [MehVahdJukaar/Supplementaries#778]
supplementaries-1.20-2.6.1-fabric
Fabric 1.20.1

Log (only related part included): https://mclo.gs/ZroU34N
CR: https://mclo.gs/aX4qWLF

**Comment by MehVahdJukaar** [comment]
Are you using latest moonlgiht? Do fluids in jars work?

**Comment by ChromaPIE** [comment]
Using moonlight 2.8.25. Issue confirmed both in SP and MP.
Trying to shift right click the ground to place tha jar crashes the game too. I burst out a laugh. CR: https://mclo.gs/GxZiGF0

**Comment by MehVahdJukaar** [comment]
Are you on a server? Must be a mod conflict fucking up the data registries

**Comment by ChromaPIE** [comment]
> Are you on a server? Must be a mod conflict fucking up the data registries

And it's reproduced in a newly created SP world too, crash reports above contain the full mod list

**Comment by MehVahdJukaar** [comment]
Does it happen on a new instamc with other mods? Unfortunately crash log doesn't have much info but should be related to data registry files somehow not being loaded

**Comment by ChromaPIE** [comment]
Works just fine with only Fabric API, Moonlight and Supplementaries installed. I can pack a zip containing mods and config folder of my instance and send it for further test if you want.

**Comment by MehVahdJukaar** [comment]
dont realy have time to test a whole modpack. what i can do is do an early check for that specific issue so the game would crash instantly as soon as the cuplrit mod is added. wont help in your case but for anybody else that installs a new one they would know somehtig went bad

**Comment by ChromaPIE** [comment]
okay imma just leave it here then

**Comment by ChromaPIE** [comment]
issue still there but i dont think im familiar with how this report i got looks like: https://mclo.gs/ZeJZYpi

**Comment by MehVahdJukaar** [comment]
yeah some other mod is messing up with datapack registry. I'm using forge api to add those so there should be no issues ideally. This means its some other mod problem

**Comment by MehVahdJukaar** [comment]
what happend in that report is that afrer having this issue here i added more logging and i dumped the content of my datapack registry. what came out on your report is not its content at all but another totally unrelated mod one.

**Comment by ChromaPIE** [comment]
gtceu modern dropped fabric support. terminating the issue
