### ISSUE TITLE
Flags do not work with patterns added by other mods

### ISSUE THREAD

**Issue by Vazkii** [MehVahdJukaar/Supplementaries#78]
![image](https://user-images.githubusercontent.com/1794735/123839926-a0c10400-d905-11eb-9f51-e70cb96d5458.png)

**Comment by MehVahdJukaar** [comment]
I've been slowly adding those texture. Unfortunately some mods just add so many so it will take a while. It's annoying because they all require a custom texture since the scale flag use is different than banners
