### ISSUE TITLE
[Suggestion] Disable Supplementaries' Ash in basalt deltas feature when Phantasmic is installed

### ISSUE THREAD

**Issue by BugmanBugman** [MehVahdJukaar/Supplementaries#780]
I'd like to recommend a feature to disable the ash patches in the basalt deltas feature when the mod [Phantasmic](https://legacy.curseforge.com/minecraft/mc-mods/phantasmic) as it also adds its own ashen basalt blocks in the Nether. To prevent overlap, could there be a disabling of the feature when Phantasmic is detected? (similar to how quark disables a feature with overlap its detected)

**Comment by MehVahdJukaar** [comment]
hm i can look into it but ash would still be doubled so does it make any sense? Feature can still be disabled via configs in older versions and datapacks in newer ones as all worldgen can

**Comment by BugmanBugman** [comment]
I'll ask the devs of phantasmic if they can add the tag so even though there's 2 of them there will still be compat in recipes. I just thought it would be a good feature since people won't have to go into the datapack to do s.

**Comment by MehVahdJukaar** [comment]
i might add forge ash tags since some mods have it

**Comment by BugmanBugman** [comment]
yeah true it's up to you. I just mainly envisioned the quark feature or autodisabling as a quick solution :p
