### ISSUE TITLE
Game crashes when I release my mouse after using the slide bar in the speaker block GUI.

### ISSUE THREAD

**Issue by VoidLifter** [MehVahdJukaar/Supplementaries#785]
Game crashes when I release my mouse after using the slide bar in the speaker block gui.

[crash-2023-09-27_17.05.47-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12740331/crash-2023-09-27_17.05.47-client.txt)

supplementaries-1.20-2.6.3
moonlight-1.20-2.8.31
Running forge 47.2.0, I also got issue on forge 47.1.0
im playing this on a server.

Video:
https://github.com/MehVahdJukaar/Supplementaries/assets/95766705/9acc7bd0-ca23-4109-82c6-993959fd4173

**Comment by MehVahdJukaar** [comment]
yeah idk no clue. this seems impossible to me, that method is not only present in the superclass (provided by vanilla so its not abstract) but knowing this i also added an implementation in there aswell. Must be some mod doing some advanced fuckery to change that method signature or someting

**Comment by VoidLifter** [comment]
Hmm interesting, i would not now what mod would affect a slider.
i did have a mouse tweaks mod, but broplem stayed even if i removed that mod. 

thanks for the attention and help.

do yuo have any ideas?

**Comment by MehVahdJukaar** [comment]
i have no idea. to my knowledge no mods wouldnt even be capable of altering code like that aside of bytecode injection hacks

**Comment by VoidLifter** [comment]
Hmm, well im not using any bytecode injection hacks.
and allt the mods are from the official curseforge.

well thanks for the help tho, lets hope that the isue will reolve itself.

**Comment by MehVahdJukaar** [comment]
Try new version

**Comment by Xelbayria** [comment]
Has the new version solved your issue or does the issue still persist?

**Comment by VoidLifter** [comment]
***Update***

I just tested the issue and it seems to work again,
I am running mod versions:
     supplementaries-1.20-2.6.17 (not latest version)
     moonlight-1.20-2.8.51           (not latest version)
(and other mods)
I did how ever add more mods like Embeddium, im not shure if this helpt solve the issue tho.



Here is a video for the visual proof:
https://github.com/MehVahdJukaar/Supplementaries/assets/95766705/ab547fde-8b53-4f3d-b85d-52f1a4a54d02
