### ISSUE TITLE
[1.20.1 Quilt] latest version crashes

### ISSUE THREAD

**Issue by glittermutt** [MehVahdJukaar/Supplementaries#787]
i have no idea what's happening, but using the older version of supplementaries fixes the issue

[2023-10-01-7.log](https://github.com/MehVahdJukaar/Supplementaries/files/12777375/2023-10-01-7.log)

i have a hunch its because of cit resewn, somehow

**Comment by MehVahdJukaar** [comment]
do you also have a crash log? that ends a bit abruptly

**Comment by mintynoura** [comment]
Seems to be an incompat with sodium. Doesn't show up in crash logs :/
but see https://mclo.gs/wtnErNq

**Comment by MehVahdJukaar** [comment]
Sodium breaks fabric api. If you are using mods you alway need indium

**Comment by mintynoura** [comment]
I do use indium (under the “sodium stuff” folder, so it wasn’t visible in
the log) but i guess i’ll try downgrading it or something

**Comment by mintynoura** [comment]
Seems to be fixed in 2.6.7 :) Thank you sm for the quick work!!
