### ISSUE TITLE
Cannot bottle XP in Better Minecraft OfflineTV edition?

### ISSUE THREAD

**Issue by ddogzog** [MehVahdJukaar/Supplementaries#79]
I have tried with supplementaries jars and standard minecraft bottles. I have turned of the modpacks carry functionality, and disabled most other shift keys in case they were conflicting. I may still be doing something wrong, any advice? 

I suspect that it has something to do with the modpacks enchanting tables being considered as chests and being able to hold an inventory.

**Comment by MehVahdJukaar** [comment]
oh yeah true. Do you know what mod is doing that?

**Comment by ddogzog** [comment]
Easy Magic by Fusz_ is what modifies the enchanting table. I hoped that I could find a standard enchanting table as well, to verify but only one enchanting table is available in the pack. I will check on configs when I can and edit/post that info here.

We have not updated the pack to the latest release yet. We are on V2.

**Comment by ddogzog** [comment]
"[general]
	#Small improvements to make working an enchantment table more convenient.
	"Easy Enchanting" = true
	#Some convenient tweaks for working with anvils.
	"Anvil Tweaks" = true

[anvil_tweaks]
	#Using an iron ingot on a chipped or damaged anvil has a chance to repair it by one stage.
	"Iron Ingot Repairs Anvil" = true
	#Using an iron block on a chipped or damaged anvil repairs it fully.
	"Iron Block Repairs Anvil" = true
	#Chance one out of set value an attempt at repairing an anvil will be successful.
	#Range: > 1
	"Anvil Repair Chance" = 5

[easy_enchanting]
	#Amount of bookshelves required to perform enchantments at the highest level.
	#Range: > 0
	"Enchanting Power" = 15
	#Inventory contents stay in their slot after closing the enchanting screen. Also makes hoppers able to input and output items.
	"Inventory Contents Stay" = true
	#Blocks without a collision shape do not block bookshelves placed behind from counting towards current enchanting power.
	"Lenient Bookshelves" = true
	#When hovering over an enchanting option show the complete outcome on the tooltip instead of only a single enchantment.
	"Show All Enchantments" = false
	#Re-roll possible enchantments in an enchanting table every time an item is placed into the enchanting slot.
	"Re-Roll Enchantments" = true"
	
	-------- I tried disabling this mods changes utilizing these configs but still was not able to shift right click a bottle or jar on the enchanting table to store XP. Could it have something to do with the Carry On mod by Tschipp/Purplicious_Cow_? That made allows you to carry entities by shift right clicking them with an empty hand.

**Comment by MehVahdJukaar** [comment]
So I checked easy magic code and it seems fine, should work with that no problem. I've tried the pack the other day and I have to say that I did notice a hand swing animation that was played every time I clicked on a block like a jar from my mod and that might have been due to carry on. I can't really say because I'm not familiar with the mod, tho it seems really odd that enchantment bottling would not work at all since it uses a simple forge even when one clicks on a table. Have you checked if for some reason xp bottling is disabled in the mod config?

**Comment by ddogzog** [comment]
I can't even find an option to disable xp bottling to be honest. Could you point directly to where I could find that?

**Comment by tal2410** [comment]
Chiming in. I have the same issue in Valhesia 3, which doesn't have Easy Magic but does have Carry On.

**Comment by tal2410** [comment]
> Chiming in. I have the same issue in Valhesia 3, which doesn't have Easy Magic but does have Carry On. I changed the key binding in Carry On but it didn't seem to help.

Nevermind me, I was on an old version. Works fine now, in 1.16.5-0.14.1.

**Comment by MehVahdJukaar** [comment]
it's located in the mod configs in the configs folder , then under tweaks. alternativelly you could installd configured mod and use its mod menu or open it using /supplementaries configured
