### ISSUE TITLE
slingshot crash on 1.19.2 quilt

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#790]
https://paste.atlauncher.com/view/3e628df0-d5af-4b49-a52b-4243d2f28c71

Not really sure what's causing it, or even if you care for the 1.19.2 version

**Comment by MehVahdJukaar** [comment]
Issue from kyori.adventure mod.known one which I thought had been fixed some time ago. Maybe you have really old version

**Comment by netcore10** [comment]
Maybe? I don't remember, i just stumbled on this bug when making a modpack
