### ISSUE TITLE
Supplementaries needs missing Moonlight 2.8.45

### ISSUE THREAD

**Issue by terzag** [MehVahdJukaar/Supplementaries#792]
Hello,
With the latest update to Supplementaries (1.20-2.6.9), I get a Java error message on start saying that it needs Moonlight 1.20-2.8.45 but only 2.8.44 is available, at least on Modrinth.

I'm not sure if this is a typo in the required version (given that both packages seem to have been updated ~13 hours ago) or if there's an update missing on Modrinth.

EDIT: using Fabric version if it matters.

**Comment by Fauli1221** [comment]
from what it seems like someone mistyped 5 instead of 4 since the latest version of Moonlight is 1.20-2.8.44 not 1.20-2.8.45

**Comment by SaviorD22** [comment]
Are they planning to release moonlight 2.8.45 or just fix the mistype?

**Comment by terzag** [comment]
Don't worry, it'll be fixed at some point. Could take a few hours or a few days at most. In the meantime, if you want to play Minecraft, you should be able to downgrade Supplementaries + Moonlight to a previous version (though with the previous one, I had some crashes; I assumed the latest update was released to address them).

I see that Moonlight has just been updated (to 2.8.46) but for Forge only.

**Comment by MehVahdJukaar** [comment]
This has been already addressed 20 hours ago or so

**Comment by terzag** [comment]
20 hours ago?

I don't see any recent update on Modrinth: Supplementaries (Fabric) is still at 1.20-2.6.9, which has a dependency on Moonlight 1.20-2.8.45 but only 1.20-2.8.44 is available. These are the versions that have been uploaded to Modrinth 2 days ago (I assume this matches the 20 hours you're mentioning).

The only recent update I see to Moonlight is the publication of 1.20-2.8.46 a few hours ago but for Forge only, no Fabric version.

**Comment by MehVahdJukaar** [comment]
Main place for mods is curseforge. Modrinth might take more to get uploaded as I mainly worttu about cf
