### ISSUE TITLE
[1.20.1 - Forge] Crash on startup

### ISSUE THREAD

**Issue by PrangellPlays** [MehVahdJukaar/Supplementaries#793]
[crash-2023-10-07_15.55.08-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12838069/crash-2023-10-07_15.55.08-fml.txt)

**Comment by PrangellPlays** [comment]
https://pastebin.com/Cd72WEvZ

**Comment by MehVahdJukaar** [comment]
That's not the latest version. Always report only issues when using latest version
