### ISSUE TITLE
Using a map throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by depiktedcx** [MehVahdJukaar/Supplementaries#796]
- Mod version, MC version and Loader you are using
- Fabric for Minecraft 1.20.1, supplementaries-1.20-2.6.9-fabric, better-end-4.0.10, and related dependencies, I had a total of 146 mods originally and removing either mods allowed maps to work as normal or setting "tinted_blocks_on_maps" in config to false

- Description
- Using the map with the mods standalone is fine, but once both are enabled along with "tinted_blocks_on_maps" in config it causes net.mehvahdjukaar.supplementaries.common.misc.ColoredMapHandler$Data.getEntry(net.mehvahdjukaar.supplementaries.common.misc.ColoredMapHandler$Vec2b) to return null
- Have a blank map
- Right-click to fill
- Crash

[crash-2023-10-08_18.50.29-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/12839889/crash-2023-10-08_18.50.29-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12839894/latest.log)

**Comment by MehVahdJukaar** [comment]
Try new version
