### ISSUE TITLE
Flute recording? (Fabric)

### ISSUE THREAD

**Issue by RiddleMeNani** [MehVahdJukaar/Supplementaries#798]
Hello, this is more of a Question than a suggestion, but I was trying to perform some flute recordings on a fabric server im in (MC 1.20.1, Mod version 2.5.28) but it says that recordings are not yet implemented.

Is this in general, that fabric does not yet have compatibility with the command or is it something to do with the Server itself? like the option isnt enabled or something. I was trying to add the full version of revenge cuz i like to do a lil bit of funny jumps on my friends n' stuff, but was struggling a bit to even attempt to do so manually, and now even more so with this revelation...

Thank you for your time :D

**Comment by MehVahdJukaar** [comment]
Yeah it relies on forge code. Not a big deal as one can just record on forge once and make their datapack like that

**Comment by RiddleMeNani** [comment]
> Yeah it relies on forge code. Not a big deal as one can just record on forge once and make their datapack like that

Ahhhhhh, I see I see. that makes sense  PFFF TY sm for letting me know lol
