### ISSUE TITLE
[suggestion] use a block tag for bellows compatibility

### ISSUE THREAD

**Issue by erisdev** [MehVahdJukaar/Supplementaries#8]
Instead of (or maybe in addition to) checking that the tile entity inherits from minecraft's furnace block, it would make sense to have a tag—might i suggest `supplementaries:furnace`—that marks a block as one that the bellows should speed up.

**Comment by MehVahdJukaar** [comment]
I can do both for max compatibility. That will also mean that the tag will be left empty for mod pack makers to add stuff to

**Comment by erisdev** [comment]
Yeah, that sounds ideal, thank you.

**Comment by MehVahdJukaar** [comment]
wouldn't it be better if I were to add the same functionality to the mod config? I thought that way it would be easier to use

**Comment by erisdev** [comment]
I suppose that works too, but a tag lets other mods support the bellows without having to inherit from the vanilla furnace. This is a pretty common use case for tags, actually.

**Comment by MehVahdJukaar** [comment]
I guess that makes sense, I'll add it then. I haven't really learned how to properly use tags, that's why I was asking.

**Comment by erisdev** [comment]
Yeah, tags are really useful for both mod compatibility and configuration. They're usually used for recipes and such, but they can be useful in other ways.

To give specific examples, Create has a couple of tags that are used by Farmer's Delight to make its stuff behave in certain ways when Create is also installed:

- `create:upright_on_belt` makes items stand up on conveyor belts rather than lying flat; Farmer's Delight adds this to its milk bottle so it stands up just like the vanilla water bottle.
- `create:fan_heater` makes a block usable as a heat source for create's bulk cooking recipes, and Farmer's Delight adds this one to its stove block.

I hope that helps!

**Comment by MehVahdJukaar** [comment]
it does, thanks. At the end I've added both a config and a tag to have the best of both words. I would have added a tag only if there was a vanilla or forge "furnace" tag. they have one for campfires but not one for those, how strange

**Comment by erisdev** [comment]
Awesome, thank you
