### ISSUE TITLE
Book stack crashes game

### ISSUE THREAD

**Issue by The9darknight** [MehVahdJukaar/Supplementaries#800]
Version 1.20-2.6.12, latest version of forge(47.2.1) and moonlight(2.8.48) as well as well

All I did was place down a book, and now it crashes every time I open the world

(Apologies if I am submitting this incorrectly, this is my first bug report for a mod)
Log:
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/12886950/latest.log)

**Comment by MehVahdJukaar** [comment]
turn off book glint for now
