### ISSUE TITLE
Error with last moonlight & Supplementaries

### ISSUE THREAD

**Issue by mindryder** [MehVahdJukaar/Supplementaries#801]
- Mod version, MC version and Loader you are using

supplementaries-1.20-2.6.12-fabric + moonlight-1.20-2.8.48-fabric | 1.20.1 FABRIC

- A description of your issue and how to reproduce
Some areas on server players get this error, previous versions works fine.

- If applicable, add screenshots to help explain your problem.

![javaw_kTcXvNGbS0](https://github.com/MehVahdJukaar/Supplementaries/assets/66848160/6c8b9e95-7955-49ed-a013-88a3fdf36853)

**Comment by MehVahdJukaar** [comment]
send latest.log

**Comment by donnie-danko** [comment]
Hey I'm still getting this issue after the moonlight lib update. Client log:
https://pastebin.com/aaDdyFAE

**Comment by donnie-danko** [comment]
Hey I'm still getting the same issue as OP after the moonlight lib update. forge version, most recent for both. Client log: https://pastebin.com/yNAp1msS

**Comment by ArmouredDrood** [comment]
my player had issue occur after picking up a bastion map

**Comment by donnie-danko** [comment]
most recent update seemed to have fixed it :)
