### ISSUE TITLE
1.20.1 Placable books have no textures

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#808]
Overall works but Placing signed Books is missing its Textures
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/181536/5072930d-e141-4a79-b29e-8db48b3f0423)

1.20.1 fabric, don't really have a log because it doesn't ping anything

**Comment by Xelbayria** [comment]
Please use "Report Bug" template

**Comment by MehVahdJukaar** [comment]
Forgot to add their model
