### ISSUE TITLE
[🐞]: 1.19.2 Fabric Server Can't handle Adventure maps from Cartographer. 

### ISSUE THREAD

**Issue by szabiszekely** [MehVahdJukaar/Supplementaries#810]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [x] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit

### Version-Loader

1.19.2-fabric

### Supplementaries Version

supplementaries-1.19.2-2.3.24-fabric

### Moonlight Lib Version

moonlight-1.19.2-2.2.44-fabric

### Issue Detail

Hi, me and my friends had this issue recently when a cartographer reaches level 2 in his job in theory an adventure map should be sold, however every time he reaches the level and I exit the menu the whole server crashes. We tried to change it in the .jason files because I read that it is quite configurable mod. So my friend did that, however it still doesn't let me through the second level despite turning it off. 

We theorized that because we have better xyz structure's mod it probably can't find anything and just idk breaks. It is a big problem for us that cartographer does not work manly because we have and atlas mod that requires us to add maps to it. (just tiny explanation why its important)

I come here for help to get maybe an answer or ideas where to reach next or what to do next.

**Comment by MehVahdJukaar** [comment]
you need to include a latest.log

**Comment by szabiszekely** [comment]
My friend who runs the server said he saw a log, but when we went to check it didn't appear. So sadly we cannot provide any logs.
However I asked him to record it and send it to me. Here  is that video:

 https://youtu.be/1JVfqvN46QM

**Comment by szabiszekely** [comment]
hi we found out what can cause the problem. It was not supplementary problem! It was a bug between numismatic overhaul and Yung's Better Ocean Monuments. If someone find this info and come here again. Here is the fix and more info.
https://github.com/wisp-forest/numismatic-overhaul/issues/93

For the moderators we are thanking for the fast response and wishing a wonderful day/night.
