### ISSUE TITLE
[🐞]: Caging anything on server causes client to crash?

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Supplementaries#812]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below

### Version-Loader

1.20.1-fabric

### Supplementaries Version

latest

### Moonlight Lib Version

latest

### Issue Detail

I've been going through the paces, disabling mods and such, it works client side, but the moment i cage something on a server, client crashes due to something involving  the inventory. Not sure if it is this mod, but it's only when something is caged and it's at least a starting point.

Can you pinpoint the area that might be affecting this?

### Optional Attachment

https://mclo.gs/0S4Z5TU

**Comment by MehVahdJukaar** [comment]
that doesnt seem to be the log from when it crashed. no crash is reported there

**Comment by netcore10** [comment]
odd, i guess it just CTD. Guess i need to look else where, at least i can disable cages for now. I'll reopen if it turns out to be cages somehow
