### ISSUE TITLE
[🐞]: [Compatibility] Placing Book and Quill crashes game when running Indium

### ISSUE THREAD

**Issue by GJdude** [MehVahdJukaar/Supplementaries#818]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.17-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.53-fabric

### Issue Detail

Yes, this is connected to Lithium (And thus loosely to Sodium) but only occurs with Lithium installed, so I thought it was worth pointing this crash out anyways.

Lithium version used is lithium-fabric-mc1.20.1-0.11.2

When placing a book and quill, the game will crash. The world can be reloaded, but the chunk the book is placed in won't render, though the book can be safely destroyed and chunks refreshed.

Not quite a showstopping bug, but one that would be nice to get looked into at some point so that someone placing a book doesn't accidentally crash my server in the future.

If the issue appears to be something that can only be resolved on Lithium's end I'll consider referring it over to the issues section there.

### Optional Attachment

[crash-2023-10-29_14.21.13-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13198318/crash-2023-10-29_14.21.13-client.txt)

**Comment by MehVahdJukaar** [comment]
indium issue. Someboy is doing an unsafe cast somewhere

**Comment by GJdude** [comment]
Confirmed that this is a Sodium bug, fixed in 0.5+, so for those who can use that it's already sorted.
