### ISSUE TITLE
[🐞]: [1.20.1] [Fabric] Crash upon having map in inventory

### ISSUE THREAD

**Issue by WildFyr16** [MehVahdJukaar/Supplementaries#822]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] Do NOT report an issue related to Indium/Sodium/Optifine or other rendering mods unless you have contacted them first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.18-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.53-fabric

### Issue Detail

Maps will immediately crash the game if in the players inventory (even if not held in player's hand) `Critical injection failure: @WrapOperation annotation on supplementaries_IFupdateColoredTexture could not find any targets matching '@MixinSquared:Handler[mixin='fabric.net.raphimc.immediatelyfast.injection.mixins.map_atlas_generation.MixinMapRenderer_MapTexture'` with this crash error. The only fix I had was to edit my player data with NBTedit and delete the map from my inventory, trying to rejoin the world would crash immediately.

### Optional Attachment

https://pastebin.com/NipqFidK

**Comment by MehVahdJukaar** [comment]
use previous version. that version was achieved

**Comment by WildFyr16** [comment]
Just tested this on v1.20-2.6.19 and this still happens.

**Comment by WildFyr16** [comment]
Actually looks like there is a new v1.20-2.6.19- version, will try this one and see what it does.

**Comment by WildFyr16** [comment]
https://github.com/MehVahdJukaar/TrickOrTreatMod/issues/45#issue-1955814863
Using the latest version causes some conflicts with Haunted Harvest. Not sure if it is them or this mod but considering it only happens when updating this mod might have something to do with the update.

**Comment by MehVahdJukaar** [comment]
That's another issue that was already there. This issue here has been fixed

**Comment by WildFyr16** [comment]
Went into a testing world on the latest version and found a buried treasure map in a new, unloaded chunk. And still got a crash when having it enter my inventory from the chest. Here is the crash log, https://pastebin.com/0ZCXKgWw .

For now will just not use maps. Don't use them that often, so not a big deal.
