### ISSUE TITLE
Add a toggle for the custom paintings

### ISSUE THREAD

**Issue by lumiscosity** [MehVahdJukaar/Supplementaries#823]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Description:
It would be nice to have a way to disable the custom paintings added by the mod.

## Why should we implement the feature?
Most other features in the mod are already toggleable, so why not this one?

**Comment by MehVahdJukaar** [comment]
All paintings that can be placed appear in a tag. If removed from it they worn be placed

**Comment by lumiscosity** [comment]
ah, i wasn't aware of such a feature. this does fulfill this, so should i close the issue, or do you plan on adding a toggle regardless?
