### ISSUE TITLE
[🐞]: Game crash when putting Buried Treasure Map in inventory

### ISSUE THREAD

**Issue by AaronKasai** [MehVahdJukaar/Supplementaries#824]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] Do NOT report an issue related to Indium/Sodium/Optifine or other rendering mods unless you have contacted them first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.19

### Moonlight Lib Version

moonlight-1.20-2.8.56

### Issue Detail

When putting a Buried Treasure Map in inventory (I had taken it from a ship wreck) game crashes.
Every time you try to open the world from that point forward, game crashes.

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13265280/latest.log)

### To Produce

Unsure if this will be the same for everyone, but my specific case is at:
Seed: -4771647469819543247
X,Y,Z: 889, 55, -195
If you want my treasure map location.

**Comment by MehVahdJukaar** [comment]
use new mod version
