### ISSUE TITLE
Cannot draw on blackboards with plain white chalk from Chalk mod

### ISSUE THREAD

**Issue by idle-z** [MehVahdJukaar/Supplementaries#825]
https://github.com/MehVahdJukaar/Supplementaries/blob/d0e47cd470e6e6d4784818b5c8a9547e2d1e1f5a/common/src/main/resources/data/supplementaries/tags/items/blackboard_white.json#L7

The chalk mod, at least on the version I'm using, uses id `chalk:chalk` for white chalk, which isn't included in the tag defined here.

**Comment by MehVahdJukaar** [comment]
fixed
