### ISSUE TITLE
[🐞]: Client-Server Block ID Desync

### ISSUE THREAD

**Issue by fruitmeister101** [MehVahdJukaar/Supplementaries#826]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] Do NOT report an issue related to Indium/Sodium/Optifine or other rendering mods unless you have contacted them first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.20-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.57-fabric

### Issue Detail

The blocks provided my this mod that are placed down (books, goblets, cog blocks, etc.) are server-client desynced. Cogs look like bamboo punji sticks waterlogged, but still function as cogs server-side. 
This didn't happen pre-update to the most recent version, and does happen now, and the only thing that changed was Moonlight and Sup's updates.
Yes, I am using many other mods, but I believe I can reasonably rule out any other mods' shenanigans.

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/79765028/5f5ec1b8-1561-43c2-bef5-286f0b200e93)
Attached image is a drawer of mending books with placed books all around. They still function as book piles even being able to pick them back up, but look like lit gunpowder.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/79765028/c8d7753f-58f3-47d2-afdb-ca634a5517fa)
Attached image is a goblet... or what once was... I guess I'm going to drink milk from my Waterlogged roped post now...

Since the desync doesn't cause anything but collision-box and visual disturbances, I'm not concerned (especially because making stuff look nice isn't my speciallity to begin with), but this should be addressed nonetheless.

Keep up the good work! I await your response.
=)

### To Produce

Join server with Sup, place block, and poof, it's wrong.
At least two other people in my server have complained with (not similar)Exact results (desynced the same way)

If your own testing proves fruitless, I will do more rigorous testing.

**Comment by MehVahdJukaar** [comment]
such desyncs are caused by client server mod desync. They have different versions

**Comment by fruitmeister101** [comment]
I feel dumb, but it was the Fabric Loader version...
The one thing I always forget to Update...

Keep up the great work!
