### ISSUE TITLE
Config Request: Turn off horizontal ropes

### ISSUE THREAD

**Issue by svew** [MehVahdJukaar/Supplementaries#830]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Description:

Add a config option to turn off the ability to extend ropes horizontally.

This is separate from the ability to place ropes next to walls, which leads to the following combinations:

- Ropes can be connected to walls, and extend horizontally
- Ropes can be connected to walls, but cannot be extended horizontally any further
- Ropes can only be connected to ceilings, but can extend horizontally after (not sure why you'd want this)
- Ropes can only be connected to ceilings, and can only extend downwards

## Why should we implement the feature?

I find that most of the time, when I'm placing horizontal ropes, I'm doing it accidentally, in a situation where it doesn't make sense (e.g. I'm repeatedly placing ropes downwards to go down a cave shaft, but when it reaches the end, it starts placing ropes sideways).

It's cool to be able to span ropes horizontally to navigate a chasm, but actually doing so is way more dangerous than just using blocks in your inventory, and doesn't feel realistic (or at least it feels way less realistic in comparison), so its primary use case is not useful.

**Comment by MehVahdJukaar** [comment]
added. kind of

**Comment by svew** [comment]
@MehVahdJukaar what is the config option for this? I can't seem to find it
