### ISSUE TITLE
option to make bombs give damage to the player

### ISSUE THREAD

**Issue by peow** [MehVahdJukaar/Supplementaries#831]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Why should we implement the feature?

i configured that Slingshots can throw bombs, and it was a lot of fun, but it becomes extremely unfair due to the fact that you don't take damage from the bombs themselves, for example in PvP you could aim at the ground and throw bombs, and this would only cause damage to the opponent, and a bomb does more damage than a Netherite sword with Sharpness 5
![2023-11-11_01 05 14](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/87fbbbba-5867-4d30-9dc4-e539e6f09873)

pls make an update to 1.20.1 if you are going to add this suggestion

**Comment by MehVahdJukaar** [comment]
hm but thats already how it works

**Comment by MehVahdJukaar** [comment]
unless you are in peaceful. thats a vanila mechanic

**Comment by MehVahdJukaar** [comment]
Are you using latest mod version? Some mod must be interfering
