### ISSUE TITLE
[🐞]: Wrench can be used to rotate Command Blocks on Survival mode

### ISSUE THREAD

**Issue by peow** [MehVahdJukaar/Supplementaries#835]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries v1.20-2.6.24

### Moonlight Lib Version

moonlight v1.20-2.8.60

### Issue Detail

if you are in creative mode and use the Wrench on a Command Block it rotates and that is expected, however when you are in Survival mode the Command Block also rotates, and this doesnt make sense since in Survival you cant even access much less break a Command Block

with this bug you can rotate the Command Block, Chain Command Block and the Repeating Command Block

context of this pic below: 1 normal command block + 2 chain command blocks
i put /say command inside them

@ 1 : normal command block
@ 2: first chain command block
@ 3: second chain command block
![2023-11-12_23 16 06](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/064e285a-1d28-4756-b702-20304d4d5120)

and what's the problem with being able to rotate? well, a Chain Command Block needs to be pointed in the right direction to energize the other Chain Command Block that is above it, I can imagine situations in which the server administrator places command blocks in one place, and someone goes there and changes the command blocks, rendering them unusable

*using the Wrench to rotate the 2 chain command block
![2023-11-12_23 16 22](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/7dcebb68-4111-4416-ba27-9e0ca8e4eb6a)
![2023-11-12_23 16 24](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/76789e86-ed3b-4da7-865c-2ccea79cc839)
![2023-11-12_23 16 28](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/c419bdb5-d148-49c6-bc72-57e5915bdf76)

then, when i press the button, in chat only appears "@ 1 @ 2", because the first chain command block has been rotated
![2023-11-12_23 16 45](https://github.com/MehVahdJukaar/Supplementaries/assets/105888751/3faa2a37-e356-4958-9efa-b7bcd921f61c)

im only using fabric 1.20.1, moonlight and supplementaries

### To Produce

/give @p minecraft:command_block
/give @p minecraft:chain_command_block
/give @p minecraft:repeating_command_block

**Comment by MehVahdJukaar** [comment]
fixd

**Comment by MehVahdJukaar** [comment]
nevermind i forgot those other 2 command blocks
