### ISSUE TITLE
[🐞]: Missing side textures on raked gravel

### ISSUE THREAD

**Issue by AnOutdatedMind** [MehVahdJukaar/Supplementaries#836]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [x] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-forge

### Supplementaries Version

supplementaries-1.19.2-2.4.10

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-forge

### Issue Detail

Forge version: 43.3.5

The sides of the raked gravel block has missing textures (black-purple checkerboard).

### To Produce

Error is reproducible with only moonlight and supplementaries installed.

**Comment by MehVahdJukaar** [comment]
do you have a textur pack that alters famrland model? gravel is a child of farmland model

**Comment by AnOutdatedMind** [comment]
I feel so dumb right now, the issue was indeed caused by one of the resource packs I use, specifically Blockstates+. It alters farmland to show intermediate levels of moisture.
