### ISSUE TITLE
[🐞]: Placeable book options are broken

### ISSUE THREAD

**Issue by lumiscosity** [MehVahdJukaar/Supplementaries#837]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.6.26

### Moonlight Lib Version

1.20-2.8.60

### Issue Detail

In the comon config, there are two toggles named "Enable". Judging by the latter having a unique description, it's meant to be a toggle for the feature where books give power to enchanting tables. The state of the former "Enable" option is always set to the state of the latter "Enable" option.

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/26834471/0ea0e8e3-1be7-498a-8593-3dbd9a6b5c3b)

### To Produce

1. Enter the common config.
2. Try changing the options for placed books.

**Comment by MehVahdJukaar** [comment]
should be fixed
