### ISSUE TITLE
[🐞]: weird bug with Wrench and a texturepack 

### ISSUE THREAD

**Issue by peow** [MehVahdJukaar/Supplementaries#838]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries v1.20-2.6.28

### Moonlight Lib Version

moonlight v1.20-2.8.60

### Issue Detail

im using a meme texture that puts an overlay and music at random speeds, sometimes faster or slower, when you use Spyglass, but the same sound is playing when i use Wrench,  and i really have no idea why this is happening, in this video i show the bug, where i download it, and whats in the texture files

https://www.youtube.com/watch?v=GQzWHxFBSzk

name of the texture: VanillaTweaks_r238273 WHAT
link where i downloaded: https://vanillatweaks.net/picker/resource-packs/

*im only using moonlight, fabric api and supplementaries newest version

**Comment by MehVahdJukaar** [comment]
You can resolve by editing the sound wrench use with a texture pack
