### ISSUE TITLE
Client crash when right-clicking water jars with Tea Kettle

### ISSUE THREAD

**Issue by Carloslionheart** [MehVahdJukaar/Supplementaries#84]
Whenever I right click a jar full of water with a kettle from the [Tea Kettle](https://www.curseforge.com/minecraft/mc-mods/tea-kettle) mod, the client crashes.

This didn't happen in the previous version of the mod I was using, which is why Im reporting it here.

Version of Tea Kettle: 0.3.2.0
Version of Supplementaries where issue is present: 0.14.4f
Version of Supplementaries where issue is not present: 0.14.2

**Crash log:**
[crash-2021-07-13_11.33.12-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/6810527/crash-2021-07-13_11.33.12-client.txt)

**Comment by MehVahdJukaar** [comment]
yes they used some class from my mod and it's not compatible anymore since the latest update since I improved alot of code and moved it to my library too. You should report this to their page

**Comment by a-soulspark** [comment]
yeah, I'll be sure to take a look at it 👍

**Comment by MehVahdJukaar** [comment]
awesome. I'll close this
