### ISSUE TITLE
Crash after pillager uses crossbow[🐞]: 

### ISSUE THREAD

**Issue by MiniRaptor** [MehVahdJukaar/Supplementaries#841]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [ ] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [ ] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [ ] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.29-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.64-fabric

### Issue Detail

When a pillager loads an arrow into a crossbow, the game crashes immediately after that

### Optional Attachment

[crash-2023-11-17_19.38.40-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13394557/crash-2023-11-17_19.38.40-server.txt)

### To Produce

When a pillager loads an arrow into a crossbow, the game crashes immediately after that

**Comment by MehVahdJukaar** [comment]
use 2.6.30
