### ISSUE TITLE
[🐞]: shrinkquiver? Crashes the game.

### ISSUE THREAD

**Issue by coldReactive** [MehVahdJukaar/Supplementaries#845]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.6.29

### Moonlight Lib Version

1.20-2.8.62

### Issue Detail

When a villager (from another mod) killed an enemy at the same time a vanilla iron golem attacked that enemy (it was a vanilla zombie) the game crashed. A user on the modpack server stated it had to do with supplementaries and "shrinkquiverarrow."

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13445148/latest.log)
[crash-2023-11-22_17.55.56-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13445150/crash-2023-11-22_17.55.56-server.txt)

### To Produce

Using MMC2 v1 (Medieval MC Fabric) have a warrior villager kill an enemy. This was done in a jungle biome's jungle village where a few of supplementary items were.

**Comment by MehVahdJukaar** [comment]
you are not using latest version

**Comment by coldReactive** [comment]
So far no crashes, had the villagers kill a bunch of enemies. So marking fixed for now.
