### ISSUE TITLE
[🐞]: Rendering issues of Distant Horizon LOD

### ISSUE THREAD

**Issue by Artwind2** [MehVahdJukaar/Supplementaries#847]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.31-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.65-fabric

### Issue Detail

When using Distant Horizon mod, the non-full blocks (torches, stairs, fences and more) get their LOD block to be black instead of their color. It's especially visible in villages, and in detailed structures added by other mods.

(I had the issue with Supplementaries and Distant Horizon only mods. And the issue's gone without supplementaries and the rest of my 150+ mod list.)

![black LOD](https://github.com/MehVahdJukaar/Supplementaries/assets/38019992/bbca50a4-2bf9-42ec-a932-3ffc8289bb21)
LOD appears black with Supplementaries
![normal behaviour](https://github.com/MehVahdJukaar/Supplementaries/assets/38019992/093f71d2-fcb9-4743-8f83-71bcdf6bbd0d)
Normal behaviour, uses block color for the LOD.

I tried to disable all the options of Supplementaries to see if it resolved the issue but it's still there, I also open a ticket on Distant Horizon mod.

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13449172/latest.log)

### To Produce

Use Distant Horizon and Supplementaries together

**Comment by MehVahdJukaar** [comment]
no idea why this would happen. supplementaries doesnt touch other blocks models nor anything related to rendering. Did you report to distant orizons?

**Comment by Artwind2** [comment]
Yes I also posted an issue to Distant Horizon

**Comment by Artwind2** [comment]
The issue look solved with the recent updates of both mods
