### ISSUE TITLE
Config option for Soap block conversion

### ISSUE THREAD

**Issue by Darkosto** [MehVahdJukaar/Supplementaries#848]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

### Details

Hello!

I am currently working on a new modpack for 1.20.1 and was hoping you would consider a new feature involving the Soap item. Currently, when using Soap on a colored block it will convert it to White. Can we have a config option to determine what block it becomes when using Soap? The project I'm making right now has a set of "Colorless" blocks that would benefit from Soap to clear any color.

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/10309699/bb1b8e43-2d42-4916-9c37-e18685dedd5c)

Please let me know if I can provide any more info. Thank you!
Darkosto

**Comment by MehVahdJukaar** [comment]
You can technically do this with the new configs
