### ISSUE TITLE
Payload to large exception 0.14.4*, 0.14.3

### ISSUE THREAD

**Issue by CKY-** [MehVahdJukaar/Supplementaries#85]
Minecraft version: 1.16.5
Forge Version: 36.1.32
Supplementaries version: 0.14.4f
Selene: 1.3 and 1.4
When updating to supplementaries-1.16.5-0.14.4f.jar and supplementaries-1.16.5-0.14.4c.jar  and  supplementaries-1.16.5-0.14.3.jar from supplementaries-1.16.5-0.14.2.jar
On server environments 

there is payload to large exception 

![image](https://user-images.githubusercontent.com/8982158/125675190-43f97baf-2dc2-4ba4-9233-6d79b247044a.png)

This is not visible on single player worlds 

[OverKillSMP version 0.0.40](https://www.curseforge.com/minecraft/modpacks/overkill-smp/files/3388474)

List of Mods, 

Ropes Mod! (by TheGoldCrayon)
Tool Belt (by gigaherz)
Camera Mod (by henkelmax)
Spartan Weaponry (by ObliviousSpartan)
Botania (by Vazkii)
Compressium (by DinnerBeef)
Waystones (by BlayTheNinth)
Cloth Config API (Forge) (by shedaniel)
Lighting Wand 🌟 (by Snownee_)
Additional Banners (by DarkhaxDev)
More Red (by Commoble)
Save My Stronghold! (Forge) (by YUNGNICKYOUNG)
Flux Networks (by sonar_sonic)
Reliquary v1.3 (by P3pp3rF1y)
XNet Gases (by Terrails)
Ding (by ohaiiChun)
Integrated Tunnels (by kroeser)
The Undergarden (by Quek04)
RSInfinityBooster (by hexeptiondev)
JEI Integration (by SnowShock35)
Mystical Customization (by BlakeBr0)
Sophisticated Backpacks (by P3pp3rF1y)
Bigger Reactors (by RogueLogix)
Valhelsia Tweaks (by ValhelsiaTeam)
Client Tweaks (by BlayTheNinth)
Water Strainer (by Ruuubi)
Polymorph (Forge) (by TheIllusiveC4)
Mantle (by mDiyo)
Modular Routers (by desht_08)
Miner's Helmet (by ModdingLegacy)
Apotheosis (by Shadows_of_Fire)
Valhelsia Structures (by ValhelsiaTeam)
Integrated NBT (by scleox)
Additional Bars - Biomes O' Plenty addon (by CodenameRevy)
Bountiful (by ejektaflex)
JEITweaker (by Jaredlll08)
FTB Quests (Forge) (by FTB)
Wither Skeleton Tweaks (by Shadows_of_Fire)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
FTB Library (Forge) (by FTB)
FTB Teams (Forge) (by FTB)
Solar Flux Reborn (by Zeitheron)
ATO - All the Ores (by ATMTeam)
Overloaded Armor Bar (by tfarecnim)
Rope Bridge (by lordcazsius)
Structure Gel API (by ModdingLegacy)
AttributeFix (by DarkhaxDev)
Common Capabilities (by kroeser)
AutoRegLib (by Vazkii)
CraftTweaker (by Jaredlll08)
Platforms (by ShetiPhian)
KubeJS (Forge) (by LatvianModder)
Immersive Petroleum (by Flaxbeard)
Bag of Yurting (by Commoble)
MythicBotany (by noeppinoeppi)
FastFurnace (by Shadows_of_Fire)
Macaw's Roofs (by sketch_macaw)
Citadel (by alex1the1666)
Controlling (by Jaredlll08)
Thermal Innovation (by TeamCoFH)
Corail Tombstone (by Corail_31)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Abnormals Core (by TeamAbnormals)
Item Collectors (by SuperMartijn642)
Restrictions (by McJty)
Crafting Station (by tfarecnim)
Advanced Chimneys (by EnderLanky)
ForgeEndertech (by EnderLanky)
Advanced Hook Launchers (by EnderLanky)
ExtraStorage (by 3divad99)
Trash Cans (by SuperMartijn642)
Occultism (by kli_kli)
Additional Enchanted Miner (by Kotori316)
SmoothFocus (by notunfound)
Tiny Redstone (by Danny_and_Son)
Cyclic (by Lothrazar)
Dungeons Plus (by ModdingLegacy)
ShetiPhianCore (by ShetiPhian)
Wizard Staff (by vemerion)
Macaw's Paintings (by sketch_macaw)
Spawner Bug Fix (by MacTso)
Engineer's Tools (by wilechaote)
TOP Addons (by DrManganese)
Resourceful Bees (by epic_oreo)
JEI Professions (by pau101)
Item Filters (Forge) (by LatvianModder)
Cooking for Blockheads (by BlayTheNinth)
FlickerFix (by MutantGumdrop)
Wormhole (Portals) (by SuperMartijn642)
Biomes O' Plenty (by Forstride)
AppliedEnergisticsTweaker (by Jaredlll08)
'Dustrial Decor (by BlueDuckYT)
Mekanism Additions (by bradyaidanc)
Titanium (by Buuz135)
Simple Farming (by enemeez1)
Blood Magic (by WayofTime)
Integrated Crafting (by kroeser)
Create Plus (by Robocraft999)
Valhelsia Core (by ValhelsiaTeam)
Botany Trees (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
CompactStorage (by tobyystrong)
FerriteCore (Forge) (by malte0811)
Pretty Pipes (by Ellpeck)
Toast Control (by Shadows_of_Fire)
RFTools Builder (by McJty)
Scuba Gear (by ModdingLegacy)
Allthemodium (by ATMTeam)
Extended Caves (by Polyvalord)
Extreme sound muffler (Forge) (by LeoBeliik)
NoMoWanderer (by TheJDill)
Scalable Cat's Force (by Kotori316)
Tinkers Construct (by mDiyo)
LibX (by noeppinoeppi)
The Outer End (by BlueDuckYT)
Bedspreads (Forge) (by TheIllusiveC4)
PneumaticCraft: Repressurized (by desht_08)
Akashic Tome (by Vazkii)
Thermal Locomotion (by TeamCoFH)
UwUtilities (by UItramega)
Ma Enchants (by Maciej916)
Tome of Blood (by ToxicMintTea)
Phosphophyllite (by RogueLogix)
RFTools Storage (by McJty)
Rats: Ratlantis (by alex1the1666)
Applied Energistics 2 (by AlgorithmX2)
Portable Stonecutter (by weirdbrackets)
Additional Ender Items (by Hidoni)
Curious Jetpacks (by tfarecnim)
Thermal Cultivation (by TeamCoFH)
Nature's Compass (by Chaosyr)
EnderTanks (by ShetiPhian)
No Villager Death Messages (by MutantGumdrop)
Cyclops Core (by kroeser)
Macaw's Fences and Walls (by sketch_macaw)
Archer's Paradox (by TeamCoFH)
CodeChicken Lib 1.8.+ (by covers1624)
Waddles (by Girafi)
KubeJS Create (by LatvianModder)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Astral Sorcery (by HellFirePvP)
Forbidden and Arcanus (by cesar_zorak)
Pipez (by henkelmax)
Storage Drawers (by Texelsaur)
Mystical Agradditions (by BlakeBr0)
It's the little things (by Zlepper)
/tank/null (by tfarecnim)
Time in a bottle standalone (by haoict)
EmbellishCraft: Biomes O'Plenty Addon (by Mapper)
KubeJS Blood Magic (by LatvianModder)
SuperMartijn642's Config Lib (by SuperMartijn642)
Just Enough Resources (JER) (by way2muchnoise)
Balanced Enchanting (by tfarecnim)
Potions Master (by thevortexFoxTopia)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Curious Elytra (Forge) (by TheIllusiveC4)
Easy Piglins (by henkelmax)
Sound Device Options (by ichttt)
Cosmetic Armor Reworked (by LainMI)
Structurize (by H3lay)
EnderChests (by ShetiPhian)
CC: Tweaked (by SquidDev)
Curios API (Forge) (by TheIllusiveC4)
Cartographer (by thevortexFoxTopia)
Kotlin for Forge (by thedarkcolour)
Angel Ring (by DenisMasterHerobrine)
Tiny Chests (by liskoslayer63)
DataPack Anvil (by Sirttas)
Woot (by Ipsis)
Macaw's Windows (by sketch_macaw)
Farming for Blockheads (by BlayTheNinth)
Ender Storage 1.8.+ (by covers1624)
RFTools Control (by McJty)
Configurable Cane (by gigaherz)
Entangled (by SuperMartijn642)
Advanced Peripherals (by Sr_endi)
RecipeBuffers (by malte0811)
Simple Voice Chat (by henkelmax)
Lollipop (by owmii)
Global XP (by bl4ckscor3)
Nature's Aura (by Ellpeck)
Farmer's Delight Cookbook Addon [Discontinued] (by dalumma)
GeckoLib (by ThanosGecko)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Dank Storage (by tfarecnim)
Quark Oddities (by Vazkii)
Sit (by bl4ckscor3)
KubeJS Thermal (by LatvianModder)
Shutup Experimental Settings! (by Corgi_Taco)
The One Probe (by McJty)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Thermal Foundation (by TeamCoFH)
Spice of Life: Carrot Edition (by lordcazsius)
Emojiful (by Buuz135)
Silent Lib (silentlib) (by SilentChaos512)
Refined Storage: Requestify (by Buuz135)
Ice and Fire: Dragons (by alex1the1666)
Creative Apiary (by UItramega)
Decorative Blocks (by stohun)
Integrated Dynamics (by kroeser)
Bed Benefits (by DarkhaxDev)
OpenBlocks Elevator (by vsngarcia)
Easy Villagers (by henkelmax)
Ranged Pumps (by raoulvdberge)
ConnectedTexturesMod (by tterrag1098)
Repair Chests (by Dyonovan)
Environmental Core (by ValkyrieofNight)
Environmental Energy (by ValkyrieofNight)
XNet (by McJty)
Decorative Blocks modded compat (by Evo_934)
Bookshelf (by DarkhaxDev)
KubeJS Immersive Engineering (by LatvianModder)
Morph-o-Tool (by Vazkii)
RFTools Utility (by McJty)
bpm (by adoozyz)
Lightest Lamps (by Prefex89)
Industrial Foregoing (by Buuz135)
Culinary Construct (by TheIllusiveC4)
Gauges and Switches (by wilechaote)
Mob Grinding Utils (by vadis365)
AI Improvements (by QueenOfMissiles)
Refined Storage (by raoulvdberge)
Environmental Materials (by ValkyrieofNight)
Caelus API (Forge) (by TheIllusiveC4)
Eidolon (by elucent_)
FastWorkbench (by Shadows_of_Fire)
Star Wars : The Mandalorian Mod (by resuijaix)
Oh The Biomes You'll Go (by AOCAWOL)
MrCrayfish's Furniture Mod (by MrCrayfish)
Content Creator Integration (by ohaiiChun)
Drawers Tooltip (by Snownee_)
Torchmaster (by xalcon)
Artifacts (by ochotonida)
Refined Storage Large Patterns (by TheLMiffy1111)
Patchouli (by Vazkii)
Configured (by MrCrayfish)
ObserverLib (by HellFirePvP)
Immersive Engineering (by BluSunrize)
Quark (by Vazkii)
Botania Additions (by ToMe250)
Crafting Tweaks (by BlayTheNinth)
CleanCut (by Rongmario)
Mahou Tsukai (by stepcros)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Additional Lights (by mgen256)
PackMenu (by Shadows_of_Fire)
XP Tome (by bl4ckscor3)
Extra Disks (by MelanX)
"To the Bat Poles!" (by EnderLanky)
Immersive Posts (by TwistedGate)
McJtyLib (by McJty)
FTB Ultimine (Forge) (by FTB)
Rhino (by LatvianModder)
Lightstones (by Paperdomo101)
BountifulBaubles (by Cursed1nferno)
RandomPatches (Forge) (by TheRandomLabs)
Iron Jetpacks (by BlakeBr0)
Chocolate Fix (by AlcatrazEscapee)
Collective (by Serilum)
Rats (by alex1the1666)
Construction Wand (by ThetaDev)
ATM: Additions (by ATMTeam)
Repurposed Structures (Forge) (by telepathicgrunt)
Powah! (by owmii)
Lost Trinkets (by owmii)
Create (by simibubi)
Compact Crafting (by RobotGryphon)
Shrink. (by GigaBit101)
AppleSkin (by squeek502)
Compact Machines (by davenonymous)
Architectury API (Forge) (by shedaniel)
Mod Name Tooltip (by mezz)
Aquaculture 2 (by Shadowclaimer)
Environmental Tech (by ValkyrieofNight)
Pickle Tweaks (by BlakeBr0)
Mystical Adaptations (by Focamacho)
Glassential (by Lykrast)
Better End Sky (Forge) (by Jet_Mouse)
ValkyrieLib (by ValkyrieofNight)
Elemental Craft (by Sirttas)
[FORGE] Iron Furnaces (by XenoMustache)
Cat Jammies (by Buuz135)
Login Protection (by someaddon)
Farmer's Delight (by vectorwing)
SuperMartijn642's Core Lib (by SuperMartijn642)
Refined Storage Addons (by raoulvdberge)
FTB Essentials (Forge) (by FTB)
Fast Leaf Decay (by olafskiii)
Cable Tiers (by UItramega)
Dynamic View (by someaddon)
MineColonies (by H3lay)
Demagnetize (by comp500)
Mouse Tweaks (by YaLTeR)
The Twilight Forest (by Benimatic)
Iron Chests (by ProgWML6)
Mana and Artifice (by AWildCanadianEh)
Advanced Mining Dimension (by henkelmax)
Oh My Gourd (by TeamCoFH)
KubeJS Mekanism (by LatvianModder)
ReAuth (by TechnicianLP)
Absent by Design (by Lothrazar)
Mystical Agriculture (by BlakeBr0)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Cucumber Library (by BlakeBr0)
RFTools Power (by McJty)
Uppers (by vadis365)
Create Crafts & Additions (by MRHminer)
Centrifuge Tiers (by UItramega)
DimStorage (by 3divad99)
Default Options (by BlayTheNinth)
Spartan Shields (by ObliviousSpartan)
Dark Utilities (by DarkhaxDev)
Clumps (by Jaredlll08)
Ensorcellation (by TeamCoFH)
Lantern Colors (by schmecky90)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Colytra (Forge) (by TheIllusiveC4)
Ars Nouveau (by baileyholl2)
Simple Magnets (by SuperMartijn642)
Botany Pots (by DarkhaxDev)
Refined Pipes (by raoulvdberge)
Crash Utilities (by Darkere)
Flat Bedrock (by Sunekaer)
Simply Light (by Flanks255)
Alex's Mobs (by alex1the1666)
Builders Crafts & Additions (Forge) (by MRHminer)
EmbellishCraft (by Mapper)
Macaw's Furniture (by sketch_macaw)
Tinkers' Mechworks (by mDiyo)
Macaw's Bridges (by sketch_macaw)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Chisels & Bits (by AlgorithmX2)
RFTools Base (by McJty)
NetherPortalFix (by BlayTheNinth)
Fairy Lights (by pau101)
TrashSlot (by BlayTheNinth)
Mana Gear (by Partonetrain)
Mining Gadgets (by Direwolf20)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Storage for ComputerCraft (by uecasm)
Integrated Terminals (by kroeser)
Trample Stopper (by UnRealDinnerbone)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Supplementaries (by MehVahdJukaar)
FTB Backups (Forge) (by FTB)
FTB Ranks (Forge) (by FTB)
FTB Chunks (Forge) (by FTB)
Silent Gear (by SilentChaos512)
Additional Bars [FORGE] (by CodenameRevy)
Framed Compacting Drawers (by Eutropium)
Creative Crafter (by UItramega)
Placebo (by Shadows_of_Fire)
Dungeon Crawl (by XIROC1337)
AIOT Botania (by MelanX)
Jumbo Furnace (by Commoble)
Macaw's Trapdoors (by sketch_macaw)
Comforts (Forge) (by TheIllusiveC4)
Metal Barrels (by tfarecnim)
Inventory Tweaks Renewed (by David1544)
Armor Toughness Bar (by tfarecnim)
Configurable Extra Mob Drops (by Serilum)
Travel Anchors (by CastCrafter)
Building Gadgets (by Direwolf20)
BetterEnd (Forge) (by Beethoven92)
Mapper Base (by Mapper)
Portality (by Buuz135)
Runelic (by DarkhaxDev)
Better Advancements (by way2muchnoise)
Pedestals (by Mowmaster)
The Endergetic Expansion (by TeamAbnormals)
Bamboo Everything (Forge) (by Gaz_)
Macaw's Doors (by sketch_macaw)
Engineer's Decor (by wilechaote)
AE2 Extras (by tfarecnim)
Connected Glass (by SuperMartijn642)

Thank you for your time...

**Comment by MehVahdJukaar** [comment]
Can you send me the log file/crash report? It looks like some networking issue and it's trying to send way too much data. I wonder what that is.

**Comment by CKY-** [comment]
after posting this  there was more testing 
it would seem that the conflict is between this mod and  quarry plus I will be reaching out to the devs over there shortly with all the information that I'm sending to you.. YES that's a lot of data. I'm not sure what your new library is doing or brings to the table but it would seem that on the surface its part of the issue. then again I may just be have too many mods.  this error occurs during the  AUTH to the server. and the reason I came to you was I keep a list of what we are updating. when an error occurs  its time to look at why. the error log did not say why. you will see that in the log that I'm posting. and when its unclear  its time to  do a difference of one version to another then go back to the older versions. 

`
Only in 0.40.2/setup/mods/: AdditionalEnchantedMiner-1.16.5-16.1.8.jar 
Only in 0.40/setup/mods/: AdditionalEnchantedMiner-1.16.5-16.1.9.jar
Only in 0.40.2/setup/mods/: architectury-1.19.27-forge.jar
Only in 0.40/setup/mods/: architectury-1.20.28-forge.jar
Only in 0.40.2/setup/mods/: ars_nouveau-1.16.5-1.19.3.jar
Only in 0.40/setup/mods/: ars_nouveau-1.16.5-1.19.5.jar
Only in 0.40.2/setup/mods/: BetterStrongholds-1.16.4-1.1.jar
Only in 0.40/setup/mods/: BetterStrongholds-1.16.4-1.2.jar
Only in 0.40.2/setup/mods/: Botania-1.16.5-418.jar
Only in 0.40/setup/mods/: Botania-1.16.5-419.jar
Only in 0.40.2/setup/mods/: ferritecore-2.0.4-forge.jar
Only in 0.40/setup/mods/: ferritecore-2.0.5-forge.jar
Only in 0.40.2/setup/mods/: industrial-foregoing-1.16.5-3.2.13.1-5.jar
Only in 0.40/setup/mods/: industrial-foregoing-1.16.5-3.2.14.1-7.jar
Only in 0.40.2/setup/mods/: ironfurnaces-1.16.5-2.6.8.jar
Only in 0.40/setup/mods/: ironfurnaces-1.16.5-2.6.9.jar
Only in 0.40.2/setup/mods/: kotlinforforge-1.13.0-obf.jar
Only in 0.40/setup/mods/: kotlinforforge-1.14.0-obf.jar
Only in 0.40.2/setup/mods/: mahoutsukai-1.16.5-v1.31.29.jar
Only in 0.40/setup/mods/: mahoutsukai-1.16.5-v1.31.30.jar
Only in 0.40.2/setup/mods/: minecolonies-0.14.224-BETA-universal.jar
Only in 0.40/setup/mods/: minecolonies-0.14.280-BETA-universal.jar
Only in 0.40.2/setup/mods/: MysticalAdaptations-1.16.4-1.1.1.jar
Only in 0.40/setup/mods/: MysticalAdaptations-1.16.5-1.2.1.jar
Only in 0.40.2/setup/mods/: NaturesCompass-1.16.5-1.9.0.jar
Only in 0.40/setup/mods/: NaturesCompass-1.16.5-1.9.1-forge.jar
Only in 0.40.2/setup/mods/: occultism-1.16.5-1.3.0.jar
Only in 0.40/setup/mods/: occultism-1.16.5-1.6.5.jar
Only in 0.40.2/setup/mods/: Patchouli-1.16.4-51.jar
Only in 0.40/setup/mods/: Patchouli-1.16.4-53.1.jar
Only in 0.40.2/setup/mods/: pipez-1.16.5-1.1.5.jar
Only in 0.40/setup/mods/: pipez-1.16.5-1.2.7.jar
Only in 0.40.2/setup/mods/: pneumaticcraft-repressurized-1.16.5-2.12.5-190.jar
Only in 0.40/setup/mods/: pneumaticcraft-repressurized-1.16.5-2.13.1-202.jar
Only in 0.40.2/setup/mods/: Quark-r2.4-312.jar
Only in 0.40/setup/mods/: Quark-r2.4-314.jar
Only in 0.40/setup/mods/: repurposed_structures-1.16.5-2.7.10-forge.jar
Only in 0.40.2/setup/mods/: repurposed_structures-1.16.5-2.7.5-forge.jar
Only in 0.40.2/setup/mods/: rftoolsbase-1.16-2.0.10.jar
Only in 0.40/setup/mods/: rftoolsbase-1.16-2.0.11.jar
Only in 0.40.2/setup/mods/: rftoolsbuilder-1.16-3.0.17.jar
Only in 0.40/setup/mods/: rftoolsbuilder-1.16-3.1.0.jar
Only in 0.40.2/setup/mods/: rftoolscontrol-1.16-4.0.10.jar
Only in 0.40/setup/mods/: rftoolscontrol-1.16-4.0.11.jar
Only in 0.40.2/setup/mods/: rftoolspower-1.16-3.0.8.jar
Only in 0.40/setup/mods/: rftoolspower-1.16-3.0.9.jar
Only in 0.40.2/setup/mods/: rftoolsutility-1.16-3.0.26.jar
Only in 0.40/setup/mods/: rftoolsutility-1.16-3.1.0.jar
Only in 0.40/setup/mods/: selene-1.16.5-1.4.jar
Only in 0.40.2/setup/mods/: silent-gear-1.16.5-2.6.27.jar
Only in 0.40/setup/mods/: silent-gear-1.16.5-2.6.30.jar
Only in 0.40.2/setup/mods/: structurize-0.13.177-ALPHA-universal.jar
Only in 0.40/setup/mods/: structurize-0.13.199-ALPHA-universal.jar
Only in 0.40.2/setup/mods/: supplementaries-1.16.5-0.13.2.jar
Only in 0.40/setup/mods/: supplementaries-1.16.5-0.14.4f.jar
Only in 0.40.2/setup/mods/: TMechworks-1.16.3+-2.2.4.jar
Only in 0.40/setup/mods/: TMechworks-1.16.3+-2.2.5.jar
Only in 0.40.2/setup/mods/: tombstone-1.16-6.4.5.jar
Only in 0.40/setup/mods/: tombstone-1.16-6.4.6.jar
Only in 0.40/setup/mods/: YungsApi-1.16.4-Forge-11.jar
Only in 0.40.2/setup/mods/: YungsApi-1.16.4-Forge-6.jar
`

this is the difference of what was updated that day.

when I got to the bottom of the list here it started to work then stopped then started and this went on for a few hours.. 

this is a large pack with 381 mods. 

anyway here is the log  and thank you for taking the time to listen.
[client log.txt](https://gist.githubusercontent.com/CKY-/401574f15372838c80674b6eaf55fd97/raw/4b8e4df0196d6c103c2bd1e52c2fd63336cefd84/gistfile1.txt)

the client log has nothing in it 

[server debug,txt](https://gist.githubusercontent.com/CKY-/e628dd4a710c3096c081378f92d78f91/raw/71dffe179f0fe67fcbf427e88727c13d1c043ae2/gistfile1.txt)

the server log shows my suspensions of too many mods.

**Comment by MehVahdJukaar** [comment]
Ok first of all the server crash seems to be caused by the server taking too long to process a tick (probably when loading a world). This can happen quite frequently when installing many mods and it can be fixed by increasing the maximum allowed tick time in the server configs (by default it's set at 1m). Of course it would be best to identify why it was taking so long in the first place. Could be a mod taking too long to initialize or just too many mods. 
For the client log I can't see any crash there...

**Comment by CKY-** [comment]
I'm going to close this  after more testing AdditionalEnchantedMiner and tinkersconstruct are conflicting with Supplementaries and  another mod or 6 or 7, I dont have the time right now to help bound that nor do I want to waste anyone else's.. as of right now I can have Supplementaries or tinkers and AdditionalEnchantedMiner. I choose to leave this mod in. and take the other 2 out for now.  after I did that everything is working fine. also a side note all 3 work together in a smaller package. just the 3 of them.  thank you for your time.

**Comment by MehVahdJukaar** [comment]
hmm sure but you weren't wasting my time. I want to fix any possible compatibility bug
