### ISSUE TITLE
[🐞]: Wrong Bewitchment hanging sign textures

### ISSUE THREAD

**Issue by unoMato** [MehVahdJukaar/Supplementaries#850]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.6.31-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.66-fabric

### Issue Detail

When Supplementaries is enabled Bewitchment hanging sign textures are wrong when placed in world but correct in players hand and inventory.

### Optional Attachment

[error from log](https://gist.github.com/unoMato/b5d61023946f186b74eef72fcb72ee89)

### Mods needed
- Patchouli [1.20.1-83-FABRIC]
- Fabric API [0.91.0+1.20.1]
- Pehkui [3.7.11+1.14.4-1.20.2]
- Bewitchment [1.20-6]
- Trinkets [3.7.1]
- Supplementaries [1.20-2.6.31]
- Moonlight [1.20-2.8.66]

1. Create world
2. Place juniper, cypress, elder and dragons_blood hanging sing
3. Notice that they all look same
4. Shutdown Minecraft and disable Supplementaries
5. Load previous world again to see right textures

**Comment by unoMato** [comment]
https://github.com/MoriyaShiine/bewitchment/issues/385#issue-2011291950

**Comment by MehVahdJukaar** [comment]
Very Likely their issue. Of they aren't adding thsoe textures to vanilla maps right that's what happens

**Comment by MehVahdJukaar** [comment]
And fabric mods never do for some reason...

**Comment by MoriyaShiine** [comment]
Seems nobody has reported the cause for it, but it's between Terraform and Supplementaries, not Bewitchment. Any mod that uses Terraform Wood API will have their sign textures wrong once Supplementaries is installed; multiple mods using Terraform work fine together.

**Comment by MehVahdJukaar** [comment]
Supplementaries just calls the vanilla wood to texture map to gw those textures. If mods don't populate those properly it's their issue

**Comment by unoMato** [comment]
Textures are now working correctly with bewitchment version 1.20-7.
