### ISSUE TITLE
[🐞]: Server crashing

### ISSUE THREAD

**Issue by knivesbow** [MehVahdJukaar/Supplementaries#852]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-fabric

### Supplementaries Version

supplementaries-1.19.2-2.4.11-fabric

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-fabric

### Issue Detail

I've been using supplementaries for a few days on my server and starting yesterday it has been causing my server to crash (per my hosting) any idea why this would just start to happen after working just fine? (fabric 1.19.2)

### Optional Attachment

[crash-2023-11-30_03.07.03-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13512387/crash-2023-11-30_03.07.03-server.txt)

**Comment by MehVahdJukaar** [comment]
Some structure is taking way too long to get located. Either increase server max tick time, disable adventurer maps or untag the structure (it's probably villages)

**Comment by knivesbow** [comment]
what to you recommend i set the tick to? or should just disable it all together ? thank you.

**Comment by MehVahdJukaar** [comment]
use new version
