### ISSUE TITLE
[🐞]: Unknown custom packed identifier: supplementaries:25 spammed in logs

### ISSUE THREAD

**Issue by lumiscosity** [MehVahdJukaar/Supplementaries#853]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.7.1 - error first spotted on 1.20-2.6.34, but not present on 1.20-2.6.30 (the version before it on Modrinth)

### Moonlight Lib Version

1.20-2.8.67

### Issue Detail

The Minecraft logs are spammed with Unknown custom packed identifier: supplementaries:25 while in-game.

**Comment by lumiscosity** [comment]
sorry, i should've specified: the issue happens when loading chunks.
[logs](https://mclo.gs/qV9ZUJn)

**Comment by MehVahdJukaar** [comment]
use new moonlight version

**Comment by lumiscosity** [comment]
can confirm, the new moonlight lib version fixes this!
