### ISSUE TITLE
[🐞]: 

### ISSUE THREAD

**Issue by EMKWdesign** [MehVahdJukaar/Supplementaries#857]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [x] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-forge

### Supplementaries Version

all up to most recent - 1.19.2-2.4.13

### Moonlight Lib Version

Moonlight 1.19.2 - 2.3.5 (forge)

### Issue Detail

My game crashes at the end of the the loading screen before the main menu. It used to work just fine. I know that Optifine is causing issues, but I wanted to know if anyone could explain why? or if there is a way to fix it..? This is the only Mod that conflicts with it for some reason... I'm using OptiFine_1.19.2_HD_U_H9

### Optional Attachment

[crash-2023-12-04_15.53.15-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13551923/crash-2023-12-04_15.53.15-fml.txt)

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13551939/latest.log)

![Screenshot 2023-12-04 at 3 53 39 PM](https://github.com/MehVahdJukaar/Supplementaries/assets/58442494/6d54ef25-dbb4-4807-b18e-40ce136f60cb)

### To Produce

Open Minecraft, Crash occurs at the end of loading screen before the menu.

**Comment by MehVahdJukaar** [comment]
Because otpifine is bad and breaks forge itself. Don't use it there are way better alternatives that ctually improve performance and aren't a complete mess

**Comment by MehVahdJukaar** [comment]
And it doesn tconflcit with the mod it freaking removes a forge method. This will not crash until that's called that's why othe rmods might "just" crash randomly. I'm calling it immediately to sanity check
