### ISSUE TITLE
FD Compatibility: Place the blaze rod block into the `#farmersdelight:tray_heat_source` tag

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Supplementaries#858]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

### Details

Because blaze rod are set you on fire and is therefore probably hot enough to cook food with :3

**Comment by MehVahdJukaar** [comment]
added
