### ISSUE TITLE
[🐞]: Duplication of silent gear arrow

### ISSUE THREAD

**Issue by Mattsingen** [MehVahdJukaar/Supplementaries#860]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries-1.20-2.7.4.jar

### Moonlight Lib Version

moonlight-1.20-2.8.67.jar

### Issue Detail

Add a Silent Gear (silent-gear-.12.1-3.5.2.jar, silent-lib-1.20.1.8.0.0.jar) arrow to the quiver, shoot arrows and pick them up. You get a new arrow (1 ammo count) instead of the normal silent gear behaviour that they are added back to the existing arrows durability.
If it's hard to fix (as it's a non standard way of handling arrows), a blacklist for mods could be a simpler fix.

**Comment by MehVahdJukaar** [comment]
whats their id? does this mean they dont even get subtracted from the quiver when used?

**Comment by Mattsingen** [comment]
The ammo count (durability) is decreased when shooting so that part is working. 
ID: silentgear:arrow
Item tag: minecraft:arrows

**Comment by MehVahdJukaar** [comment]
i feel like if i blaclist then people will complain that it doesnt work

**Comment by Mattsingen** [comment]
Maybe, but the arrows aren't handeled in a normal way that can cause issues. For reference: https://github.com/SilentChaos512/Silent-Gear/issues/270
The best way is if it's handled. If you go for a blacklist, do that in the config so that it's easy to add remove if it's fixed or new clashes are found.

**Comment by MehVahdJukaar** [comment]
blacklist was added in latest udate
