### ISSUE TITLE
Please set up a separate slot for the Quiver in the Curios API.

### ISSUE THREAD

**Issue by Nekori347** [MehVahdJukaar/Supplementaries#861]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Description:
Please set up a separate slot for the Quiver in the Curios API.
## Why should we implement the feature?
In this mod, the quiver occupies a slot in the backpack through the Curios API, conflicting with most backpack mods. However, I don't want to add more backpack slots, as this would lead to players carrying many backpacks, disrupting game balance! I hope you can set up a separate slot for the quiver. Thank you very much!

**Comment by MehVahdJukaar** [comment]
you can edit, alter and modify all slots added by curio using curio itself. mod has a wiki for it
