### ISSUE TITLE
[🐞]: Urns does not generate (especially when WF's Cave Overhaul is installed) [tested in 1.19.2]

### ISSUE THREAD

**Issue by B-Wither** [MehVahdJukaar/Supplementaries#863]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-forge

### Supplementaries Version

1.19.2-2.4.13

### Moonlight Lib Version

1.19.2-2.3.5

### Issue Detail

When "WF's Cave Overhaul" (1.0.2) is installed, urns stops to generate.

**Comment by B-Wither** [comment]
More like, I feel urn generation itself become much rarer than previously is, flying with spectator mode over 10 minutes still cannot find any urns, I only found urn generation at once

**Comment by MehVahdJukaar** [comment]
maybe that mod replaces existing cave features including urns. try to make them more common and see if they generate more

**Comment by B-Wither** [comment]
I feel WF's mod may not be main cause of that. I have to see more...

**Comment by B-Wither** [comment]
I can't really test, because even I only use it and Journeymap, JEI, and making spawn_attempts = 80 and attempts_per_patch = 5, it still only rarely generates. I think there is just issue about urn generation.

**Comment by MehVahdJukaar** [comment]
seems like the paced feature was using ratity filter instead of count filter, effectively its opposite.this means it was spawning 1/7 chunks instad of 7 attempts per chunk. you can change that to increase it

**Comment by B-Wither** [comment]
So attempt =1, per patch = 50 would work?

**Comment by MehVahdJukaar** [comment]
fixed
