### ISSUE TITLE
[🐞]: Way signs generating even with config option set to 'false'

### ISSUE THREAD

**Issue by turabian-luvr** [MehVahdJukaar/Supplementaries#864]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.7.11

### Moonlight Lib Version

moonlight-1.20-2.8.68

### Issue Detail

'way_sign' has been disabled in the config for a while, but a brand-new world is still generating with the structures:

```
    "sign_post": {
      "enabled": true,
      "way_sign": {
        "enabled": false,
        "show_distance_text": true
      }
    },
```

e: I've deleted and re-generated the config file to make sure I didn't mess up the json formatting or anything. The option just isn't being respected.

### Optional Attachment

![2023-12-18_15 41 42](https://github.com/MehVahdJukaar/Supplementaries/assets/54744184/6b6cdd70-af3c-4532-bbab-8fb27aed2c20)

**Comment by MehVahdJukaar** [comment]
So does the locate command work if you use it?

**Comment by MehVahdJukaar** [comment]
Also did you reboot your game/ reload resources?

**Comment by turabian-luvr** [comment]
Yes, the locate command works. After recreating the config file by deleting it, restarting the game, and making a completely new world, it still finds supplementaries:way_sign in the same location.
![Uploading 2023-12-18_16.13.11.png…]()

**Comment by turabian-luvr** [comment]
Thank you!
