### ISSUE TITLE
[🐞]: Quiver Multi-stack deletion of items.

### ISSUE THREAD

**Issue by Nyu5135** [MehVahdJukaar/Supplementaries#865]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

Supplementaries-1.20-2.5.26

### Moonlight Lib Version

moonlight-1.20-2.8.15

### Issue Detail

Potential issues with multi-stack inventories (Multiple potential mod clashes)

Using the Sophisticated Backpacks mod with a stack upgrade, making a single item slot have more than 64 items in one individual slot, when right clicking a stack of arrows, in my instance over 1k arrows, with a quiver, 64 arrows gets added to the quiver, however all arrows from the stack are removed.

I'm not using any other mods which provide more than one stack in a singular slot, however could prove to be the same case with all that do.

**Comment by Nyu5135** [comment]
Not to familiar with Java / Minecraft modding or Supplementaries, however looking at Minecraft modding documentation, a simple if statement to check ItemStack.Amount should fix this issue, Either only interacting with stack's of 64 or less, or only removing 64. This should solve this issue completely for any mods that have multiple stacked slots.

**Comment by MehVahdJukaar** [comment]
Yeah I know I already fixed it. Properly
