### ISSUE TITLE
[🐞]: Incompatibility with better nether maps

### ISSUE THREAD

**Issue by Jerhom3** [MehVahdJukaar/Supplementaries#866]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries-1.20-2.7.12-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.68-fabric

### Issue Detail

Whenever a slice map is used while better nether maps is installed, the map generated is a normal overworld map.

https://github.com/MehVahdJukaar/Supplementaries/assets/152254711/8d1083b7-4a7b-4a43-ac34-d2e7a987ad9b

https://github.com/MehVahdJukaar/Supplementaries/assets/152254711/c4ec1638-b5cd-4d07-8271-f568df95810d

**Comment by MehVahdJukaar** [comment]
Why would anyone would ever want to use better nether maps with slice maps? The whole porpyse of them was to provide a way to map the nether

**Comment by Jerhom3** [comment]
Well, mostly to get automatic nether mapping with map atlases. I also opened an issue with better nether maps too, and kind of understand the absurdity of trying to get this fixed. Thanks for noticing, keep up the good work!

**Comment by MehVahdJukaar** [comment]
Thing is these are 2 competitor solutions. You either use better nether maps or slice maps. Slice were added for this exact propuse, to map the nether automatically

**Comment by Jerhom3** [comment]
I see, very well ill go ahead and marked this as closed
