### ISSUE TITLE
Maps compatibility with OptiFine

### ISSUE THREAD

**Issue by akra73** [MehVahdJukaar/Supplementaries#867]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Description:
I am aware of the reasons against OptiFine. Yet, so far, I've only encountered one breaking issue and it is regarding the map rendering. For the sake of us who still need OptiFine (some great textures such as Conquest are still not working without it), would it be possible/too much trouble to separate the map code in Supplementaries so that we can switch it off in the config (unless there is a way to work out the incompatibilities, of course)?

## Why should we implement the feature?
So that more players can use it. Many players love texture packs which depend on OptiFine.

**Comment by MehVahdJukaar** [comment]
and we modders despise optifine becasue of all the issues such as this which it causes. What feature of those packs dont work? from what i know there isnt no pack whihc just dont work, just some features of them that might not because a mod which adds that system doesnt eixst yet. Compatibility is possible however like all things with optifine its just a matter of blindly coding stuff trying to imagine what optifine might have done to those poor classes which is almost impossible due to the fact that optifine source code cant be viewed due to its licens and one of the many factors onto why the community is against optifine

**Comment by akra73** [comment]
Hi, yes, as I said I am aware of the reasons against Optifine. I've been playing Minecraft since beta and followed it through its many changes. The MCPatcher and later Optifine brought dozens of features but kept the closed code. As a fellow programmer I understand the frustration with it and with the requests such as mine.

Mine was more of a suggestion, something that if can be done easily it may be worth trying. If not, then no worries. In any case, thank you for this awesome mod which is one of the top content mods for the current MC versions.

I cannot imagine how the maps code is implemented, so I can't really say if it would work or if it can be made modular on your end. I mentioned it as I've noticed that may be the only thing that is clashing with Optifine.

It is true that today we finally have many mods that replace parts of Optifine. I'll be very glad to get rid of it unless they can open the code and work together with the community. However, these mods address just some of the features and sometimes in different ways, that do not work with the existing texture packs. Additional trouble is that they depend on the availability of many developers, so currently the CTM is behind and the last update was for 1.19 almost a year ago.

There are several popular texture packs that depend on Optifine, such as Conquest and John Smith. Their authors invested years in them, keeping them alive since early MC versions. CTM is one of the most important features for those to work.

Again, thank you and keep up the good work!

**Comment by MehVahdJukaar** [comment]
well optifine is a core mod, unlike any others. this means that mixins from mods, which normally when done well cannot conflict with eachother can fonclift with optifine as source code is different. One could remove the affected mixin from the mod jar mixin config file and the issue would be "solved"

**Comment by MehVahdJukaar** [comment]
Also i thought CTM replacement was called Continuity or Athena
https://github.com/TheUsefulLists/UsefulMods
As for conquest i remmeber playing it in 1.7.10 for years after other versions came ot. I thought tha they "recently" made a 1.12 mod that adds all those custom blocks they had. That stuff had somuch content that being on a really oldversion didnt matter one bit

**Comment by akra73** [comment]
OK, I understand about the core mod issue. So, no worries.

As for the CTM, yes - Athena and Continuity are the options but they are not the same format as the Optifine CTM and the connected textures do not work for the texture packs that rely on it. The thing is, this feature is not just a small visual improvement, the blocks combine into new ones to the point that it's useless to run these texture packs without the support.

Conquest is still alive and looking as fantastic as ever :) There are releases for all versions from 1.0 to 1.20! There is also Conquest Reforged with the releases for 1.12 (the one you've seen) and then for all from 1.15 to 1.19. Those are among the most popular packs for people who love medieval style. Along with John Smith (also maintained for all MC versions from 1.0 to 1.20) - I think during 1.7.10 all the MC showcases were run with that pack :)

Thanks for listening to my troubles :)
