### ISSUE TITLE
[🐞]: Quiver trinket does not work in 1.20-2.7.14

### ISSUE THREAD

**Issue by solonovamax** [MehVahdJukaar/Supplementaries#872]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.7.14

### Moonlight Lib Version

1.20-2.8.71

### Issue Detail

If you use supplementaries version 2.7.14, along with trinkets version 3.7.1 (unsure about other trinkets versions), the quiver slot is does not exist.
Downgrading to supplementaries 2.7.13 fixes the issue.

**Comment by SaltSouls** [comment]
I can also say this is the case though I am using Sinytra Connector. For me it causes a disconnection on loading a world, saying invalid player data, when only those two mods exist, and if it doesn't crash, it fails to add the quiver slot. 2.7.13 fixes both the disconnect and the slot failing to be added.

**Comment by MehVahdJukaar** [comment]
Are you using latest version?

**Comment by SaltSouls** [comment]
> Are you using latest version?

Of what specifically? Sinytra Connector, yes. Supplementaries, yes. Moonlight Lib, Yes, Trinkets, Yes.

**Comment by MehVahdJukaar** [comment]
supplemetaries. latest is 2.7.15

**Comment by SaltSouls** [comment]
> supplemetaries. latest is 2.7.15

I'll test that version and see if the issue is fixed.

**Comment by solonovamax** [comment]
I believe that [this](https://github.com/MehVahdJukaar/Supplementaries/commit/b5ffd855b2b9a80814d87e7bb1943c3bc2f5d73a#diff-105e87e01be2d101c0ee08ebd337aad59d925bb8e3686eeb5fa09ac0b468810e) is the change that broke it. unsure why it did, though.

**Comment by MehVahdJukaar** [comment]
question is why. seems right to me, should add it to legs slot instead

**Comment by solonovamax** [comment]
yeah, I have no clue either.

it *should* simply be moving the item into your inventory (as it removed the previous slot it was in), but then you should be able to shift + click it into a slot on the legs. however, this last step fails for some reason.

maybe something about the item not being configured properly with the correct tags? idk.
unsure if the correct slot actually exists; have not checked this.

**Comment by SaltSouls** [comment]
I was looking at the tags, and nothing changes between how the tags or slot are being configured, so I have no idea how that could be the cause.

**Comment by SaltSouls** [comment]
I was looking at the tags, and nothing changes between how the tags or slot are being configured, so I have no idea how that could be the cause.

**Comment by MehVahdJukaar** [comment]
I tested this an i cant replicate
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/24719182/162036ec-cf73-401c-a11b-9957dd6c59da)

**Comment by solonovamax** [comment]
hmm

I will try and reproduce later tonight. will update then.
