### ISSUE TITLE
[🐞]: Hat stand doesn't render Herbal Brews and Vinery hats, wrong render for Alex's Mobs Fedora

### ISSUE THREAD

**Issue by CatAndPaste** [MehVahdJukaar/Supplementaries#873]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

1.20-2.7.14

### Moonlight Lib Version

1.20-2.8.78

### Issue Detail

Hat stand doesn't render Let's Do's hats at all (2-4 hat stands):
- Straw Hat (Vinery)
- Witch Hat (Herbal Brews)
- Top Hat (Herbal Brews)

![2023-12-29_23 38 33](https://github.com/MehVahdJukaar/Supplementaries/assets/85940028/c1d3ab1a-67cc-4b9e-98ea-103f9947caa9)

Fedora's (from Alex's Mobs) bottom layer gets cut when on Hat stand. 

![2023-12-29_23 42 27](https://github.com/MehVahdJukaar/Supplementaries/assets/85940028/e686cf64-5564-4926-bec1-386f789dce18)

Tested only with 9 mods installed (Supplementaries, Moonlight, DoAPI, Architectury, Vinery, HB, Citadel, Alex's Mobs). With normal Forge 47.2.19 and NeoForge 47.1.79.

### To Produce

1. Start the game with Supplementaries + Moonlight and:
1.a Let's Do API + Vinery + Herbal Brews + Architectury
1.b Alex's Mobs + Citadel
2. Put Hat Stand down and put Alex's Mobs Fedora / Vinery's Straw Hat / HB's Witch or Top Hat on

**Comment by MehVahdJukaar** [comment]
so trickiest thing about the hat was making it extend the HumanoidModel, same one that zombie and player use. Thats not that trivial to do but assures as much compatibility as one can and its not something other hat mods have done. If a mod is coded properly this should work with their armor. MmmMmmMmmMmm mod does the same. However if a mod were to say add a special layer to only player entities or specific entities, thus loosing generality in their approach, this entity wont be able to use them. I believe those are done incorrectly too as forge does easily allow for custom armor models via their item properties. 
As for the fedora thats quite odd, maybe i have the model head acually offset by one pixel. Ill check with that. For the other mod it should be done properly by them

**Comment by MehVahdJukaar** [comment]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/24719182/95ca6c79-3e14-4bf3-8389-9e42dac16b1a)
fedora seems "correct"
