### ISSUE TITLE
[🐞]: Keys no longer go in any Curio slot.

### ISSUE THREAD

**Issue by AnyankaT** [MehVahdJukaar/Supplementaries#877]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries 1.20-2.7.14

### Moonlight Lib Version

moonlight 1.20.1-1.1.378-BETA

### Issue Detail

The Supplementaries key will no longer fit into any Curio slot - it will only go in the belt slot. This changed on my last update.

Why is it no longer universal, and can  it be reverted - or changed with an NBT code?

**Comment by MehVahdJukaar** [comment]
i changed it beacsue i liked it that way more. Curio is entirely data driven. refer to their wiki

**Comment by AnyankaT** [comment]
The problem is I have a toolbelt in my belt slot, and two keys for two different purposes on our server. Is there any way to allow it in a different slot, maybe with a config option?
