### ISSUE TITLE
Compatibility with modded Bricks

### ISSUE THREAD

**Issue by QwertRvg** [MehVahdJukaar/Supplementaries#880]
### Before continuing, do the following checklist:

- [X] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [X] Confirm there is no existing feature that meets your ideal feature
- [X] Confirm there is no existing submitted feature request in the issue

## Description:
Compatibility between the throwable bricks feature and bricks from other mods.
A config option, which you can use to give any item the throwable brick properties.

## Why should we implement the feature?
The throwable bricks feature is a fun, small feature. But it'd feel weird for the player if only the vanilla brick was throwable.
So adding a config option would be great for modpacks. That way the modpack maker could just add the properties to any brick-like item.

**Comment by MehVahdJukaar** [comment]
the mod already has a tag which already contains around 30 entries to it. If users want to add more tey can just do so themselves or send the item ids to me. Moreover on forge the tag incldes the #forge:ingots/brick tag which menas that if a forge mod does not have their bricks as throwabe its completely their fault for not properly tagging their items

**Comment by QwertRvg** [comment]
oh okay, didn't know. that does make sense though
so the Silt Brick from the Twigs mod is not throwable (twigs:silt_brick)
I suppose I'll contact that mod's developer then
