### ISSUE TITLE
[🐞]: Index out of bounds in ColorData.processTexture

### ISSUE THREAD

**Issue by XspeedPL** [MehVahdJukaar/Supplementaries#882]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

1.20-2.7.19

### Moonlight Lib Version

1.20-2.8.79

### Issue Detail

Sorry, not entirely sure what happened. Me and a friend were swimming through an ocean on a dedicated server and both of us crashed at the same time, with the same stack trace and exception message.

### Optional Attachment

[crash-2024-01-03_05.33.07-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13815839/crash-2024-01-03_05.33.07-client.txt)

**Comment by craboat** [comment]
im also having this same problem... 
[crash-2024-01-03_05.33.07-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13816610/crash-2024-01-03_05.33.07-client.txt)

**Comment by craboat** [comment]
i figured it out, the server was running an older version and i was running the updated one today, so i just went back to the old version of the mod.

**Comment by MehVahdJukaar** [comment]
use new version should be fixed
