### ISSUE TITLE
Is there a way to remove the cage blacklist from modded mobs?

### ISSUE THREAD

**Issue by BoardAnims** [MehVahdJukaar/Supplementaries#885]
### Before continuing, do the following checklist:

- [x] Read the list of features via [Home](https://github.com/MehVahdJukaar/Supplementaries/wiki)
- [ ] Confirm there is no existing feature that meets your ideal feature
- [x] Confirm there is no existing submitted feature request in the issue

### Details

I know there's a setting in the config to allow all mobs to be caged, however even with that option enabled, some mobs like the Cachalot Whale and Giant Squid from Alex's Mobs still remain un-cageable. (The Orca is cage-able though...)

Is there a way to access and/or edit the cage blacklist?

**Comment by MehVahdJukaar** [comment]
Might be because they are multipaet entities, stuff that's technically multiple entities. Those wouldn't work in cages as only1 segment would be caught so they are naturally disabled

**Comment by BoardAnims** [comment]
> Might be because they are multipaet entities, stuff that's technically multiple entities. Those wouldn't work in cages as only1 segment would be caught so they are naturally disabled

There are 5 mobs in Alex's Mobs that have segmented parts used as entities. (Cave Centipede, Bone Serpent, Void Worm, Anaconda and Murmur)

I cannot capture the centipede at all BUT i can capture the rest of the mobs. Capturing the head, cages the head of the mob, making the segments disappear. Capturing a segment cages the segment that was right clicked and disappears any segment that was connected to the captured segment down the body. Leaving a few or no segments connected to the head. (Releasing a caged head spawns the mobs with all of it's segments intact, but if a caged segment is released, it quickly disappears)


This is a bug in it of itself as you can cut parts off these mobs. (or make a murmur have multiple heads by releasing caged murmur heads near a murmur)

However what im looking for is a way to make pretty much all mobs/entities be cageable with no restrictions. 
Since it seems that certain massive mobs like the Cachalot Whale, Giant Squid and Hullbreaker are immune to being caged. (These mobs are not segmented, and appear as single entities, but do seem a little "complicatedly animated"=
almost as if there is a blacklist within the mod that prevents caging certain modded mobs. (I can capture the Ender Dragon though..)
Is this something I have to configure through Supplementaries or Alex's Mobs?

**Comment by MehVahdJukaar** [comment]
I had to hardcode the centipede because for some reason those dont extend the vanilla multipar entites class. gues i got to add a proper blacklist tag. The only other remaining hardcoded check is for mobs that can have an owner. If they can then you wont be able to catch unless you are the owner. Is that whats happening here?

**Comment by MehVahdJukaar** [comment]
So I checked. All those are vanilla multipart entities. This means its working as intended
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/24719182/3b09f276-ff56-4d85-903c-f196ad74846b)

**Comment by MehVahdJukaar** [comment]
regardless hardcoded checks have been moved below the global config one. Before that ive added a blacklist tag. this will cover this
