### ISSUE TITLE
[🐞]: Quark/Zeta 1.20 Compatability

### ISSUE THREAD

**Issue by Reyzerbit** [MehVahdJukaar/Supplementaries#887]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

2.7.7

### Moonlight Lib Version

2.8.67

### Issue Detail

This isn't extremely time sensitive, but Quark (soon to be renamed Zeta) has some beta builds you can access for 1.20. The new versions of Quark cause NoClassDefFound errors because of refactoring. If you check out the [zeta120](https://github.com/VazkiiMods/Quark/tree/zeta120) branch of the Quark repo, you can get a step ahead on quark compat before official releases of quark come out.

### To Produce

1. Install any 1.20 version of Supplementaries
2. Install any beta build of Quark

**Comment by MehVahdJukaar** [comment]
please dont double post. Also 
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/24719182/1530f55f-be27-47ba-a2f9-11dbfa06a9af)

**Comment by Reyzerbit** [comment]
@MehVahdJukaar apologies, i thought i had closed the issue on Curseforge as I had formatted it incorrectly.

**Comment by Reyzerbit** [comment]
@MehVahdJukaar also if this is something you dont plan on taking care of, I am willing to contribute it myself.

**Comment by MehVahdJukaar** [comment]
I appreciate the offer but theres nothing to take care of. Im part od quark 1.20 team and supplementaries works with latest version. As I've said you are just using a very old mod version

**Comment by Reyzerbit** [comment]
Oh I see. I apologize again, I had looked through all your release notes on curseforge and couldn't see anything in regards to Quark compact updates, so I just figured you hadn't made any changes. Thanks for clarifying!

**Comment by MineCraftPro150** [comment]
i have a problem too so i updated quark and it says i need 1.20.1-1.0-15 Zeta for quark but it is stuck at 1.20.1-1.0-14
for zeta and 1.20.1-1.0-15 isnt released could you help?
