### ISSUE TITLE
[🐞]: Double Trades

### ISSUE THREAD

**Issue by QwertRvg** [MehVahdJukaar/Supplementaries#888]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

2.7.22

### Moonlight Lib Version

2.8.79

### Issue Detail

These trades show up twice in EMI / JEI:

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/89683173/acb10541-1dc3-426b-8035-9862b0658247)
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/89683173/a90c3fa0-32e9-4f10-acbf-f6decd20afd3)

### To Produce

Download Supplementaries
Download EMI
Download EMI Trades

view the Trades for the Globe and Flax Seeds

**Comment by MehVahdJukaar** [comment]
yeah because it gets added twice. to make it more common. You can change in the configs

**Comment by QwertRvg** [comment]
thank you!
