### ISSUE TITLE
Crash When Planting Rose in the Flower Box

### ISSUE THREAD

**Issue by Darkosto** [MehVahdJukaar/Supplementaries#89]
Hello, 

I just downloaded the newest update and tried placing a Rose into the flower box and got a client crash:

Crash: https://pastebin.com/sPewQdgB

MC: 1.16.5
Selene: 1.16.5-1.0
Supplementaries: 1.16.5-0.15.0
Forge: 36.2.2

Thank you!

**Comment by MehVahdJukaar** [comment]
Fixed in 0.15.1
