### ISSUE TITLE
[🐞]: Crash when pillager loads crossbow

### ISSUE THREAD

**Issue by Whizzywig** [MehVahdJukaar/Supplementaries#891]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-fabric

### Supplementaries Version

supplementaries-1.19.2-2.4.16

### Moonlight Lib Version

moonlight-1.19.2-2.3.5

### Issue Detail

Whenever a pillager loads a crossbow it crashes the game. I have tested it on both the latest fabric api and quilted fabric api, using both fabric and quilt loaders. The issue seems to stem from the `shrinkQuiverArrow` mixin.

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13891912/latest.log)

### To Produce

1. Start world
2. Summon pillager
3. Be in survival mode
4. Crash

**Comment by MehVahdJukaar** [comment]
backported fix.

**Comment by kaydenvg** [comment]
Same bug occurs on 1.20-2.6.29-fabric!
