### ISSUE TITLE
[🐞]: When I use Velocity to proxy Mohist and give the player op permission, he will be kicked out of the game!

### ISSUE THREAD

**Issue by wlm1455925277** [MehVahdJukaar/Supplementaries#892]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries-1.20-2.7.22

### Moonlight Lib Version

moonlight-1.20-2.8.81-forge

### Issue Detail
When I use Velocity to proxy Mohist and give the player op permission, he will be kicked out of the game!

wlm123 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Registry moonlight:map_markers not found

### Optional Attachment

wlm123 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Registry moonlight:map_markers not found

### To Produce

When I use Velocity to proxy Mohist and give the player op permission, he will be kicked out of the game!

**Comment by MehVahdJukaar** [comment]
Velocity is for Vanilla!!!!

This is their issue. If they are nuking mod-added datapack registries they are not incompatible with a mod, they are incompatible with forge architecture and modded in general.
Dont use said hybrid servers for modded, its a known fact that those people make thsoe for vanilla and dont care if stuff doesnt work for mods
