### ISSUE TITLE
[🐞]: Blackboard causes a crash

### ISSUE THREAD

**Issue by rabbit-time** [MehVahdJukaar/Supplementaries#893]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.7.21

### Moonlight Lib Version

moonlight-1.20-2.8.72

### Issue Detail

The game crashes when I attempt to draw on a blackboard.

### Optional Attachment

[crash-2024-01-06_20.27.37-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13897635/crash-2024-01-06_20.27.37-client.txt)

**Comment by MehVahdJukaar** [comment]
Is immediately fast updated?

**Comment by rabbit-time** [comment]
@MehVahdJukaar Yes, ImmediatelyFast version 1.28 for Minecraft 1.20.1.
