### ISSUE TITLE
[🐞]: Wrench Dupe Glitch with Chipped

### ISSUE THREAD

**Issue by MoonstruckDev** [MehVahdJukaar/Supplementaries#898]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

2.7.22

### Moonlight Lib Version

2.8.82

### Issue Detail

When rotating a table from chipped it will create an invisible version of it which you can mine and obtain.

https://imgur.com/a/VJwFhxl

### To Produce

1 - Place down carpenter's/tinkerer's table
2 - Rotate with wrench
3 - mine the original table
4 - then mine the invisible block next to it

**Comment by MehVahdJukaar** [comment]
whats its id?
