### ISSUE TITLE
Getting my cat to standup from the bed makes the (singleplayer) server crash

### ISSUE THREAD

**Issue by hvdklauw** [MehVahdJukaar/Supplementaries#9]
[crash-2021-01-24_15.01.35-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/5862399/crash-2021-01-24_15.01.35-server.txt)
[crash-2021-01-24_15.09.43-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/5862400/crash-2021-01-24_15.09.43-server.txt)

**Comment by MehVahdJukaar** [comment]
fixed it. new version will come asap

**Comment by hvdklauw** [comment]
Awesome!
