### ISSUE TITLE
[🐞]: Enderman Head texture not showing

### ISSUE THREAD

**Issue by DragonFire93** [MehVahdJukaar/Supplementaries#901]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.7.23-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.84-fabric

### Issue Detail

Enderman head texture is invisible when placed in hotbar and on JEI 

![2024-01-18_14 22 04](https://github.com/MehVahdJukaar/Supplementaries/assets/85889418/618a7ebe-cda6-411d-81ce-57b540fc2775)

**Comment by MehVahdJukaar** [comment]
Entity model features issues. Report to them I already did many times

**Comment by MehVahdJukaar** [comment]
Issue on the GitHub mod page like you did here
