### ISSUE TITLE
[🐞]: Modpack crashing when i add supplementaries

### ISSUE THREAD

**Issue by CACOKKOTA** [MehVahdJukaar/Supplementaries#902]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

supplementaries-1.20-2.7.24 and supplementaries-1.20-2.7.25

### Moonlight Lib Version

moonlight-1.20-2.8.81-forge

### Issue Detail

Im having issues with supplementaries with: 
chisel and bits (chisels-and-bits-forge-1.4.145)
Star Worm Equestrian Mod (swem-1.20.1-1.4.0)
everything loaded fine until i added supplementaries

at first try it wrote about both of them, second and third only SWEM, at 4th loaded successfully :/ (latest version)

### Optional Attachment

[crash-2024-01-18_22.17.57-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13980931/crash-2024-01-18_22.17.57-fml.txt)
[crash-2024-01-18_22.15.04-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13980932/crash-2024-01-18_22.15.04-fml.txt)
[crash-2024-01-18_22.19.47-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/13980933/crash-2024-01-18_22.19.47-fml.txt)

successful load
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/13980941/latest.log)

**Comment by MehVahdJukaar** [comment]
Some mod is doing something offthread on common setup event that they shouldnt do. This means that its a concurrency issue which could blame any mod that do things right because some mod is accsssing stuff offtread causing said race issue. I cant rell you which it is but its not supplementaries, i do all on main thread there

**Comment by Xelbayria** [comment]
Disable all of your mods except **Supplementaries** & **Moonlight Lib**, and enable the mods one by one until you get the error. that will be your culprit.

**Comment by CACOKKOTA** [comment]
i don't understand what the hell is happening right now, but i think iceberg and item highlighter caused crashes :/
i'll play more and warn you if something will happen
