### ISSUE TITLE
[🐞]: Supplementaries causes error when joining an Essential world

### ISSUE THREAD

**Issue by ianm1647** [MehVahdJukaar/Supplementaries#903]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-forge

### Supplementaries Version

1.20-2.7.27

### Moonlight Lib Version

1.20-2.8.84

### Issue Detail

trying to join a friends world with the essential mod causes an error, removing supplementaries fixes the error.

### Optional Attachment

[2024-01-20-7.log](https://github.com/MehVahdJukaar/Supplementaries/files/13999836/2024-01-20-7.log)

**Comment by MehVahdJukaar** [comment]
i dont see any error related to supplementaries in your log. last error i see is from mechanism. not sure if that causes a crash or not tho. You might want to report to essentials
