### ISSUE TITLE
[🐞]: Game crashes on load

### ISSUE THREAD

**Issue by IamKayrox** [MehVahdJukaar/Supplementaries#904]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

1.20-2.7.28

### Moonlight Lib Version

fabric_1.20-2.8.86

### Issue Detail

The game crashes on startup, tested with an empty modpack using:
- Minecraft 1.20.1
- Fabric Loader 0.15.6
- Fabric API 0.91.0+1.20.1
And the reported Supplementaries and Moonlight Lib versions.
If it's of any help, the modpack was made using Modrinth App.

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14003307/latest.log)

**Comment by twenty41** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14003339/latest.log)

Same here, doesn't happen if I downgrade to the Jan 19th build

**Comment by MehVahdJukaar** [comment]
try new version

**Comment by IamKayrox** [comment]
Newest version seems to work fine. Closing the issue
