### ISSUE TITLE
[🐞]: Incompatibility between Supplementaries and FTB Dimensions causing server to hang indefinitly

### ISSUE THREAD

**Issue by DatenThielt** [MehVahdJukaar/Supplementaries#909]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.19.2-forge

### Supplementaries Version

supplementaries-1.19.2-2.4.16

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue Detail

Incompatibility between FTB Dimensions and Supplementaries is causing server to hang with no crash, If watchman is enabled then the server crashes after the alloted timeout,  The logs only point to Supplementaries and Sareth mentioned that it seems to be an issue with that and FTB Dimensions. 

The internal issue if you have access can be found at 
https://github.com/FTBTesting/Testing-Issues/issues/1889

I have also put the logs here in case you do not have access.  Thanks!

debug.log https://pste.ch/mikinihoxa.md
latest.log https://pste.ch/okotuhicow.md
crash.log https://pste.ch/ekiputineb.pl

I have put the original description in the steps below.

### To Produce

Randomly, the server will stop responding completely, until watchman picks it up and crashes the server
Disabling watchman causes the server to hang forever
restarting the server and attempting to log in will cause it to hang again, Not logging into the same region has no issue.
The last batch of lines in the logs points to supplementaries
Disabling supplementaries on the server fixes the issue
re-enabling supplementaries the server runs for a while again (several hours) until the issue randomly comes back, This is random and sometimes does not fix the issue.

**Comment by MehVahdJukaar** [comment]
Who knows whose fault its here. I see FTB stuff doing stuff with chunk loading, ends up calling some vanilla update chunk methods which calls supplementaries which calls forge capabilities which calls ends up getting a productive bees capability at that pos and that somehow causes something to lock up I assume

**Comment by MehVahdJukaar** [comment]
should be solved
