### ISSUE TITLE
[❓]: Internal Exception, Non0-9a-z character, help needed

### ISSUE THREAD

**Issue by twenty41** [MehVahdJukaar/Supplementaries#912]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others. Do NOT report issues related to said mods
- [X] If you are unsure which mod is the culprit.
Disable half your mods at time until you isolate the culprit
- [X] If you have a crash ALWAYS post LATEST.LOG below
- [X] If the issue is about behaviors be sure to consult the WIKI first

### Version-Loader

1.20.1-fabric

### Supplementaries Version

supplementaries-1.20-2.7.30

### Moonlight Lib Version

moonlight-1.20-2.9.3-fabric

### Issue Detail

I don't think this is necessarily a problem with your mod whatsoever but I do not even know where to begin diagnosing this, any pointers needed

I maintain a server and modpack for my friends. I recently updated the server to the newest modpack version.

The server launches successfully. When I join on my personal client, the one where I "made" the new update, I am able to join the server.
Once I export the modpack and import the profile to Curseforge (the process all my friends have to do), I am no longer able to join and I get [this error.](https://i.bloomworldwi.de/m3gMDN)

I am just trying to start somewhere. I don't know how to research this, it doesn't really make any sense to me how this can happen. Vinery's help section is walled off by Discord and yours is the next mod mentioned.

It just can't be an actual invalid character issue because I can join the server on my copy like I said. It only breaks once reimported. I don't know what it is about my "original" profile that allows it to join the server.
Can you help me even _begin_ troubleshooting this?

Attached is the latest.log of a person who just got the error.

### Optional Attachment

[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14078250/latest.log)

### To Produce

described above

**Comment by MehVahdJukaar** [comment]
Is your system language set to English?

**Comment by twenty41** [comment]
Yes system and game both set to English. All players systems are in English

**Comment by MehVahdJukaar** [comment]
That's usually due to some encoding issue, usually due to a non English system language. Issue is unrelated to supplementaries, all characters in those files are correct. Unfortunately only thing I know about this is that. Troubleshooting is hard . Try to reproduce on s minimal setup

**Comment by twenty41** [comment]
alright ty
