### ISSUE TITLE
Issue with Sodium and Supplemantaries on 1.20.1?

### ISSUE THREAD

**Issue by suerion** [MehVahdJukaar/Supplementaries#916]
**Always include**
[MC Logs](https://mclo.gs/TAxCRT3)

- Mod version, MC version and Loader you are using
Fabric 1.20.1

- A description of your issue and how to reproduce
Added Sodium and Supplemantarys in the Modpack, the Modpack is not starting anymore.

- If applicable, add screenshots to help explain your problem.

**Comment by Xelbayria** [comment]
:\ uh you did not use the "Report Bug"?  here's the picture: 
![example-github](https://github.com/MehVahdJukaar/Supplementaries/assets/12866666/aa2e6364-43a4-424f-a56c-f97f9d24d3e1)

I hope that clear up the confusion.

**Comment by MehVahdJukaar** [comment]
report to sodium

**Comment by suerion** [comment]
> :\ uh you did not use the "Report Bug"? here's the picture: ![example-github](https://private-user-images.githubusercontent.com/12866666/301954294-aa2e6364-43a4-424f-a56c-f97f9d24d3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDU3NjAsIm5iZiI6MTcwNjkwNTQ2MCwicGF0aCI6Ii8xMjg2NjY2Ni8zMDE5NTQyOTQtYWEyZTYzNjQtNDNhNC00MjRmLWE1NmMtZjk3ZjlkMjRkM2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIwMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNDc5Nzk3YjkyNmJkYzhjMDZhZmIxMGI2MjRjNDEzZTU3MmY5NWY4YWU5MjkzNTcyYWJlYzlmMDhmZWU1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XcPapiPxEE56i-RS3Zslm8vQddJws185_2QSt2K1Lfo)
> 
> I hope that clear up the confusion.

I had clicked on report a bug, stoping this annoying sentence…

**Comment by Xelbayria** [comment]
> I had clicked on report a bug, stoping this annoying sentence…

Sorry. I thought the "Report Bug" has the template setup. turned out it didn't. i updated it.
