### ISSUE TITLE
[🐞]: Cannot find hanging signs in creative inventory and JEI (MC 1.20.1)

### ISSUE THREAD

**Issue by DuisPlay** [MehVahdJukaar/Supplementaries#918]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20.2.7.33

### Moonlight Lib Version

moonlight-1.20.2.9.7

### Issue Detail

I cannot find the hanging signs in creative inventory and in JEI, only the vanilla hanging signs are available. In the log files there are no Error messages.

**Comment by MehVahdJukaar** [comment]
Why would there need to be 2 hanging signs :p

**Comment by DuisPlay** [comment]
> Why would there need to be 2 hanging signs :p

Supply's signs are better than Vanilla's, especially because you can put items in them and they have more text lines.

**Comment by MehVahdJukaar** [comment]
Well they've been removed since vanilla adds then. I'm still planning to also make vanilla signs accept items but they won't be able to accept more lines
