### ISSUE TITLE
[🐞]: Skeleton Quiver spawn chance doesn't work on Fabric

### ISSUE THREAD

**Issue by Partonetrain** [MehVahdJukaar/Supplementaries#919]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.7.32-fabric

### Moonlight Lib Version

moonlight-1.20-2.9.7-fabric

### Issue Detail

To reproduce: 
Change the config file to this:

```
"quiver": {
      "enabled": true,
      "use_without_slow": true,
      "slots": 6,
      "quiver_skeleton_spawn_chance": 1.0,
      "only_works_in_curio": false,
      "quiver_pickup": true
    },
```
Spawn a skeleton in-game
Observe that it doesn't spawn with a quiver

Tested with only moonlight and supplementaries on fabric 0.15.3

**Comment by MehVahdJukaar** [comment]
Are you on at least normal difficulty?

**Comment by Partonetrain** [comment]
Yes. Tested with natural night surface spawns, /summon, mob egg, and monster spawner.

**Comment by MehVahdJukaar** [comment]
Algith, well I'm pretty sure that actual issue is the quiver not rendering

**Comment by Partonetrain** [comment]
The skeletons are not dropping quivers, even with 1.0 quiver_skeleton_spawn_chance

**Comment by Partonetrain** [comment]
working as intended as discussed in Discord - skeleton quiver spawn chance 1.0 != 100% of the time, still depends on difficulty, and quivered skeletons will drop the quiver 1/3rd of the time
