### ISSUE TITLE
[🐞]: Supplementaries crashes with Sodium 0.5.8

### ISSUE THREAD

**Issue by AmberRoseZA** [MehVahdJukaar/Supplementaries#920]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.7.32

### Moonlight Lib Version

1.20-2.9.7-Fabric

### Issue Detail

It crashes your game when you have both Sodium 0.5.8 and supplementaries 2.7.32

[2024-02-06-1.log](https://github.com/MehVahdJukaar/Supplementaries/files/14175585/2024-02-06-1.log)

**Comment by Kosmaster** [comment]
Same

**Comment by glittermutt** [comment]
+1, it does crash

**Comment by MehVahdJukaar** [comment]
Not my issue

**Comment by OceanFifty** [comment]
Check this Sodium Issue for further details: [https://github.com/CaffeineMC/sodium-fabric/issues/2303](https://github.com/CaffeineMC/sodium-fabric/issues/2303)
