### ISSUE TITLE
main menu button

### ISSUE THREAD

**Issue by OM3GA6400** [MehVahdJukaar/Supplementaries#923]
Can you add an option to move the main menu button to the right of the multiplayer button please? i need to complete the main menu.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/98067930/a9a459e9-ba98-4a30-a280-3660131abefc)

**Comment by OM3GA6400** [comment]
@MehVahdJukaar

**Comment by MehVahdJukaar** [comment]
closin this as ive added a config in new version

**Comment by OM3GA6400** [comment]
but 1.19.2 😭😭😭😭

**Comment by MehVahdJukaar** [comment]
Guess you could use Slotify mod to move slots around

**Comment by OM3GA6400** [comment]
> Guess you could use Slotify mod to move slots around

https://m.youtube.com/watch?v=8Go6dHuylyM
