### ISSUE TITLE
[🐞]: [Server thread/ERROR] [supplementaries/]: 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/Supplementaries#924]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.19.jar

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge.jar

### Issue Detail

I don't understand if this applies to this mod or not, but its name is in the log.

[08Feb2024 02:53:03.661] [Render thread/ERROR] [supplementaries/]: Some mod loaded the Sheets class to early! This causes the banner texture maps to not contain modded patterns. Supplementaries will not attempt to fix...

<html>
<body>
<div class="log" style="margin: 0px; padding: 0px; box-sizing: border-box; font-family: &quot;Roboto Mono&quot;, monospace; word-break: break-all; font-size: 14px; color: rgb(240, 240, 240); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(45, 57, 67); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
98 lines
--
21966 | [08Feb2024 02:58:54.131] [Server thread/ERROR] [supplementaries/]: [!!!!] Some mods (see below stack trace) have errors which will prevent Supplementaries from working correctly.Continuing anyways but you might experience random crashes. You have been warned
  | 3034 lines

</div><div class="log-bottom" style="margin: 0px; padding: 0px 12px; box-sizing: border-box; display: flex; justify-content: space-between; color: rgb(240, 240, 240); font-family: Play, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(45, 57, 67); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="btn btn-blue btn-small btn-notext" id="up-button" style="margin: 10px 8px 10px 0px; padding: 5px 8px; box-sizing: border-box; line-height: 1; border-radius: 2px; font-weight: bold; color: rgb(240, 240, 240); background: rgb(45, 135, 211); font-size: 14px; display: inline-block; transition: background 0.05s ease 0s; cursor: pointer;"><i class="fa fa-arrow-circle-up" style="margin: 0px; padding: 0px; box-sizing: border-box; font-family: var(--fa-style-family,&quot;Font Awesome 6 Free&quot;); font-weight: var(--fa-style,900); -webkit-font-smoothing: antialiased; display: var(--fa-display,inline-block); font-style: normal; font-variant: normal; line-height: 1; text-rendering: auto;"></i></div><div class="checkbox-container" style="margin: 0px; padding: 0px; box-sizing: border-box; display: flex; align-items: center; justify-content: center;"></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by MehVahdJukaar** [comment]
error says that supplementaries detected other mods doing bad stuff. obviously not a supplementaries issue

**Comment by Krimatoria** [comment]
> ошибка говорит о том, что дополнения обнаружили, что другие моды делают плохие вещи. явно не проблема дополнений

Ok) I'm just new to understanding how mods work so far) I just try to send errors that I see on GitHub)
