### ISSUE TITLE
[🐞]: doesnt support latest sodium version 0.5.8

### ISSUE THREAD

**Issue by harithmf** [MehVahdJukaar/Supplementaries#927]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

latest

### Moonlight Lib Version

latest

### Issue Detail

^%%

**Comment by MehVahdJukaar** [comment]
Log says the exact opposite. Not my problem. Stop reporting this nonsense to me. Also I suggest using embeddium fabric

**Comment by harithmf** [comment]
> Log says the exact opposite. Not my problem. Stop reporting this nonsense to me. Also I suggest using embeddium fabric

someone else has this problem? idk man ¯\_(ツ)_/¯ doesnt sound like nonsense to me lol
