### ISSUE TITLE
[🐞]: crash when launching with latest sodium (0.5.8)

### ISSUE THREAD

**Issue by teadudes** [MehVahdJukaar/Supplementaries#929]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

Latest version

### Moonlight Lib Version

2.9.7

### Issue Detail

Game crashes at launch with latest sodium indium etc. Says i have the wrong version of supplementaries but then recommends the same version? so confused

**Comment by MehVahdJukaar** [comment]
Send latest.log, like the issue desc saya

**Comment by BowBoy1** [comment]
This is like the 4th issue about this I've seen. There's information about what's going on with this here. Be sure to read all the comments too for the full context.
https://github.com/CaffeineMC/sodium-fabric/issues/2303

**Comment by MehVahdJukaar** [comment]
Very biased and incorrect information but sure. Use embeddium fabric, they don't set arbitrary "incompatibilities" with mods not invalidate fabric API itself
