### ISSUE TITLE
[🐞]:  placed down books are just the missing texture 

### ISSUE THREAD

**Issue by PopSikle23** [MehVahdJukaar/Supplementaries#933]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.7.36

### Moonlight Lib Version

moonlight-1.20-2.9.13-forge

### Issue Detail

![2024-02-13_16 37 07](https://github.com/MehVahdJukaar/Supplementaries/assets/88212115/ed55277e-1772-45c3-b0ce-5a8f2101d204)

**Comment by MehVahdJukaar** [comment]
send latest.log
