### ISSUE TITLE
log flooded with sign texture errors

### ISSUE THREAD

**Issue by Linguardium** [MehVahdJukaar/Supplementaries#934]
https://github.com/MehVahdJukaar/Supplementaries/blob/73fcd9508fb2f88aa0609bfe049e380fe5330f5f/common/src/main/java/net/mehvahdjukaar/supplementaries/dynamicpack/ClientDynamicResourcesGenerator.java#L236-L265

This should be an opt-in situation not a global situation. You are throwing errors for things that are not opting into your system and then logging those errors blaming other mods.

[error snippet](https://github.com/MehVahdJukaar/Supplementaries/files/14302809/supplementaries.blaming.everyone.else.error.txt)

**Comment by MehVahdJukaar** [comment]
It is opt in. You can disable enhance hanging signs (and hence that stuff) via configs

**Comment by MehVahdJukaar** [comment]
Also that's not my system at all. That's vanilla system. If you add a wood type and it's texture isn't even in the vanilla maps then it's not done properly

**Comment by Linguardium** [comment]
* You then make an assumption about what exists based on the vanilla system, but you are the one generating invalid file paths and throwing errors, not vanilla, meaning its still your system having problems
`Sheets.getHangingSignMaterial(w.toVanilla()).texture())`


* You can disable the system by changing a config value, which means by definition that as a user you have to opt out, not in. 
https://github.com/MehVahdJukaar/Supplementaries/blob/73fcd9508fb2f88aa0609bfe049e380fe5330f5f/common/src/main/java/net/mehvahdjukaar/supplementaries/configs/ClientConfigs.java#L403-L404


* You arent trying to get a texture from the vanilla renderer, you are generating it based on assumptions and then throwing errors for any mod that handles their own mod differently, telling the user that they can opt out of your system of vanilla sign modifications, which arent just for vanilla. As a mod developer making a sign mod without your mod in my environment at all, I would not be opting into anything. 

your mods have errors being thrown for a global, user-opt-out system, based on assumptions you make about what might exist in the vanilla game without actually checking. you throw errors based on your unchecked assumptions mentioning a non-existent mod resource. Thats entirely a "your system" issue not a vanilla one

**Comment by MehVahdJukaar** [comment]
I'd that's what's failing then that's a bug. It's only supposed to log when those textures don't exist not when that returns null

**Comment by Linguardium** [comment]
Vanilla adds all wood types to the RenderLayer map, even if they arent used for hanging signs. the renderer would be using `renderer.getTextureId` which would handle the texture id for that renderer.

**Comment by MehVahdJukaar** [comment]
Alright so 2 things:
I've tried so hard to import any of those  mods (blockus, minecelss, ad astra and spectrum) but failed.
They all have many dependencies which either are unliested like its the case for spectrum that has 3, one of them cant be even found on curseforge, or use other dependencies with JIJ which my architectury setup cant import. In the case of better archeology yungs api throws some error. In short I cannot import and test any of them.

Secondly i have checked the toVanilla call and that should just get the hanging sign block (which we know exist otherwise it wouldnt have appeared in that for loop to begin with, and then just call its own .type() method which returns the vanilla wood type so that should never be null

**Comment by Linguardium** [comment]
yes, importing is a no-go for many of them. ideally you should be applying only to vanilla and to mods that explicitly opt-in to your system.

without logging the actual error, its hard to say whats actually failing but i expect it either isn't finding a hanging sign for them or you are trying to load the default texture id path instead of using the block's own renderer TextureId.

I would suggesting doing some checks at the head of the loop to verify the mod has both opted into your system and that the expected path exists. If either isn't true, dont process that wood type.

**Comment by Linguardium** [comment]
if i recall correctly (also not in dev) BlockFamily doesnt list hanging signs, but does list signs. Vanilla is not consistent on what does and doesnt exist. Helper methods that generate a list of potential texture paths should not be expected to be a source of truth.

The vanilla renderer is fairly hardcoded. Sometimes its better to have your own custom renderer to be more flexible, hanging sign or not.

Not adding the hanging sign might just be an oversight from updating mods from old versions. if you see it, you may want to open issues on their trackers to let them know its missing,
