### ISSUE TITLE
[🐞]: Crash makes blocks only visible as outlines

### ISSUE THREAD

**Issue by JetpackJackson** [MehVahdJukaar/Supplementaries#937]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.7.36

### Moonlight Lib Version

moonlight-1.20-2.9.17

### Issue Detail

Was building my house and then when I went to place a book, the game crashed. I then made a backup and tried to log on again. After moving a shelf the game crashed again. When I reopened, the blocks in this specific area look transparent.
![Screenshot 2024-02-16 180934](https://github.com/MehVahdJukaar/Supplementaries/assets/88674707/465314a9-c074-4fec-8e02-63953a87266a)
[crash-2024-02-16_17.13.38-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14316784/crash-2024-02-16_17.13.38-client.txt)
[crash-2024-02-16_17.15.40-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14316785/crash-2024-02-16_17.15.40-client.txt)

**Comment by MehVahdJukaar** [comment]
sodium issue.
And a fixed one at that
update your mods and use embeddium if you arent

**Comment by JetpackJackson** [comment]
alright. will that make the textures go back to normal? i found embeddium in my mods list but its disabled, I think I was having an issue with it so I used rubidium (I think. I'm very sorry but I can't remember)

**Comment by JetpackJackson** [comment]
alright its fixed now. i removed rubidium and updated everything. i think i had those other mods as an older version to fix some other issue i was having. thank you for your help and sorry for the trouble.
