### ISSUE TITLE
[🐞]: Cake and mob heads missing tooltip message

### ISSUE THREAD

**Issue by Emery319** [MehVahdJukaar/Supplementaries#938]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.7.36

### Moonlight Lib Version

moonlight-1.20-2.9.16-forge

### Issue Detail

![2024-02-18_12 09 30](https://github.com/MehVahdJukaar/Supplementaries/assets/124550540/afde2e7c-75be-4109-a308-2c8e4815a81b)
![2024-02-18_12 09 41](https://github.com/MehVahdJukaar/Supplementaries/assets/124550540/bb2ea264-d019-4d26-b12f-638d7578da51)
Cake and mob heads missing tooltip message. It looks like there should be a tooltip message like "can stack two", but that seems to be missing from en_us.json?

**Comment by MehVahdJukaar** [comment]
You can turn it off in the configs for now
