### ISSUE TITLE
[🐞]: `#minecraft:candles` block tag broken as of v2.8.0

### ISSUE THREAD

**Issue by unilock** [MehVahdJukaar/Supplementaries#949]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.8.0

### Moonlight Lib Version

moonlight-1.20-2.10.0-forge

### Issue Detail

```
[Worker-Main-11/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag minecraft:candles as it is missing following references: 
	supplementaries:skull_candle (from supplementaries-1.20-2.8.0.jar)
```

I guess the `skull_candle` block was moved to Amendments, but its block tag entry was never removed from Supplementaries.

https://github.com/MehVahdJukaar/Supplementaries/blob/ca095f2a8776645c9f056d8eafbe06ddc8995cc7/common/src/main/resources/data/minecraft/tags/blocks/candles.json#L1-L6

**Comment by MehVahdJukaar** [comment]
fixed
