### ISSUE TITLE
Support Third-Party Items For Painting Tooltip

### ISSUE THREAD

**Issue by ChloeDawn** [MehVahdJukaar/Supplementaries#951]
Currently the feature for showing paintings on painting item tooltips is only applied to `Items.PAINTING`. If you instead checked `instanceof HangingEntityItem` and `HangingEntityItem#type == EntityType.PAINTING` it would allow the feature to work with mods such as [Handcrafted](https://modrinth.com/mod/handcrafted) - you can find their Fancy Painting implementation [here](https://github.com/terrarium-earth/Handcrafted/blob/13456d7d47c6935f94b1e5927abd15d95d991b2e/common/src/main/java/earth/terrarium/handcrafted/common/items/CustomPaintingItem.java). The caveat is that `HangingEntityItem#type` is private, so would need an Accessor mixin or equivalent.

**Comment by MehVahdJukaar** [comment]
holdup, are you sure they would have that type set to EntityType.PAINTING? wouldnt they have to useanother entity type?

**Comment by MehVahdJukaar** [comment]
well i see. added
