### ISSUE TITLE
[🐞]: Amendments nag screen doesn't stop appearing after selecting "Don't show this again"

### ISSUE THREAD

**Issue by lumiscosity** [MehVahdJukaar/Supplementaries#952]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.8.1

### Moonlight Lib Version

1.20-2.10.0

### Issue Detail

The Amendments nag screen doesn't stop appearing after selecting "Don't show this again".

**Comment by MehVahdJukaar** [comment]
for now you can edit theconfig manually

**Comment by MehVahdJukaar** [comment]
i cant replicate so i assume its fixed in latest release
