### ISSUE TITLE
[🐞]: crash with 1.20.1 forge 47.2.0

### ISSUE THREAD

**Issue by Thunderrock424242** [MehVahdJukaar/Supplementaries#953]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

2.8.1

### Moonlight Lib Version

2.10.0

### Issue Detail

crashed fatal error
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14377471/latest.log)

**Comment by MehVahdJukaar** [comment]
issue with thirst mod (their issue)
