### ISSUE TITLE
Make the Enderman Head texture another location to complete with ETF&EMF.

### ISSUE THREAD

**Issue by Dantigator** [MehVahdJukaar/Supplementaries#961]
Hey! I'm a resource pack author and I also love this mod. Recently I've make a random texture for enderman that will change its texture size and model. This will make the head item only shows correct texture in hand, but the texture will be broken when you place it on the land. Thus I hope you can make it using another path of the texture to avoid this problem.
I also find the pack Fresh Animation will make different head model for the vanilla skulls and i've tried to make a head_enderman.jem but it doesn't work.

**Comment by MehVahdJukaar** [comment]
In the latest version it does not use the enderman model but a new one. It does however use the texture from it. Guess I can give it a new one at this point. Bet this way I'll get complaints from people using simple retextures saying that enderman head does not get retextured properly

**Comment by MehVahdJukaar** [comment]
added diff texture loc
