### ISSUE TITLE
Fluid Duplication w/ the Faucet

### ISSUE THREAD

**Issue by sharkweekthings** [MehVahdJukaar/Supplementaries#964]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.20

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue Detail

In the pack I have made, the interaction with a Supplementaries Faucet, and Pneumatic Craft Thermopneumatic Processing Plant allows for duplication of any fluid inside the Processing Plant, if a Faucet is attached to it. 

More details can be seen here from my original report: 
https://github.com/TeamPneumatic/pnc-repressurized/issues/1290

The dev of PNC suggests:

"This is absolutely a problem with the Faucet, which is misusing the forge IFluidHandler API. The faucet is extracting an arbitrary tank from the fluid handler it gets and extracting from that. The arbitrary tank is picks is tank 0, the input tank.

The correct way to do this is to call drain() directly on the fluid handler itself, not mess about with the tank internals."

**Comment by MehVahdJukaar** [comment]
try on new version

**Comment by MehVahdJukaar** [comment]
on my bad this was 1.19

**Comment by sharkweekthings** [comment]
> on my bad this was 1.19

If you get a new version for 1.19.2 I'll definitely give it a test.

**Comment by MehVahdJukaar** [comment]
there is one

**Comment by sharkweekthings** [comment]
Thanks seems to be working as well!
