### ISSUE TITLE
[🐞]: crash with Apothitweaks

### ISSUE THREAD

**Issue by AnomalousDeity** [MehVahdJukaar/Supplementaries#965]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries 1.20-2.8.1 forge

### Moonlight Lib Version

moonlight 1.20-2.10.9 forge

### Issue Detail

latest- https://mclo.gs/09zxnlP
debug-https://mclo.gs/nwdSrV3

this is just with apothitweaks, supplementaries and moonlight. it crashes during the mojang loading screen.

**Comment by MehVahdJukaar** [comment]
Totally their issue for using incompatible mixibs. I checked that mod GitHub and it's terrible, full I've @Overwrite mixins, replacing while methods at once. These are inherently incompatible with any mod that alter that behaviour and the one I seen could totally be done in a proper way
