### ISSUE TITLE
[🐞]: Odd marker without Twilight-Forest Installed???

### ISSUE THREAD

**Issue by StormFire451** [MehVahdJukaar/Supplementaries#967]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.19

### Moonlight Lib Version

moonlight-1.19.2-2.3.6

### Issue Detail

I do not have twilight forest installed and i got the map marker for twilight portal while i was eating something in my offhand and i cant remove it from my map. i am unsure of the cause and am unable to replicate it but i was on a boat in a swamp
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/149024705/7dc3b1de-1172-422e-98b2-e9fdcadce180)
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/149024705/e03522a2-754f-4f91-af84-2abf7e19b99b)

**Comment by MehVahdJukaar** [comment]
thats very very odd. normally that can only happen when one clicks with a map on that portal. what even is there at that location?

**Comment by MehVahdJukaar** [comment]
marker was removed in latest version
