### ISSUE TITLE
[🐞]: Supplementaries + Geckolib3 + AzureLib

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/Supplementaries#969]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FORGE

### Supplementaries Version

supplementaries-1.19.2-2.4.20.jar

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge.jar

### Issue Detail

https://github.com/bernie-g/geckolib/issues/550 - Everything is here

**Comment by MehVahdJukaar** [comment]
why is this here? theres no mention of supplementaries anywhere in the log. I have no json or anything that uses either gekolib or azure lib in any of my mods

**Comment by Krimatoria** [comment]
> why is this here? theres no mention of supplementaries anywhere in the log. I have no json or anything that uses either gekolib or azure lib in any of my mods

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/106809386/edb9c632-8ac2-4949-ae9e-d7b971c73f0d)
https://github.com/AzureDoom/AzureLib/issues/43 - It comes from here)

**Comment by Krimatoria** [comment]
I also didn't understand why the Supplementaries were in the log with the broken Sculk-Horde animation, I don't understand myself, it's just that the @AzureDoom AzureLib developer said it was geckolib3 @Tslat - and they said the Supplementaries I got confused myself.

**Comment by Tslat** [comment]
> why is this here? theres no mention of supplementaries anywhere in the log. I have no json or anything that uses either gekolib or azure lib in any of my mods
@MehVahdJukaar 

He keeps opening multiple posts in basically every git for this
He has some sort of invalid animation json that is failing to load, and all the info I had was that it happens with supplementaries, azurelib, geckolib
I haven't looked into supplementaries so I just suggested he go look into the pack or whatever to see where the invalid json is

**Comment by MehVahdJukaar** [comment]
Well then Disable your resource  packs and disable all the mods that depend on geko or azure until you find the one that has the incorrect json
