### ISSUE TITLE
[🐞]: Bubble Blocks are not rendered with Minecraft's "Fabulous!" graphics

### ISSUE THREAD

**Issue by Lolothepro** [MehVahdJukaar/Supplementaries#971]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.20-2.8.5

### Moonlight Lib Version

1.20-2.10.10

### Issue Detail

https://github.com/MehVahdJukaar/Supplementaries/assets/68275908/36e188af-2a39-4fea-a2b6-b361698ddf12

**Comment by MehVahdJukaar** [comment]
Not an issue. With the mod that is. Thats how the game works. Get embeddium for better transparency sorting

**Comment by Lolothepro** [comment]
> Not an issue. With the mod that is. Thats how the game works. Get embeddium for better transparency sorting

wdym?

**Comment by Lolothepro** [comment]
Embeddium has no effect on this bug

**Comment by MehVahdJukaar** [comment]
you need to turn off fabulous when thats on. Its a vanilla issueregardless but sodium and embeddium are supposed to fix transparency sorting

**Comment by Lolothepro** [comment]
> you need to turn off fabulous when thats on. Its a vanilla issueregardless but sodium and embeddium are supposed to fix transparency sorting

No, Sodium/Embeddium does not fix the bug

**Comment by Lolothepro** [comment]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/68275908/5d2c6700-fb39-40b7-80a1-74e9a7ededd8)

NeoForge developers say this
