### ISSUE TITLE
Republish under more permissive license?

### ISSUE THREAD

**Issue by svew** [MehVahdJukaar/Supplementaries#972]
Hello,

I'm a new modder who recently found this mod and found it a great source of ideas and example code for developing my own works. I'm not so good at this yet, so instead of building it from scratch I was planning on trying to copy over a few pieces of work found here, tweaking them as needed, and giving full credit to this mod and its developers in my mod page/credits.

However, the current license reserves all rights to the works found here, so I'm very wary of even slightly using content found here. I'm wondering how the maintainers would feel about republishing this mod under a more permissive license, such as MIT or GNU? Or in lieu of that, granting permission to specific developers to remix this mod?

Feedback appreciated, thanks!

**Comment by MehVahdJukaar** [comment]
I understand the concern. reaason its like this is that i heard some stories i didnt like when it comes to licenses so i opted in taking no risks by being as restrictive as possible, sacrificing the open source-ness of the project. I have no problem in you taking inspiration from this or learning from it, so long as you dont copy paste big chunks of specialized code thats would be fine for me, within the realms of reason of course. 
Obviously this would mianly apply if you would like to make your own mod and wanted to get into modded mc in general. If however you would like to create a derivative work off supplementaries (fork), then licens would prohibit that and you would need special permission from me. Which of the two was it?

**Comment by svew** [comment]
Yeah I can completely understand that, I haven't heard about these stories but I can imagine for sure...

Being completely transparent about my intentions, I'm hoping to create an overhaul mod which seeks to completely re-balance the game (I'm aware it's a enormous task... good luck to me, right?). Think something like RLCraft.

Looking at Supplimentaries, there were a couple ideas/things here that I thought would be great addition to my mod, but it'd be a very small subset, like 10% of the content here. Specifically I liked the ideas behind ropes & pulleys, quivers & arrows, signposts, and some small aesthetic stuff like rugs on stairs/slabs and book stacks. The rest, while cool, I don't think would fit the vibe I'm going for. I probably wouldn't tweak these all that much except some slight changes to models, behavior (horizontal ropes is weird...), and integration for new block types.

I totally understand if you're still wary about giving me any license to your works here, but any permission here would be appreciated :)

**Comment by svew** [comment]
Oh and to be double clear about my intentions, this wouldn't be a mod pack, this would be a one-mod overhaul that has no intention of accommodating removing parts of the mod you might not like, so I'd essentially be copying assets/code from this mod and a few others and making tweaks how I'd like.

**Comment by MehVahdJukaar** [comment]
well specifically using assets (textures) from the mod would be harder to do. 
Given the scale of this project and complexity of it i would say that you could contact me again once you have made more progress on your own code. Once i'llbe able to see what it was all about i believe we could come to some agreement for the assets and part of the code that you would like to include. Heavily depends on how much custom code you'll have as, as you might understand, i would not be ok in just having entire part of my mod with minor modification part of a bigger project that would only made up of parts of other existing mods

**Comment by svew** [comment]
Yep, totally understandable. I'll ask again later when I've come further along and if I haven't already decided to try writing the code/make the assets from scratch myself. Appreciate the quick responses and the good work y'all are doing here!
