### ISSUE TITLE
[🐞]: Map markers have stopped working? [1.20.1]

### ISSUE THREAD

**Issue by TheShadow5** [MehVahdJukaar/Supplementaries#973]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.8.6

### Moonlight Lib Version

moonlight-1.20-2.10.10

### Issue Detail

I had a set of custom markers in 1.19.2 that worked fine.  When I updated to 1.20.1, the markers get placed but have a 'missing texture'.  (Yes, I advanced the resource and data packs to the correct versions.)

**Comment by MehVahdJukaar** [comment]
Texture folder changed. Check new version of supp for reference
