### ISSUE TITLE
[🐞]: Minecraft Crashed due to corrupted configs

### ISSUE THREAD

**Issue by aotumanx** [MehVahdJukaar/Supplementaries#974]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2-FORGE

### Supplementaries Version

1.18.2-1.5.18

### Moonlight Lib Version

1.18.2-1.17.14

### Issue Detail

[错误报告-2024-3-5_22.18.52.zip](https://github.com/MehVahdJukaar/Supplementaries/files/14497293/-2024-3-5_22.18.52.zip)

**Comment by MehVahdJukaar** [comment]
your configs got corrupted. delete the folder
