### ISSUE TITLE
Client crash when rendering a jukebox containing an Etched disc

### ISSUE THREAD

**Issue by drown3d** [MehVahdJukaar/Supplementaries#979]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

amendments-1.20-1.1.10

### Moonlight Lib Version

moonlight-1.20-2.11.2-forge

### Issue Detail

Rendering a jukebox containing a disc from Etched causes the client to crash.

[Crash report](https://pastebin.com/bhPBuFMj)

**Comment by MehVahdJukaar** [comment]
fixed
