### ISSUE TITLE
[🐞]: How do you use the converter for midi?

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [MehVahdJukaar/Supplementaries#981]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-2.7.36

### Moonlight Lib Version

moonlight-1.20-2.9.17-forge

### Issue Detail

Hello, so I recently downloaded some MIDI music to add to the flute when I go to use your conversion Python script it says found 1 track select one, from that point on no matter what I enter it says track not found, what am I meant to be typing into the script when it says 1 track found but then doesn't find the track?

**Comment by TWIISTED-STUDIOS** [comment]
Never mind i found out the issue, user error sorry.

**Comment by MehVahdJukaar** [comment]
programmer stuff. indexes start from  0
