### ISSUE TITLE
[🐞]: Hanging sign breaks the game

### ISSUE THREAD

**Issue by k41s3rr** [MehVahdJukaar/Supplementaries#984]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [ ] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

1.19.4-2.4.16

### Moonlight Lib Version

1.19.4-2.4.15

### Issue Detail

I'm using the 1.19.4 version of the mod.
When I open the game, the starting screen starts to load, then proceeds to crash moments later.
Looking at the error log, this is what it gives me;

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/163713885/f3083dec-61a3-40dc-835a-7f3ad98745d6)

crash error:
https://mclo.gs/MyahonE

**Comment by MehVahdJukaar** [comment]
Must be some mod conflict. Anyways 1.19.4 is not supported
