### ISSUE TITLE
[❓]: HOW TO BUILD?

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [MehVahdJukaar/Supplementaries#986]
when i try to build the mod it gets the error that the moonlight .pom was not found
when i try to build moonlight it gets the error that the supplementaries .pom was not found

**Comment by MehVahdJukaar** [comment]
import the mod, add required dependencies to build.gradle

**Comment by SonicGamerEpisode55** [comment]
what dependencies?

**Comment by SonicGamerEpisode55** [comment]
basically i do: `git clone --recursive repository, cd repository, chmod +x gradlew, ./gradlew build`

**Comment by SonicGamerEpisode55** [comment]
and the error pops up

**Comment by MehVahdJukaar** [comment]
use intellij. you will need to import the dependencies in the 3 built.gradle because i have them on my maven local. get them from curse maven

**Comment by SonicGamerEpisode55** [comment]
how to import them?
now i use intellij

**Comment by SonicGamerEpisode55** [comment]
moonlight forge builds fine but not supplementaries

**Comment by SonicGamerEpisode55** [comment]
so how to build supplems forge-only?

**Comment by SonicGamerEpisode55** [comment]
and why it tries to download an older version (2.11.2a) vs newer (2.11.4)

**Comment by SonicGamerEpisode55** [comment]
so what?

**Comment by MehVahdJukaar** [comment]
idk

**Comment by SonicGamerEpisode55** [comment]
fixed that by building the error mods
