### ISSUE TITLE
[❓]: 1.20.4 Support

### ISSUE THREAD

**Issue by nco2k** [MehVahdJukaar/Supplementaries#987]
### Your Question

any plans to support 1.20.4?

### Detail

:3

**Comment by MehVahdJukaar** [comment]
not really, nobody is playing that and its a snapshot version

**Comment by nco2k** [comment]
what? the final version is out since december. the current snapshots are for 1.20.5. also no idea where you got the info that no one is playing it. there are thousands of public servers with hundreds of players each. check out any minecraft server list.
