### ISSUE TITLE
[🐞]: Fatal Error when Generating Blocks on Singleplayer World Fabric 1.20.1/0.15.7

### ISSUE THREAD

**Issue by pokesmells** [MehVahdJukaar/Supplementaries#989]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

supplementaries-1.20-2.8.6-fabric.jar

### Moonlight Lib Version

moonlight-1.20-2.11.4-fabric.jar

### Issue Detail

It seems to come up occasionally, and causes world generation to hang behind at times. Does not cause a crash.
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14666814/latest.log)

**Comment by pokesmells** [comment]
It seems to occur structure lookup or generation, it causes the tick to take a TON, like ages to load sometimes.

**Comment by pokesmells** [comment]
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14705175/latest.log)

**Comment by MehVahdJukaar** [comment]
fixed thoi never figured out what real cause was
