### ISSUE TITLE
[🐞]: Bellows prevent players standing on top of them from jumping once depressed

### ISSUE THREAD

**Issue by LessThanBenji** [MehVahdJukaar/Supplementaries#990]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.8.4

### Moonlight Lib Version

1.20-2.11.9

### Issue Detail

Jumping onto/on top of a Bellows causes it to depress and push air out. Once the Bellows have depressed (even just a little bit), it becomes impossible for the player to jump again/off them. You have to horizontally walk/fall off the Bellows to regain the ability to jump.

**Comment by MehVahdJukaar** [comment]
Also happens with shulker boxes so it's consistent with them

**Comment by LessThanBenji** [comment]
Sorry, I've tried jumping on Shulker Boxes in a bunch of different ways and I don't understand what you're saying. At no point does the player lose the ability to jump when on top of one. What do you mean it also happens / is consistent with them?

(PS. Turns out the Bellows do have to be *fully* depressed for this issue to occur, not just partially as I originally stated).

**Comment by MehVahdJukaar** [comment]
fixed it, at least some. will be in next release
