### ISSUE TITLE
[🐞]: Speaker Block's "Narrator" and "Chat Message" functions are flipped

### ISSUE THREAD

**Issue by LessThanBenji** [MehVahdJukaar/Supplementaries#991]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.8.4

### Moonlight Lib Version

1.20-2.11.9

### Issue Detail

Speaker Blocks set to "Narrator Message" execute as chat messages, whilst Speaker Blocks set to "Chat Message" execute as audible narrated voice lines.

Additionally, setting the config option supplementaries-common.json > speaker_block > Narrator Enabled to "false" greys out the mode-setting button in Speaker Blocks' GUIs, rendering them unusable (I believe these issues are related).

I apologize, I did find some previously-existing issues apparently reporting this behavior/bug, but they were all closed and seemingly marked as resolved.

By the way, awesome mod! It's a joy to use and fits in with vanilla Minecraft seamlessly, huge kudos to you!

**Comment by MehVahdJukaar** [comment]
fixed
