### ISSUE TITLE
Cancel changes on blackboard GUI when pressing ESC

### ISSUE THREAD

**Issue by Insane96** [MehVahdJukaar/Supplementaries#992]
Sometimes, I press "clear" and there's no way to prevent saving it, it's annoying

**Comment by MehVahdJukaar** [comment]
Hm would need to check how signs do it. If they keep changes once inventory is closed when pressing escape. Needs to be consistent with them so players know what to expect otherwise some others might find it annoying that their changes are NOT kept when they accidentally exit with esc

**Comment by Insane96** [comment]
Makes sense. I'll try to write in-world with quartz and coal then

**Comment by Insane96** [comment]
Countersuggestion

Allow to undo a clear in 5 seconds after pressing it

**Comment by MehVahdJukaar** [comment]
added undo button. proper one with full history and all. idk when it will actaually be released as im working on a big updated. closing this for now
