### ISSUE TITLE
[🐞]: Crashes after generating SERVER_DATA

### ISSUE THREAD

**Issue by DMNight6** [MehVahdJukaar/Supplementaries#998]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2-FABRIC

### Supplementaries Version

supplementaries-1.19.2-2.4.20-fabric

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-fabric.jar

### Issue Detail

Server crashed after generating SERVER_DATA.

Logs:
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14766112/latest.log)

**Comment by MehVahdJukaar** [comment]
That's unrelated

**Comment by DMNight6** [comment]
> That's unrelated

Happened right after generating your dynamic data pack. This is on the server side. I tried loading the world in single-player but with similar error

**Comment by DMNight6** [comment]
Note: There is no data pack on the server

**Comment by DMNight6** [comment]
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/50548798/c144efe7-6852-48d6-af60-34a1c2129c07)

**Comment by MehVahdJukaar** [comment]
mods always come with a builtin datapack. As ive said that message is unrelated as it just happens to be the last valid thing that is logged before that error occurs. Idk what causes that error, maybe corrupted files

**Comment by DMNight6** [comment]
> mods always come with a builtin datapack. As ive said that message is unrelated as it just happens to be the last valid thing that is logged before that error occurs. Idk what causes that error, maybe corrupted world files

Thx g, it is in fact a corrupted world. Corrupted due to not-so-graceful shutdowns due to broken PSU.
