### ISSUE TITLE
[🐞]: New release 2.8.8 crashes when installed alongside Farmer's Delight

### ISSUE THREAD

**Issue by LessThanBenji** [MehVahdJukaar/Supplementaries#999]
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.8.8

### Moonlight Lib Version

1.20-2.11.9

### Issue Detail

As of the latest release, 2.8.8, Supplementaries causes a crash upon load when installed alongside Farmer's Delight. This is on 1.20.1, using Fabric 0.15.6, and Farmer's Delight 1.4.3.

[crash-2024-03-28_01.23.07-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14773186/crash-2024-03-28_01.23.07-client.txt)
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/14773188/latest.log)

Reverting to Supplementaries 2.8.7 resolves this issue.

**Comment by Erik9996** [comment]
Having the same issue, with the exact same error.

**Comment by MehVahdJukaar** [comment]
New version only works with Farmers Delight Refabricated 2.0.0

**Comment by roleester** [comment]
What about our existing worlds? Do we just switch from the old Farmer's Delight to the new refabricated one? Also what about the old Farmer's Delight add-ons?

**Comment by Allexio** [comment]
> What about our existing worlds? Do we just switch from the old Farmer's Delight to the new refabricated one? Also what about the old Farmer's Delight add-ons? It says they're not compatible on the refabricated mod page, but again what about our existing worlds?

Simply don't update supplementaries.
If you use packwiz to manage your modpack you can use the "pin" command to make sure it does not get updated when you update all your mods.

**Comment by MehVahdJukaar** [comment]
new version has compat for the new port. IF you want to use the old port you got to use an old version.
Both mods have same ids but very different internal structure. New one is identical to forge so cross loader mods like supplementaries can just have 1 set of integration classes (also comes with all the newest features that were missing and some extra ones)

**Comment by ittouwjpi** [comment]
May i have some questions? If i update to the new port will all the contents of the older port be lost, i have to start from the very beginning right? And if i don't, will there be future Supplementaries updates that support both ports? Amazing work and thank you!!!

**Comment by MehVahdJukaar** [comment]
They have same IDs. All will stay the same

**Comment by serioos** [comment]
I'm having this problem too.

https://ibb.co/19FzZNq

**Comment by Wizardon777** [comment]
Same crash here with version 2.8.9.

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Supplementaries' (supplementaries) 1.20-2.8.9 with version 1.20-2.5.2 or later that is compatible with:
		 - farmersdelight 1.20.1-1.4.3
More details:
	 - Mod 'Supplementaries' (supplementaries) 1.20-2.8.9 is incompatible with any version before 1.20.1-2.0.0 of mod 'Farmer's Delight' (farmersdelight), but a matching version is present: 1.20.1-1.4.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by LessThanBenji** [comment]
I've switched to Farmer's Delight Refabricated (v2.0.9) alongside Supplementaries (v2.8.9, Moonlight v2.11.9), and now I'm getting a different crash report:

[crash-2024-03-31_21.41.31-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/14814698/crash-2024-03-31_21.41.31-client.txt)

**Comment by MehVahdJukaar** [comment]
All FD addons won't work with the new version unless they update to it

**Comment by nrnsab** [comment]
Having a similar issue. Here is my crash log. I really do want both farmer's delight and supplementaries tgt. 
[https://mclo.gs/7rYqe8y](url)
